# About

## About the author

I'm a biomedical scientist. But I've always had a high level of interest in statistical methods. I learned "statistical design and analysis of experiments" as a graduate student at Mizzou in a couple of deeply impactful courses offered by the late Gary Krause, then a professor and statistician in Mizzou's agricultural college.

It was in Gary's course entitled *Experimenal Design* that the light turned on for me. That's when I finally was able to see through the fog of mathematical statistics to "get" the pragmatic value of statistics for the researcher, which at its core is nothing more or less than a framework for conducting unbiased reasearch.

I was a biomedical student working on my PhD in pharmacology. But the typical student in Gary's courses was working on a PhD in one of the agriculture programs, usually in some area of agronomy or in animal science. 

The problem my classmates shared, which was not one that really affected me, is having one growing or mating season by which to run a fully replicated experiment.

One shot.

hamilton image

Under that constraint it was all about the planning. They needed to map out their experimental design in advance. Once the experiment began, any new wrinkles or oversights would have to wait a growing season. They didn't have the luxury of running out to the field to plant another row of the crop, or to arrange additional breeding groups. 

Of course, these experiments were planned in advance using statistical design principles. Statistics weren't just post-hoc tests, but also an intrinsic aspect of the planning process so that the experimental design is capable of addressing specific questions. The overall idea, which is not very complicated, was to be sure to plan an experiment that can be analyzed after it ran! And to run experiments the way they are planned.

At the end of the season the samples were harvested. After all the biochemistry was completed at their lab benches, the final statistical analysis was performed according to the planned approach.

That's how unbiased research is performed. That's how experimental statistics should be used. Have an idea. Put some effort into planning a test for it. And then follow that plan as closely as possible.

It has become common for biomedical researchers to take more of a "fly by the seat of their pants" approach to running experiments and their replicates. In this approach, bunches of near and partial replicates are munged together before looking at the results and making a decision about what statistical analysis would be most appropriate to confirm their inclined interpretation. Statistics is practices as an afterthought, rather than a planning tool. Unfortunately, that's an approach that is riddled with biases and can lead to a large number of negative outcomes...mostly in terms of a researchers career.

In fact, experimental statistics was never intended to be exploited in that way. Experimental statistics was invented by the founders as a means of instilling some structure into the discovery and inference process in the planning stages. 

## About this book

This is one of those books that's actually a collection of RMarkdown handouts that I prepared for the course when I switched over to using R as the computational resource.

The purpose is so that the student has a resource on the material not only for the course, but afterwards, too. What I try to get across in the book is the "how and why" of statistical design and analysis. 

The focus of this course is in teaching statistics as experimental design. The ideal learner will finish the course knowing how to map out the statistical plan for an experiment in advance and appreciate why this is so important to reduce bias.  

That same learner will also know how to analyze, interpret, visualize, and write up the results for a wide array of experimental designs. Most of which she will forget immediately. 

And since I emphasize pre-planning, this book is full of simulations. That's the really great advantage of using R to teach biostats, in my view.

I'm not a mathematician so I only offer enough theoretical and mathematical statistics to provide a glimpse of how how things work "under the hood". When I do, it is mostly for stuff I think is helpful to interpret statistical output, or illustrate why a test works in a specific way. 

I very much believe there is an important place for mathematical statistics, I just don't believe I'm the person who should be teaching it.  

Scientists have a lot of overt biases and are the last to realize it. Data frequently has a lot of hidden biases we fail to see. That's why operating within a statistical design framework is so important. 

For the biomedical PhD student hoping to graduate while still young, a statistical design framework also offers potential to keep things rolling downhill for you. Statistical thinking should help you avoid the time-sucking rabbit holes that are associated with sloppy experiments and prolonged time to degrees. 

## Software

The course requires that you use the latest version of R. It also assumes you are using the RStudio environment. Both are free. They need to be installed sequentially, in the proper order, for a smooth experience.

Installation is pretty straight forward but not idiot proof. One sign you are doing it wrong if you find yourself about to purchase something. The software you need for this course is free.

Note for Windows students: If you have a 64bit processor, be sure to install and work with the 64bit R version.

R is open source. There is base R and then there are packages that you'll need to install separately. At the start of every chapter I list the packages that will be necessary to run the scripts in that chapter.  

From time-to-time your machine is not configured correctly to play well with some package you are using. You will have to figure out what R is trying to do and then how to get your machine configured so it can do it. A place to start is to copy and paste R error codes into your browser search bar.

To get up and running so you can do R on your machine do the following **in this sequence**:

1) Step 1. Install the latest version of R. 
* [Go here](https://www.r-project.org/).

2) Step 2. Install RStudio only after you have completed installing R. [Go here](https://cran.rstudio.com/). Select the free option.

If you installed R prior to RStudio as instructed, launching RStudio on your machine should automagically configure R to work within the RStudio console. You should be good to go. 

Poke around with the RStudio menu bar and the RStudio panes. Under `Tools` select `Global Options` and experiment with an appearance configuration to your liking.

## Getting started with R

Once you have R and RStudio up and running I highly recommend taking the R Programming module in the interactive [swirl package](https://swirlstats.com/). Install and load the swirl library by typing the following into the R console within R studio.

```#{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
install.packages("swirl")
library(swirl)
```

Swirl does a quick overview of the basics. But there are a lot of basics, most of which you'll forget! As you go through swirl I suggest you open up a fresh R script or R markdown file to take notes (eg, copy/paste code snippets) for a custom cheatsheet.

There are many, many other resources with which to get started.

[If you are ready to roll up your sleaves and play with R go here](https://www.r-bloggers.com/the-5-most-effective-ways-to-learn-r/).

As you work with R you'll make mistakes. Of these, >90% will be typos. If you didn't mistype a command, just copy and paste error messages into your browser search bar. Most of the errors you will make have happened before. Most of what you want to do someone has done before. The best documented solutions are usually found in StackOverflow.

The bottom line is the best way to learn R is to just start using it to solve the problems you need to solve. I'll provide you the problems you need to solve in this course. They are about learning statistics, but you'll end up learning how to use R as a side benefit.


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

