--- 
title: 'JABSTB: Statistical Design and Analysis of Experiments with R'
author: TJ Murphy PhD, Department of Pharmacology, School of Medicine, Department
  of Biostatistics and Bioinformatics, Rollins School of Public Health, Emory University,
  Atlanta, GA  biostats538@gmail.com
date: "`r Sys.Date()`"
bibliography:
- book.bib
- packages.bib
description: Experimental biostatistics using R.
documentclass: book
link-citations: yes
location: Atlanta
site: bookdown::bookdown_site
biblio-style: apalike
---

# Preface {-}

This "book" is actually a bunch of RMarkdown handouts stitched together. This is intended as a resource for a semester-long "biostats" course that I teach at Emory University entitled, *Statistical Design and Analysis of Experiments*. Not included is additional material (eg, take home and group exercises, slide decks, data sets, cartoons, etc).

The audience is (mostly) students in Emory University's interdepartmental biomedical and biological sciences PhD programs. There is the ocassional Emory undergrad, students from Emory's public health school, and usually a few Georgia Tech students. 

Each chapter corresponds to a RMarkdown document. The first few chapters deal with statistical fundamentals that are applicable to all types of statistical analysis. From then on, beginning with a chapter on the statistics of categorical variables, the material covers the statistical analysis of the three main types of data: sorted, ordered and measured. The basic idea is to illustrate how to analyze a certain kind of data phenotype, within a certain kind of experimental structure.

Most of the chapters have R script embedded in code chunks. These scripts generally serve two purposes. The first is to illustrate a statistical principle. The second is so studentds can read and learn how to write their own R code for that specific purpose. 

For that reason, the html of the code chunks in the book are admittedly bit long at times. To have the chunks in hand, the reader can download this book from Github. To more conveniently access those RMarkdown documents and all that script. Just bear in mind, this book is a living document and will be subjected to a lot of on the fly revision.

Speaking of which, if you find any errors or have any suggestions please send me a pull request via Github (@TJMurphy). 

You are free to use this material as you wish, available via the Creative Commons license. 

Copyright 2018 © TJ Murphy

