<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 38 Non-linear regression introduction | JABSTB: Statistical Design and Analysis of Experiments with R</title>
  <meta name="description" content="Experimental biostatistics using R." />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 38 Non-linear regression introduction | JABSTB: Statistical Design and Analysis of Experiments with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Experimental biostatistics using R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 38 Non-linear regression introduction | JABSTB: Statistical Design and Analysis of Experiments with R" />
  
  <meta name="twitter:description" content="Experimental biostatistics using R." />
  

<meta name="author" content="TJ Murphy PhD, Department of Pharmacology and Chemical Biology, School of Medicine, Emory University, Atlanta, GA biostats538@gmail.com" />


<meta name="date" content="2020-04-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regress.html"/>
<link rel="next" href="nestedregress.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">JABSTB</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i><b>1</b> About the author and book</a></li>
<li class="chapter" data-level="2" data-path="history.html"><a href="history.html"><i class="fa fa-check"></i><b>2</b> A Brief History of Experimental Design</a></li>
<li class="chapter" data-level="3" data-path="software.html"><a href="software.html"><i class="fa fa-check"></i><b>3</b> Installing and Understanding the software</a><ul>
<li class="chapter" data-level="3.1" data-path="software.html"><a href="software.html#spring-2020-term-versions"><i class="fa fa-check"></i><b>3.1</b> Spring 2020 term versions</a><ul>
<li class="chapter" data-level="3.1.1" data-path="software.html"><a href="software.html#what-are-these"><i class="fa fa-check"></i><b>3.1.1</b> What are these?</a></li>
<li class="chapter" data-level="3.1.2" data-path="software.html"><a href="software.html#rule-1-install-r-first-install-rstudio-second"><i class="fa fa-check"></i><b>3.1.2</b> Rule 1: Install R first, install RStudio second</a></li>
<li class="chapter" data-level="3.1.3" data-path="software.html"><a href="software.html#rule-2-dont-pay"><i class="fa fa-check"></i><b>3.1.3</b> Rule 2: Don’t pay!</a></li>
<li class="chapter" data-level="3.1.4" data-path="software.html"><a href="software.html#rule-3-dont-compile"><i class="fa fa-check"></i><b>3.1.4</b> Rule 3: Don’t compile!</a></li>
<li class="chapter" data-level="3.1.5" data-path="software.html"><a href="software.html#rule-4-install-the-right-software-for-your-machine"><i class="fa fa-check"></i><b>3.1.5</b> Rule 4: Install the right software for your machine</a></li>
<li class="chapter" data-level="3.1.6" data-path="software.html"><a href="software.html#rule-5-use-this-installation-guide"><i class="fa fa-check"></i><b>3.1.6</b> Rule 5: Use this installation guide</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="software.html"><a href="software.html#after-installation"><i class="fa fa-check"></i><b>3.2</b> After installation</a><ul>
<li class="chapter" data-level="3.2.1" data-path="software.html"><a href="software.html#what-is-r"><i class="fa fa-check"></i><b>3.2.1</b> What is R?</a></li>
<li class="chapter" data-level="3.2.2" data-path="software.html"><a href="software.html#r-packages"><i class="fa fa-check"></i><b>3.2.2</b> R packages</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="software.html"><a href="software.html#important-avoid-compiling"><i class="fa fa-check"></i><b>3.3</b> Important: Avoid compiling</a><ul>
<li class="chapter" data-level="3.3.1" data-path="software.html"><a href="software.html#reasons-not-to-compile"><i class="fa fa-check"></i><b>3.3.1</b> Reasons not to compile</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>4</b> Start Learning R</a><ul>
<li class="chapter" data-level="4.1" data-path="getting-started.html"><a href="getting-started.html#digging-in-with-rrstudio"><i class="fa fa-check"></i><b>4.1</b> Digging in with R/RStudio</a></li>
<li class="chapter" data-level="4.2" data-path="getting-started.html"><a href="getting-started.html#the-tidyverse-package"><i class="fa fa-check"></i><b>4.2</b> The tidyverse package</a><ul>
<li class="chapter" data-level="4.2.1" data-path="getting-started.html"><a href="getting-started.html#do-swirlstats"><i class="fa fa-check"></i><b>4.2.1</b> Do swirlstats</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="getting-started.html"><a href="getting-started.html#other-resources"><i class="fa fa-check"></i><b>4.3</b> Other resources</a><ul>
<li class="chapter" data-level="4.3.1" data-path="getting-started.html"><a href="getting-started.html#internet-search"><i class="fa fa-check"></i><b>4.3.1</b> Internet search</a></li>
<li class="chapter" data-level="4.3.2" data-path="getting-started.html"><a href="getting-started.html#help-documents"><i class="fa fa-check"></i><b>4.3.2</b> Help Documents</a></li>
<li class="chapter" data-level="4.3.3" data-path="getting-started.html"><a href="getting-started.html#package-vignettes"><i class="fa fa-check"></i><b>4.3.3</b> Package Vignettes</a></li>
<li class="chapter" data-level="4.3.4" data-path="getting-started.html"><a href="getting-started.html#people"><i class="fa fa-check"></i><b>4.3.4</b> People</a></li>
<li class="chapter" data-level="4.3.5" data-path="getting-started.html"><a href="getting-started.html#typos"><i class="fa fa-check"></i><b>4.3.5</b> typos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="philos.html"><a href="philos.html"><i class="fa fa-check"></i><b>5</b> What is your philosophy?</a><ul>
<li class="chapter" data-level="5.1" data-path="philos.html"><a href="philos.html#exploration-and-uncertainty"><i class="fa fa-check"></i><b>5.1</b> Exploration and uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bigpic.html"><a href="bigpic.html"><i class="fa fa-check"></i><b>6</b> Stats: The Big Picture</a><ul>
<li class="chapter" data-level="6.1" data-path="bigpic.html"><a href="bigpic.html#what-are-experimental-statistics"><i class="fa fa-check"></i><b>6.1</b> What are experimental statistics?</a><ul>
<li class="chapter" data-level="6.1.1" data-path="bigpic.html"><a href="bigpic.html#descriptive-modeling"><i class="fa fa-check"></i><b>6.1.1</b> Descriptive modeling</a></li>
<li class="chapter" data-level="6.1.2" data-path="bigpic.html"><a href="bigpic.html#statistical-inference"><i class="fa fa-check"></i><b>6.1.2</b> Statistical inference</a></li>
<li class="chapter" data-level="6.1.3" data-path="bigpic.html"><a href="bigpic.html#experimental-design"><i class="fa fa-check"></i><b>6.1.3</b> Experimental design</a></li>
<li class="chapter" data-level="6.1.4" data-path="bigpic.html"><a href="bigpic.html#statistics-as-an-anti-bias-framework"><i class="fa fa-check"></i><b>6.1.4</b> Statistics as an anti-bias framework</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>7</b> Statistical Sampling</a><ul>
<li class="chapter" data-level="7.1" data-path="sampling.html"><a href="sampling.html#experimental-units"><i class="fa fa-check"></i><b>7.1</b> Experimental units</a><ul>
<li class="chapter" data-level="7.1.1" data-path="sampling.html"><a href="sampling.html#a-simple-test-to-define-the-experimental-unit"><i class="fa fa-check"></i><b>7.1.1</b> A simple test to define the experimental unit</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="sampling.html"><a href="sampling.html#independent-replicates"><i class="fa fa-check"></i><b>7.2</b> Independent Replicates</a><ul>
<li class="chapter" data-level="7.2.1" data-path="sampling.html"><a href="sampling.html#a-simple-test-for-independence"><i class="fa fa-check"></i><b>7.2.1</b> A simple test for independence</a></li>
<li class="chapter" data-level="7.2.2" data-path="sampling.html"><a href="sampling.html#some-replication-examples"><i class="fa fa-check"></i><b>7.2.2</b> Some replication examples</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sampling.html"><a href="sampling.html#random-process"><i class="fa fa-check"></i><b>7.3</b> Random process</a></li>
<li class="chapter" data-level="7.4" data-path="sampling.html"><a href="sampling.html#statistically-valid-samples"><i class="fa fa-check"></i><b>7.4</b> Statistically valid samples</a><ul>
<li class="chapter" data-level="7.4.1" data-path="sampling.html"><a href="sampling.html#select-random-subjects"><i class="fa fa-check"></i><b>7.4.1</b> Select random subjects</a></li>
<li class="chapter" data-level="7.4.2" data-path="sampling.html"><a href="sampling.html#randomize-to-sequence"><i class="fa fa-check"></i><b>7.4.2</b> Randomize to sequence</a></li>
<li class="chapter" data-level="7.4.3" data-path="sampling.html"><a href="sampling.html#randomize-to-location"><i class="fa fa-check"></i><b>7.4.3</b> Randomize to location</a></li>
<li class="chapter" data-level="7.4.4" data-path="sampling.html"><a href="sampling.html#randomize-to-block"><i class="fa fa-check"></i><b>7.4.4</b> Randomize to block</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sampling.html"><a href="sampling.html#independence-of-replicates"><i class="fa fa-check"></i><b>7.5</b> Independence of replicates</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>8</b> Data Classification</a><ul>
<li class="chapter" data-level="8.1" data-path="data.html"><a href="data.html#dependent-and-independent-variables"><i class="fa fa-check"></i><b>8.1</b> Dependent and independent variables</a><ul>
<li class="chapter" data-level="8.1.1" data-path="data.html"><a href="data.html#statistical-notation"><i class="fa fa-check"></i><b>8.1.1</b> Statistical notation</a></li>
<li class="chapter" data-level="8.1.2" data-path="data.html"><a href="data.html#when-there-is-no-independent-variable"><i class="fa fa-check"></i><b>8.1.2</b> When there is no independent variable</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="data.html"><a href="data.html#discrete-or-continuous-variables"><i class="fa fa-check"></i><b>8.2</b> Discrete or continuous variables</a><ul>
<li class="chapter" data-level="8.2.1" data-path="data.html"><a href="data.html#measured-variables"><i class="fa fa-check"></i><b>8.2.1</b> Measured variables</a></li>
<li class="chapter" data-level="8.2.2" data-path="data.html"><a href="data.html#discrete-categorical-and-ordinal-variables"><i class="fa fa-check"></i><b>8.2.2</b> Discrete categorical and ordinal variables</a></li>
<li class="chapter" data-level="8.2.3" data-path="data.html"><a href="data.html#rescaling-variables"><i class="fa fa-check"></i><b>8.2.3</b> Rescaling variables</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="data.html"><a href="data.html#working-with-data"><i class="fa fa-check"></i><b>8.3</b> Working with data</a><ul>
<li class="chapter" data-level="8.3.1" data-path="data.html"><a href="data.html#entering-data"><i class="fa fa-check"></i><b>8.3.1</b> Entering data</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="data.html"><a href="data.html#summary"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="dispersion.html"><a href="dispersion.html"><i class="fa fa-check"></i><b>9</b> Variability, Accuracy and Precision</a><ul>
<li class="chapter" data-level="9.0.1" data-path="dispersion.html"><a href="dispersion.html#data-are-messy"><i class="fa fa-check"></i><b>9.0.1</b> Data are messy</a></li>
<li class="chapter" data-level="9.1" data-path="dispersion.html"><a href="dispersion.html#illustration-of-a-model-with-error"><i class="fa fa-check"></i><b>9.1</b> Illustration of a model with error</a></li>
<li class="chapter" data-level="9.2" data-path="dispersion.html"><a href="dispersion.html#variance-quantifying-variation-by-least-squares"><i class="fa fa-check"></i><b>9.2</b> Variance: Quantifying variation by least squares</a><ul>
<li class="chapter" data-level="9.2.1" data-path="dispersion.html"><a href="dispersion.html#definition-of-variance"><i class="fa fa-check"></i><b>9.2.1</b> Definition of variance</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="dispersion.html"><a href="dispersion.html#standard-deviation"><i class="fa fa-check"></i><b>9.3</b> Standard deviation</a><ul>
<li class="chapter" data-level="9.3.1" data-path="dispersion.html"><a href="dispersion.html#what-does-the-standard-deviation-tell-us"><i class="fa fa-check"></i><b>9.3.1</b> What does the standard deviation tell us</a></li>
<li class="chapter" data-level="9.3.2" data-path="dispersion.html"><a href="dispersion.html#ways-of-describing-sample-variability"><i class="fa fa-check"></i><b>9.3.2</b> Ways of describing sample variability</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="dispersion.html"><a href="dispersion.html#precision-and-accuracy"><i class="fa fa-check"></i><b>9.4</b> Precision and Accuracy</a></li>
<li class="chapter" data-level="9.5" data-path="dispersion.html"><a href="dispersion.html#standard-error"><i class="fa fa-check"></i><b>9.5</b> Standard error</a><ul>
<li class="chapter" data-level="9.5.1" data-path="dispersion.html"><a href="dispersion.html#what-exactly-does-the-standard-error-represent"><i class="fa fa-check"></i><b>9.5.1</b> What exactly does the standard error represent?</a></li>
<li class="chapter" data-level="9.5.2" data-path="dispersion.html"><a href="dispersion.html#should-i-use-sd-or-sem"><i class="fa fa-check"></i><b>9.5.2</b> “Should I use SD or SEM?”</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="dispersion.html"><a href="dispersion.html#confidence-intervals"><i class="fa fa-check"></i><b>9.6</b> Confidence intervals</a><ul>
<li class="chapter" data-level="9.6.1" data-path="dispersion.html"><a href="dispersion.html#ci-definition"><i class="fa fa-check"></i><b>9.6.1</b> CI Definition</a></li>
<li class="chapter" data-level="9.6.2" data-path="dispersion.html"><a href="dispersion.html#evaluating-confidence-intervals"><i class="fa fa-check"></i><b>9.6.2</b> Evaluating confidence intervals</a></li>
<li class="chapter" data-level="9.6.3" data-path="dispersion.html"><a href="dispersion.html#ci-simulation-tools"><i class="fa fa-check"></i><b>9.6.3</b> CI Simulation tools</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="dispersion.html"><a href="dispersion.html#key-take-aways"><i class="fa fa-check"></i><b>9.7</b> Key take aways</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>10</b> Framing statistical hypotheses</a><ul>
<li class="chapter" data-level="10.1" data-path="hypotheses.html"><a href="hypotheses.html#the-decision-process"><i class="fa fa-check"></i><b>10.1</b> The decision process</a></li>
<li class="chapter" data-level="10.2" data-path="hypotheses.html"><a href="hypotheses.html#popper-and-falsification"><i class="fa fa-check"></i><b>10.2</b> Popper and falsification</a></li>
<li class="chapter" data-level="10.3" data-path="hypotheses.html"><a href="hypotheses.html#statistical-hypothesis-rubric"><i class="fa fa-check"></i><b>10.3</b> Statistical hypothesis rubric</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="error.html"><a href="error.html"><i class="fa fa-check"></i><b>11</b> Error</a><ul>
<li class="chapter" data-level="11.1" data-path="error.html"><a href="error.html#setting-type-1-and-type-2-error-thresholds"><i class="fa fa-check"></i><b>11.1</b> Setting type 1 and type 2 error thresholds</a><ul>
<li class="chapter" data-level="11.1.1" data-path="error.html"><a href="error.html#setting-alpha-the-type-1-error"><i class="fa fa-check"></i><b>11.1.1</b> Setting alpha-the type 1 error</a></li>
<li class="chapter" data-level="11.1.2" data-path="error.html"><a href="error.html#power-setting-beta-the-type-2-error"><i class="fa fa-check"></i><b>11.1.2</b> Power: Setting beta-the type 2 error</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="error.html"><a href="error.html#striking-the-right-balance"><i class="fa fa-check"></i><b>11.2</b> Striking the right balance</a></li>
<li class="chapter" data-level="11.3" data-path="error.html"><a href="error.html#false-discovery-rate"><i class="fa fa-check"></i><b>11.3</b> False discovery rate</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="pvalues.html"><a href="pvalues.html"><i class="fa fa-check"></i><b>12</b> P Values</a><ul>
<li class="chapter" data-level="12.1" data-path="pvalues.html"><a href="pvalues.html#definition"><i class="fa fa-check"></i><b>12.1</b> Definition</a></li>
<li class="chapter" data-level="12.2" data-path="pvalues.html"><a href="pvalues.html#test-statistics-come-from-null-distributions"><i class="fa fa-check"></i><b>12.2</b> Test statistics come from null distributions</a><ul>
<li class="chapter" data-level="12.2.1" data-path="pvalues.html"><a href="pvalues.html#p-value-behavior"><i class="fa fa-check"></i><b>12.2.1</b> P-value behavior</a></li>
<li class="chapter" data-level="12.2.2" data-path="pvalues.html"><a href="pvalues.html#p-values-and-the-decision-process"><i class="fa fa-check"></i><b>12.2.2</b> P-values and the decision process</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="pvalues.html"><a href="pvalues.html#a-blood-glucose-p-value"><i class="fa fa-check"></i><b>12.3</b> A blood glucose p-value</a></li>
<li class="chapter" data-level="12.4" data-path="pvalues.html"><a href="pvalues.html#how-p-values-should-be-interpreted"><i class="fa fa-check"></i><b>12.4</b> How p-values should be interpreted</a></li>
<li class="chapter" data-level="12.5" data-path="pvalues.html"><a href="pvalues.html#interpretation"><i class="fa fa-check"></i><b>12.5</b> Interpretation</a></li>
<li class="chapter" data-level="12.6" data-path="pvalues.html"><a href="pvalues.html#criticisms-of-p-values"><i class="fa fa-check"></i><b>12.6</b> Criticisms of p-values</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="jaxwest7.html"><a href="jaxwest7.html"><i class="fa fa-check"></i><b>13</b> Reproducible Data Munging in R</a><ul>
<li class="chapter" data-level="13.1" data-path="jaxwest7.html"><a href="jaxwest7.html#jaxwest7-data"><i class="fa fa-check"></i><b>13.1</b> Jaxwest7 data</a><ul>
<li class="chapter" data-level="13.1.1" data-path="jaxwest7.html"><a href="jaxwest7.html#inspect-the-source-data"><i class="fa fa-check"></i><b>13.1.1</b> Inspect the source data</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="jaxwest7.html"><a href="jaxwest7.html#munge-the-glucose-data-into-r"><i class="fa fa-check"></i><b>13.2</b> Munge the glucose data into R</a></li>
<li class="chapter" data-level="13.3" data-path="jaxwest7.html"><a href="jaxwest7.html#munge-the-bodyweight-data"><i class="fa fa-check"></i><b>13.3</b> Munge the bodyweight data</a></li>
<li class="chapter" data-level="13.4" data-path="jaxwest7.html"><a href="jaxwest7.html#merge-and-explore-the-glucose-and-bw-data"><i class="fa fa-check"></i><b>13.4</b> Merge and explore the glucose and bw data</a></li>
<li class="chapter" data-level="13.5" data-path="jaxwest7.html"><a href="jaxwest7.html#summary-1"><i class="fa fa-check"></i><b>13.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="binomial.html"><a href="binomial.html"><i class="fa fa-check"></i><b>14</b> The Binomial Distribution</a><ul>
<li class="chapter" data-level="14.1" data-path="binomial.html"><a href="binomial.html#dbinom"><i class="fa fa-check"></i><b>14.1</b> dbinom</a></li>
<li class="chapter" data-level="14.2" data-path="binomial.html"><a href="binomial.html#pbinom"><i class="fa fa-check"></i><b>14.2</b> pbinom</a></li>
<li class="chapter" data-level="14.3" data-path="binomial.html"><a href="binomial.html#qbinom"><i class="fa fa-check"></i><b>14.3</b> qbinom</a></li>
<li class="chapter" data-level="14.4" data-path="binomial.html"><a href="binomial.html#rbinom"><i class="fa fa-check"></i><b>14.4</b> rbinom</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="poisson.html"><a href="poisson.html"><i class="fa fa-check"></i><b>15</b> The Poisson Distribution</a><ul>
<li class="chapter" data-level="15.1" data-path="poisson.html"><a href="poisson.html#poisson-events"><i class="fa fa-check"></i><b>15.1</b> Poisson Events</a></li>
<li class="chapter" data-level="15.2" data-path="poisson.html"><a href="poisson.html#dpois"><i class="fa fa-check"></i><b>15.2</b> dpois</a></li>
<li class="chapter" data-level="15.3" data-path="poisson.html"><a href="poisson.html#ppois"><i class="fa fa-check"></i><b>15.3</b> ppois</a></li>
<li class="chapter" data-level="15.4" data-path="poisson.html"><a href="poisson.html#rpois"><i class="fa fa-check"></i><b>15.4</b> rpois</a></li>
<li class="chapter" data-level="15.5" data-path="poisson.html"><a href="poisson.html#overdispersion"><i class="fa fa-check"></i><b>15.5</b> Overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="normal.html"><a href="normal.html"><i class="fa fa-check"></i><b>16</b> The Normal Distribution</a><ul>
<li class="chapter" data-level="16.0.1" data-path="normal.html"><a href="normal.html#the-standard-normal"><i class="fa fa-check"></i><b>16.0.1</b> The Standard Normal</a></li>
<li class="chapter" data-level="16.1" data-path="normal.html"><a href="normal.html#dnorm"><i class="fa fa-check"></i><b>16.1</b> dnorm</a></li>
<li class="chapter" data-level="16.2" data-path="normal.html"><a href="normal.html#pnorm"><i class="fa fa-check"></i><b>16.2</b> pnorm</a><ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#calculating-p-values-using-pnorm"><i class="fa fa-check"></i>Calculating “p-values”" using pnorm</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#calculating-percentiles-using-pnorm"><i class="fa fa-check"></i>Calculating percentiles using pnorm</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="normal.html"><a href="normal.html#qnorm"><i class="fa fa-check"></i><b>16.3</b> qnorm</a></li>
<li class="chapter" data-level="16.4" data-path="normal.html"><a href="normal.html#rnorm"><i class="fa fa-check"></i><b>16.4</b> rnorm</a><ul>
<li class="chapter" data-level="16.4.1" data-path="normal.html"><a href="normal.html#plotting-histograms-of-some-rnorm-samples"><i class="fa fa-check"></i><b>16.4.1</b> Plotting histograms of some rnorm samples</a></li>
<li class="chapter" data-level="16.4.2" data-path="normal.html"><a href="normal.html#bins-and-binwidth"><i class="fa fa-check"></i><b>16.4.2</b> Bins and Binwidth</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="categorical.html"><a href="categorical.html"><i class="fa fa-check"></i><b>17</b> Statistics for Categorical Data</a><ul>
<li class="chapter" data-level="17.1" data-path="categorical.html"><a href="categorical.html#types-of-categorical-data"><i class="fa fa-check"></i><b>17.1</b> Types of categorical data</a><ul>
<li class="chapter" data-level="17.1.1" data-path="categorical.html"><a href="categorical.html#proportions"><i class="fa fa-check"></i><b>17.1.1</b> Proportions</a></li>
<li class="chapter" data-level="17.1.2" data-path="categorical.html"><a href="categorical.html#frequencies"><i class="fa fa-check"></i><b>17.1.2</b> Frequencies</a></li>
<li class="chapter" data-level="17.1.3" data-path="categorical.html"><a href="categorical.html#associations"><i class="fa fa-check"></i><b>17.1.3</b> Associations</a></li>
<li class="chapter" data-level="17.1.4" data-path="categorical.html"><a href="categorical.html#statistics-covered-here"><i class="fa fa-check"></i><b>17.1.4</b> Statistics Covered Here</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="categorical.html"><a href="categorical.html#exact-v-asymptotic-calculations-of-p-values"><i class="fa fa-check"></i><b>17.2</b> Exact v Asymptotic Calculations of p-values</a><ul>
<li class="chapter" data-level="17.2.1" data-path="categorical.html"><a href="categorical.html#choosing-exact-or-asymptotic"><i class="fa fa-check"></i><b>17.2.1</b> Choosing exact or asymptotic</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="categorical.html"><a href="categorical.html#overview-of-the-types-of-hypothesis-testing"><i class="fa fa-check"></i><b>17.3</b> Overview of the types of hypothesis testing</a><ul>
<li class="chapter" data-level="17.3.1" data-path="categorical.html"><a href="categorical.html#proportion-analysis"><i class="fa fa-check"></i><b>17.3.1</b> Proportion analysis</a></li>
<li class="chapter" data-level="17.3.2" data-path="categorical.html"><a href="categorical.html#goodness-of-fit-testing"><i class="fa fa-check"></i><b>17.3.2</b> Goodness of fit testing</a></li>
<li class="chapter" data-level="17.3.3" data-path="categorical.html"><a href="categorical.html#contingency-analysis"><i class="fa fa-check"></i><b>17.3.3</b> Contingency Analysis</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="categorical.html"><a href="categorical.html#comparing-proportions"><i class="fa fa-check"></i><b>17.4</b> Comparing proportions</a><ul>
<li class="chapter" data-level="17.4.1" data-path="categorical.html"><a href="categorical.html#a-mouse-t-cell-pilot-experiment-the-cytokine-inducible-antigen-gradstudin"><i class="fa fa-check"></i><b>17.4.1</b> A Mouse T Cell Pilot Experiment: The Cytokine-inducible antigen gradstudin</a></li>
<li class="chapter" data-level="17.4.2" data-path="categorical.html"><a href="categorical.html#calculating-proportions"><i class="fa fa-check"></i><b>17.4.2</b> Calculating Proportions</a></li>
<li class="chapter" data-level="17.4.3" data-path="categorical.html"><a href="categorical.html#what-a-proportion-estimates"><i class="fa fa-check"></i><b>17.4.3</b> What A Proportion Estimates</a></li>
<li class="chapter" data-level="17.4.4" data-path="categorical.html"><a href="categorical.html#confidence-intervals-of-proportions"><i class="fa fa-check"></i><b>17.4.4</b> Confidence Intervals of Proportions</a></li>
<li class="chapter" data-level="17.4.5" data-path="categorical.html"><a href="categorical.html#a-one-sample-proportion-test"><i class="fa fa-check"></i><b>17.4.5</b> A One-Sample Proportion Test</a></li>
<li class="chapter" data-level="17.4.6" data-path="categorical.html"><a href="categorical.html#an-exact-test-for-one-proportion"><i class="fa fa-check"></i><b>17.4.6</b> An exact test for one proportion</a></li>
<li class="chapter" data-level="17.4.7" data-path="categorical.html"><a href="categorical.html#comparing-two-proportions"><i class="fa fa-check"></i><b>17.4.7</b> Comparing Two Proportions</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="categorical.html"><a href="categorical.html#exact-tests-for-two-proportions"><i class="fa fa-check"></i><b>17.5</b> Exact tests for two proportions</a></li>
<li class="chapter" data-level="17.6" data-path="categorical.html"><a href="categorical.html#goodness-of-fit-tests"><i class="fa fa-check"></i><b>17.6</b> Goodness of fit Tests</a><ul>
<li class="chapter" data-level="17.6.1" data-path="categorical.html"><a href="categorical.html#an-exact-goodness-of-fit-test"><i class="fa fa-check"></i><b>17.6.1</b> An Exact Goodness of Fit test</a></li>
<li class="chapter" data-level="17.6.2" data-path="categorical.html"><a href="categorical.html#an-approximate-goodness-of-fit-test"><i class="fa fa-check"></i><b>17.6.2</b> An Approximate Goodness of Fit test</a></li>
</ul></li>
<li class="chapter" data-level="17.7" data-path="categorical.html"><a href="categorical.html#contingency-testing"><i class="fa fa-check"></i><b>17.7</b> Contingency Testing</a><ul>
<li class="chapter" data-level="17.7.1" data-path="categorical.html"><a href="categorical.html#interpretation-of-contingency-results"><i class="fa fa-check"></i><b>17.7.1</b> Interpretation of Contingency Results</a></li>
<li class="chapter" data-level="17.7.2" data-path="categorical.html"><a href="categorical.html#write-up-4"><i class="fa fa-check"></i><b>17.7.2</b> Write Up</a></li>
<li class="chapter" data-level="17.7.3" data-path="categorical.html"><a href="categorical.html#interpretation-of-chi-square-output"><i class="fa fa-check"></i><b>17.7.3</b> Interpretation of chi-square output</a></li>
<li class="chapter" data-level="17.7.4" data-path="categorical.html"><a href="categorical.html#write-up-5"><i class="fa fa-check"></i><b>17.7.4</b> Write Up</a></li>
<li class="chapter" data-level="17.7.5" data-path="categorical.html"><a href="categorical.html#which-contingency-test-is-best"><i class="fa fa-check"></i><b>17.7.5</b> Which contingency test is best?</a></li>
<li class="chapter" data-level="17.7.6" data-path="categorical.html"><a href="categorical.html#higher-dimension-contingency-analysis"><i class="fa fa-check"></i><b>17.7.6</b> Higher dimension contingency analysis</a></li>
<li class="chapter" data-level="17.7.7" data-path="categorical.html"><a href="categorical.html#other-experimental-designs-involving-categorical-data"><i class="fa fa-check"></i><b>17.7.7</b> Other experimental designs involving categorical data</a></li>
</ul></li>
<li class="chapter" data-level="17.8" data-path="categorical.html"><a href="categorical.html#power-analysis-for-proportion-tests"><i class="fa fa-check"></i><b>17.8</b> Power analysis for proportion tests</a></li>
<li class="chapter" data-level="17.9" data-path="categorical.html"><a href="categorical.html#power-analysis-functions-for-proportion-tests"><i class="fa fa-check"></i><b>17.9</b> Power analysis functions for proportion tests</a></li>
<li class="chapter" data-level="17.10" data-path="categorical.html"><a href="categorical.html#graphing-proportions"><i class="fa fa-check"></i><b>17.10</b> Graphing Proportions</a></li>
<li class="chapter" data-level="17.11" data-path="categorical.html"><a href="categorical.html#key-takeaways"><i class="fa fa-check"></i><b>17.11</b> Key Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chisquare.html"><a href="chisquare.html"><i class="fa fa-check"></i><b>18</b> The Chi-square Distribution</a><ul>
<li class="chapter" data-level="18.1" data-path="chisquare.html"><a href="chisquare.html#background"><i class="fa fa-check"></i><b>18.1</b> Background</a></li>
<li class="chapter" data-level="18.2" data-path="chisquare.html"><a href="chisquare.html#dchisq"><i class="fa fa-check"></i><b>18.2</b> dchisq</a></li>
<li class="chapter" data-level="18.3" data-path="chisquare.html"><a href="chisquare.html#pchisq"><i class="fa fa-check"></i><b>18.3</b> pchisq</a><ul>
<li class="chapter" data-level="18.3.1" data-path="chisquare.html"><a href="chisquare.html#calculating-p-values-from-pchisq"><i class="fa fa-check"></i><b>18.3.1</b> Calculating p-values from pchisq</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="chisquare.html"><a href="chisquare.html#qchisq"><i class="fa fa-check"></i><b>18.4</b> qchisq</a></li>
<li class="chapter" data-level="18.5" data-path="chisquare.html"><a href="chisquare.html#rchisq"><i class="fa fa-check"></i><b>18.5</b> rchisq</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="nonparametrics.html"><a href="nonparametrics.html"><i class="fa fa-check"></i><b>19</b> Nonparametric Statistical Tests</a><ul>
<li class="chapter" data-level="19.1" data-path="nonparametrics.html"><a href="nonparametrics.html#nonparametric-sampling-distributions"><i class="fa fa-check"></i><b>19.1</b> Nonparametric sampling distributions</a></li>
<li class="chapter" data-level="19.2" data-path="nonparametrics.html"><a href="nonparametrics.html#experiments-involving-discrete-data"><i class="fa fa-check"></i><b>19.2</b> Experiments involving discrete data</a><ul>
<li class="chapter" data-level="19.2.1" data-path="nonparametrics.html"><a href="nonparametrics.html#ordered-data-1"><i class="fa fa-check"></i><b>19.2.1</b> Ordered data</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="nonparametrics.html"><a href="nonparametrics.html#experiments-involving-deviant-data"><i class="fa fa-check"></i><b>19.3</b> Experiments involving deviant Data</a></li>
<li class="chapter" data-level="19.4" data-path="nonparametrics.html"><a href="nonparametrics.html#sign-test"><i class="fa fa-check"></i><b>19.4</b> Sign Test</a><ul>
<li class="chapter" data-level="19.4.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-1"><i class="fa fa-check"></i><b>19.4.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.4.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-6"><i class="fa fa-check"></i><b>19.4.2</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-test-for-one-group"><i class="fa fa-check"></i><b>19.5</b> Wilcoxon Sign Rank Test for One Group</a><ul>
<li class="chapter" data-level="19.5.1" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-experimental-designs"><i class="fa fa-check"></i><b>19.5.1</b> Wilcoxon Sign Rank Experimental Designs</a></li>
<li class="chapter" data-level="19.5.2" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-2"><i class="fa fa-check"></i><b>19.5.2</b> Interpretation</a></li>
<li class="chapter" data-level="19.5.3" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-7"><i class="fa fa-check"></i><b>19.5.3</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-mann-whitney-rank-sum-test-for-2-independent-groups"><i class="fa fa-check"></i><b>19.6</b> Wilcoxon Mann Whitney Rank Sum Test for 2 independent groups</a><ul>
<li class="chapter" data-level="19.6.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-3"><i class="fa fa-check"></i><b>19.6.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.6.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-8"><i class="fa fa-check"></i><b>19.6.2</b> Write Up</a></li>
<li class="chapter" data-level="19.6.3" data-path="nonparametrics.html"><a href="nonparametrics.html#plot"><i class="fa fa-check"></i><b>19.6.3</b> Plot</a></li>
</ul></li>
<li class="chapter" data-level="19.7" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-test-for-paired-groups"><i class="fa fa-check"></i><b>19.7</b> Wilcoxon Sign Rank Test for paired groups</a><ul>
<li class="chapter" data-level="19.7.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-4"><i class="fa fa-check"></i><b>19.7.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.7.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-9"><i class="fa fa-check"></i><b>19.7.2</b> Write up</a></li>
<li class="chapter" data-level="19.7.3" data-path="nonparametrics.html"><a href="nonparametrics.html#plot-1"><i class="fa fa-check"></i><b>19.7.3</b> Plot</a></li>
</ul></li>
<li class="chapter" data-level="19.8" data-path="nonparametrics.html"><a href="nonparametrics.html#kruskal-wallis"><i class="fa fa-check"></i><b>19.8</b> Kruskal-Wallis</a><ul>
<li class="chapter" data-level="19.8.1" data-path="nonparametrics.html"><a href="nonparametrics.html#the-experimental-design"><i class="fa fa-check"></i><b>19.8.1</b> The experimental design</a></li>
<li class="chapter" data-level="19.8.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-10"><i class="fa fa-check"></i><b>19.8.2</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.9" data-path="nonparametrics.html"><a href="nonparametrics.html#friedman-test"><i class="fa fa-check"></i><b>19.9</b> Friedman test</a><ul>
<li class="chapter" data-level="19.9.1" data-path="nonparametrics.html"><a href="nonparametrics.html#blocked-experimental-design"><i class="fa fa-check"></i><b>19.9.1</b> Blocked experimental design</a></li>
<li class="chapter" data-level="19.9.2" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-5"><i class="fa fa-check"></i><b>19.9.2</b> Interpretation</a></li>
<li class="chapter" data-level="19.9.3" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-11"><i class="fa fa-check"></i><b>19.9.3</b> Write up</a></li>
</ul></li>
<li class="chapter" data-level="19.10" data-path="nonparametrics.html"><a href="nonparametrics.html#nonparametric-power-calculations"><i class="fa fa-check"></i><b>19.10</b> Nonparametric power calculations</a><ul>
<li class="chapter" data-level="19.10.1" data-path="nonparametrics.html"><a href="nonparametrics.html#how-it-works"><i class="fa fa-check"></i><b>19.10.1</b> How it works</a></li>
<li class="chapter" data-level="19.10.2" data-path="nonparametrics.html"><a href="nonparametrics.html#simulating-response-data"><i class="fa fa-check"></i><b>19.10.2</b> Simulating response data</a></li>
<li class="chapter" data-level="19.10.3" data-path="nonparametrics.html"><a href="nonparametrics.html#an-example"><i class="fa fa-check"></i><b>19.10.3</b> An example</a></li>
<li class="chapter" data-level="19.10.4" data-path="nonparametrics.html"><a href="nonparametrics.html#nonpara.pwr"><i class="fa fa-check"></i><b>19.10.4</b> nonpara.pwr</a></li>
</ul></li>
<li class="chapter" data-level="19.11" data-path="nonparametrics.html"><a href="nonparametrics.html#summary-2"><i class="fa fa-check"></i><b>19.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="signrank.html"><a href="signrank.html"><i class="fa fa-check"></i><b>20</b> Signed Rank Distribution</a><ul>
<li class="chapter" data-level="20.1" data-path="signrank.html"><a href="signrank.html#transformation-of-data-into-sign-ranks"><i class="fa fa-check"></i><b>20.1</b> Transformation of data into sign ranks</a><ul>
<li class="chapter" data-level="20.1.1" data-path="signrank.html"><a href="signrank.html#for-a-one-group-sample"><i class="fa fa-check"></i><b>20.1.1</b> For a one group sample</a></li>
<li class="chapter" data-level="20.1.2" data-path="signrank.html"><a href="signrank.html#for-a-paired-sample"><i class="fa fa-check"></i><b>20.1.2</b> For a paired sample</a></li>
<li class="chapter" data-level="20.1.3" data-path="signrank.html"><a href="signrank.html#the-sign-rank-test-statistic-in-r"><i class="fa fa-check"></i><b>20.1.3</b> The sign rank test statistic in R</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="signrank.html"><a href="signrank.html#rs-four-sign-rank-distribution-functions"><i class="fa fa-check"></i><b>20.2</b> R’s Four Sign Rank Distribution Functions</a><ul>
<li class="chapter" data-level="20.2.1" data-path="signrank.html"><a href="signrank.html#dsignrank"><i class="fa fa-check"></i><b>20.2.1</b> dsignrank</a></li>
<li class="chapter" data-level="20.2.2" data-path="signrank.html"><a href="signrank.html#psignrank"><i class="fa fa-check"></i><b>20.2.2</b> psignrank</a></li>
<li class="chapter" data-level="20.2.3" data-path="signrank.html"><a href="signrank.html#qsignrank"><i class="fa fa-check"></i><b>20.2.3</b> qsignrank</a></li>
<li class="chapter" data-level="20.2.4" data-path="signrank.html"><a href="signrank.html#rsignrank"><i class="fa fa-check"></i><b>20.2.4</b> rsignrank</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="ranksum.html"><a href="ranksum.html"><i class="fa fa-check"></i><b>21</b> Rank Sum Distribution</a><ul>
<li class="chapter" data-level="21.0.1" data-path="ranksum.html"><a href="ranksum.html#transformation-of-data-into-rank-summs"><i class="fa fa-check"></i><b>21.0.1</b> Transformation of data into rank summs</a></li>
<li class="chapter" data-level="21.0.2" data-path="ranksum.html"><a href="ranksum.html#the-sign-rank-test-statistic-in-r-1"><i class="fa fa-check"></i><b>21.0.2</b> The sign rank test statistic in R</a></li>
<li class="chapter" data-level="21.1" data-path="ranksum.html"><a href="ranksum.html#rs-four-sign-rank-distribution-functions-1"><i class="fa fa-check"></i><b>21.1</b> R’s Four Sign Rank Distribution Functions</a><ul>
<li class="chapter" data-level="21.1.1" data-path="ranksum.html"><a href="ranksum.html#dwilcox"><i class="fa fa-check"></i><b>21.1.1</b> dwilcox</a></li>
<li class="chapter" data-level="21.1.2" data-path="ranksum.html"><a href="ranksum.html#pwilcox"><i class="fa fa-check"></i><b>21.1.2</b> pwilcox</a></li>
<li class="chapter" data-level="21.1.3" data-path="ranksum.html"><a href="ranksum.html#qwilcox"><i class="fa fa-check"></i><b>21.1.3</b> qwilcox</a></li>
<li class="chapter" data-level="21.1.4" data-path="ranksum.html"><a href="ranksum.html#rwilcox"><i class="fa fa-check"></i><b>21.1.4</b> rwilcox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="ttests.html"><a href="ttests.html"><i class="fa fa-check"></i><b>22</b> The t-tests</a><ul>
<li class="chapter" data-level="22.1" data-path="ttests.html"><a href="ttests.html#data-assumptions-for-t-tests"><i class="fa fa-check"></i><b>22.1</b> Data assumptions for t-tests</a></li>
<li class="chapter" data-level="22.2" data-path="ttests.html"><a href="ttests.html#the-t-statistic"><i class="fa fa-check"></i><b>22.2</b> The t Statistic</a><ul>
<li class="chapter" data-level="22.2.1" data-path="ttests.html"><a href="ttests.html#one-sample-t-tests"><i class="fa fa-check"></i><b>22.2.1</b> One sample t tests</a></li>
<li class="chapter" data-level="22.2.2" data-path="ttests.html"><a href="ttests.html#unpaired-t-tests"><i class="fa fa-check"></i><b>22.2.2</b> Unpaired t tests</a></li>
<li class="chapter" data-level="22.2.3" data-path="ttests.html"><a href="ttests.html#paired-t-tests"><i class="fa fa-check"></i><b>22.2.3</b> Paired t tests</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="ttests.html"><a href="ttests.html#t-test-hypotheses"><i class="fa fa-check"></i><b>22.3</b> t Test Hypotheses</a><ul>
<li class="chapter" data-level="22.3.1" data-path="ttests.html"><a href="ttests.html#one-sided-or-two-sided"><i class="fa fa-check"></i><b>22.3.1</b> One-sided or two-sided??</a></li>
<li class="chapter" data-level="22.3.2" data-path="ttests.html"><a href="ttests.html#one-sample-hypotheses"><i class="fa fa-check"></i><b>22.3.2</b> One sample hypotheses</a></li>
<li class="chapter" data-level="22.3.3" data-path="ttests.html"><a href="ttests.html#unpaired-hypotheses"><i class="fa fa-check"></i><b>22.3.3</b> Unpaired hypotheses</a></li>
<li class="chapter" data-level="22.3.4" data-path="ttests.html"><a href="ttests.html#paired-hypotheses"><i class="fa fa-check"></i><b>22.3.4</b> Paired hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="ttests.html"><a href="ttests.html#confidence-intervals-of-means"><i class="fa fa-check"></i><b>22.4</b> Confidence Intervals of Means</a></li>
<li class="chapter" data-level="22.5" data-path="ttests.html"><a href="ttests.html#parameters-small-samples-and-reliability"><i class="fa fa-check"></i><b>22.5</b> Parameters, small samples, and reliability</a><ul>
<li class="chapter" data-level="22.5.1" data-path="ttests.html"><a href="ttests.html#reporting-sd-or-sem"><i class="fa fa-check"></i><b>22.5.1</b> Reporting SD or SEM?</a></li>
</ul></li>
<li class="chapter" data-level="22.6" data-path="ttests.html"><a href="ttests.html#t-tests-running-the-analysis"><i class="fa fa-check"></i><b>22.6</b> t Tests: Running the analysis</a><ul>
<li class="chapter" data-level="22.6.1" data-path="ttests.html"><a href="ttests.html#one-sample-t-test"><i class="fa fa-check"></i><b>22.6.1</b> One sample t test</a></li>
<li class="chapter" data-level="22.6.2" data-path="ttests.html"><a href="ttests.html#unpaired-t-test"><i class="fa fa-check"></i><b>22.6.2</b> Unpaired t test</a></li>
<li class="chapter" data-level="22.6.3" data-path="ttests.html"><a href="ttests.html#paired-t-test"><i class="fa fa-check"></i><b>22.6.3</b> Paired t Test</a></li>
</ul></li>
<li class="chapter" data-level="22.7" data-path="ttests.html"><a href="ttests.html#plotting-t-tests"><i class="fa fa-check"></i><b>22.7</b> Plotting t Tests</a><ul>
<li class="chapter" data-level="22.7.1" data-path="ttests.html"><a href="ttests.html#one-sample"><i class="fa fa-check"></i><b>22.7.1</b> One-sample</a></li>
<li class="chapter" data-level="22.7.2" data-path="ttests.html"><a href="ttests.html#unpaired"><i class="fa fa-check"></i><b>22.7.2</b> Unpaired</a></li>
<li class="chapter" data-level="22.7.3" data-path="ttests.html"><a href="ttests.html#paired"><i class="fa fa-check"></i><b>22.7.3</b> Paired</a></li>
</ul></li>
<li class="chapter" data-level="22.8" data-path="ttests.html"><a href="ttests.html#t-test-power"><i class="fa fa-check"></i><b>22.8</b> t Test Power</a><ul>
<li class="chapter" data-level="22.8.1" data-path="ttests.html"><a href="ttests.html#pwr.t.test"><i class="fa fa-check"></i><b>22.8.1</b> pwr.t.test</a></li>
<li class="chapter" data-level="22.8.2" data-path="ttests.html"><a href="ttests.html#interpretation-9"><i class="fa fa-check"></i><b>22.8.2</b> Interpretation</a></li>
<li class="chapter" data-level="22.8.3" data-path="ttests.html"><a href="ttests.html#t-pwr-a-monte-carlo-method"><i class="fa fa-check"></i><b>22.8.3</b> t-pwr: A Monte Carlo method</a></li>
</ul></li>
<li class="chapter" data-level="22.9" data-path="ttests.html"><a href="ttests.html#summary-3"><i class="fa fa-check"></i><b>22.9</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="ttestmc.html"><a href="ttestmc.html"><i class="fa fa-check"></i><b>23</b> Statistical design of t-tests</a><ul>
<li class="chapter" data-level="23.1" data-path="ttestmc.html"><a href="ttestmc.html#about-this-chapter"><i class="fa fa-check"></i><b>23.1</b> About this chapter</a><ul>
<li class="chapter" data-level="23.1.1" data-path="ttestmc.html"><a href="ttestmc.html#overview-of-the-monte-carlo"><i class="fa fa-check"></i><b>23.1.1</b> Overview of the Monte Carlo</a></li>
<li class="chapter" data-level="23.1.2" data-path="ttestmc.html"><a href="ttestmc.html#tldr-on-data-simulation"><i class="fa fa-check"></i><b>23.1.2</b> tl;dr on data simulation</a></li>
<li class="chapter" data-level="23.1.3" data-path="ttestmc.html"><a href="ttestmc.html#tldr-on-the-test"><i class="fa fa-check"></i><b>23.1.3</b> tl;dr on the test</a></li>
<li class="chapter" data-level="23.1.4" data-path="ttestmc.html"><a href="ttestmc.html#changing-n"><i class="fa fa-check"></i><b>23.1.4</b> Changing n</a></li>
<li class="chapter" data-level="23.1.5" data-path="ttestmc.html"><a href="ttestmc.html#diabetes-drug-scenario"><i class="fa fa-check"></i><b>23.1.5</b> Diabetes drug scenario</a></li>
<li class="chapter" data-level="23.1.6" data-path="ttestmc.html"><a href="ttestmc.html#what-would-be-a-scientifically-meaningful-response"><i class="fa fa-check"></i><b>23.1.6</b> What would be a scientifically meaningful response?</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="ttestmc.html"><a href="ttestmc.html#one-sample-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.2</b> One sample t-test Monte Carlo</a><ul>
<li class="chapter" data-level="23.2.1" data-path="ttestmc.html"><a href="ttestmc.html#step-1-2"><i class="fa fa-check"></i><b>23.2.1</b> Step 1</a></li>
<li class="chapter" data-level="23.2.2" data-path="ttestmc.html"><a href="ttestmc.html#step-2-2"><i class="fa fa-check"></i><b>23.2.2</b> Step 2</a></li>
<li class="chapter" data-level="23.2.3" data-path="ttestmc.html"><a href="ttestmc.html#step-3-2"><i class="fa fa-check"></i><b>23.2.3</b> Step 3</a></li>
<li class="chapter" data-level="23.2.4" data-path="ttestmc.html"><a href="ttestmc.html#step-4-2"><i class="fa fa-check"></i><b>23.2.4</b> Step 4</a></li>
<li class="chapter" data-level="23.2.5" data-path="ttestmc.html"><a href="ttestmc.html#step-5-2"><i class="fa fa-check"></i><b>23.2.5</b> Step 5</a></li>
<li class="chapter" data-level="23.2.6" data-path="ttestmc.html"><a href="ttestmc.html#step-6-2"><i class="fa fa-check"></i><b>23.2.6</b> Step 6</a></li>
<li class="chapter" data-level="23.2.7" data-path="ttestmc.html"><a href="ttestmc.html#step-7-1"><i class="fa fa-check"></i><b>23.2.7</b> Step 7</a></li>
</ul></li>
<li class="chapter" data-level="23.3" data-path="ttestmc.html"><a href="ttestmc.html#unpaired-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.3</b> Unpaired t-test Monte Carlo</a><ul>
<li class="chapter" data-level="23.3.1" data-path="ttestmc.html"><a href="ttestmc.html#step-1-3"><i class="fa fa-check"></i><b>23.3.1</b> Step 1</a></li>
<li class="chapter" data-level="23.3.2" data-path="ttestmc.html"><a href="ttestmc.html#step-2-3"><i class="fa fa-check"></i><b>23.3.2</b> Step 2</a></li>
<li class="chapter" data-level="23.3.3" data-path="ttestmc.html"><a href="ttestmc.html#step-3-3"><i class="fa fa-check"></i><b>23.3.3</b> Step 3</a></li>
<li class="chapter" data-level="23.3.4" data-path="ttestmc.html"><a href="ttestmc.html#step-4-3"><i class="fa fa-check"></i><b>23.3.4</b> Step 4</a></li>
<li class="chapter" data-level="23.3.5" data-path="ttestmc.html"><a href="ttestmc.html#step-5-3"><i class="fa fa-check"></i><b>23.3.5</b> Step 5</a></li>
<li class="chapter" data-level="23.3.6" data-path="ttestmc.html"><a href="ttestmc.html#step-6-3"><i class="fa fa-check"></i><b>23.3.6</b> Step 6</a></li>
<li class="chapter" data-level="23.3.7" data-path="ttestmc.html"><a href="ttestmc.html#step-7-2"><i class="fa fa-check"></i><b>23.3.7</b> Step 7</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="ttestmc.html"><a href="ttestmc.html#paired-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.4</b> Paired t-test Monte Carlo</a><ul>
<li class="chapter" data-level="23.4.1" data-path="ttestmc.html"><a href="ttestmc.html#step-1-4"><i class="fa fa-check"></i><b>23.4.1</b> Step 1</a></li>
<li class="chapter" data-level="23.4.2" data-path="ttestmc.html"><a href="ttestmc.html#step-2-4"><i class="fa fa-check"></i><b>23.4.2</b> Step 2</a></li>
<li class="chapter" data-level="23.4.3" data-path="ttestmc.html"><a href="ttestmc.html#step-3-4"><i class="fa fa-check"></i><b>23.4.3</b> Step 3</a></li>
</ul></li>
<li class="chapter" data-level="23.5" data-path="ttestmc.html"><a href="ttestmc.html#step-4-4"><i class="fa fa-check"></i><b>23.5</b> Step 4</a><ul>
<li class="chapter" data-level="23.5.1" data-path="ttestmc.html"><a href="ttestmc.html#step-5-4"><i class="fa fa-check"></i><b>23.5.1</b> Step 5</a></li>
<li class="chapter" data-level="23.5.2" data-path="ttestmc.html"><a href="ttestmc.html#step-6-4"><i class="fa fa-check"></i><b>23.5.2</b> Step 6</a></li>
<li class="chapter" data-level="23.5.3" data-path="ttestmc.html"><a href="ttestmc.html#step-7-3"><i class="fa fa-check"></i><b>23.5.3</b> Step 7</a></li>
</ul></li>
<li class="chapter" data-level="23.6" data-path="ttestmc.html"><a href="ttestmc.html#comparison-to-pwr-tests"><i class="fa fa-check"></i><b>23.6</b> Comparison to pwr tests</a></li>
<li class="chapter" data-level="23.7" data-path="ttestmc.html"><a href="ttestmc.html#dt"><i class="fa fa-check"></i><b>23.7</b> dt</a></li>
<li class="chapter" data-level="23.8" data-path="ttestmc.html"><a href="ttestmc.html#pt"><i class="fa fa-check"></i><b>23.8</b> pt</a></li>
<li class="chapter" data-level="23.9" data-path="ttestmc.html"><a href="ttestmc.html#qt"><i class="fa fa-check"></i><b>23.9</b> qt</a></li>
<li class="chapter" data-level="23.10" data-path="ttestmc.html"><a href="ttestmc.html#rt"><i class="fa fa-check"></i><b>23.10</b> rt</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="simcorrelation.html"><a href="simcorrelation.html"><i class="fa fa-check"></i><b>24</b> Simulating correlated variables</a><ul>
<li class="chapter" data-level="24.1" data-path="simcorrelation.html"><a href="simcorrelation.html#estimating-correlation-between-two-variables"><i class="fa fa-check"></i><b>24.1</b> Estimating correlation between two variables</a></li>
<li class="chapter" data-level="24.2" data-path="simcorrelation.html"><a href="simcorrelation.html#simulating-correlated-variables"><i class="fa fa-check"></i><b>24.2</b> Simulating correlated variables</a></li>
<li class="chapter" data-level="24.3" data-path="simcorrelation.html"><a href="simcorrelation.html#monte-carlo-simulation"><i class="fa fa-check"></i><b>24.3</b> Monte Carlo simulation</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="introanova.html"><a href="introanova.html"><i class="fa fa-check"></i><b>25</b> Introduction to ANOVA</a><ul>
<li class="chapter" data-level="25.1" data-path="introanova.html"><a href="introanova.html#assumptions"><i class="fa fa-check"></i><b>25.1</b> Assumptions</a></li>
<li class="chapter" data-level="25.2" data-path="introanova.html"><a href="introanova.html#types-of-designs"><i class="fa fa-check"></i><b>25.2</b> Types of designs</a></li>
<li class="chapter" data-level="25.3" data-path="introanova.html"><a href="introanova.html#jargon-factors-and-levels"><i class="fa fa-check"></i><b>25.3</b> Jargon: Factors and levels</a><ul>
<li class="chapter" data-level="25.3.1" data-path="introanova.html"><a href="introanova.html#woring-with-factors-in-r"><i class="fa fa-check"></i><b>25.3.1</b> Woring with factors in R</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="introanova.html"><a href="introanova.html#anova-models-one--two--and-three-way"><i class="fa fa-check"></i><b>25.4</b> ANOVA models: One-, Two-, and Three-way</a></li>
<li class="chapter" data-level="25.5" data-path="introanova.html"><a href="introanova.html#inference"><i class="fa fa-check"></i><b>25.5</b> Inference</a><ul>
<li class="chapter" data-level="25.5.1" data-path="introanova.html"><a href="introanova.html#a-quick-peek-at-posthoc-testing"><i class="fa fa-check"></i><b>25.5.1</b> A quick peek at posthoc testing</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="introanova.html"><a href="introanova.html#anova-calculations"><i class="fa fa-check"></i><b>25.6</b> ANOVA calculations</a><ul>
<li class="chapter" data-level="25.6.1" data-path="introanova.html"><a href="introanova.html#sums-of-squares-partitioning"><i class="fa fa-check"></i><b>25.6.1</b> Sums of Squares partitioning</a></li>
<li class="chapter" data-level="25.6.2" data-path="introanova.html"><a href="introanova.html#the-anova-table"><i class="fa fa-check"></i><b>25.6.2</b> The ANOVA table</a></li>
<li class="chapter" data-level="25.6.3" data-path="introanova.html"><a href="introanova.html#post-hoc-group-comparisons"><i class="fa fa-check"></i><b>25.6.3</b> Post-hoc group comparisons</a></li>
</ul></li>
<li class="chapter" data-level="25.7" data-path="introanova.html"><a href="introanova.html#completely-randomized-or-related-measures"><i class="fa fa-check"></i><b>25.7</b> Completely randomized or related measures</a><ul>
<li class="chapter" data-level="25.7.1" data-path="introanova.html"><a href="introanova.html#the-problem-of-lost-data-in-related-measures-designs"><i class="fa fa-check"></i><b>25.7.1</b> The problem of lost data in related measures designs</a></li>
</ul></li>
<li class="chapter" data-level="25.8" data-path="introanova.html"><a href="introanova.html#two-way-anova"><i class="fa fa-check"></i><b>25.8</b> Two-way ANOVA</a></li>
<li class="chapter" data-level="25.9" data-path="introanova.html"><a href="introanova.html#other-anova-models"><i class="fa fa-check"></i><b>25.9</b> Other ANOVA models</a><ul>
<li class="chapter" data-level="25.9.1" data-path="introanova.html"><a href="introanova.html#r-and-anova"><i class="fa fa-check"></i><b>25.9.1</b> R and ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="25.10" data-path="introanova.html"><a href="introanova.html#alternatives-to-anova"><i class="fa fa-check"></i><b>25.10</b> Alternatives to ANOVA</a><ul>
<li class="chapter" data-level="25.10.1" data-path="introanova.html"><a href="introanova.html#screw-anova-just-tell-me-how-to-t-test-everything"><i class="fa fa-check"></i><b>25.10.1</b> Screw ANOVA, Just Tell Me How to t-Test Everything</a></li>
</ul></li>
<li class="chapter" data-level="25.11" data-path="introanova.html"><a href="introanova.html#summary-4"><i class="fa fa-check"></i><b>25.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="fdistr.html"><a href="fdistr.html"><i class="fa fa-check"></i><b>26</b> The F distribution</a><ul>
<li class="chapter" data-level="26.1" data-path="fdistr.html"><a href="fdistr.html#background-1"><i class="fa fa-check"></i><b>26.1</b> Background</a><ul>
<li class="chapter" data-level="26.1.1" data-path="fdistr.html"><a href="fdistr.html#sample-variance-and-fs-pdf"><i class="fa fa-check"></i><b>26.1.1</b> Sample Variance and F’s PDF</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="fdistr.html"><a href="fdistr.html#df"><i class="fa fa-check"></i><b>26.2</b> df</a></li>
<li class="chapter" data-level="26.3" data-path="fdistr.html"><a href="fdistr.html#pf"><i class="fa fa-check"></i><b>26.3</b> pf</a></li>
<li class="chapter" data-level="26.4" data-path="fdistr.html"><a href="fdistr.html#qf"><i class="fa fa-check"></i><b>26.4</b> qf</a></li>
<li class="chapter" data-level="26.5" data-path="fdistr.html"><a href="fdistr.html#rf"><i class="fa fa-check"></i><b>26.5</b> rf</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="onewayanova.html"><a href="onewayanova.html"><i class="fa fa-check"></i><b>27</b> One-way ANOVA Completely Randomized</a><ul>
<li class="chapter" data-level="27.1" data-path="onewayanova.html"><a href="onewayanova.html#using-ezanova"><i class="fa fa-check"></i><b>27.1</b> Using <code>ezANOVA</code></a></li>
<li class="chapter" data-level="27.2" data-path="onewayanova.html"><a href="onewayanova.html#the-chickwt-data-set"><i class="fa fa-check"></i><b>27.2</b> The chickwt data set</a><ul>
<li class="chapter" data-level="27.2.1" data-path="onewayanova.html"><a href="onewayanova.html#inspect-the-data"><i class="fa fa-check"></i><b>27.2.1</b> Inspect the data</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="onewayanova.html"><a href="onewayanova.html#run-the-anova"><i class="fa fa-check"></i><b>27.3</b> Run the ANOVA</a><ul>
<li class="chapter" data-level="27.3.1" data-path="onewayanova.html"><a href="onewayanova.html#run-the-chickwts-one-way-anova"><i class="fa fa-check"></i><b>27.3.1</b> Run the chickwts One Way ANOVA</a></li>
<li class="chapter" data-level="27.3.2" data-path="onewayanova.html"><a href="onewayanova.html#interpreting-the-one-way-cr-anova-output"><i class="fa fa-check"></i><b>27.3.2</b> Interpreting the One-Way CR ANOVA Output</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="onewayanova.html"><a href="onewayanova.html#post-hoc-pairwise-comparisons"><i class="fa fa-check"></i><b>27.4</b> Post hoc pairwise comparisons</a><ul>
<li class="chapter" data-level="27.4.1" data-path="onewayanova.html"><a href="onewayanova.html#range-tests"><i class="fa fa-check"></i><b>27.4.1</b> Range tests</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="onewayanova.html"><a href="onewayanova.html#summary-5"><i class="fa fa-check"></i><b>27.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="onewayRM.html"><a href="onewayRM.html"><i class="fa fa-check"></i><b>28</b> One-way ANOVA Related Measures</a><ul>
<li class="chapter" data-level="28.1" data-path="onewayRM.html"><a href="onewayRM.html#data-prep"><i class="fa fa-check"></i><b>28.1</b> Data prep</a></li>
<li class="chapter" data-level="28.2" data-path="onewayRM.html"><a href="onewayRM.html#data-visualization"><i class="fa fa-check"></i><b>28.2</b> Data visualization</a><ul>
<li class="chapter" data-level="28.2.1" data-path="onewayRM.html"><a href="onewayRM.html#visualize-the-statistical-design"><i class="fa fa-check"></i><b>28.2.1</b> Visualize the statistical design</a></li>
</ul></li>
<li class="chapter" data-level="28.3" data-path="onewayRM.html"><a href="onewayRM.html#the-anova"><i class="fa fa-check"></i><b>28.3</b> The ANOVA</a><ul>
<li class="chapter" data-level="28.3.1" data-path="onewayRM.html"><a href="onewayRM.html#running-ezanova"><i class="fa fa-check"></i><b>28.3.1</b> Running ezANOVA</a></li>
</ul></li>
<li class="chapter" data-level="28.4" data-path="onewayRM.html"><a href="onewayRM.html#interpretation-10"><i class="fa fa-check"></i><b>28.4</b> Interpretation</a></li>
<li class="chapter" data-level="28.5" data-path="onewayRM.html"><a href="onewayRM.html#post-hoc-analysis"><i class="fa fa-check"></i><b>28.5</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="28.6" data-path="onewayRM.html"><a href="onewayRM.html#write-up-12"><i class="fa fa-check"></i><b>28.6</b> Write up</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="twowayCR.html"><a href="twowayCR.html"><i class="fa fa-check"></i><b>29</b> Two-way ANOVA Completely Randomized</a><ul>
<li class="chapter" data-level="29.1" data-path="twowayCR.html"><a href="twowayCR.html#effect-of-strain-and-diet-on-liver"><i class="fa fa-check"></i><b>29.1</b> Effect of Strain and Diet on Liver</a></li>
<li class="chapter" data-level="29.2" data-path="twowayCR.html"><a href="twowayCR.html#the-test"><i class="fa fa-check"></i><b>29.2</b> The test</a></li>
<li class="chapter" data-level="29.3" data-path="twowayCR.html"><a href="twowayCR.html#interpretation-of-2-way-cr-anova-output"><i class="fa fa-check"></i><b>29.3</b> Interpretation of 2 Way CR ANOVA Output</a><ul>
<li class="chapter" data-level="29.3.1" data-path="twowayCR.html"><a href="twowayCR.html#levenes"><i class="fa fa-check"></i><b>29.3.1</b> Levene’s</a></li>
<li class="chapter" data-level="29.3.2" data-path="twowayCR.html"><a href="twowayCR.html#anova-table"><i class="fa fa-check"></i><b>29.3.2</b> ANOVA Table</a></li>
</ul></li>
<li class="chapter" data-level="29.4" data-path="twowayCR.html"><a href="twowayCR.html#post-hoc-multiple-comparisons"><i class="fa fa-check"></i><b>29.4</b> Post Hoc Multiple Comparisons</a><ul>
<li class="chapter" data-level="29.4.1" data-path="twowayCR.html"><a href="twowayCR.html#pairwise.t.tests"><i class="fa fa-check"></i><b>29.4.1</b> Pairwise.t.tests</a></li>
<li class="chapter" data-level="29.4.2" data-path="twowayCR.html"><a href="twowayCR.html#write-up-13"><i class="fa fa-check"></i><b>29.4.2</b> Write Up</a></li>
<li class="chapter" data-level="29.4.3" data-path="twowayCR.html"><a href="twowayCR.html#range-tests-1"><i class="fa fa-check"></i><b>29.4.3</b> Range tests</a></li>
</ul></li>
<li class="chapter" data-level="29.5" data-path="twowayCR.html"><a href="twowayCR.html#summary-6"><i class="fa fa-check"></i><b>29.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="twowayRM.html"><a href="twowayRM.html"><i class="fa fa-check"></i><b>30</b> Two-way ANOVA Related Measures</a><ul>
<li class="chapter" data-level="30.1" data-path="twowayRM.html"><a href="twowayRM.html#cell-culture"><i class="fa fa-check"></i><b>30.1</b> Cell culture</a></li>
<li class="chapter" data-level="30.2" data-path="twowayRM.html"><a href="twowayRM.html#the-test-1"><i class="fa fa-check"></i><b>30.2</b> The test</a></li>
<li class="chapter" data-level="30.3" data-path="twowayRM.html"><a href="twowayRM.html#interpretation-of-the-output"><i class="fa fa-check"></i><b>30.3</b> Interpretation of the output</a><ul>
<li class="chapter" data-level="30.3.1" data-path="twowayRM.html"><a href="twowayRM.html#anova-table-1"><i class="fa fa-check"></i><b>30.3.1</b> ANOVA Table</a></li>
<li class="chapter" data-level="30.3.2" data-path="twowayRM.html"><a href="twowayRM.html#mauchlys-sphericity-test"><i class="fa fa-check"></i><b>30.3.2</b> Mauchly’s Sphericity Test</a></li>
</ul></li>
<li class="chapter" data-level="30.4" data-path="twowayRM.html"><a href="twowayRM.html#post-hoc-multiple-comparisons-1"><i class="fa fa-check"></i><b>30.4</b> Post Hoc multiple comparisons</a></li>
<li class="chapter" data-level="30.5" data-path="twowayRM.html"><a href="twowayRM.html#write-up-14"><i class="fa fa-check"></i><b>30.5</b> Write Up</a></li>
<li class="chapter" data-level="30.6" data-path="twowayRM.html"><a href="twowayRM.html#summary-7"><i class="fa fa-check"></i><b>30.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="twowaymixed.html"><a href="twowaymixed.html"><i class="fa fa-check"></i><b>31</b> Two-way ANOVA RM/CR</a><ul>
<li class="chapter" data-level="31.1" data-path="twowaymixed.html"><a href="twowaymixed.html#chickweight-data-set"><i class="fa fa-check"></i><b>31.1</b> ChickWeight Data set</a></li>
<li class="chapter" data-level="31.2" data-path="twowaymixed.html"><a href="twowaymixed.html#munge-chickweight-data"><i class="fa fa-check"></i><b>31.2</b> Munge ChickWeight data</a></li>
<li class="chapter" data-level="31.3" data-path="twowaymixed.html"><a href="twowaymixed.html#the-test-2"><i class="fa fa-check"></i><b>31.3</b> The test</a></li>
<li class="chapter" data-level="31.4" data-path="twowaymixed.html"><a href="twowaymixed.html#interpreting-the-anova-output"><i class="fa fa-check"></i><b>31.4</b> Interpreting the ANOVA output</a><ul>
<li class="chapter" data-level="31.4.1" data-path="twowaymixed.html"><a href="twowaymixed.html#anova-the-anova-table-1"><i class="fa fa-check"></i><b>31.4.1</b> $ANOVA: The ANOVA table</a></li>
<li class="chapter" data-level="31.4.2" data-path="twowaymixed.html"><a href="twowaymixed.html#mauchlys-test-and-corrections"><i class="fa fa-check"></i><b>31.4.2</b> Mauchly’s Test and Corrections</a></li>
</ul></li>
<li class="chapter" data-level="31.5" data-path="twowaymixed.html"><a href="twowaymixed.html#post-hoc"><i class="fa fa-check"></i><b>31.5</b> Post hoc</a><ul>
<li class="chapter" data-level="31.5.1" data-path="twowaymixed.html"><a href="twowaymixed.html#pairwise.t.tests-1"><i class="fa fa-check"></i><b>31.5.1</b> Pairwise.t.tests</a></li>
<li class="chapter" data-level="31.5.2" data-path="twowaymixed.html"><a href="twowaymixed.html#tukey-test-a-range-test"><i class="fa fa-check"></i><b>31.5.2</b> Tukey test: A range test</a></li>
<li class="chapter" data-level="31.5.3" data-path="twowaymixed.html"><a href="twowaymixed.html#heres-whats-been-discovered-by-the-tukeyhsd-test"><i class="fa fa-check"></i><b>31.5.3</b> Here’s what’s been discovered by the TukeyHSD test</a></li>
<li class="chapter" data-level="31.5.4" data-path="twowaymixed.html"><a href="twowaymixed.html#why-is-the-tukeyhsd-result-so-different-than-the-pairwise.t.test"><i class="fa fa-check"></i><b>31.5.4</b> Why is the TukeyHSD result so different than the pairwise.t.test??</a></li>
</ul></li>
<li class="chapter" data-level="31.6" data-path="twowaymixed.html"><a href="twowaymixed.html#summary-8"><i class="fa fa-check"></i><b>31.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="posthoc.html"><a href="posthoc.html"><i class="fa fa-check"></i><b>32</b> ANOVA Posthoc Comparisons</a><ul>
<li class="chapter" data-level="32.1" data-path="posthoc.html"><a href="posthoc.html#overview-of-options"><i class="fa fa-check"></i><b>32.1</b> Overview of options</a><ul>
<li class="chapter" data-level="32.1.1" data-path="posthoc.html"><a href="posthoc.html#pairwise.t.test-with-p-value-adjustments"><i class="fa fa-check"></i><b>32.1.1</b> Pairwise.t.test with p-value adjustments</a></li>
<li class="chapter" data-level="32.1.2" data-path="posthoc.html"><a href="posthoc.html#range-tests-2"><i class="fa fa-check"></i><b>32.1.2</b> Range tests</a></li>
</ul></li>
<li class="chapter" data-level="32.2" data-path="posthoc.html"><a href="posthoc.html#reporting-the-result-1"><i class="fa fa-check"></i><b>32.2</b> Reporting the result</a></li>
<li class="chapter" data-level="32.3" data-path="posthoc.html"><a href="posthoc.html#summary-9"><i class="fa fa-check"></i><b>32.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="jaxwest2.html"><a href="jaxwest2.html"><i class="fa fa-check"></i><b>33</b> Reproducible Data Munging Mostly with Tidyverse</a><ul>
<li class="chapter" data-level="33.1" data-path="jaxwest2.html"><a href="jaxwest2.html#look-at-the-original-data-carefully"><i class="fa fa-check"></i><b>33.1</b> Look at the original data carefully</a></li>
<li class="chapter" data-level="33.2" data-path="jaxwest2.html"><a href="jaxwest2.html#our-goal"><i class="fa fa-check"></i><b>33.2</b> Our goal</a></li>
<li class="chapter" data-level="33.3" data-path="jaxwest2.html"><a href="jaxwest2.html#step-1-read-the-data-into-r"><i class="fa fa-check"></i><b>33.3</b> Step 1: Read the data into R</a></li>
<li class="chapter" data-level="33.4" data-path="jaxwest2.html"><a href="jaxwest2.html#step-2-select-the-variables"><i class="fa fa-check"></i><b>33.4</b> Step 2: Select the variables</a></li>
<li class="chapter" data-level="33.5" data-path="jaxwest2.html"><a href="jaxwest2.html#step-3-trim-the-cases"><i class="fa fa-check"></i><b>33.5</b> Step 3: Trim the cases</a></li>
<li class="chapter" data-level="33.6" data-path="jaxwest2.html"><a href="jaxwest2.html#step-4-we-have-a-variable-problem-to-fix"><i class="fa fa-check"></i><b>33.6</b> Step 4: We have a variable problem to fix</a></li>
<li class="chapter" data-level="33.7" data-path="jaxwest2.html"><a href="jaxwest2.html#step-5-impute-or-delete"><i class="fa fa-check"></i><b>33.7</b> Step 5: Impute or Delete</a></li>
<li class="chapter" data-level="33.8" data-path="jaxwest2.html"><a href="jaxwest2.html#step-6-go-long"><i class="fa fa-check"></i><b>33.8</b> Step 6: Go long</a></li>
<li class="chapter" data-level="33.9" data-path="jaxwest2.html"><a href="jaxwest2.html#step-7-convert-other-variables-to-factor"><i class="fa fa-check"></i><b>33.9</b> Step 7: Convert other variables to factor</a></li>
<li class="chapter" data-level="33.10" data-path="jaxwest2.html"><a href="jaxwest2.html#step-8-plot"><i class="fa fa-check"></i><b>33.10</b> Step 8: Plot</a></li>
<li class="chapter" data-level="33.11" data-path="jaxwest2.html"><a href="jaxwest2.html#step-9-run-the-anova"><i class="fa fa-check"></i><b>33.11</b> Step 9: Run the ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="34" data-path="anovamc.html"><a href="anovamc.html"><i class="fa fa-check"></i><b>34</b> ANOVA power using Monte Carlo</a><ul>
<li class="chapter" data-level="34.1" data-path="anovamc.html"><a href="anovamc.html#alternatives-to-monte-carlo"><i class="fa fa-check"></i><b>34.1</b> Alternatives to Monte Carlo</a></li>
<li class="chapter" data-level="34.2" data-path="anovamc.html"><a href="anovamc.html#what-is-monte-carlo"><i class="fa fa-check"></i><b>34.2</b> What is Monte Carlo</a></li>
<li class="chapter" data-level="34.3" data-path="anovamc.html"><a href="anovamc.html#one-way-completely-randomized-anova-monte-carlo"><i class="fa fa-check"></i><b>34.3</b> One-way completely randomized ANOVA Monte Carlo</a><ul>
<li class="chapter" data-level="34.3.1" data-path="anovamc.html"><a href="anovamc.html#directions"><i class="fa fa-check"></i><b>34.3.1</b> Directions</a></li>
<li class="chapter" data-level="34.3.2" data-path="anovamc.html"><a href="anovamc.html#step-1-create-initial-values"><i class="fa fa-check"></i><b>34.3.2</b> Step 1: Create initial values</a></li>
<li class="chapter" data-level="34.3.3" data-path="anovamc.html"><a href="anovamc.html#step-2-visualize-one-random-sample"><i class="fa fa-check"></i><b>34.3.3</b> Step 2: Visualize one random sample</a></li>
<li class="chapter" data-level="34.3.4" data-path="anovamc.html"><a href="anovamc.html#step-3-run-the-power-simulator"><i class="fa fa-check"></i><b>34.3.4</b> Step 3: Run The Power Simulator</a></li>
<li class="chapter" data-level="34.3.5" data-path="anovamc.html"><a href="anovamc.html#step-4-optimize-for-suitable-power"><i class="fa fa-check"></i><b>34.3.5</b> Step 4: Optimize for suitable power</a></li>
<li class="chapter" data-level="34.3.6" data-path="anovamc.html"><a href="anovamc.html#notes-and-considerations"><i class="fa fa-check"></i><b>34.3.6</b> Notes And Considerations</a></li>
</ul></li>
<li class="chapter" data-level="34.4" data-path="anovamc.html"><a href="anovamc.html#one-way-related-measures-anova-monte-carlo"><i class="fa fa-check"></i><b>34.4</b> One-way related measures ANOVA Monte Carlo</a></li>
<li class="chapter" data-level="34.5" data-path="anovamc.html"><a href="anovamc.html#directions-1"><i class="fa fa-check"></i><b>34.5</b> Directions</a><ul>
<li class="chapter" data-level="34.5.1" data-path="anovamc.html"><a href="anovamc.html#step-1-initial-values"><i class="fa fa-check"></i><b>34.5.1</b> Step 1: Initial values</a></li>
<li class="chapter" data-level="34.5.2" data-path="anovamc.html"><a href="anovamc.html#step-2-visualize-one-sample"><i class="fa fa-check"></i><b>34.5.2</b> Step 2: Visualize one sample</a></li>
<li class="chapter" data-level="34.5.3" data-path="anovamc.html"><a href="anovamc.html#step-3-run-the-power-simulator-1"><i class="fa fa-check"></i><b>34.5.3</b> Step 3: Run the power simulator</a></li>
<li class="chapter" data-level="34.5.4" data-path="anovamc.html"><a href="anovamc.html#step-4-should-anything-be-changed"><i class="fa fa-check"></i><b>34.5.4</b> Step 4: Should anything be changed?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="35" data-path="manova.html"><a href="manova.html"><i class="fa fa-check"></i><b>35</b> Multivariate Analysis of Variance (MANOVA)</a><ul>
<li class="chapter" data-level="35.1" data-path="manova.html"><a href="manova.html#what-does-manova-test"><i class="fa fa-check"></i><b>35.1</b> What does MANOVA test?</a></li>
<li class="chapter" data-level="35.2" data-path="manova.html"><a href="manova.html#types-of-experiments"><i class="fa fa-check"></i><b>35.2</b> Types of experiments</a></li>
<li class="chapter" data-level="35.3" data-path="manova.html"><a href="manova.html#manova-is-not-many-anovas"><i class="fa fa-check"></i><b>35.3</b> MANOVA is not many ANOVAs</a><ul>
<li class="chapter" data-level="35.3.1" data-path="manova.html"><a href="manova.html#why-manova"><i class="fa fa-check"></i><b>35.3.1</b> Why MANOVA?</a></li>
</ul></li>
<li class="chapter" data-level="35.4" data-path="manova.html"><a href="manova.html#assumptions-1"><i class="fa fa-check"></i><b>35.4</b> Assumptions</a><ul>
<li class="chapter" data-level="35.4.1" data-path="manova.html"><a href="manova.html#multicolinearity"><i class="fa fa-check"></i><b>35.4.1</b> Multicolinearity</a></li>
</ul></li>
<li class="chapter" data-level="35.5" data-path="manova.html"><a href="manova.html#calculating-variation"><i class="fa fa-check"></i><b>35.5</b> Calculating variation</a><ul>
<li class="chapter" data-level="35.5.1" data-path="manova.html"><a href="manova.html#eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>35.5.1</b> Eigenvectors and eigenvalues</a></li>
<li class="chapter" data-level="35.5.2" data-path="manova.html"><a href="manova.html#manova-test-statistics"><i class="fa fa-check"></i><b>35.5.2</b> MANOVA test statistics</a></li>
<li class="chapter" data-level="35.5.3" data-path="manova.html"><a href="manova.html#which-manova-test-statistic-is-best"><i class="fa fa-check"></i><b>35.5.3</b> Which MANOVA test statistic is best?</a></li>
</ul></li>
<li class="chapter" data-level="35.6" data-path="manova.html"><a href="manova.html#drug-clearance-example"><i class="fa fa-check"></i><b>35.6</b> Drug clearance example</a><ul>
<li class="chapter" data-level="35.6.1" data-path="manova.html"><a href="manova.html#rationale-for-manova"><i class="fa fa-check"></i><b>35.6.1</b> Rationale for MANOVA</a></li>
<li class="chapter" data-level="35.6.2" data-path="manova.html"><a href="manova.html#data-structure"><i class="fa fa-check"></i><b>35.6.2</b> Data structure</a></li>
<li class="chapter" data-level="35.6.3" data-path="manova.html"><a href="manova.html#manova-procedure"><i class="fa fa-check"></i><b>35.6.3</b> MANOVA procedure</a></li>
</ul></li>
<li class="chapter" data-level="35.7" data-path="manova.html"><a href="manova.html#planning-manova-experiments"><i class="fa fa-check"></i><b>35.7</b> Planning MANOVA experiments</a><ul>
<li class="chapter" data-level="35.7.1" data-path="manova.html"><a href="manova.html#manova-monte-carlo-power-analysis"><i class="fa fa-check"></i><b>35.7.1</b> MANOVA Monte Carlo Power Analysis</a></li>
<li class="chapter" data-level="35.7.2" data-path="manova.html"><a href="manova.html#an-manova-monte-carlo-power-function"><i class="fa fa-check"></i><b>35.7.2</b> An MANOVA Monte Carlo Power function</a></li>
</ul></li>
<li class="chapter" data-level="35.8" data-path="manova.html"><a href="manova.html#summary-10"><i class="fa fa-check"></i><b>35.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="36" data-path="correl.html"><a href="correl.html"><i class="fa fa-check"></i><b>36</b> Correlation</a><ul>
<li class="chapter" data-level="36.1" data-path="correl.html"><a href="correl.html#correlation-causation"><i class="fa fa-check"></i><b>36.1</b> Correlation != Causation</a></li>
<li class="chapter" data-level="36.2" data-path="correl.html"><a href="correl.html#correlation-in-multivariate-outcomes-and-paired-designs"><i class="fa fa-check"></i><b>36.2</b> Correlation in Multivariate Outcomes and Paired Designs</a></li>
<li class="chapter" data-level="36.3" data-path="correl.html"><a href="correl.html#correlation-coefficients"><i class="fa fa-check"></i><b>36.3</b> Correlation coefficients</a><ul>
<li class="chapter" data-level="36.3.1" data-path="correl.html"><a href="correl.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>36.3.1</b> Pearson’s correlation coefficient</a></li>
<li class="chapter" data-level="36.3.2" data-path="correl.html"><a href="correl.html#spearmans-rank-correlation"><i class="fa fa-check"></i><b>36.3.2</b> Spearman’s rank correlation</a></li>
<li class="chapter" data-level="36.3.3" data-path="correl.html"><a href="correl.html#kendalls-tau"><i class="fa fa-check"></i><b>36.3.3</b> Kendall’s tau</a></li>
<li class="chapter" data-level="36.3.4" data-path="correl.html"><a href="correl.html#which-correlation-method-to-use"><i class="fa fa-check"></i><b>36.3.4</b> Which correlation method to use?</a></li>
<li class="chapter" data-level="36.3.5" data-path="correl.html"><a href="correl.html#r-correlation-analysis-functions"><i class="fa fa-check"></i><b>36.3.5</b> R correlation analysis functions</a></li>
<li class="chapter" data-level="36.3.6" data-path="correl.html"><a href="correl.html#plot-the-correlations"><i class="fa fa-check"></i><b>36.3.6</b> Plot the correlations</a></li>
<li class="chapter" data-level="36.3.7" data-path="correl.html"><a href="correl.html#calculate-a-correlation-coefficient-and-posthoc-test"><i class="fa fa-check"></i><b>36.3.7</b> Calculate a correlation coefficient and posthoc test</a></li>
<li class="chapter" data-level="36.3.8" data-path="correl.html"><a href="correl.html#interpretation-of-correlation-output"><i class="fa fa-check"></i><b>36.3.8</b> Interpretation of correlation output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="regress.html"><a href="regress.html"><i class="fa fa-check"></i><b>37</b> Linear Regression</a><ul>
<li class="chapter" data-level="37.1" data-path="regress.html"><a href="regress.html#the-linear-regression-model"><i class="fa fa-check"></i><b>37.1</b> The linear regression model</a></li>
<li class="chapter" data-level="37.2" data-path="regress.html"><a href="regress.html#least-squares-fitting"><i class="fa fa-check"></i><b>37.2</b> Least squares fitting</a></li>
<li class="chapter" data-level="37.3" data-path="regress.html"><a href="regress.html#the-practical-importance-of-linear-model-parameters"><i class="fa fa-check"></i><b>37.3</b> The practical importance of linear model parameters</a></li>
<li class="chapter" data-level="37.4" data-path="regress.html"><a href="regress.html#linear-model-standard-errors"><i class="fa fa-check"></i><b>37.4</b> Linear model standard errors</a></li>
<li class="chapter" data-level="37.5" data-path="regress.html"><a href="regress.html#linear-regression-in-r"><i class="fa fa-check"></i><b>37.5</b> Linear regression in R</a></li>
<li class="chapter" data-level="37.6" data-path="regress.html"><a href="regress.html#intepretation"><i class="fa fa-check"></i><b>37.6</b> Intepretation</a><ul>
<li class="chapter" data-level="37.6.1" data-path="regress.html"><a href="regress.html#residuals"><i class="fa fa-check"></i><b>37.6.1</b> Residuals</a></li>
<li class="chapter" data-level="37.6.2" data-path="regress.html"><a href="regress.html#coefficients"><i class="fa fa-check"></i><b>37.6.2</b> Coefficients</a></li>
<li class="chapter" data-level="37.6.3" data-path="regress.html"><a href="regress.html#degrees-of-freedom-1"><i class="fa fa-check"></i><b>37.6.3</b> Degrees of freedom</a></li>
<li class="chapter" data-level="37.6.4" data-path="regress.html"><a href="regress.html#r-squared"><i class="fa fa-check"></i><b>37.6.4</b> R-squared</a></li>
<li class="chapter" data-level="37.6.5" data-path="regress.html"><a href="regress.html#f-statistic"><i class="fa fa-check"></i><b>37.6.5</b> F-statistic</a></li>
<li class="chapter" data-level="37.6.6" data-path="regress.html"><a href="regress.html#plotting-regression-results"><i class="fa fa-check"></i><b>37.6.6</b> Plotting regression results</a></li>
<li class="chapter" data-level="37.6.7" data-path="regress.html"><a href="regress.html#visualizing-residuals"><i class="fa fa-check"></i><b>37.6.7</b> Visualizing residuals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="nonlinearintro.html"><a href="nonlinearintro.html"><i class="fa fa-check"></i><b>38</b> Non-linear regression introduction</a><ul>
<li class="chapter" data-level="38.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#uses-for-nonlinear-regression"><i class="fa fa-check"></i><b>38.1</b> Uses for nonlinear regression</a></li>
<li class="chapter" data-level="38.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#example-of-the-process"><i class="fa fa-check"></i><b>38.2</b> Example of the process</a><ul>
<li class="chapter" data-level="38.2.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#it-starts-with-nonlinear-data"><i class="fa fa-check"></i><b>38.2.1</b> It starts with nonlinear data</a></li>
<li class="chapter" data-level="38.2.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#what-nonlinear-model-describes-that-data"><i class="fa fa-check"></i><b>38.2.2</b> What nonlinear model describes that data?</a></li>
<li class="chapter" data-level="38.2.3" data-path="nonlinearintro.html"><a href="nonlinearintro.html#fitting-a-model-to-data"><i class="fa fa-check"></i><b>38.2.3</b> Fitting a model to data</a></li>
<li class="chapter" data-level="38.2.4" data-path="nonlinearintro.html"><a href="nonlinearintro.html#interpreting-regression-model-output"><i class="fa fa-check"></i><b>38.2.4</b> Interpreting regression model output</a></li>
<li class="chapter" data-level="38.2.5" data-path="nonlinearintro.html"><a href="nonlinearintro.html#check-the-fit-graphically"><i class="fa fa-check"></i><b>38.2.5</b> Check the fit graphically</a></li>
<li class="chapter" data-level="38.2.6" data-path="nonlinearintro.html"><a href="nonlinearintro.html#convergence"><i class="fa fa-check"></i><b>38.2.6</b> Convergence?</a></li>
<li class="chapter" data-level="38.2.7" data-path="nonlinearintro.html"><a href="nonlinearintro.html#convergence-is-not-idiot-proof"><i class="fa fa-check"></i><b>38.2.7</b> Convergence is not idiot proof</a></li>
</ul></li>
<li class="chapter" data-level="38.3" data-path="nonlinearintro.html"><a href="nonlinearintro.html#nonlinear-models-in-general"><i class="fa fa-check"></i><b>38.3</b> Nonlinear models in general</a></li>
<li class="chapter" data-level="38.4" data-path="nonlinearintro.html"><a href="nonlinearintro.html#nlfitr"><i class="fa fa-check"></i><b>38.4</b> nlfitr</a></li>
<li class="chapter" data-level="38.5" data-path="nonlinearintro.html"><a href="nonlinearintro.html#nonlinear-regression-functions-in-r"><i class="fa fa-check"></i><b>38.5</b> Nonlinear regression functions in R</a><ul>
<li class="chapter" data-level="38.5.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#the-fitting-algorithms"><i class="fa fa-check"></i><b>38.5.1</b> The fitting algorithms</a></li>
<li class="chapter" data-level="38.5.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#formula"><i class="fa fa-check"></i><b>38.5.2</b> formula</a></li>
<li class="chapter" data-level="38.5.3" data-path="nonlinearintro.html"><a href="nonlinearintro.html#data-1"><i class="fa fa-check"></i><b>38.5.3</b> data</a></li>
<li class="chapter" data-level="38.5.4" data-path="nonlinearintro.html"><a href="nonlinearintro.html#start"><i class="fa fa-check"></i><b>38.5.4</b> start</a></li>
<li class="chapter" data-level="38.5.5" data-path="nonlinearintro.html"><a href="nonlinearintro.html#weighting"><i class="fa fa-check"></i><b>38.5.5</b> weighting</a></li>
</ul></li>
<li class="chapter" data-level="38.6" data-path="nonlinearintro.html"><a href="nonlinearintro.html#nonlinear-models-and-parameters"><i class="fa fa-check"></i><b>38.6</b> Nonlinear models and parameters</a><ul>
<li class="chapter" data-level="38.6.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#hyperbolic-stimulus-response-functions"><i class="fa fa-check"></i><b>38.6.1</b> Hyperbolic stimulus response functions</a></li>
<li class="chapter" data-level="38.6.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#visualizing-nonlinear-data-and-log-scaling"><i class="fa fa-check"></i><b>38.6.2</b> Visualizing nonlinear data and log scaling</a></li>
<li class="chapter" data-level="38.6.3" data-path="nonlinearintro.html"><a href="nonlinearintro.html#selecting-the-right-model"><i class="fa fa-check"></i><b>38.6.3</b> Selecting the right model</a></li>
<li class="chapter" data-level="38.6.4" data-path="nonlinearintro.html"><a href="nonlinearintro.html#from-models-to-formulas"><i class="fa fa-check"></i><b>38.6.4</b> From models to formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="39" data-path="nestedregress.html"><a href="nestedregress.html"><i class="fa fa-check"></i><b>39</b> Nested-model nonlinear regression</a><ul>
<li class="chapter" data-level="39.1" data-path="nestedregress.html"><a href="nestedregress.html#read-and-plot-the-data"><i class="fa fa-check"></i><b>39.1</b> Read and plot the data</a></li>
<li class="chapter" data-level="39.2" data-path="nestedregress.html"><a href="nestedregress.html#which-model-is-a-better-fit"><i class="fa fa-check"></i><b>39.2</b> Which model is a better fit?</a><ul>
<li class="chapter" data-level="39.2.1" data-path="nestedregress.html"><a href="nestedregress.html#nonlinear-models"><i class="fa fa-check"></i><b>39.2.1</b> Nonlinear models</a></li>
<li class="chapter" data-level="39.2.2" data-path="nestedregress.html"><a href="nestedregress.html#the-nlfitr-alternative"><i class="fa fa-check"></i><b>39.2.2</b> The nlfitr alternative</a></li>
<li class="chapter" data-level="39.2.3" data-path="nestedregress.html"><a href="nestedregress.html#troubleshooting-the-regression"><i class="fa fa-check"></i><b>39.2.3</b> Troubleshooting the regression</a></li>
<li class="chapter" data-level="39.2.4" data-path="nestedregress.html"><a href="nestedregress.html#interpreting-the-parameters"><i class="fa fa-check"></i><b>39.2.4</b> Interpreting the parameters</a></li>
<li class="chapter" data-level="39.2.5" data-path="nestedregress.html"><a href="nestedregress.html#residual-plots-to-compare-fits"><i class="fa fa-check"></i><b>39.2.5</b> Residual plots to compare fits</a></li>
<li class="chapter" data-level="39.2.6" data-path="nestedregress.html"><a href="nestedregress.html#compare-aic"><i class="fa fa-check"></i><b>39.2.6</b> Compare AIC</a></li>
<li class="chapter" data-level="39.2.7" data-path="nestedregress.html"><a href="nestedregress.html#other-ways-to-compare-models"><i class="fa fa-check"></i><b>39.2.7</b> Other ways to compare models</a></li>
<li class="chapter" data-level="39.2.8" data-path="nestedregress.html"><a href="nestedregress.html#interpretation-of-this-one-replicate"><i class="fa fa-check"></i><b>39.2.8</b> Interpretation of this one replicate</a></li>
<li class="chapter" data-level="39.2.9" data-path="nestedregress.html"><a href="nestedregress.html#alternate-analysis"><i class="fa fa-check"></i><b>39.2.9</b> Alternate analysis</a></li>
</ul></li>
<li class="chapter" data-level="39.3" data-path="nestedregress.html"><a href="nestedregress.html#summary-11"><i class="fa fa-check"></i><b>39.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html"><i class="fa fa-check"></i><b>40</b> Nonlinear regression of independent replicates</a><ul>
<li class="chapter" data-level="40.1" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#the-problem"><i class="fa fa-check"></i><b>40.1</b> The problem</a></li>
<li class="chapter" data-level="40.2" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#the-dataset"><i class="fa fa-check"></i><b>40.2</b> The dataset</a></li>
<li class="chapter" data-level="40.3" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#munging-for-regression-analysis"><i class="fa fa-check"></i><b>40.3</b> Munging for regression analysis</a><ul>
<li class="chapter" data-level="40.3.1" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#average-the-technical-replicates"><i class="fa fa-check"></i><b>40.3.1</b> Average the technical replicates</a></li>
<li class="chapter" data-level="40.3.2" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#create-one-table"><i class="fa fa-check"></i><b>40.3.2</b> Create one table</a></li>
<li class="chapter" data-level="40.3.3" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#plot-the-data"><i class="fa fa-check"></i><b>40.3.3</b> Plot the data</a></li>
<li class="chapter" data-level="40.3.4" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#run-the-regressions"><i class="fa fa-check"></i><b>40.3.4</b> Run the regressions</a></li>
<li class="chapter" data-level="40.3.5" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#clean-up-regression-results"><i class="fa fa-check"></i><b>40.3.5</b> Clean up regression results</a></li>
</ul></li>
<li class="chapter" data-level="40.4" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#t-test-on-half-lives"><i class="fa fa-check"></i><b>40.4</b> T-test on half-lives</a></li>
<li class="chapter" data-level="40.5" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#conclusion"><i class="fa fa-check"></i><b>40.5</b> Conclusion</a></li>
<li class="chapter" data-level="40.6" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#summary-figure"><i class="fa fa-check"></i><b>40.6</b> Summary figure</a></li>
</ul></li>
<li class="chapter" data-level="41" data-path="multregress.html"><a href="multregress.html"><i class="fa fa-check"></i><b>41</b> Multiple regression</a><ul>
<li class="chapter" data-level="41.1" data-path="multregress.html"><a href="multregress.html#the-linear-regression-model-1"><i class="fa fa-check"></i><b>41.1</b> The linear regression model</a></li>
<li class="chapter" data-level="41.2" data-path="multregress.html"><a href="multregress.html#multiple-regression-models"><i class="fa fa-check"></i><b>41.2</b> Multiple regression models</a></li>
<li class="chapter" data-level="41.3" data-path="multregress.html"><a href="multregress.html#experimental-multiple-regression"><i class="fa fa-check"></i><b>41.3</b> Experimental multiple regression</a><ul>
<li class="chapter" data-level="41.3.1" data-path="multregress.html"><a href="multregress.html#a-one-factor-experiment-with-3-groups"><i class="fa fa-check"></i><b>41.3.1</b> A one factor experiment with 3 groups</a></li>
<li class="chapter" data-level="41.3.2" data-path="multregress.html"><a href="multregress.html#a-two-factor-experiment-with-6-groups"><i class="fa fa-check"></i><b>41.3.2</b> A two factor experiment with 6 groups</a></li>
</ul></li>
<li class="chapter" data-level="41.4" data-path="multregress.html"><a href="multregress.html#multiple-linear-mixed-models"><i class="fa fa-check"></i><b>41.4</b> Multiple linear mixed models</a></li>
<li class="chapter" data-level="41.5" data-path="multregress.html"><a href="multregress.html#multiple-regression-of-observational-data"><i class="fa fa-check"></i><b>41.5</b> Multiple regression of observational data</a></li>
</ul></li>
<li class="chapter" data-level="42" data-path="logregress.html"><a href="logregress.html"><i class="fa fa-check"></i><b>42</b> Logistic regression</a><ul>
<li class="chapter" data-level="42.1" data-path="logregress.html"><a href="logregress.html#uses-of-logistic-regression"><i class="fa fa-check"></i><b>42.1</b> Uses of logistic regression</a><ul>
<li class="chapter" data-level="42.1.1" data-path="logregress.html"><a href="logregress.html#sidebar-doing-logistic-regression-is-machine-learning"><i class="fa fa-check"></i><b>42.1.1</b> Sidebar: Doing logistic regression is machine learning</a></li>
</ul></li>
<li class="chapter" data-level="42.2" data-path="logregress.html"><a href="logregress.html#derivation-of-the-logistic-regression-model"><i class="fa fa-check"></i><b>42.2</b> Derivation of the logistic regression model</a><ul>
<li class="chapter" data-level="42.2.1" data-path="logregress.html"><a href="logregress.html#relationship-of-logit-to-odds-to-the-model-coefficients-and-probability"><i class="fa fa-check"></i><b>42.2.1</b> Relationship of logit to odds to the model coefficients and probability</a></li>
<li class="chapter" data-level="42.2.2" data-path="logregress.html"><a href="logregress.html#additional-types-of-logistic-regression-models"><i class="fa fa-check"></i><b>42.2.2</b> Additional types of logistic regression models</a></li>
</ul></li>
<li class="chapter" data-level="42.3" data-path="logregress.html"><a href="logregress.html#stress-and-survival"><i class="fa fa-check"></i><b>42.3</b> Stress and survival</a><ul>
<li class="chapter" data-level="42.3.1" data-path="logregress.html"><a href="logregress.html#interpretation-of-output"><i class="fa fa-check"></i><b>42.3.1</b> Interpretation of output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="43" data-path="mixedlogistic.html"><a href="mixedlogistic.html"><i class="fa fa-check"></i><b>43</b> Mixed model logistic regression</a><ul>
<li class="chapter" data-level="43.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#mixed-models-fixed-and-random-effects"><i class="fa fa-check"></i><b>43.1</b> Mixed models, fixed and random effects</a><ul>
<li class="chapter" data-level="43.1.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#nfat-localization-within-smooth-muscle-cells"><i class="fa fa-check"></i><b>43.1.1</b> NFAT localization within smooth muscle cells</a></li>
</ul></li>
<li class="chapter" data-level="43.2" data-path="mixedlogistic.html"><a href="mixedlogistic.html#data-2"><i class="fa fa-check"></i><b>43.2</b> Data</a><ul>
<li class="chapter" data-level="43.2.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#inference-2"><i class="fa fa-check"></i><b>43.2.1</b> Inference</a></li>
</ul></li>
<li class="chapter" data-level="43.3" data-path="mixedlogistic.html"><a href="mixedlogistic.html#alternative-analysis"><i class="fa fa-check"></i><b>43.3</b> Alternative analysis</a></li>
</ul></li>
<li class="chapter" data-level="44" data-path="lda.html"><a href="lda.html"><i class="fa fa-check"></i><b>44</b> Linear discriminant analysis</a><ul>
<li class="chapter" data-level="44.1" data-path="lda.html"><a href="lda.html#flipping-the-general-linear-model"><i class="fa fa-check"></i><b>44.1</b> Flipping the general linear model</a><ul>
<li class="chapter" data-level="44.1.1" data-path="lda.html"><a href="lda.html#graph"><i class="fa fa-check"></i><b>44.1.1</b> graph</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="45" data-path="lognormal.html"><a href="lognormal.html"><i class="fa fa-check"></i><b>45</b> The lognormal distribution</a><ul>
<li class="chapter" data-level="45.1" data-path="lognormal.html"><a href="lognormal.html#dlnorm"><i class="fa fa-check"></i><b>45.1</b> dlnorm</a></li>
<li class="chapter" data-level="45.2" data-path="lognormal.html"><a href="lognormal.html#plnorm"><i class="fa fa-check"></i><b>45.2</b> plnorm</a></li>
<li class="chapter" data-level="45.3" data-path="lognormal.html"><a href="lognormal.html#qlnorm"><i class="fa fa-check"></i><b>45.3</b> qlnorm</a></li>
<li class="chapter" data-level="45.4" data-path="lognormal.html"><a href="lognormal.html#rlnorm"><i class="fa fa-check"></i><b>45.4</b> rlnorm</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">JABSTB: Statistical Design and Analysis of Experiments with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="nonlinearintro" class="section level1">
<h1><span class="header-section-number">Chapter 38</span> Non-linear regression introduction</h1>
<p>Nonlinear regression is a statistical method to fit nonlinear models to the kinds of data sets that have nonlinear relationships between predictor and dependent variables. The regression fits produce estimates of the model parameters. These model parameters are useful because they provide a way to quantify some biological process (eg, rate and equilibrium constants, minimal and maximal responses, etc).</p>
<p>Nonlinear regression has added importance since biological systems tend to operate in nonlinear ways.</p>
<p>In general, models are just mathematical equations that describe how <span class="math inline">\(Y\)</span> is produced by <span class="math inline">\(X\)</span>. In nonlinear regression we’ll feed a model formula pairs of <span class="math inline">\(X,Y\)</span> data from an experiment. The model parameters responsible for giving nonlinear shape to the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are then determined by the regression method.</p>
<p>The statistical analysis involving nonlinear models is nearly identical to that for linear models. The regression technique itself customizes the fit of a chosen nonlinear model to some data produced in the lab. These best fits are determined by a minimization of the sum of the squared residuals between the model values for the response and the experimentally-derived values. The only difference is that nonlinear regression solves the problem iteratively, rather than mathematically.</p>
<p>A common misconception is that a data set is fed into some mythical omnibus function, which then identifies the right model and fits it to the data.</p>
<p>Nobody really has that one…yet. There are too many ways nonlinear data can happen, yet in biology, only some of these ways are important. Therefore, it takes the expertise of a researcher to select the right model for the data.</p>
<p>By important I mean that the models have some theoretical basis. Most of the time we’re working on experiments where the right models to choose are obvious. For example, if we are doing enzyme kinetics we are probably using the Michaelis-Menten model. If we are doing binding assays we are using a model based upon the mass action law. And so on.</p>
<p>If there is no pre-existing theoretical framework, as a general rule, the nonlinear regression process is flexible enough to accept completely new models.</p>
<div id="uses-for-nonlinear-regression" class="section level2">
<h2><span class="header-section-number">38.1</span> Uses for nonlinear regression</h2>
<p>There are three big reasons why you’d use nonlinear regression:</p>
<ul>
<li>Artistic</li>
<li>Interpolation (and simulation)</li>
<li>Conducting statistical inference</li>
</ul>
<p>Sometimes we have nonlinear data and all we want to do is draw a pretty curve through the points. The objective is purely visual. Sometimes we’ll run a model-based regression to get the pretty curve. Other times we’ll use a smoothing regression that is, truly, just a pretty curve. You’ll see how to do both of those below.</p>
<p>Other times we have measured values of <span class="math inline">\(Y\)</span> for which we want to impute values of <span class="math inline">\(X\)</span>. That’s achieved by nonlinear regression of an <span class="math inline">\(X,Y\)</span> standard curve (eg, ELISA), which is used to interpolate values for unknown samples.</p>
<p>Conceptually related to this is simulating nonlinear data for a range of <span class="math inline">\(X\)</span> values using a given model and fixed parameter values. There are several use cases for simulation. Perhaps the most important is in trying to write a custom model that looks like data you’ve generated. Or to figure out what a model really means, by playing with it as in a sandbox. There’s no better way to learn it quickly than by simulating data with it. Extensions of this include creating explanatory or comparative figures, and performing Monte Carlo-based preplanning.</p>
<p>The most common statistical use is to estimate the parameter values of the nonlinear model that best fits some sample data, and then conduct statistical inference on those values. These parameter values from our data represent “constants” that represent an important biological feature.</p>
</div>
<div id="example-of-the-process" class="section level2">
<h2><span class="header-section-number">38.2</span> Example of the process</h2>
<p>Some common laboratory phenomena in their pre-depletion states can be described using exponential growth models. For example, bacterial growth in culture, or the polymerase chain reaction.</p>
<div id="it-starts-with-nonlinear-data" class="section level3">
<h3><span class="header-section-number">38.2.1</span> It starts with nonlinear data</h3>
<p>We wish to estimate the growth rate and initial inoculate of a bacterial culture by taking aliquots at the indicated times through measuring optical density (A600 nm) on a spectrophotometer.</p>
<p>We have a data set (<code>edata</code>) of <span class="math inline">\(x, y\)</span> pairs. The variable names are actually <code>hours</code> and <code>A600</code>, respectively, and plotted in panel A of the figure below.</p>
<p>The response <span class="math inline">\(A600\)</span> is clearly nonlinear on values of <span class="math inline">\(hours\)</span>.</p>
<div class="figure"><span id="fig:unnamed-chunk-418"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-418-1.png" alt="A. Primary nonlinear data looks exponential. B. Same data as A log-transformed looks linear." width="672" />
<p class="caption">
Figure 38.1: A. Primary nonlinear data looks exponential. B. Same data as A log-transformed looks linear.
</p>
</div>
</div>
<div id="what-nonlinear-model-describes-that-data" class="section level3">
<h3><span class="header-section-number">38.2.2</span> What nonlinear model describes that data?</h3>
<p>We remember enough algebra to realize an exponential function could have produced something like the data in panel A. Consistent with this, natural log transformation of the values of <span class="math inline">\(Y\)</span> linearizes the response (see panel B in the figure).</p>
<p>We can write a general exponential growth model as follows: <span class="math display">\[y=y_{min}\times e^{k*x}\]</span> In this form the parameter <span class="math inline">\(k\)</span> is a constant with units of reciprocal <span class="math inline">\(x\)</span>. The parameter <span class="math inline">\(y_{min}\)</span> is the lower asymptote, serving to estimate the value of <span class="math inline">\(Y\)</span> in the absence of <span class="math inline">\(X\)</span>. Therefore, <span class="math inline">\(k\)</span> modifies the exponential rate by which <span class="math inline">\(Y\)</span> changes with <span class="math inline">\(X\)</span>.</p>
<p>The nonlinear regression method in general exists to obtain estimates for <span class="math inline">\(k\)</span> and <span class="math inline">\(y_{min}\)</span> from experimental data such as that shown in figure A.</p>
<p>That’s useful when these model parameters have biological meaning. Sometimes we are interested in only <span class="math inline">\(k\)</span> or in <span class="math inline">\(y_{min}\)</span>. Other times, both parameters are important in drawing some scientific picture. It depends on the project we’re working on.</p>
</div>
<div id="fitting-a-model-to-data" class="section level3">
<h3><span class="header-section-number">38.2.3</span> Fitting a model to data</h3>
<p>To get those estimates we run a regression to fit an exponential model to the data.</p>
<p>Here, we’re using a fitting function from the <code>nlfitr</code> package. Why <code>fitegro</code> and not some other function? The function <code>fitegro</code> has the right model for this purpose.</p>
<div class="sourceCode" id="cb812"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb812-1" title="1">myfit &lt;-<span class="st"> </span><span class="kw">fitegro</span>(<span class="dt">x=</span>hours, <span class="dt">y=</span>A600, <span class="dt">data=</span>edata, <span class="dt">k=</span><span class="dv">1</span>, <span class="dt">ylo=</span><span class="dv">0</span>, <span class="dt">weigh=</span>T)</a>
<a class="sourceLine" id="cb812-2" title="2">myfit</a></code></pre></div>
<pre><code>## Nonlinear regression model
##   model: A600 ~ (ylo) * exp(k * hours)
##    data: data
##       k     ylo 
##  0.5092 77.0827 
##  weighted residual sum-of-squares: 2.074
## 
## Number of iterations to convergence: 13 
## Achieved convergence tolerance: 1.49e-08</code></pre>
</div>
<div id="interpreting-regression-model-output" class="section level3">
<h3><span class="header-section-number">38.2.4</span> Interpreting regression model output</h3>
<p>Let’s go over that output.</p>
<p>First of all, understand that <code>fitegro</code> is just a wrapper function for <code>nlsLM</code>, which is also a wrapper function for <code>nls</code>. It produces class “nls” R object. There is a lot more information produced through the regression besides the default <code>nls</code> output seen here. This additional information can be accessed by other generic functions (eg, <code>confint</code>, <code>summary</code>, <code>predict</code>, <code>residuals</code>, etc). See <code>?nlsLM</code> for more details.</p>
<p>Second, it states the model, not in general terms, but in terms of the input variables. In spoken English reading from right to left, the model says, “fit this model to the A600 values”. This is worthy of a look just to make sure we have the right model.</p>
<p>The output estimates for the parameters k and ylo are the most important features of this regression output. They are what we most want. <span class="math inline">\(k=0.5092 per hour\)</span> while <span class="math inline">\(ylo=77.08 in A600 units\)</span></p>
<p>We’ll discuss later how we work with these parameter estimates statistically when doing experiments.</p>
<p>The fact that the regression converges to a solution is hopeful. It suggests a good fit but that’s not always the case. It is important to look at that fit because sometimes regression can converge to an absurd solution.</p>
</div>
<div id="check-the-fit-graphically" class="section level3">
<h3><span class="header-section-number">38.2.5</span> Check the fit graphically</h3>
<p>As a first step, the bloody obvious test is the best way to assess a fit of the model to the data. That comes from looking at the regression fit graphically. Does that curve look good and right?</p>
<p>In the code chunk below shows two regression fits. The blue line is similar to the fitted output, but not identical because it is unweighted. The regression for the blue line is actually performed within ggplot2’s <code>geom_smooth</code> function. It’s the way to go when doing unweighted regression.</p>
<p>Some quirks. Note how the formula must be argued in a generic form. The ggplot <code>aes</code> previously defined x=hours and y=A600. Notice the start argument values, put there to make it easier to get the right solution. Without them the regression may or may not self start. I’d say that blue curve is a pretty good fit. But YMMV.</p>
<p>Drawing the model that is the precise fit of the <code>fitegro</code> function is executed using the <code>stat_function</code>. Remember homework 4 when we did this with the dnorm function? We simply take the regression parameter values and pop them into a custom function.</p>
<div class="sourceCode" id="cb814"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb814-1" title="1"><span class="kw">ggplot</span>(edata, </a>
<a class="sourceLine" id="cb814-2" title="2">       <span class="kw">aes</span>(hours, A600))<span class="op">+</span></a>
<a class="sourceLine" id="cb814-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb814-4" title="4"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span>minpack.lm<span class="op">::</span>nlsLM,</a>
<a class="sourceLine" id="cb814-5" title="5">      <span class="dt">formula =</span> <span class="st">&quot;y ~ ylo*exp(k*x)&quot;</span>, <span class="co">#note how this is a general formula</span></a>
<a class="sourceLine" id="cb814-6" title="6">      <span class="dt">method.args =</span> <span class="kw">list</span>(</a>
<a class="sourceLine" id="cb814-7" title="7">        <span class="dt">start=</span><span class="kw">c</span>(<span class="dt">ylo=</span><span class="dv">77</span>,<span class="dt">k=</span><span class="fl">0.5</span>)),</a>
<a class="sourceLine" id="cb814-8" title="8">      <span class="dt">se=</span>F)<span class="op">+</span></a>
<a class="sourceLine" id="cb814-9" title="9"><span class="st">  </span><span class="kw">stat_function</span>(<span class="dt">fun =</span> <span class="cf">function</span>(.x) <span class="fl">77.0827</span><span class="op">*</span><span class="kw">exp</span>(.x<span class="op">*</span><span class="fl">0.5092</span>), <span class="dt">color=</span><span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-420"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-420-1.png" alt="Look at the model's curves to check on the fit." width="672" />
<p class="caption">
Figure 38.2: Look at the model’s curves to check on the fit.
</p>
</div>
<p>Notice how the red line is not equivalent to the blue line. That is the effect of weighted regression.</p>
</div>
<div id="convergence" class="section level3">
<h3><span class="header-section-number">38.2.6</span> Convergence?</h3>
<p>Now a word about the word convergence, which has pragmatic importance.</p>
<p>Nonlinear regression in R (and commercial software) resolves parameter values by an iterative algorithm that converges onto the solution. Iterative minimization of the residual error via ordinary least squares lies at the core of this method.</p>
<p>The model these algorithms are actually working with has an added term for residual error, <span class="math inline">\(\epsilon\)</span></p>
<p><span class="math display">\[y=y_{min}\times e^{k*x}+\epsilon\]</span></p>
<p>The nonlinear regression algorithm calculates values for <span class="math inline">\(y_{min}\)</span> and <span class="math inline">\(k\)</span> that also give the lowest possible value of <span class="math inline">\(\epsilon\)</span>. Best fit happens when the sum of the residual differences from the data points to the model’s curve are minimized with any additional changes in <span class="math inline">\(y_{min}\)</span> and <span class="math inline">\(k\)</span>.</p>
<p>The software method takes the data along with starting parameter estimates fed by the researcher, calculates residuals, modifies those estimates, re-calculates residuals, modifies the parameter values again, and so on. Usually it takes a half-dozen or more of these cycles to converge on a stable minimization of residual error. It took 13 cycles in the example above.</p>
</div>
<div id="convergence-is-not-idiot-proof" class="section level3">
<h3><span class="header-section-number">38.2.7</span> Convergence is not idiot proof</h3>
<p>Getting regression to converge is the key. But did it converge correctly?</p>
<p>It is important to understand that several factors influence how well regression goes and whether it converges.</p>
<p>The starting values the researcher suggests can affect how well convergence to a solution works. Bad estimates can cause convergence to not occur, or to veer off into a nonsense fit.</p>
<p>The fitting algorithm itself impacts whether there is convergence to a solution. Of the 4 options (see below), I think the Levenberg-Marquardt algorithm plays best with typical biological models and over a range of data from crappy to tight. YMMV.</p>
<p>Noisy data is hard to look at and even harder for the fitting algorithms to solve. When the data is crappy, don’t expect a fit to work. This isn’t reading tea leaves.</p>
<p>Use as many data points as possible. Nonlinear regression feasts on data points. The more data points in a data set, the better things work. There are a few ways to do this. When the set has technical replicates, leave them all there. Don’t average them. When doing time courses or dose-responses, add more time points or doses.</p>
<p>The number of parameters influences convergence. Every model parameter comes at the cost of a degree of freedom. A model with too many parameters and too few data points is probably not going to work. If there are only 6 dose levels, no replicates, and 4 parameters in the model, it is probably not going to converge. YMMV.</p>
<p>Finally, when there are results, the question is did this function produce the the best fit?</p>
<p>Technically, yes, when convergence is achieved, by the standard of minimizing <span class="math inline">\(\epsilon\)</span>, these parameter values are the best fit <strong>of that model</strong>. That is not the same as asking whether this model is the best for that data. There may be other models that fit better. Nested model nonlinear regression is a way to test if one of two related models fit.</p>
<p>The bottom line is that compared to the other statistical methods we’ve covered to this point in the course, nonlinear regression is bit more hands on. We have to know our models. We have to know our data. Which means we have to know what the model parameters mean, and we have to know what values we can reasonably expect for them.</p>
</div>
</div>
<div id="nonlinear-models-in-general" class="section level2">
<h2><span class="header-section-number">38.3</span> Nonlinear models in general</h2>
<p>There are many different nonlinear models to choose from that are routinely deployed for analysis of biological systems. Every model has parameters that carry specific biological meaning.</p>
<p>It’s not necessary to learn every nonlinear model. Chances are that if we need nonlinear regression in our work we’re working with a single model or maybe a pair. Chances are we’ll need one that is a well-understood, “off the shelf” model, rather than writing a new custom model.</p>
<p>The GraphPad Prism Statistics Guide offers <a href="https://www.graphpad.com/guides/prism/8/curve-fitting/index.htm?Reg_Classic_DR_variable.htm">an excellent comprehensive resource</a> for nonlinear regression, including a couple of dozen different functions. You may recognize the shape of your own data in some of these. All of the basic concepts that are part of solving nonlinear regression problems using the Prism software apply to using R (or any other software).</p>
</div>
<div id="nlfitr" class="section level2">
<h2><span class="header-section-number">38.4</span> nlfitr</h2>
<p>We (myself, Jessica Hoffman, Austin Nuckols and Lauren Jeffers) are working on a package called <code>nlfitr</code>. You can install the most current MVP (minimal viable product) onto your R version from Github. Our vision is for nlfitr to be a comprehensive resource for nonlinear regression in R.</p>
<p>The ultimate goal of the package is to offer researchers off the shelf functionality in terms of specific models, along with the better behaved Levenberg-Marquardt algorithm. This can go a long ways towards making nonlinear regression in R easier.</p>
<p>At its current stage, the functions in nlfitr fall into two classes: simulation or fitting functions. The simulation functions are intended to serve as sandboxes for learning how a given nonlinear model works. That’s through playing with the model parameters and variables and see how that affects the curves.</p>
<p>These sim functions are also intended for use in experimental planning, such as establishing feasibility, Monte Carlo testing, and so on. The sim functions with heterscedastic simulation capability offer a way to simulate a very common feature of biological data…higher variance at higher input levels.</p>
<p>The fitting functions are for fitting a given nonlinear model to some experimental data. In effect, they are wrapper functions for <code>nlsLM</code>. For the most part, they do the formula specification work for the user, which makes using nlsLM much easier.</p>
</div>
<div id="nonlinear-regression-functions-in-r" class="section level2">
<h2><span class="header-section-number">38.5</span> Nonlinear regression functions in R</h2>
<p>From here on the assumption is the researcher wishes to use <code>nls</code> or <code>nlsLM</code> directly, and not <code>nlfitr</code>. This section also provides more information about nonlinear regression in R that is worth understanding.</p>
<p>The main nonlinear regression functions in R are <code>nls</code> in the base <code>stats</code> package and also <code>nlsLM</code> from the <code>minpack.lm</code> package. <code>nlsLM</code> is a wrapper function for <code>nls</code>, designed to run virtually the same as <code>nls</code>.</p>
<div id="the-fitting-algorithms" class="section level3">
<h3><span class="header-section-number">38.5.1</span> The fitting algorithms</h3>
<p>The fitting algorithms used in <code>nls</code> are the real engine in nonlinear regression. The three fitting algorithm options in <code>nls</code> include the Gauss-Newton, Golub_Pereyra and Port. <code>nlsLM</code> offers a fourth–the Levenberg-Marquardt. The details of these are beyond the scope. When they work, all four will give very close to the same results, but not exactly the same.</p>
<p>Pragmatically, their main differences is that they don’t always work on a given dataset.</p>
<p>The researcher can select among these to find one that solves their own nonlinear regression. Of the four, my general impression is that the Levenberg-Marquardt plays nicest, which means it is less likely to fail to reach convergence than the others. That explains why we use it in the <code>nlfitr</code> package. YMMV.</p>
<p>Let’s just keep things simple for a moment and talk as if <code>nls</code> and <code>nlsLM</code> are the same thing and discuss the key features:</p>
</div>
<div id="formula" class="section level3">
<h3><span class="header-section-number">38.5.2</span> formula</h3>
<p>Nonlinear regression functions require the researcher to define a nonlinear formula. A formula is a translation of a nonlinear model equation into a format that R can work with. For example, here again is the exponential model: <span class="math display">\[y=y_{min}\times e^{k*x}\]</span></p>
<p>Here is the corresponding general formula for nls: <span class="math display">\[y \sim~ ylo*exp(k*x) \]</span></p>
<p>When using the nls-based functions, the formula has to be modified further to correspond to the variables in the working dataset. For our bacterial growth example above we have to tell the <code>nlsLM</code> function exactly which variables to regress. Note how y and x in the formula are replaced by A600 and hours:</p>
<div class="sourceCode" id="cb815"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb815-1" title="1"><span class="kw">nlsLM</span>(A600<span class="op">~</span>ylo<span class="op">*</span><span class="kw">exp</span>(k<span class="op">*</span>hours), <span class="dt">data=</span>edata, <span class="dt">start=</span><span class="kw">list</span>(<span class="dt">ylo=</span><span class="dv">100</span>, <span class="dt">k=</span><span class="dv">1</span>))</a></code></pre></div>
<pre><code>## Nonlinear regression model
##   model: A600 ~ ylo * exp(k * hours)
##    data: edata
##     ylo       k 
## 44.8304  0.5831 
##  residual sum-of-squares: 1.09e+08
## 
## Number of iterations to convergence: 13 
## Achieved convergence tolerance: 1.49e-08</code></pre>
<p>A point of confusion: ggplot has a different standard (see the graph above with the fitted curve). In geom_smooth, the formula is kept in general terms.</p>
</div>
<div id="data-1" class="section level3">
<h3><span class="header-section-number">38.5.3</span> data</h3>
<p>We have experimental data as <span class="math inline">\(x, y\)</span> pairs. Both are continuous variables. Create a data frame that has a column for each. When the experiment has multiple replicates, whether independent or technical, list all replicates under either of the two columns. Add a third column with a replicate ID.</p>
<p>R differs from other software. You don’t want a separate column for every replicate. <code>pivot_longer</code> is your friend.</p>
<p>The column names can, and should, be natural. Name the variables as you would otherwise. There is no need to label them <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
</div>
<div id="start" class="section level3">
<h3><span class="header-section-number">38.5.4</span> start</h3>
<p>Although nls can self Start without any hints for the values of the model parameters, it’s usually best to feed a list of starting values. These get the iterations off on the right track. They only need to be rough guesses of what the final values might be.</p>
</div>
<div id="weighting" class="section level3">
<h3><span class="header-section-number">38.5.5</span> weighting</h3>
<p>In OLS the data points that are furthest from the model’s curve contribute more to the overall sums of squares. As a result, the curve tends to be “pulled” in the direction of these outliers.</p>
<p>It is very common for nonlinear biological data to have greater variation at higher values of responses than at lower values. Therefore, when we don’t adjust for this heteroscedasticity the regression solutions are biased towards the data points in the sample that are further away from the curve.</p>
<p>Weighted nonlinear regression is just a method to discount this excessive variation and give all data points a more equal contribution to the overall regression solution. Weighted nonlinear regression minimizes the weighted sums of squares rather than minimizing the unweighted sums of squares.</p>
<p>There are a variety of weighting schemes. The one recommended for continuous data is the reciprocal y^2 method. Reciprocation is a simple way of reducing variance without changing the relationship of a variables values. Thus, the sums of squares are minimized using <span class="math inline">\(1/y^2\)</span> values rather than <span class="math inline">\(y\)</span>.</p>
</div>
</div>
<div id="nonlinear-models-and-parameters" class="section level2">
<h2><span class="header-section-number">38.6</span> Nonlinear models and parameters</h2>
<p>A nonlinear model is just an equation or function that describes the relationship between a predictor variable <span class="math inline">\(X\)</span> and an outcome variable <span class="math inline">\(Y\)</span>. The shape of the relationship is dictated by the equation’s parameters. Thus, values for <span class="math inline">\(Y\)</span> are determined by a nonlinear combination of values for <span class="math inline">\(X\)</span> and the equation parameter(s), which we can label generically as <span class="math inline">\(\beta\)</span>.</p>
<div id="hyperbolic-stimulus-response-functions" class="section level3">
<h3><span class="header-section-number">38.6.1</span> Hyperbolic stimulus response functions</h3>
<p>The general hyperbolic function is, <span class="math display">\[Y=\frac{y_{max}\times X^h}{K^h + X^h}\]</span></p>
<p>This function, <strong>and its many derivatives</strong>, are used to model a diverse array of stimulus-response systems in biology, making it perhaps the most important mathematical relationship in the field.</p>
<p>The basis of these phenomena is the mass action principle, <span class="math display">\[X+Y \rightleftharpoons  XY\]</span>, where <span class="math inline">\(XY\)</span> represents any response dependent upon both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
<p>These include Michaelis-Menten enzyme kinetics, stimulus/dose-response phenomena, bi-molecular binding, and much more.</p>
<p>The equation has three parameters: The maximal value of <span class="math inline">\(Y\)</span> is estimated asymptotically as <span class="math inline">\(y_{max}\)</span>. The parameter <span class="math inline">\(K\)</span> represents the value of <span class="math inline">\(X\)</span> that yields the half-maximal response, or <span class="math inline">\(\frac{y_{max}}{2}\)</span>. The Hill slope, <span class="math inline">\(h\)</span>, operates in the function as an exponential coefficient. Therefore, it determines both the steepness and the sign of the relationship between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>.</p>
<p>Each of these parameters can have different physical meanings, depending upon the biological process that the hyperbolic function is applied to.</p>
<p>For example, with bi molecular binding data, <span class="math inline">\(y_{max}\)</span> represents the number of binding sites or complexes, <span class="math inline">\(XY\)</span>; <span class="math inline">\(K\)</span> represents the equilibrium dissociation constant, or affinity, between the two molecules; and the value of <span class="math inline">\(h\)</span> provides insights into whether the binding deviates from simple mass action. For example, the Hill slope value may suggest positive (<span class="math inline">\(h&gt;1\)</span>) or negative (<span class="math inline">\(0&lt;h&lt;1\)</span>) cooperativity. Negative values of <span class="math inline">\(h\)</span> generate downward-sloping curves; for example, inhibition of <span class="math inline">\(Y\)</span> by <span class="math inline">\(X\)</span> occur when <span class="math inline">\(h&lt;0\)</span>, and these can be very steep or shallow, too.</p>
<p>Hyperbolic functions are responsible for graded responses that can occur over a wide range of values of the predictor variable. When plotted on a linear X-scale, the predictor-response relationship has a hyperbolic-like shape, thus their name.</p>
<div class="sourceCode" id="cb817"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb817-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb817-2" title="2">p1 &lt;-<span class="st"> </span><span class="kw">simhetdr</span>(<span class="dt">x=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">10</span>,<span class="dv">30</span>,<span class="dv">100</span>,<span class="dv">300</span>,<span class="dv">1000</span>,<span class="dv">3000</span>), <span class="dt">k=</span><span class="dv">100</span>, <span class="dt">ylo=</span><span class="dv">100</span>, <span class="dt">yhi=</span><span class="dv">300</span>, <span class="dt">h=</span><span class="dv">1</span>, <span class="dt">cv=</span><span class="fl">0.15</span>, <span class="dt">reps=</span><span class="dv">3</span>, <span class="dt">log=</span>F)</a>
<a class="sourceLine" id="cb817-3" title="3"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb817-4" title="4">p2 &lt;-<span class="st"> </span><span class="kw">simhetdr</span>(<span class="dt">x=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">10</span>,<span class="dv">30</span>,<span class="dv">100</span>,<span class="dv">300</span>,<span class="dv">1000</span>,<span class="dv">3000</span>), <span class="dt">k=</span><span class="dv">100</span>, <span class="dt">ylo=</span><span class="dv">100</span>, <span class="dt">yhi=</span><span class="dv">300</span>, <span class="dt">h=</span><span class="dv">1</span>, <span class="dt">cv=</span><span class="fl">0.15</span>, <span class="dt">reps=</span><span class="dv">3</span>, <span class="dt">log=</span>T)</a>
<a class="sourceLine" id="cb817-5" title="5"><span class="kw">plot_grid</span>(p1, p2, <span class="dt">labels=</span><span class="st">&quot;AUTO&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-422"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-422-1.png" alt="A. Linear scale plot of hyperbolic data. B. Log10 scale plot of hyperbolic data." width="672" />
<p class="caption">
Figure 38.3: A. Linear scale plot of hyperbolic data. B. Log10 scale plot of hyperbolic data.
</p>
</div>
<p>The same data appear more ‘S’ shaped when plotted on a log x-scale. However, it is important to point out that extreme values of <span class="math inline">\(h\)</span> can dramatically change these more typical relationships. As values of <span class="math inline">\(h\)</span> get larger, the <span class="math inline">\(Y\)</span> response to <span class="math inline">\(X\)</span> is more switch-like than graded.</p>
<div class="sourceCode" id="cb818"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb818-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1233</span>)</a>
<a class="sourceLine" id="cb818-2" title="2">p1 &lt;-<span class="st"> </span><span class="kw">simhetdr</span>(<span class="dt">x=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">10</span>,<span class="dv">30</span>,<span class="dv">100</span>,<span class="dv">300</span>,<span class="dv">1000</span>,<span class="dv">3000</span>), <span class="dt">k=</span><span class="dv">100</span>, <span class="dt">ylo=</span><span class="dv">100</span>, <span class="dt">yhi=</span><span class="dv">300</span>, <span class="dt">h=</span><span class="dv">2</span>, <span class="dt">cv=</span><span class="fl">0.15</span>, <span class="dt">reps=</span><span class="dv">3</span>, <span class="dt">log=</span>F)</a>
<a class="sourceLine" id="cb818-3" title="3"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb818-4" title="4">p2 &lt;-<span class="st"> </span><span class="kw">simhetdr</span>(<span class="dt">x=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">10</span>,<span class="dv">30</span>,<span class="dv">100</span>,<span class="dv">300</span>,<span class="dv">1000</span>,<span class="dv">3000</span>), <span class="dt">k=</span><span class="dv">100</span>, <span class="dt">ylo=</span><span class="dv">100</span>, <span class="dt">yhi=</span><span class="dv">300</span>, <span class="dt">h=</span><span class="dv">2</span>, <span class="dt">cv=</span><span class="fl">0.15</span>, <span class="dt">reps=</span><span class="dv">3</span>, <span class="dt">log=</span>T)</a>
<a class="sourceLine" id="cb818-5" title="5"><span class="kw">plot_grid</span>(p1, p2, <span class="dt">labels=</span><span class="st">&quot;AUTO&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-423"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-423-1.png" alt="Influence of higher Hill slope. A. Linear scale plot of hyperbolic data. B. Log10 scale plot of hyperbolic data." width="672" />
<p class="caption">
Figure 38.4: Influence of higher Hill slope. A. Linear scale plot of hyperbolic data. B. Log10 scale plot of hyperbolic data.
</p>
</div>
<p>S-shaped curves have lower and upper plateaus. These plateau values correspond to the <code>ylo</code> and <code>yhi</code> parameter values that you’ll see in the formulas for the nonlinear models below. The span between the plateaus represents the dynamic range of the response variable, <span class="math inline">\(y_{max}=yhi-ylo\)</span>.</p>
<p>Incorporating <code>ylo</code> and <code>yhi</code> into a working formula for the hyperbolic model allows for a more regression friendly way of expressing it. This allows the operator some flexibility when initializing the regression using start estimates. For example, when working with a difficult data set the regression has a better chance for solving the other parameters, <code>ylo</code> or <code>yhi</code>, or both, when they are held at fixed values.</p>
</div>
<div id="visualizing-nonlinear-data-and-log-scaling" class="section level3">
<h3><span class="header-section-number">38.6.2</span> Visualizing nonlinear data and log scaling</h3>
<p>Nonlinear data generally occur over orders of magnitudes. Either the responses are ‘log normal’ or, more often, the predictor variable is applied over a range spanning a few orders of magnitude. For example, doses of a drug at 10, 100 and 1000 units span three orders of magnitude.</p>
<p>Look very carefully at the code below, which simulates nonlinear data.</p>
<p>The code passes <em>linear values</em> of <span class="math inline">\(X\)</span> into a hyperbolic formula that’s been written for regression. Some initial, arbitrary parameter values are entered to give the data shape and location.</p>
<p>I strongly urge you to use this code chunk as a sandbox. Leave the formula alone but play around with with the values of the initial variables, including the predictor, <span class="math inline">\(x\)</span>. That’s the best way to see how they all work together.</p>
<p>The two graphs plot identical values for both the <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> variables. The only difference is the plotting background, one is log scale and the other is not. Note how that is accomplished using ggplot arguments. You can think of the plot on the left as being drawn on linear graph paper, and the one on the right as being drawn on semi-log graph paper. The latter rescales the x-variable without changing it’s values.</p>
<div class="sourceCode" id="cb819"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb819-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">1e-8</span>, <span class="fl">3e-8</span>, <span class="fl">1e-7</span>, <span class="fl">3e-7</span>, <span class="fl">1e-6</span>, <span class="fl">3e-6</span>, <span class="fl">1e-5</span>)</a>
<a class="sourceLine" id="cb819-2" title="2"></a>
<a class="sourceLine" id="cb819-3" title="3"><span class="co">#initial values, arbitrary units</span></a>
<a class="sourceLine" id="cb819-4" title="4">h &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb819-5" title="5">k &lt;-<span class="st"> </span><span class="fl">3e-7</span></a>
<a class="sourceLine" id="cb819-6" title="6">ylo &lt;-<span class="st"> </span><span class="dv">30</span></a>
<a class="sourceLine" id="cb819-7" title="7">yhi &lt;-<span class="st"> </span><span class="dv">330</span></a>
<a class="sourceLine" id="cb819-8" title="8"></a>
<a class="sourceLine" id="cb819-9" title="9"><span class="co">#hyperbolic formula for linear scale</span></a>
<a class="sourceLine" id="cb819-10" title="10">y &lt;-<span class="st"> </span>ylo<span class="op">+</span><span class="st"> </span>((yhi<span class="op">-</span>ylo)<span class="op">*</span>x<span class="op">^</span>h)<span class="op">/</span>(k<span class="op">^</span>h<span class="op">+</span>x<span class="op">^</span>h)</a>
<a class="sourceLine" id="cb819-11" title="11"></a>
<a class="sourceLine" id="cb819-12" title="12"><span class="co">#linear x scale</span></a>
<a class="sourceLine" id="cb819-13" title="13">p3 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(</a>
<a class="sourceLine" id="cb819-14" title="14">  <span class="kw">data.frame</span>(x, y), </a>
<a class="sourceLine" id="cb819-15" title="15">  <span class="kw">aes</span>(x, y))<span class="op">+</span></a>
<a class="sourceLine" id="cb819-16" title="16"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size=</span><span class="dv">4</span>, <span class="dt">color=</span><span class="st">&quot;#f2a900&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb819-17" title="17"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits=</span><span class="kw">c</span>(<span class="fl">1e-8</span>, <span class="fl">1e-5</span>))<span class="op">+</span></a>
<a class="sourceLine" id="cb819-18" title="18"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;Linear scale&quot;</span>)</a>
<a class="sourceLine" id="cb819-19" title="19"></a>
<a class="sourceLine" id="cb819-20" title="20"><span class="co">#log10 x scale</span></a>
<a class="sourceLine" id="cb819-21" title="21">p4 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(</a>
<a class="sourceLine" id="cb819-22" title="22">  <span class="kw">data.frame</span>(x, y), </a>
<a class="sourceLine" id="cb819-23" title="23">  <span class="kw">aes</span>(x, y))<span class="op">+</span></a>
<a class="sourceLine" id="cb819-24" title="24"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size=</span><span class="dv">4</span>, <span class="dt">color=</span><span class="st">&quot;#f2a900&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb819-25" title="25"><span class="st">  </span><span class="co">#scale_x_log10()+</span></a>
<a class="sourceLine" id="cb819-26" title="26"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">trans=</span><span class="st">&quot;log10&quot;</span>, <span class="dt">limits=</span> <span class="kw">c</span>(<span class="fl">1e-8</span>, <span class="fl">1e-5</span>))<span class="op">+</span></a>
<a class="sourceLine" id="cb819-27" title="27"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;Log10 scaled aesthetic&quot;</span>, <span class="dt">x=</span><span class="st">&quot;log10[X]&quot;</span>)</a>
<a class="sourceLine" id="cb819-28" title="28"></a>
<a class="sourceLine" id="cb819-29" title="29"><span class="kw">plot_grid</span>(p3, p4, <span class="dt">labels=</span><span class="st">&quot;AUTO&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-424"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-424-1.png" alt="A closer look at linear log10 scaling." width="672" />
<p class="caption">
Figure 38.5: A closer look at linear log10 scaling.
</p>
</div>
<div id="logx-scaling-the-hyperbolic-function" class="section level4">
<h4><span class="header-section-number">38.6.2.1</span> LogX scaling the hyperbolic function</h4>
<p>As usual for R, there are a few ways to solve the log scaling problem. An alternative is transform the predictor variable to a log scale. For example, the dose range mentioned above of 10, 100 and 1000 units transformed to <span class="math inline">\(log_{10}\)</span> units is 1, 2 and 3. Thus, the vector for the predictor would be <code>x&lt;-c(1, 2, 3)</code>.</p>
<p>When using a vector on a log scale, the regression is performed using a semi-log transformation of the hyperbolic function: <span class="math display">\[Y=\frac{Y_{max}}{1+10^{(log10K-X)\times h}}\]</span></p>
<p>Note in the code below that the <span class="math inline">\(X\)</span> is transformed from a linear to log10 scale. Since we are regressing on <span class="math inline">\(log_{10}\)</span> values of <span class="math inline">\(X\)</span>, we solve the <span class="math inline">\(K\)</span> parameter in in log units, as well. The values of <span class="math inline">\(Y\)</span> remain on a linear scale.</p>
<p>Note also that the log10 of 3e-8 is -7.523, which is approximately a half log unit between 1e-8 and 1e-7. A value of 5e-8, which is half-way between 1e-8 and 1e-7 on a linear scale, is about a third of a log unit (-7.301) between -8 and -7.</p>
<div class="sourceCode" id="cb820"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb820-1" title="1">x &lt;-<span class="st"> </span><span class="kw">log10</span>(<span class="kw">c</span>(<span class="fl">1e-8</span>, <span class="fl">3e-8</span>, <span class="fl">1e-7</span>, <span class="fl">3e-7</span>, <span class="fl">1e-6</span>, <span class="fl">3e-6</span>, <span class="fl">1e-5</span>))</a>
<a class="sourceLine" id="cb820-2" title="2"><span class="co">#or you could just write these out:</span></a>
<a class="sourceLine" id="cb820-3" title="3"><span class="co">#x &lt;- c(-8, -7.523, -7, -6.523, -6, -5.523, -5)</span></a>
<a class="sourceLine" id="cb820-4" title="4"></a>
<a class="sourceLine" id="cb820-5" title="5">h &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb820-6" title="6"></a>
<a class="sourceLine" id="cb820-7" title="7">logk &lt;-<span class="st"> </span><span class="kw">log10</span>(<span class="fl">3e-7</span>)</a>
<a class="sourceLine" id="cb820-8" title="8"></a>
<a class="sourceLine" id="cb820-9" title="9">ylo &lt;-<span class="st"> </span><span class="dv">30</span></a>
<a class="sourceLine" id="cb820-10" title="10">yhi &lt;-<span class="st"> </span><span class="dv">330</span></a>
<a class="sourceLine" id="cb820-11" title="11"></a>
<a class="sourceLine" id="cb820-12" title="12"><span class="co">#hyperbolic semi-log model rewritten as a formula</span></a>
<a class="sourceLine" id="cb820-13" title="13">y=ylo<span class="op">+</span>((yhi<span class="op">-</span>ylo)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="dv">10</span><span class="op">^</span>((logk<span class="op">-</span>x)<span class="op">*</span>h)))</a>
<a class="sourceLine" id="cb820-14" title="14"></a>
<a class="sourceLine" id="cb820-15" title="15"><span class="kw">ggplot</span>(</a>
<a class="sourceLine" id="cb820-16" title="16">  <span class="kw">data.frame</span>(x, y), </a>
<a class="sourceLine" id="cb820-17" title="17">  <span class="kw">aes</span>(x, y))<span class="op">+</span></a>
<a class="sourceLine" id="cb820-18" title="18"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size=</span><span class="dv">4</span>, <span class="dt">color=</span><span class="st">&quot;#f2a900&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb820-19" title="19"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;Linearized X scale by log10(X) transform&quot;</span>)</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-425-1.png" width="672" /></p>
</div>
<div id="creating-a-best-fit-curve-in-graph" class="section level4">
<h4><span class="header-section-number">38.6.2.2</span> Creating a best fit curve in graph</h4>
<p>It’s very simple to generate an on-the-fly best fit curve using ggplot. This doesn’t yield regression output and parameter values, but it does draw a pretty picture.</p>
<p>This is on simulated data, but all you’d need to do is pass a data frame of your own <span class="math inline">\(x,y\)</span> data into ggplot and add the <code>stat_smooth function</code> to achieve the same effect. It really is that simple!</p>
<p>The only trick is knowing the formula that you’d like to model to the data, and coming up with a list of some starting parameter values.</p>
<p>Note below how it’s been fed some start estimates that are a bit off the mark, given the data points, but it still arrives at a solution that fits well. You should experiment with changing those estimates to get a sense of how far off is too far off before the <code>nls</code> function fails to provide a curve.</p>
<div class="sourceCode" id="cb821"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb821-1" title="1">x &lt;-<span class="st"> </span><span class="kw">log10</span>(<span class="kw">c</span>(<span class="fl">1e-8</span>, <span class="fl">3e-8</span>, <span class="fl">1e-7</span>, <span class="fl">3e-7</span>, <span class="fl">1e-6</span>, <span class="fl">3e-6</span>, <span class="fl">1e-5</span>))</a>
<a class="sourceLine" id="cb821-2" title="2"><span class="co">#x &lt;- c(-8, -7.523, -7, -6.523, -6, -5.523, -5)</span></a>
<a class="sourceLine" id="cb821-3" title="3"></a>
<a class="sourceLine" id="cb821-4" title="4">h &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb821-5" title="5"></a>
<a class="sourceLine" id="cb821-6" title="6">logk &lt;-<span class="st"> </span><span class="kw">log10</span>(<span class="fl">3e-7</span>)</a>
<a class="sourceLine" id="cb821-7" title="7"></a>
<a class="sourceLine" id="cb821-8" title="8">ylo &lt;-<span class="st"> </span><span class="dv">30</span></a>
<a class="sourceLine" id="cb821-9" title="9">yhi &lt;-<span class="st"> </span><span class="dv">330</span></a>
<a class="sourceLine" id="cb821-10" title="10"></a>
<a class="sourceLine" id="cb821-11" title="11"><span class="co">#hyperbolic function</span></a>
<a class="sourceLine" id="cb821-12" title="12">y=ylo<span class="op">+</span>((yhi<span class="op">-</span>ylo)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="dv">10</span><span class="op">^</span>((logk<span class="op">-</span>x)<span class="op">*</span>h))) <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(x), <span class="dv">0</span>, <span class="dv">45</span>)</a>
<a class="sourceLine" id="cb821-13" title="13"></a>
<a class="sourceLine" id="cb821-14" title="14"><span class="kw">ggplot</span>(</a>
<a class="sourceLine" id="cb821-15" title="15">  <span class="kw">data.frame</span>(x, y), </a>
<a class="sourceLine" id="cb821-16" title="16">  <span class="kw">aes</span>(x, y))<span class="op">+</span></a>
<a class="sourceLine" id="cb821-17" title="17"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size=</span><span class="dv">4</span>, <span class="dt">color=</span><span class="st">&quot;#f2a900&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb821-18" title="18"><span class="st">  </span><span class="kw">geom_smooth</span>(</a>
<a class="sourceLine" id="cb821-19" title="19">    <span class="dt">method=</span>nls,</a>
<a class="sourceLine" id="cb821-20" title="20">    <span class="dt">formula =</span> <span class="st">&quot;y~ylo+((yhi-ylo)/(1+10^((logk-x)*h)))&quot;</span>,</a>
<a class="sourceLine" id="cb821-21" title="21">              <span class="dt">method.args =</span> <span class="kw">list</span>(</a>
<a class="sourceLine" id="cb821-22" title="22">                <span class="dt">start=</span><span class="kw">c</span>(<span class="dt">yhi=</span><span class="dv">150</span>,</a>
<a class="sourceLine" id="cb821-23" title="23">                        <span class="dt">ylo=</span><span class="dv">50</span>,</a>
<a class="sourceLine" id="cb821-24" title="24">                        <span class="dt">logk=</span><span class="op">-</span><span class="dv">7</span>)</a>
<a class="sourceLine" id="cb821-25" title="25">                               ),</a>
<a class="sourceLine" id="cb821-26" title="26">              <span class="dt">se=</span>F, <span class="co">#you need this line for nls graphs and it is not obvious!!</span></a>
<a class="sourceLine" id="cb821-27" title="27">              <span class="dt">color=</span><span class="st">&quot;red&quot;</span></a>
<a class="sourceLine" id="cb821-28" title="28">    </a>
<a class="sourceLine" id="cb821-29" title="29">  )<span class="op">+</span></a>
<a class="sourceLine" id="cb821-30" title="30"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;Best fit for random Y values; Linearized X by Log10(X) transform&quot;</span>)</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-426-1.png" width="672" /></p>
</div>
<div id="smoothing" class="section level4">
<h4><span class="header-section-number">38.6.2.3</span> Smoothing</h4>
<p>Smoothing is an artistic method to draw a nonlinear regression-ish line through the data. Smooths are more akin to polynomial fits. Every little twist and turn in a smooth would have a corresponding parameter if it were a polynomial regression!</p>
<p>The underlying calculation is a regression run over a sliding window, called <code>span</code> in R. If that span is small, the smooth is closer to point-to-point. And if the span is larger, the smooth is smoother. You simply adjust the value of span to dial in a curve that suites your eye.</p>
<div class="sourceCode" id="cb822"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb822-1" title="1"><span class="kw">set.seed</span>(<span class="dv">12345</span>)</a>
<a class="sourceLine" id="cb822-2" title="2">x &lt;-<span class="st"> </span><span class="kw">log10</span>(<span class="kw">c</span>(<span class="fl">1e-8</span>, <span class="fl">3e-8</span>, <span class="fl">1e-7</span>, <span class="fl">3e-7</span>, <span class="fl">1e-6</span>, <span class="fl">3e-6</span>, <span class="fl">1e-5</span>))</a>
<a class="sourceLine" id="cb822-3" title="3"><span class="co">#x &lt;- c(-8, -7.523, -7, -6.523, -6, -5.523, -5)</span></a>
<a class="sourceLine" id="cb822-4" title="4"></a>
<a class="sourceLine" id="cb822-5" title="5">h &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb822-6" title="6"></a>
<a class="sourceLine" id="cb822-7" title="7">logk &lt;-<span class="st"> </span><span class="kw">log10</span>(<span class="fl">3e-7</span>)</a>
<a class="sourceLine" id="cb822-8" title="8"></a>
<a class="sourceLine" id="cb822-9" title="9">ylo &lt;-<span class="st"> </span><span class="dv">30</span></a>
<a class="sourceLine" id="cb822-10" title="10">yhi &lt;-<span class="st"> </span><span class="dv">330</span></a>
<a class="sourceLine" id="cb822-11" title="11"></a>
<a class="sourceLine" id="cb822-12" title="12"><span class="co">#hyperbolic function</span></a>
<a class="sourceLine" id="cb822-13" title="13">y=ylo<span class="op">+</span>((yhi<span class="op">-</span>ylo)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="dv">10</span><span class="op">^</span>((logk<span class="op">-</span>x)<span class="op">*</span>h))) <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(x), <span class="dv">0</span>, <span class="dv">45</span>)</a>
<a class="sourceLine" id="cb822-14" title="14"></a>
<a class="sourceLine" id="cb822-15" title="15"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x,y), (<span class="kw">aes</span>(x, y)))<span class="op">+</span></a>
<a class="sourceLine" id="cb822-16" title="16"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size=</span><span class="dv">4</span>, <span class="dt">color=</span><span class="st">&quot;#f2a900&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb822-17" title="17"><span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;auto&quot;</span>,</a>
<a class="sourceLine" id="cb822-18" title="18">             <span class="dt">se=</span>F,</a>
<a class="sourceLine" id="cb822-19" title="19">              <span class="dt">color=</span><span class="st">&quot;red&quot;</span> ,</a>
<a class="sourceLine" id="cb822-20" title="20">              <span class="dt">span=</span><span class="fl">0.8</span></a>
<a class="sourceLine" id="cb822-21" title="21">              )<span class="op">+</span></a>
<a class="sourceLine" id="cb822-22" title="22"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y=</span><span class="st">&quot;mRNA levels&quot;</span>, <span class="dt">x=</span><span class="st">&quot;time, min&quot;</span>)</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="jabstb_files/figure-html/unnamed-chunk-427-1.png" width="672" /></p>
</div>
</div>
<div id="selecting-the-right-model" class="section level3">
<h3><span class="header-section-number">38.6.3</span> Selecting the right model</h3>
<div class="figure"><span id="fig:unnamed-chunk-428"></span>
<img src="images/nonlinear_model_choices.jpg" alt="Choosing the right model for your data is a scientific decision." width="480" />
<p class="caption">
Figure 38.6: Choosing the right model for your data is a scientific decision.
</p>
</div>
<p>We lean on scientific judgement to select the most appropriate nonlinear model for our data. Simply reach up to our metaphorical equation shelf to select one based upon our expertise (or willingness to become an expert) with the biological system.</p>
<p>At some point, <code>nlfitr</code> will be such a book shelf. Fork it on Github and keep an eye on our progress. Or write your own function and send a pull request to have it incorporated into the package. Whatever.</p>
<p>As I mentioned before, when unclear on what model to use inspiration can be found at <a href="https://www.graphpad.com/guides/prism/7/curve-fitting/reg_a_guide_to_nonlinear_regressio.htm">GraphPad’s nonlinear regression guide</a>.</p>
<p>If the model you need is not there, you’ve probably got something pretty unusual and will need to create one. That’s doable, <a href="https://stats.stackexchange.com/questions/62995/how-to-choose-initial-values-for-nonlinear-least-squares-fit">but usually not straightforward</a>.</p>
</div>
<div id="from-models-to-formulas" class="section level3">
<h3><span class="header-section-number">38.6.4</span> From models to formulas</h3>
<p>This section provides a potpourri view of nonlinear models. It focuses on translating nonlinear model equations into a formula needed to operate within a nonlinear regression function in R.</p>
<div id="michaelis-menten" class="section level4">
<h4><span class="header-section-number">38.6.4.1</span> Michaelis-Menten</h4>
<p>Take for example the generic hyperbolic model, which has many descendants and cousins. For example, one descendant is the Michaelis-Menten model for reaction kinetics: <span class="math display">\[v=\frac{V_{max}\times S}{K_M + S}\]</span></p>
<p>The initial velocity of a reaction <span class="math inline">\(v\)</span> at a given substrate concentration <span class="math inline">\(S\)</span> is bounded by the enzymes <span class="math inline">\(K_m\)</span> and maximal velocity <span class="math inline">\(V_{max}\)</span>. An experiment typically involves measuring product formation under initial velocity conditions over a broad range of substrate concentrations. The goal of the experiment to derive estimates for <span class="math inline">\(V_{max}\)</span> and <span class="math inline">\(K_m\)</span>. Nonlinear regression is needed to get those estimates.</p>
<p>Here’s a generalized formula readable by R’s nonlinear regression functions that can be used to regress Michaelis-Menten data: <span class="math display">\[y=ylo+((yhi-ylo)*x)/(K+x)\]</span></p>
<p>The value of <span class="math inline">\(Y\)</span> at it’s lowest and highest levels are <code>ylo</code> and <code>yhi</code>, respectively. The difference between those two values is the amplitude or dynamic range of the data, <code>y_{max}</code>, which corresponds to <span class="math inline">\(V_{max}\)</span>. The regression solves values for <code>ylo</code> and <code>yhi</code>. Later, you can calculate<code>y_{max}</code>.</p>
<p>Breaking out the amplitude in this way provides some flexibility in model fitting.</p>
</div>
<div id="hyperbolic-function-inhibition" class="section level4">
<h4><span class="header-section-number">38.6.4.2</span> Hyperbolic function inhibition</h4>
<p>Hyperbolic models can either be stimulation or inhibitory. There are a few different ways to model the latter.</p>
<p>The simplest is to use a negative Hill slope in the standard hyperbolic formula.</p>
<p><code>y &lt;- ylo+ ((yhi-ylo)*x^h)/(k^h+x^h)</code></p>
<div class="sourceCode" id="cb824"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb824-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">60</span>)</a>
<a class="sourceLine" id="cb824-2" title="2"></a>
<a class="sourceLine" id="cb824-3" title="3">ylo &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb824-4" title="4">yhi &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb824-5" title="5">h &lt;-<span class="st"> </span><span class="dv">-1</span></a>
<a class="sourceLine" id="cb824-6" title="6">k &lt;-<span class="st"> </span><span class="dv">30</span></a>
<a class="sourceLine" id="cb824-7" title="7"></a>
<a class="sourceLine" id="cb824-8" title="8">y &lt;-<span class="st"> </span>ylo<span class="op">+</span>((yhi<span class="op">-</span>ylo)<span class="op">*</span>x<span class="op">^</span>h)<span class="op">/</span>(k<span class="op">^</span>h<span class="op">+</span>x<span class="op">^</span>h)</a>
<a class="sourceLine" id="cb824-9" title="9"></a>
<a class="sourceLine" id="cb824-10" title="10"><span class="co">#linear plot</span></a>
<a class="sourceLine" id="cb824-11" title="11"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x,y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb824-12" title="12"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb824-13" title="13"></a>
<a class="sourceLine" id="cb824-14" title="14"><span class="co">#log plot</span></a>
<a class="sourceLine" id="cb824-15" title="15"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x,y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb824-16" title="16"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb824-17" title="17"><span class="st">  </span><span class="kw">scale_x_log10</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb824-18" title="18"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Log10(x)&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-429"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-429-1.png" alt="Inhibition: Linear and log plots" width="288" /><img src="jabstb_files/figure-html/unnamed-chunk-429-2.png" alt="Inhibition: Linear and log plots" width="288" />
<p class="caption">
Figure 38.7: Inhibition: Linear and log plots
</p>
</div>
<p>Alternately, the hyperbolic function can be inverted algebraically, deriving this model:</p>
<p><span class="math display">\[Y=\frac{Y_{max}}{1+\frac{X^h}{K^h}}\]</span></p>
<p>Whose formula is <code>y=ylo+((yhi-ylo)/(1+x^h/k^h))</code></p>
<div class="sourceCode" id="cb825"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb825-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">60</span>)</a>
<a class="sourceLine" id="cb825-2" title="2"></a>
<a class="sourceLine" id="cb825-3" title="3">ylo &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb825-4" title="4">yhi &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb825-5" title="5">h &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb825-6" title="6">k &lt;-<span class="st"> </span><span class="dv">30</span></a>
<a class="sourceLine" id="cb825-7" title="7"></a>
<a class="sourceLine" id="cb825-8" title="8">y &lt;-<span class="st"> </span>ylo<span class="op">+</span>((yhi<span class="op">-</span>ylo)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span>x<span class="op">^</span>h<span class="op">/</span>k<span class="op">^</span>h))</a>
<a class="sourceLine" id="cb825-9" title="9"></a>
<a class="sourceLine" id="cb825-10" title="10"><span class="co">#linear</span></a>
<a class="sourceLine" id="cb825-11" title="11"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x,y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb825-12" title="12"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb825-13" title="13"></a>
<a class="sourceLine" id="cb825-14" title="14"><span class="co">#log</span></a>
<a class="sourceLine" id="cb825-15" title="15"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x,y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb825-16" title="16"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb825-17" title="17"><span class="st">  </span><span class="kw">scale_x_log10</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb825-18" title="18"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Log10(x)&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-430"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-430-1.png" alt="More inhibition: Linear and log plots" width="288" /><img src="jabstb_files/figure-html/unnamed-chunk-430-2.png" alt="More inhibition: Linear and log plots" width="288" />
<p class="caption">
Figure 38.8: More inhibition: Linear and log plots
</p>
</div>
<p>Finally, a model for inhibition on a log10 scale would be:</p>
<p><span class="math display">\[Y=\frac{Y_{max}}{1+10^{(X-log10(K))*h}}\]</span></p>
<p>Its formula is <code>y=ylo+(yhi-ylo)/(1+10^(x-log10(K))*h)</code></p>
<div class="sourceCode" id="cb826"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb826-1" title="1">x &lt;-<span class="st"> </span><span class="kw">log10</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">600</span>, <span class="dv">10</span>))</a>
<a class="sourceLine" id="cb826-2" title="2"></a>
<a class="sourceLine" id="cb826-3" title="3">ylo &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb826-4" title="4">yhi &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb826-5" title="5">h &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb826-6" title="6">K  &lt;-<span class="st"> </span><span class="dv">45</span></a>
<a class="sourceLine" id="cb826-7" title="7"></a>
<a class="sourceLine" id="cb826-8" title="8">y &lt;-<span class="st"> </span>ylo<span class="op">+</span>(yhi<span class="op">-</span>ylo)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="dv">10</span><span class="op">^</span>(x<span class="op">-</span><span class="kw">log10</span>(K))<span class="op">*</span>h) </a>
<a class="sourceLine" id="cb826-9" title="9"></a>
<a class="sourceLine" id="cb826-10" title="10"></a>
<a class="sourceLine" id="cb826-11" title="11"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x,y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb826-12" title="12"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb826-13" title="13"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Log10(x)&quot;</span>)</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-431-1.png" width="672" /></p>
</div>
<div id="time-series" class="section level4">
<h4><span class="header-section-number">38.6.4.3</span> Time series</h4>
<p>When performing time-series experiments, many outcome responses can be modeled using exponential association or decay equations. For example, here’s a first order decay model: <span class="math display">\[Y=Y_0e^{-kt}\]</span></p>
<p>Here, the independent variable is time <span class="math inline">\(t\)</span>, in whatever units. The rate constant for a first order process has units of reciprocal time and is related to half-life: <span class="math inline">\(k=0.693/t_{1/2}\)</span></p>
<p>Here’s a generalized formula of it: <code>y=ylo+(yhi-ylo)*exp(-k*x)</code></p>
<p>A diagnostic of a first order decay process is that log10 transformation of <span class="math inline">\(Y\)</span> yields a linear response with time.</p>
<div class="sourceCode" id="cb827"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb827-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">60</span>)</a>
<a class="sourceLine" id="cb827-2" title="2"></a>
<a class="sourceLine" id="cb827-3" title="3">ylo &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb827-4" title="4">yhi &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb827-5" title="5">k &lt;-<span class="st"> </span><span class="kw">log</span>(<span class="dv">2</span>)<span class="op">/</span><span class="dv">30</span></a>
<a class="sourceLine" id="cb827-6" title="6"></a>
<a class="sourceLine" id="cb827-7" title="7">y &lt;-<span class="st"> </span>ylo<span class="op">+</span>(yhi<span class="op">-</span>ylo)<span class="op">*</span><span class="kw">exp</span>(<span class="op">-</span>k<span class="op">*</span>x)</a>
<a class="sourceLine" id="cb827-8" title="8"></a>
<a class="sourceLine" id="cb827-9" title="9"><span class="co">#linear</span></a>
<a class="sourceLine" id="cb827-10" title="10"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x, y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb827-11" title="11"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-432-1.png" width="672" /></p>
<div class="sourceCode" id="cb828"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb828-1" title="1"><span class="co">#log</span></a>
<a class="sourceLine" id="cb828-2" title="2"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x, y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb828-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb828-4" title="4"><span class="st">  </span><span class="kw">scale_y_log10</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb828-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y=</span><span class="st">&quot;Log10(y)&quot;</span>)</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-432-2.png" width="672" /></p>
</div>
<div id="rhythmic-functions" class="section level4">
<h4><span class="header-section-number">38.6.4.4</span> Rhythmic functions</h4>
<p>Rhythmic phenomena can be modeled using sine-wave function for given amplitudes <span class="math inline">\(\alpha\)</span>, wavelengths <span class="math inline">\(\lambda\)</span> and/or frequencies <span class="math inline">\(\frac{1}{\lambda}\)</span> and phase shifts <span class="math inline">\(\varphi\)</span>: <span class="math display">\[Y=\alpha sin\frac{2\pi}{\lambda}X+\varphi\]</span></p>
<p>Here’s a formula: <code>y=ylo+(yhi-ylo)*sin(2*(pi/lambda)*x)+phi</code></p>
<div class="sourceCode" id="cb829"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb829-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">60</span>)</a>
<a class="sourceLine" id="cb829-2" title="2"></a>
<a class="sourceLine" id="cb829-3" title="3">ylo &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb829-4" title="4">yhi &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb829-5" title="5">lambda &lt;-<span class="dv">20</span></a>
<a class="sourceLine" id="cb829-6" title="6">phi &lt;-<span class="st"> </span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb829-7" title="7"></a>
<a class="sourceLine" id="cb829-8" title="8">y &lt;-<span class="st"> </span>ylo<span class="op">+</span>(yhi<span class="op">-</span>ylo)<span class="op">*</span><span class="kw">sin</span>(<span class="dv">2</span><span class="op">*</span>(pi<span class="op">/</span>lambda)<span class="op">*</span>x)<span class="op">+</span>phi</a>
<a class="sourceLine" id="cb829-9" title="9"></a>
<a class="sourceLine" id="cb829-10" title="10"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x,y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb829-11" title="11"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-433-1.png" width="672" /></p>
</div>
<div id="polynomial-functions" class="section level4">
<h4><span class="header-section-number">38.6.4.5</span> Polynomial functions</h4>
<p>Virtually any nonlinear process can be modeled with outstanding fit using a high-order polynomial function. For example: <span class="math display">\[Y=\beta_0 + \beta_1X + \beta_2X^2 + \beta_3X^3 + \beta_4X^4 + \beta_5X^5 \]</span></p>
<p>Often, however, it is not clear exactly what are the physical parameters that correspond to those coefficients. Polynomials can give you incredibly good uninterpretable fits to data.</p>
<p>Nevertheless, here is the formula: <code>y=beta0+beta1*x+beta2*x^2+beta3*x^3+beta4*x^4+beta5*x^5</code></p>
<div class="sourceCode" id="cb830"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb830-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">60</span>)</a>
<a class="sourceLine" id="cb830-2" title="2"></a>
<a class="sourceLine" id="cb830-3" title="3">beta0 &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb830-4" title="4">beta1 &lt;-<span class="st"> </span><span class="dv">100</span></a>
<a class="sourceLine" id="cb830-5" title="5">beta2 &lt;-<span class="st"> </span><span class="fl">0.01</span></a>
<a class="sourceLine" id="cb830-6" title="6">beta3 &lt;-<span class="st"> </span><span class="fl">0.001</span></a>
<a class="sourceLine" id="cb830-7" title="7">beta4 &lt;-<span class="st"> </span><span class="fl">0.0001</span></a>
<a class="sourceLine" id="cb830-8" title="8">beta5 &lt;-<span class="st"> </span><span class="fl">-0.00001</span></a>
<a class="sourceLine" id="cb830-9" title="9"></a>
<a class="sourceLine" id="cb830-10" title="10">y &lt;-<span class="st"> </span>beta0<span class="op">+</span>beta1<span class="op">*</span>x<span class="op">+</span>beta2<span class="op">*</span>x<span class="op">^</span><span class="dv">2</span><span class="op">+</span>beta3<span class="op">*</span>x<span class="op">^</span><span class="dv">3</span><span class="op">+</span>beta4<span class="op">*</span>x<span class="op">^</span><span class="dv">4</span><span class="op">+</span>beta5<span class="op">*</span>x<span class="op">^</span><span class="dv">5</span></a>
<a class="sourceLine" id="cb830-11" title="11"></a>
<a class="sourceLine" id="cb830-12" title="12"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x, y), <span class="kw">aes</span>(x,y))<span class="op">+</span></a>
<a class="sourceLine" id="cb830-13" title="13"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-434-1.png" width="672" /></p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regress.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="nestedregress.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["jabstb.pdf", "jabstb.epub"],
"toc": {
"collapse": "subsection"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
