<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 27 One-way ANOVA Completely Randomized | JABSTB: Statistical Design and Analysis of Experiments with R</title>
  <meta name="description" content="Experimental biostatistics using R." />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 27 One-way ANOVA Completely Randomized | JABSTB: Statistical Design and Analysis of Experiments with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Experimental biostatistics using R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 27 One-way ANOVA Completely Randomized | JABSTB: Statistical Design and Analysis of Experiments with R" />
  
  <meta name="twitter:description" content="Experimental biostatistics using R." />
  

<meta name="author" content="TJ Murphy PhD, Department of Pharmacology and Chemical Biology, School of Medicine, Emory University, Atlanta, GA biostats538@gmail.com" />


<meta name="date" content="2020-01-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="fdistr.html"/>
<link rel="next" href="onewayRM.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">JABSTB</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i><b>1</b> About the author and book</a></li>
<li class="chapter" data-level="2" data-path="history.html"><a href="history.html"><i class="fa fa-check"></i><b>2</b> A Brief History of Experimental Design</a></li>
<li class="chapter" data-level="3" data-path="software.html"><a href="software.html"><i class="fa fa-check"></i><b>3</b> Installing and Understanding the software</a><ul>
<li class="chapter" data-level="3.1" data-path="software.html"><a href="software.html#spring-2020-term-versions"><i class="fa fa-check"></i><b>3.1</b> Spring 2020 term versions</a><ul>
<li class="chapter" data-level="3.1.1" data-path="software.html"><a href="software.html#what-are-these"><i class="fa fa-check"></i><b>3.1.1</b> What are these?</a></li>
<li class="chapter" data-level="3.1.2" data-path="software.html"><a href="software.html#rule-1-install-r-first-install-rstudio-second"><i class="fa fa-check"></i><b>3.1.2</b> Rule 1: Install R first, install RStudio second</a></li>
<li class="chapter" data-level="3.1.3" data-path="software.html"><a href="software.html#rule-2-dont-pay"><i class="fa fa-check"></i><b>3.1.3</b> Rule 2: Don’t pay!</a></li>
<li class="chapter" data-level="3.1.4" data-path="software.html"><a href="software.html#rule-3-dont-compile"><i class="fa fa-check"></i><b>3.1.4</b> Rule 3: Don’t compile!</a></li>
<li class="chapter" data-level="3.1.5" data-path="software.html"><a href="software.html#rule-4-install-the-right-software-for-your-machine"><i class="fa fa-check"></i><b>3.1.5</b> Rule 4: Install the right software for your machine</a></li>
<li class="chapter" data-level="3.1.6" data-path="software.html"><a href="software.html#rule-5-use-this-installation-guide"><i class="fa fa-check"></i><b>3.1.6</b> Rule 5: Use this installation guide</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="software.html"><a href="software.html#after-installation"><i class="fa fa-check"></i><b>3.2</b> After installation</a><ul>
<li class="chapter" data-level="3.2.1" data-path="software.html"><a href="software.html#what-is-r"><i class="fa fa-check"></i><b>3.2.1</b> What is R?</a></li>
<li class="chapter" data-level="3.2.2" data-path="software.html"><a href="software.html#r-packages"><i class="fa fa-check"></i><b>3.2.2</b> R packages</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="software.html"><a href="software.html#important-avoid-compiling"><i class="fa fa-check"></i><b>3.3</b> Important: Avoid compiling</a><ul>
<li class="chapter" data-level="3.3.1" data-path="software.html"><a href="software.html#reasons-not-to-compile"><i class="fa fa-check"></i><b>3.3.1</b> Reasons not to compile</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>4</b> Start Learning R</a><ul>
<li class="chapter" data-level="4.1" data-path="getting-started.html"><a href="getting-started.html#digging-in-with-rrstudio"><i class="fa fa-check"></i><b>4.1</b> Digging in with R/RStudio</a></li>
<li class="chapter" data-level="4.2" data-path="getting-started.html"><a href="getting-started.html#the-tidyverse-package"><i class="fa fa-check"></i><b>4.2</b> The tidyverse package</a><ul>
<li class="chapter" data-level="4.2.1" data-path="getting-started.html"><a href="getting-started.html#do-swirlstats"><i class="fa fa-check"></i><b>4.2.1</b> Do swirlstats</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="getting-started.html"><a href="getting-started.html#other-resources"><i class="fa fa-check"></i><b>4.3</b> Other resources</a><ul>
<li class="chapter" data-level="4.3.1" data-path="getting-started.html"><a href="getting-started.html#internet-search"><i class="fa fa-check"></i><b>4.3.1</b> Internet search</a></li>
<li class="chapter" data-level="4.3.2" data-path="getting-started.html"><a href="getting-started.html#help-documents"><i class="fa fa-check"></i><b>4.3.2</b> Help Documents</a></li>
<li class="chapter" data-level="4.3.3" data-path="getting-started.html"><a href="getting-started.html#package-vignettes"><i class="fa fa-check"></i><b>4.3.3</b> Package Vignettes</a></li>
<li class="chapter" data-level="4.3.4" data-path="getting-started.html"><a href="getting-started.html#people"><i class="fa fa-check"></i><b>4.3.4</b> People</a></li>
<li class="chapter" data-level="4.3.5" data-path="getting-started.html"><a href="getting-started.html#typos"><i class="fa fa-check"></i><b>4.3.5</b> typos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="philos.html"><a href="philos.html"><i class="fa fa-check"></i><b>5</b> What is your philosophy?</a><ul>
<li class="chapter" data-level="5.1" data-path="philos.html"><a href="philos.html#exploration-and-uncertainty"><i class="fa fa-check"></i><b>5.1</b> Exploration and uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bigpic.html"><a href="bigpic.html"><i class="fa fa-check"></i><b>6</b> Stats: The Big Picture</a><ul>
<li class="chapter" data-level="6.1" data-path="bigpic.html"><a href="bigpic.html#what-are-experimental-statistics"><i class="fa fa-check"></i><b>6.1</b> What are experimental statistics?</a><ul>
<li class="chapter" data-level="6.1.1" data-path="bigpic.html"><a href="bigpic.html#descriptive-modeling"><i class="fa fa-check"></i><b>6.1.1</b> Descriptive modeling</a></li>
<li class="chapter" data-level="6.1.2" data-path="bigpic.html"><a href="bigpic.html#statistical-inference"><i class="fa fa-check"></i><b>6.1.2</b> Statistical inference</a></li>
<li class="chapter" data-level="6.1.3" data-path="bigpic.html"><a href="bigpic.html#experimental-design"><i class="fa fa-check"></i><b>6.1.3</b> Experimental design</a></li>
<li class="chapter" data-level="6.1.4" data-path="bigpic.html"><a href="bigpic.html#statistics-as-an-anti-bias-framework"><i class="fa fa-check"></i><b>6.1.4</b> Statistics as an anti-bias framework</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>7</b> Statistical Sampling</a><ul>
<li class="chapter" data-level="7.1" data-path="sampling.html"><a href="sampling.html#experimental-units"><i class="fa fa-check"></i><b>7.1</b> Experimental units</a><ul>
<li class="chapter" data-level="7.1.1" data-path="sampling.html"><a href="sampling.html#a-simple-test-to-define-the-experimental-unit"><i class="fa fa-check"></i><b>7.1.1</b> A simple test to define the experimental unit</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="sampling.html"><a href="sampling.html#independent-replicates"><i class="fa fa-check"></i><b>7.2</b> Independent Replicates</a><ul>
<li class="chapter" data-level="7.2.1" data-path="sampling.html"><a href="sampling.html#a-simple-test-for-independence"><i class="fa fa-check"></i><b>7.2.1</b> A simple test for independence</a></li>
<li class="chapter" data-level="7.2.2" data-path="sampling.html"><a href="sampling.html#some-replication-examples"><i class="fa fa-check"></i><b>7.2.2</b> Some replication examples</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sampling.html"><a href="sampling.html#random-process"><i class="fa fa-check"></i><b>7.3</b> Random process</a></li>
<li class="chapter" data-level="7.4" data-path="sampling.html"><a href="sampling.html#statistically-valid-samples"><i class="fa fa-check"></i><b>7.4</b> Statistically valid samples</a><ul>
<li class="chapter" data-level="7.4.1" data-path="sampling.html"><a href="sampling.html#select-random-subjects"><i class="fa fa-check"></i><b>7.4.1</b> Select random subjects</a></li>
<li class="chapter" data-level="7.4.2" data-path="sampling.html"><a href="sampling.html#randomize-to-sequence"><i class="fa fa-check"></i><b>7.4.2</b> Randomize to sequence</a></li>
<li class="chapter" data-level="7.4.3" data-path="sampling.html"><a href="sampling.html#randomize-to-location"><i class="fa fa-check"></i><b>7.4.3</b> Randomize to location</a></li>
<li class="chapter" data-level="7.4.4" data-path="sampling.html"><a href="sampling.html#randomize-to-block"><i class="fa fa-check"></i><b>7.4.4</b> Randomize to block</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sampling.html"><a href="sampling.html#independence-of-replicates"><i class="fa fa-check"></i><b>7.5</b> Independence of replicates</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>8</b> Data Classification</a><ul>
<li class="chapter" data-level="8.1" data-path="data.html"><a href="data.html#dependent-and-independent-variables"><i class="fa fa-check"></i><b>8.1</b> Dependent and independent variables</a><ul>
<li class="chapter" data-level="8.1.1" data-path="data.html"><a href="data.html#when-there-is-no-independent-variable"><i class="fa fa-check"></i><b>8.1.1</b> When there is no independent variable</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="data.html"><a href="data.html#discrete-or-continuous-variables"><i class="fa fa-check"></i><b>8.2</b> Discrete or continuous variables</a><ul>
<li class="chapter" data-level="8.2.1" data-path="data.html"><a href="data.html#measured-variables"><i class="fa fa-check"></i><b>8.2.1</b> Measured variables</a></li>
<li class="chapter" data-level="8.2.2" data-path="data.html"><a href="data.html#discrete-categorical-and-ordinal-variables"><i class="fa fa-check"></i><b>8.2.2</b> Discrete categorical and ordinal variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="dispersion.html"><a href="dispersion.html"><i class="fa fa-check"></i><b>9</b> Variability, Accuracy and Precision</a><ul>
<li class="chapter" data-level="9.1" data-path="dispersion.html"><a href="dispersion.html#variance-quantifying-variation-by-least-squares"><i class="fa fa-check"></i><b>9.1</b> Variance: Quantifying variation by least squares</a></li>
<li class="chapter" data-level="9.2" data-path="dispersion.html"><a href="dispersion.html#standard-deviation"><i class="fa fa-check"></i><b>9.2</b> Standard deviation</a><ul>
<li class="chapter" data-level="9.2.1" data-path="dispersion.html"><a href="dispersion.html#what-does-the-standard-deviation-tell-us"><i class="fa fa-check"></i><b>9.2.1</b> What does the standard deviation tell us</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="dispersion.html"><a href="dispersion.html#other-ways-of-describing-variability"><i class="fa fa-check"></i><b>9.3</b> Other ways of describing variability</a></li>
<li class="chapter" data-level="9.4" data-path="dispersion.html"><a href="dispersion.html#precision-and-accuracy"><i class="fa fa-check"></i><b>9.4</b> Precision and Accuracy</a></li>
<li class="chapter" data-level="9.5" data-path="dispersion.html"><a href="dispersion.html#standard-error"><i class="fa fa-check"></i><b>9.5</b> Standard error</a><ul>
<li class="chapter" data-level="9.5.1" data-path="dispersion.html"><a href="dispersion.html#what-exactly-does-the-standard-error-represent"><i class="fa fa-check"></i><b>9.5.1</b> What exactly does the standard error represent?</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="dispersion.html"><a href="dispersion.html#confidence-intervals"><i class="fa fa-check"></i><b>9.6</b> Confidence intervals</a><ul>
<li class="chapter" data-level="9.6.1" data-path="dispersion.html"><a href="dispersion.html#simulations"><i class="fa fa-check"></i><b>9.6.1</b> Simulations</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="dispersion.html"><a href="dispersion.html#key-take-aways"><i class="fa fa-check"></i><b>9.7</b> Key take aways</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>10</b> Framing statistical hypotheses</a><ul>
<li class="chapter" data-level="10.1" data-path="hypotheses.html"><a href="hypotheses.html#the-decision-process"><i class="fa fa-check"></i><b>10.1</b> The decision process</a></li>
<li class="chapter" data-level="10.2" data-path="hypotheses.html"><a href="hypotheses.html#popper-and-falsification"><i class="fa fa-check"></i><b>10.2</b> Popper and falsification</a></li>
<li class="chapter" data-level="10.3" data-path="hypotheses.html"><a href="hypotheses.html#statistical-hypothesis-rubric"><i class="fa fa-check"></i><b>10.3</b> Statistical hypothesis rubric</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="error.html"><a href="error.html"><i class="fa fa-check"></i><b>11</b> Error</a><ul>
<li class="chapter" data-level="11.1" data-path="error.html"><a href="error.html#setting-type-1-and-type-2-error-thresholds"><i class="fa fa-check"></i><b>11.1</b> Setting type 1 and type 2 error thresholds</a><ul>
<li class="chapter" data-level="11.1.1" data-path="error.html"><a href="error.html#setting-alpha-the-type-1-error"><i class="fa fa-check"></i><b>11.1.1</b> Setting alpha-the type 1 error</a></li>
<li class="chapter" data-level="11.1.2" data-path="error.html"><a href="error.html#power-setting-beta-the-type-2-error"><i class="fa fa-check"></i><b>11.1.2</b> Power: Setting beta-the type 2 error</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="error.html"><a href="error.html#striking-the-right-balance"><i class="fa fa-check"></i><b>11.2</b> Striking the right balance</a></li>
<li class="chapter" data-level="11.3" data-path="error.html"><a href="error.html#false-discovery-rate"><i class="fa fa-check"></i><b>11.3</b> False discovery rate</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="pvalues.html"><a href="pvalues.html"><i class="fa fa-check"></i><b>12</b> P Values</a><ul>
<li class="chapter" data-level="12.1" data-path="pvalues.html"><a href="pvalues.html#definition"><i class="fa fa-check"></i><b>12.1</b> Definition</a></li>
<li class="chapter" data-level="12.2" data-path="pvalues.html"><a href="pvalues.html#test-statistics-come-from-null-distributions"><i class="fa fa-check"></i><b>12.2</b> Test statistics come from null distributions</a><ul>
<li class="chapter" data-level="12.2.1" data-path="pvalues.html"><a href="pvalues.html#p-value-behavior"><i class="fa fa-check"></i><b>12.2.1</b> P-value behavior</a></li>
<li class="chapter" data-level="12.2.2" data-path="pvalues.html"><a href="pvalues.html#p-values-and-the-decision-process"><i class="fa fa-check"></i><b>12.2.2</b> P-values and the decision process</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="pvalues.html"><a href="pvalues.html#a-blood-glucose-p-value"><i class="fa fa-check"></i><b>12.3</b> A blood glucose p-value</a></li>
<li class="chapter" data-level="12.4" data-path="pvalues.html"><a href="pvalues.html#how-p-values-should-be-interpreted"><i class="fa fa-check"></i><b>12.4</b> How p-values should be interpreted</a></li>
<li class="chapter" data-level="12.5" data-path="pvalues.html"><a href="pvalues.html#interpretation"><i class="fa fa-check"></i><b>12.5</b> Interpretation</a></li>
<li class="chapter" data-level="12.6" data-path="pvalues.html"><a href="pvalues.html#criticisms-of-p-values"><i class="fa fa-check"></i><b>12.6</b> Criticisms of p-values</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="jaxwest7.html"><a href="jaxwest7.html"><i class="fa fa-check"></i><b>13</b> Reproducible Data Munging in R</a><ul>
<li class="chapter" data-level="13.1" data-path="jaxwest7.html"><a href="jaxwest7.html#jaxwest7-glucose-data"><i class="fa fa-check"></i><b>13.1</b> Jaxwest7 glucose data</a><ul>
<li class="chapter" data-level="13.1.1" data-path="jaxwest7.html"><a href="jaxwest7.html#inspect-the-jaxwest7-data"><i class="fa fa-check"></i><b>13.1.1</b> Inspect the Jaxwest7 data</a></li>
<li class="chapter" data-level="13.1.2" data-path="jaxwest7.html"><a href="jaxwest7.html#munge-the-glucose-concentration-data-into-r"><i class="fa fa-check"></i><b>13.1.2</b> Munge the glucose concentration data into R</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="jaxwest7.html"><a href="jaxwest7.html#explore-the-jaxwest7-data"><i class="fa fa-check"></i><b>13.2</b> Explore the Jaxwest7 data</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="binomial.html"><a href="binomial.html"><i class="fa fa-check"></i><b>14</b> The Binomial Distribution</a><ul>
<li class="chapter" data-level="14.1" data-path="binomial.html"><a href="binomial.html#dbinom"><i class="fa fa-check"></i><b>14.1</b> dbinom</a></li>
<li class="chapter" data-level="14.2" data-path="binomial.html"><a href="binomial.html#pbinom"><i class="fa fa-check"></i><b>14.2</b> pbinom</a></li>
<li class="chapter" data-level="14.3" data-path="binomial.html"><a href="binomial.html#qbinom"><i class="fa fa-check"></i><b>14.3</b> qbinom</a></li>
<li class="chapter" data-level="14.4" data-path="binomial.html"><a href="binomial.html#rbinom"><i class="fa fa-check"></i><b>14.4</b> rbinom</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="poisson.html"><a href="poisson.html"><i class="fa fa-check"></i><b>15</b> The Poisson Distribution</a><ul>
<li class="chapter" data-level="15.1" data-path="poisson.html"><a href="poisson.html#poisson-events"><i class="fa fa-check"></i><b>15.1</b> Poisson Events</a></li>
<li class="chapter" data-level="15.2" data-path="poisson.html"><a href="poisson.html#dpois"><i class="fa fa-check"></i><b>15.2</b> dpois</a></li>
<li class="chapter" data-level="15.3" data-path="poisson.html"><a href="poisson.html#ppois"><i class="fa fa-check"></i><b>15.3</b> ppois</a></li>
<li class="chapter" data-level="15.4" data-path="poisson.html"><a href="poisson.html#rpois"><i class="fa fa-check"></i><b>15.4</b> rpois</a></li>
<li class="chapter" data-level="15.5" data-path="poisson.html"><a href="poisson.html#overdispersion"><i class="fa fa-check"></i><b>15.5</b> Overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="normal.html"><a href="normal.html"><i class="fa fa-check"></i><b>16</b> The Normal Distribution</a><ul>
<li class="chapter" data-level="16.0.1" data-path="normal.html"><a href="normal.html#the-standard-normal"><i class="fa fa-check"></i><b>16.0.1</b> The Standard Normal</a></li>
<li class="chapter" data-level="16.1" data-path="normal.html"><a href="normal.html#dnorm"><i class="fa fa-check"></i><b>16.1</b> dnorm</a></li>
<li class="chapter" data-level="16.2" data-path="normal.html"><a href="normal.html#pnorm"><i class="fa fa-check"></i><b>16.2</b> pnorm</a><ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#calculating-p-values-using-pnorm"><i class="fa fa-check"></i>Calculating “p-values”" using pnorm</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#calculating-percentiles-using-pnorm"><i class="fa fa-check"></i>Calculating percentiles using pnorm</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="normal.html"><a href="normal.html#qnorm"><i class="fa fa-check"></i><b>16.3</b> qnorm</a></li>
<li class="chapter" data-level="16.4" data-path="normal.html"><a href="normal.html#rnorm"><i class="fa fa-check"></i><b>16.4</b> rnorm</a><ul>
<li class="chapter" data-level="16.4.1" data-path="normal.html"><a href="normal.html#plotting-histograms-of-some-rnorm-samples"><i class="fa fa-check"></i><b>16.4.1</b> Plotting histograms of some rnorm samples</a></li>
<li class="chapter" data-level="16.4.2" data-path="normal.html"><a href="normal.html#bins-and-binwidth"><i class="fa fa-check"></i><b>16.4.2</b> Bins and Binwidth</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="categorical.html"><a href="categorical.html"><i class="fa fa-check"></i><b>17</b> Statistics for Categorical Data</a><ul>
<li class="chapter" data-level="17.1" data-path="categorical.html"><a href="categorical.html#types-of-categorical-data"><i class="fa fa-check"></i><b>17.1</b> Types of categorical data</a><ul>
<li class="chapter" data-level="17.1.1" data-path="categorical.html"><a href="categorical.html#proportions"><i class="fa fa-check"></i><b>17.1.1</b> Proportions</a></li>
<li class="chapter" data-level="17.1.2" data-path="categorical.html"><a href="categorical.html#frequencies"><i class="fa fa-check"></i><b>17.1.2</b> Frequencies</a></li>
<li class="chapter" data-level="17.1.3" data-path="categorical.html"><a href="categorical.html#associations"><i class="fa fa-check"></i><b>17.1.3</b> Associations</a></li>
<li class="chapter" data-level="17.1.4" data-path="categorical.html"><a href="categorical.html#statistics-covered-here"><i class="fa fa-check"></i><b>17.1.4</b> Statistics Covered Here</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="categorical.html"><a href="categorical.html#exact-v-asymptotic-calculations-of-p-values"><i class="fa fa-check"></i><b>17.2</b> Exact v Asymptotic Calculations of p-values</a><ul>
<li class="chapter" data-level="17.2.1" data-path="categorical.html"><a href="categorical.html#choosing-exact-or-asymptotic"><i class="fa fa-check"></i><b>17.2.1</b> Choosing exact or asymptotic</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="categorical.html"><a href="categorical.html#overview-of-the-types-of-hypothesis-testing"><i class="fa fa-check"></i><b>17.3</b> Overview of the types of hypothesis testing</a><ul>
<li class="chapter" data-level="17.3.1" data-path="categorical.html"><a href="categorical.html#proportion-analysis"><i class="fa fa-check"></i><b>17.3.1</b> Proportion analysis</a></li>
<li class="chapter" data-level="17.3.2" data-path="categorical.html"><a href="categorical.html#goodness-of-fit-testing"><i class="fa fa-check"></i><b>17.3.2</b> Goodness of fit testing</a></li>
<li class="chapter" data-level="17.3.3" data-path="categorical.html"><a href="categorical.html#contingency-analysis"><i class="fa fa-check"></i><b>17.3.3</b> Contingency Analysis</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="categorical.html"><a href="categorical.html#comparing-proportions"><i class="fa fa-check"></i><b>17.4</b> Comparing proportions</a><ul>
<li class="chapter" data-level="17.4.1" data-path="categorical.html"><a href="categorical.html#a-mouse-t-cell-pilot-experiment-the-cytokine-inducible-antigen-gradstudin"><i class="fa fa-check"></i><b>17.4.1</b> A Mouse T Cell Pilot Experiment: The Cytokine-inducible antigen gradstudin</a></li>
<li class="chapter" data-level="17.4.2" data-path="categorical.html"><a href="categorical.html#calculating-proportions"><i class="fa fa-check"></i><b>17.4.2</b> Calculating Proportions</a></li>
<li class="chapter" data-level="17.4.3" data-path="categorical.html"><a href="categorical.html#what-a-proportion-estimates"><i class="fa fa-check"></i><b>17.4.3</b> What A Proportion Estimates</a></li>
<li class="chapter" data-level="17.4.4" data-path="categorical.html"><a href="categorical.html#confidence-intervals-of-proportions"><i class="fa fa-check"></i><b>17.4.4</b> Confidence Intervals of Proportions</a></li>
<li class="chapter" data-level="17.4.5" data-path="categorical.html"><a href="categorical.html#a-one-sample-proportion-test"><i class="fa fa-check"></i><b>17.4.5</b> A One-Sample Proportion Test</a></li>
<li class="chapter" data-level="17.4.6" data-path="categorical.html"><a href="categorical.html#comparing-two-proportions"><i class="fa fa-check"></i><b>17.4.6</b> Comparing Two Proportions</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="categorical.html"><a href="categorical.html#exact-tests-for-two-proportions"><i class="fa fa-check"></i><b>17.5</b> Exact tests for two proportions</a></li>
<li class="chapter" data-level="17.6" data-path="categorical.html"><a href="categorical.html#goodness-of-fit-tests"><i class="fa fa-check"></i><b>17.6</b> Goodness of fit Tests</a><ul>
<li class="chapter" data-level="17.6.1" data-path="categorical.html"><a href="categorical.html#an-exact-goodness-of-fit-test"><i class="fa fa-check"></i><b>17.6.1</b> An Exact Goodness of Fit test</a></li>
<li class="chapter" data-level="17.6.2" data-path="categorical.html"><a href="categorical.html#an-approximate-goodness-of-fit-test"><i class="fa fa-check"></i><b>17.6.2</b> An Approximate Goodness of Fit test</a></li>
</ul></li>
<li class="chapter" data-level="17.7" data-path="categorical.html"><a href="categorical.html#contingency-testing"><i class="fa fa-check"></i><b>17.7</b> Contingency Testing</a><ul>
<li class="chapter" data-level="17.7.1" data-path="categorical.html"><a href="categorical.html#intepretation-of-contingency-results"><i class="fa fa-check"></i><b>17.7.1</b> Intepretation of Contingency Results</a></li>
<li class="chapter" data-level="17.7.2" data-path="categorical.html"><a href="categorical.html#write-up-3"><i class="fa fa-check"></i><b>17.7.2</b> Write Up</a></li>
<li class="chapter" data-level="17.7.3" data-path="categorical.html"><a href="categorical.html#interpretation-of-chi-square-output"><i class="fa fa-check"></i><b>17.7.3</b> Interpretation of chi-square output</a></li>
<li class="chapter" data-level="17.7.4" data-path="categorical.html"><a href="categorical.html#write-up-4"><i class="fa fa-check"></i><b>17.7.4</b> Write Up</a></li>
<li class="chapter" data-level="17.7.5" data-path="categorical.html"><a href="categorical.html#which-contingency-test-is-best"><i class="fa fa-check"></i><b>17.7.5</b> Which contingency test is best?</a></li>
<li class="chapter" data-level="17.7.6" data-path="categorical.html"><a href="categorical.html#higher-dimension-contingency-analysis"><i class="fa fa-check"></i><b>17.7.6</b> Higher dimension contingency analysis</a></li>
<li class="chapter" data-level="17.7.7" data-path="categorical.html"><a href="categorical.html#other-experimental-designs-involving-categorical-data"><i class="fa fa-check"></i><b>17.7.7</b> Other experimental designs involving categorical data</a></li>
</ul></li>
<li class="chapter" data-level="17.8" data-path="categorical.html"><a href="categorical.html#doing-a-priori-power-analysis-for-proportion-tests"><i class="fa fa-check"></i><b>17.8</b> Doing <em>a priori</em> power analysis for proportion tests</a></li>
<li class="chapter" data-level="17.9" data-path="categorical.html"><a href="categorical.html#power-analysis-functions-for-proportion-tests"><i class="fa fa-check"></i><b>17.9</b> Power analysis functions for proportion tests</a></li>
<li class="chapter" data-level="17.10" data-path="categorical.html"><a href="categorical.html#graphing-proportions"><i class="fa fa-check"></i><b>17.10</b> Graphing Proportions</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chisquare.html"><a href="chisquare.html"><i class="fa fa-check"></i><b>18</b> The Chi-square Distribution</a><ul>
<li class="chapter" data-level="18.1" data-path="chisquare.html"><a href="chisquare.html#background"><i class="fa fa-check"></i><b>18.1</b> Background</a></li>
<li class="chapter" data-level="18.2" data-path="chisquare.html"><a href="chisquare.html#dchisq"><i class="fa fa-check"></i><b>18.2</b> dchisq</a></li>
<li class="chapter" data-level="18.3" data-path="chisquare.html"><a href="chisquare.html#pchisq"><i class="fa fa-check"></i><b>18.3</b> pchisq</a><ul>
<li class="chapter" data-level="18.3.1" data-path="chisquare.html"><a href="chisquare.html#calculating-p-values-from-pchisq"><i class="fa fa-check"></i><b>18.3.1</b> Calculating p-values from pchisq</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="chisquare.html"><a href="chisquare.html#qchisq"><i class="fa fa-check"></i><b>18.4</b> qchisq</a></li>
<li class="chapter" data-level="18.5" data-path="chisquare.html"><a href="chisquare.html#rchisq"><i class="fa fa-check"></i><b>18.5</b> rchisq</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="nonparametrics.html"><a href="nonparametrics.html"><i class="fa fa-check"></i><b>19</b> Nonparametric Statistical Tests</a><ul>
<li class="chapter" data-level="19.1" data-path="nonparametrics.html"><a href="nonparametrics.html#experiments-involving-discrete-data"><i class="fa fa-check"></i><b>19.1</b> Experiments involving discrete data</a></li>
<li class="chapter" data-level="19.2" data-path="nonparametrics.html"><a href="nonparametrics.html#deviant-data"><i class="fa fa-check"></i><b>19.2</b> Deviant Data</a></li>
<li class="chapter" data-level="19.3" data-path="nonparametrics.html"><a href="nonparametrics.html#sign-test"><i class="fa fa-check"></i><b>19.3</b> Sign Test</a><ul>
<li class="chapter" data-level="19.3.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-1"><i class="fa fa-check"></i><b>19.3.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.3.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-5"><i class="fa fa-check"></i><b>19.3.2</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-test-for-one-group"><i class="fa fa-check"></i><b>19.4</b> Wilcoxon Sign Rank Test for One Group</a><ul>
<li class="chapter" data-level="19.4.1" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-experimental-designs"><i class="fa fa-check"></i><b>19.4.1</b> Wilcoxon Sign Rank Experimental Designs</a></li>
<li class="chapter" data-level="19.4.2" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-2"><i class="fa fa-check"></i><b>19.4.2</b> Interpretation</a></li>
<li class="chapter" data-level="19.4.3" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-6"><i class="fa fa-check"></i><b>19.4.3</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-mann-whitney-rank-sum-test-for-2-independent-groups"><i class="fa fa-check"></i><b>19.5</b> Wilcoxon Mann Whitney Rank Sum Test for 2 independent groups</a><ul>
<li class="chapter" data-level="19.5.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-3"><i class="fa fa-check"></i><b>19.5.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.5.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-7"><i class="fa fa-check"></i><b>19.5.2</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-test-for-paired-groups"><i class="fa fa-check"></i><b>19.6</b> Wilcoxon Sign Rank Test for paired groups</a><ul>
<li class="chapter" data-level="19.6.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-4"><i class="fa fa-check"></i><b>19.6.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.6.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-8"><i class="fa fa-check"></i><b>19.6.2</b> Write up</a></li>
</ul></li>
<li class="chapter" data-level="19.7" data-path="nonparametrics.html"><a href="nonparametrics.html#kruskal-wallis"><i class="fa fa-check"></i><b>19.7</b> Kruskal-Wallis</a><ul>
<li class="chapter" data-level="19.7.1" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-9"><i class="fa fa-check"></i><b>19.7.1</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.8" data-path="nonparametrics.html"><a href="nonparametrics.html#friedman-test"><i class="fa fa-check"></i><b>19.8</b> Friedman test</a></li>
<li class="chapter" data-level="19.9" data-path="nonparametrics.html"><a href="nonparametrics.html#nonparametric-power-calculations"><i class="fa fa-check"></i><b>19.9</b> Nonparametric power calculations</a><ul>
<li class="chapter" data-level="19.9.1" data-path="nonparametrics.html"><a href="nonparametrics.html#how-it-works"><i class="fa fa-check"></i><b>19.9.1</b> How it works</a></li>
<li class="chapter" data-level="19.9.2" data-path="nonparametrics.html"><a href="nonparametrics.html#initialization-with-population-parameters"><i class="fa fa-check"></i><b>19.9.2</b> Initialization with population parameters</a></li>
<li class="chapter" data-level="19.9.3" data-path="nonparametrics.html"><a href="nonparametrics.html#an-example"><i class="fa fa-check"></i><b>19.9.3</b> An example</a></li>
<li class="chapter" data-level="19.9.4" data-path="nonparametrics.html"><a href="nonparametrics.html#nonpara.pwr"><i class="fa fa-check"></i><b>19.9.4</b> nonpara.pwr</a></li>
</ul></li>
<li class="chapter" data-level="19.10" data-path="nonparametrics.html"><a href="nonparametrics.html#summary"><i class="fa fa-check"></i><b>19.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="signrank.html"><a href="signrank.html"><i class="fa fa-check"></i><b>20</b> Signed Rank Distribution</a><ul>
<li class="chapter" data-level="20.1" data-path="signrank.html"><a href="signrank.html#transformation-of-data-into-sign-ranks"><i class="fa fa-check"></i><b>20.1</b> Transformation of data into sign ranks</a><ul>
<li class="chapter" data-level="20.1.1" data-path="signrank.html"><a href="signrank.html#for-a-one-group-sample"><i class="fa fa-check"></i><b>20.1.1</b> For a one group sample</a></li>
<li class="chapter" data-level="20.1.2" data-path="signrank.html"><a href="signrank.html#for-a-paired-sample"><i class="fa fa-check"></i><b>20.1.2</b> For a paired sample</a></li>
<li class="chapter" data-level="20.1.3" data-path="signrank.html"><a href="signrank.html#the-sign-rank-test-statistic-in-r"><i class="fa fa-check"></i><b>20.1.3</b> The sign rank test statistic in R</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="signrank.html"><a href="signrank.html#rs-four-sign-rank-distribution-functions"><i class="fa fa-check"></i><b>20.2</b> R’s Four Sign Rank Distribution Functions</a><ul>
<li class="chapter" data-level="20.2.1" data-path="signrank.html"><a href="signrank.html#dsignrank"><i class="fa fa-check"></i><b>20.2.1</b> dsignrank</a></li>
<li class="chapter" data-level="20.2.2" data-path="signrank.html"><a href="signrank.html#psignrank"><i class="fa fa-check"></i><b>20.2.2</b> psignrank</a></li>
<li class="chapter" data-level="20.2.3" data-path="signrank.html"><a href="signrank.html#qsignrank"><i class="fa fa-check"></i><b>20.2.3</b> qsignrank</a></li>
<li class="chapter" data-level="20.2.4" data-path="signrank.html"><a href="signrank.html#rsignrank"><i class="fa fa-check"></i><b>20.2.4</b> rsignrank</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="ranksum.html"><a href="ranksum.html"><i class="fa fa-check"></i><b>21</b> Rank Sum Distribution</a><ul>
<li class="chapter" data-level="21.0.1" data-path="ranksum.html"><a href="ranksum.html#transformation-of-data-into-rank-summs"><i class="fa fa-check"></i><b>21.0.1</b> Transformation of data into rank summs</a></li>
<li class="chapter" data-level="21.0.2" data-path="ranksum.html"><a href="ranksum.html#the-sign-rank-test-statistic-in-r-1"><i class="fa fa-check"></i><b>21.0.2</b> The sign rank test statistic in R</a></li>
<li class="chapter" data-level="21.1" data-path="ranksum.html"><a href="ranksum.html#rs-four-sign-rank-distribution-functions-1"><i class="fa fa-check"></i><b>21.1</b> R’s Four Sign Rank Distribution Functions</a><ul>
<li class="chapter" data-level="21.1.1" data-path="ranksum.html"><a href="ranksum.html#dwilcox"><i class="fa fa-check"></i><b>21.1.1</b> dwilcox</a></li>
<li class="chapter" data-level="21.1.2" data-path="ranksum.html"><a href="ranksum.html#pwilcox"><i class="fa fa-check"></i><b>21.1.2</b> pwilcox</a></li>
<li class="chapter" data-level="21.1.3" data-path="ranksum.html"><a href="ranksum.html#qwilcox"><i class="fa fa-check"></i><b>21.1.3</b> qwilcox</a></li>
<li class="chapter" data-level="21.1.4" data-path="ranksum.html"><a href="ranksum.html#rwilcox"><i class="fa fa-check"></i><b>21.1.4</b> rwilcox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="ttests.html"><a href="ttests.html"><i class="fa fa-check"></i><b>22</b> The t-tests</a><ul>
<li class="chapter" data-level="22.1" data-path="ttests.html"><a href="ttests.html#data-assumptions-for-t-tests"><i class="fa fa-check"></i><b>22.1</b> Data assumptions for t-tests</a></li>
<li class="chapter" data-level="22.2" data-path="ttests.html"><a href="ttests.html#the-t-statistic"><i class="fa fa-check"></i><b>22.2</b> The t Statistic</a><ul>
<li class="chapter" data-level="22.2.1" data-path="ttests.html"><a href="ttests.html#one-sample-t-tests"><i class="fa fa-check"></i><b>22.2.1</b> One sample t tests</a></li>
<li class="chapter" data-level="22.2.2" data-path="ttests.html"><a href="ttests.html#unpaired-t-tests"><i class="fa fa-check"></i><b>22.2.2</b> Unpaired t tests</a></li>
<li class="chapter" data-level="22.2.3" data-path="ttests.html"><a href="ttests.html#paired-t-tests"><i class="fa fa-check"></i><b>22.2.3</b> Paired t tests</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="ttests.html"><a href="ttests.html#t-test-hypotheses"><i class="fa fa-check"></i><b>22.3</b> t Test Hypotheses</a><ul>
<li class="chapter" data-level="22.3.1" data-path="ttests.html"><a href="ttests.html#one-sample-hypotheses"><i class="fa fa-check"></i><b>22.3.1</b> One sample hypotheses</a></li>
<li class="chapter" data-level="22.3.2" data-path="ttests.html"><a href="ttests.html#unpaired-hypotheses"><i class="fa fa-check"></i><b>22.3.2</b> Unpaired hypotheses</a></li>
<li class="chapter" data-level="22.3.3" data-path="ttests.html"><a href="ttests.html#paired-hypotheses"><i class="fa fa-check"></i><b>22.3.3</b> Paired hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="ttests.html"><a href="ttests.html#confidence-intervals-of-means"><i class="fa fa-check"></i><b>22.4</b> Confidence Intervals of Means</a></li>
<li class="chapter" data-level="22.5" data-path="ttests.html"><a href="ttests.html#t-tests-running-the-analysis"><i class="fa fa-check"></i><b>22.5</b> t Tests: Running the analysis</a><ul>
<li class="chapter" data-level="22.5.1" data-path="ttests.html"><a href="ttests.html#one-sample-t-test"><i class="fa fa-check"></i><b>22.5.1</b> One sample t test</a></li>
<li class="chapter" data-level="22.5.2" data-path="ttests.html"><a href="ttests.html#unpaired-t-test"><i class="fa fa-check"></i><b>22.5.2</b> Unpaired t test</a></li>
<li class="chapter" data-level="22.5.3" data-path="ttests.html"><a href="ttests.html#paired-t-test"><i class="fa fa-check"></i><b>22.5.3</b> Paired t Test</a></li>
</ul></li>
<li class="chapter" data-level="22.6" data-path="ttests.html"><a href="ttests.html#plotting-t-tests"><i class="fa fa-check"></i><b>22.6</b> Plotting t Tests</a><ul>
<li class="chapter" data-level="22.6.1" data-path="ttests.html"><a href="ttests.html#unpaired"><i class="fa fa-check"></i><b>22.6.1</b> Unpaired</a></li>
<li class="chapter" data-level="22.6.2" data-path="ttests.html"><a href="ttests.html#paired"><i class="fa fa-check"></i><b>22.6.2</b> Paired</a></li>
</ul></li>
<li class="chapter" data-level="22.7" data-path="ttests.html"><a href="ttests.html#t-test-power"><i class="fa fa-check"></i><b>22.7</b> t Test Power</a><ul>
<li class="chapter" data-level="22.7.1" data-path="ttests.html"><a href="ttests.html#interpretation-7"><i class="fa fa-check"></i><b>22.7.1</b> Interpretation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="ttestmc.html"><a href="ttestmc.html"><i class="fa fa-check"></i><b>23</b> Statistical design of t-tests</a><ul>
<li class="chapter" data-level="23.1" data-path="ttestmc.html"><a href="ttestmc.html#about-this-chapter"><i class="fa fa-check"></i><b>23.1</b> About this chapter</a><ul>
<li class="chapter" data-level="23.1.1" data-path="ttestmc.html"><a href="ttestmc.html#overview"><i class="fa fa-check"></i><b>23.1.1</b> Overview</a></li>
<li class="chapter" data-level="23.1.2" data-path="ttestmc.html"><a href="ttestmc.html#simulating-data"><i class="fa fa-check"></i><b>23.1.2</b> Simulating data</a></li>
<li class="chapter" data-level="23.1.3" data-path="ttestmc.html"><a href="ttestmc.html#change-n-to-zero-in-on-the-power-you-want"><i class="fa fa-check"></i><b>23.1.3</b> Change n to zero in on the power you want</a></li>
<li class="chapter" data-level="23.1.4" data-path="ttestmc.html"><a href="ttestmc.html#scenario"><i class="fa fa-check"></i><b>23.1.4</b> Scenario</a></li>
<li class="chapter" data-level="23.1.5" data-path="ttestmc.html"><a href="ttestmc.html#what-would-be-a-scientifically-meaningful-response"><i class="fa fa-check"></i><b>23.1.5</b> What would be a scientifically meaningful response?</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="ttestmc.html"><a href="ttestmc.html#one-sample-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.2</b> One sample t-test Monte Carlo</a></li>
<li class="chapter" data-level="23.3" data-path="ttestmc.html"><a href="ttestmc.html#unpaired-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.3</b> Unpaired t-test Monte Carlo</a></li>
<li class="chapter" data-level="23.4" data-path="ttestmc.html"><a href="ttestmc.html#paired-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.4</b> Paired t-test Monte Carlo</a></li>
<li class="chapter" data-level="23.5" data-path="ttestmc.html"><a href="ttestmc.html#dt"><i class="fa fa-check"></i><b>23.5</b> dt</a></li>
<li class="chapter" data-level="23.6" data-path="ttestmc.html"><a href="ttestmc.html#pt"><i class="fa fa-check"></i><b>23.6</b> pt</a></li>
<li class="chapter" data-level="23.7" data-path="ttestmc.html"><a href="ttestmc.html#qt"><i class="fa fa-check"></i><b>23.7</b> qt</a></li>
<li class="chapter" data-level="23.8" data-path="ttestmc.html"><a href="ttestmc.html#rt"><i class="fa fa-check"></i><b>23.8</b> rt</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="simcorrelation.html"><a href="simcorrelation.html"><i class="fa fa-check"></i><b>24</b> Simulating correlated variables</a><ul>
<li class="chapter" data-level="24.1" data-path="simcorrelation.html"><a href="simcorrelation.html#estimating-correlation-between-two-variables"><i class="fa fa-check"></i><b>24.1</b> Estimating correlation between two variables</a></li>
<li class="chapter" data-level="24.2" data-path="simcorrelation.html"><a href="simcorrelation.html#simulating-correlated-variables"><i class="fa fa-check"></i><b>24.2</b> Simulating correlated variables</a></li>
<li class="chapter" data-level="24.3" data-path="simcorrelation.html"><a href="simcorrelation.html#monte-carlo-simulation"><i class="fa fa-check"></i><b>24.3</b> Monte Carlo simulation</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="introanova.html"><a href="introanova.html"><i class="fa fa-check"></i><b>25</b> Introduction to ANOVA</a><ul>
<li class="chapter" data-level="25.1" data-path="introanova.html"><a href="introanova.html#factors-and-levels"><i class="fa fa-check"></i><b>25.1</b> Factors and levels</a></li>
<li class="chapter" data-level="25.2" data-path="introanova.html"><a href="introanova.html#anova-models-one--two--and-three-way"><i class="fa fa-check"></i><b>25.2</b> ANOVA models: One-, Two-, and Three-way</a></li>
<li class="chapter" data-level="25.3" data-path="introanova.html"><a href="introanova.html#anova-inference-protocol"><i class="fa fa-check"></i><b>25.3</b> ANOVA inference protocol</a></li>
<li class="chapter" data-level="25.4" data-path="introanova.html"><a href="introanova.html#anova-calculations"><i class="fa fa-check"></i><b>25.4</b> ANOVA calculations</a><ul>
<li class="chapter" data-level="25.4.1" data-path="introanova.html"><a href="introanova.html#sums-of-squares-partitioning"><i class="fa fa-check"></i><b>25.4.1</b> Sums of Squares partitioning</a></li>
<li class="chapter" data-level="25.4.2" data-path="introanova.html"><a href="introanova.html#degrees-of-freedom"><i class="fa fa-check"></i><b>25.4.2</b> Degrees of freedom</a></li>
<li class="chapter" data-level="25.4.3" data-path="introanova.html"><a href="introanova.html#the-mean-squares"><i class="fa fa-check"></i><b>25.4.3</b> The mean squares</a></li>
<li class="chapter" data-level="25.4.4" data-path="introanova.html"><a href="introanova.html#the-anova-table"><i class="fa fa-check"></i><b>25.4.4</b> The ANOVA table</a></li>
<li class="chapter" data-level="25.4.5" data-path="introanova.html"><a href="introanova.html#the-f-test"><i class="fa fa-check"></i><b>25.4.5</b> The F-test</a></li>
<li class="chapter" data-level="25.4.6" data-path="introanova.html"><a href="introanova.html#post-hoc-group-comparisons"><i class="fa fa-check"></i><b>25.4.6</b> Post-hoc group comparisons</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="introanova.html"><a href="introanova.html#completely-randomized-or-related-measures"><i class="fa fa-check"></i><b>25.5</b> Completely randomized or related measures</a><ul>
<li class="chapter" data-level="25.5.1" data-path="introanova.html"><a href="introanova.html#the-problem-of-lost-data-in-related-measures-designs"><i class="fa fa-check"></i><b>25.5.1</b> The problem of lost data in related measures designs</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="introanova.html"><a href="introanova.html#two-way-anova"><i class="fa fa-check"></i><b>25.6</b> Two-way ANOVA</a></li>
<li class="chapter" data-level="25.7" data-path="introanova.html"><a href="introanova.html#other-anova-models"><i class="fa fa-check"></i><b>25.7</b> Other ANOVA models</a><ul>
<li class="chapter" data-level="25.7.1" data-path="introanova.html"><a href="introanova.html#r-and-anova"><i class="fa fa-check"></i><b>25.7.1</b> R and ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="25.8" data-path="introanova.html"><a href="introanova.html#alternatives-to-anova"><i class="fa fa-check"></i><b>25.8</b> Alternatives to ANOVA</a><ul>
<li class="chapter" data-level="25.8.1" data-path="introanova.html"><a href="introanova.html#screw-anova-just-tell-me-how-to-t-test-everything"><i class="fa fa-check"></i><b>25.8.1</b> Screw ANOVA, Just Tell Me How to t-Test Everything</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="fdistr.html"><a href="fdistr.html"><i class="fa fa-check"></i><b>26</b> The F distribution</a><ul>
<li class="chapter" data-level="26.1" data-path="fdistr.html"><a href="fdistr.html#background-1"><i class="fa fa-check"></i><b>26.1</b> Background</a><ul>
<li class="chapter" data-level="26.1.1" data-path="fdistr.html"><a href="fdistr.html#sample-variance-and-fs-pdf"><i class="fa fa-check"></i><b>26.1.1</b> Sample Variance and F’s PDF</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="fdistr.html"><a href="fdistr.html#df"><i class="fa fa-check"></i><b>26.2</b> df</a></li>
<li class="chapter" data-level="26.3" data-path="fdistr.html"><a href="fdistr.html#pf"><i class="fa fa-check"></i><b>26.3</b> pf</a></li>
<li class="chapter" data-level="26.4" data-path="fdistr.html"><a href="fdistr.html#qf"><i class="fa fa-check"></i><b>26.4</b> qf</a></li>
<li class="chapter" data-level="26.5" data-path="fdistr.html"><a href="fdistr.html#rf"><i class="fa fa-check"></i><b>26.5</b> rf</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="onewayanova.html"><a href="onewayanova.html"><i class="fa fa-check"></i><b>27</b> One-way ANOVA Completely Randomized</a><ul>
<li class="chapter" data-level="27.1" data-path="onewayanova.html"><a href="onewayanova.html#using-ezanova"><i class="fa fa-check"></i><b>27.1</b> Using <code>ezANOVA</code></a></li>
<li class="chapter" data-level="27.2" data-path="onewayanova.html"><a href="onewayanova.html#the-chickwt-data-set"><i class="fa fa-check"></i><b>27.2</b> The chickwt data set</a><ul>
<li class="chapter" data-level="27.2.1" data-path="onewayanova.html"><a href="onewayanova.html#inspect-the-data"><i class="fa fa-check"></i><b>27.2.1</b> Inspect the data</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="onewayanova.html"><a href="onewayanova.html#run-the-anova"><i class="fa fa-check"></i><b>27.3</b> Run the ANOVA</a><ul>
<li class="chapter" data-level="27.3.1" data-path="onewayanova.html"><a href="onewayanova.html#run-the-chickwts-one-way-anova"><i class="fa fa-check"></i><b>27.3.1</b> Run the chickwts One Way ANOVA</a></li>
<li class="chapter" data-level="27.3.2" data-path="onewayanova.html"><a href="onewayanova.html#interpreting-the-one-way-cr-anova-output"><i class="fa fa-check"></i><b>27.3.2</b> Interpreting the One-Way CR ANOVA Output</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="onewayanova.html"><a href="onewayanova.html#posthoc"><i class="fa fa-check"></i><b>27.4</b> Post hoc pairwise comparisons</a><ul>
<li class="chapter" data-level="27.4.1" data-path="onewayanova.html"><a href="onewayanova.html#overview-of-options"><i class="fa fa-check"></i><b>27.4.1</b> Overview of options</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="onewayanova.html"><a href="onewayanova.html#reporting-the-result"><i class="fa fa-check"></i><b>27.5</b> Reporting the result</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="onewayRM.html"><a href="onewayRM.html"><i class="fa fa-check"></i><b>28</b> One-way ANOVA Related Measures</a><ul>
<li class="chapter" data-level="28.1" data-path="onewayRM.html"><a href="onewayRM.html#data-prep"><i class="fa fa-check"></i><b>28.1</b> Data prep</a></li>
<li class="chapter" data-level="28.2" data-path="onewayRM.html"><a href="onewayRM.html#run-the-anova-1"><i class="fa fa-check"></i><b>28.2</b> Run the ANOVA</a></li>
<li class="chapter" data-level="28.3" data-path="onewayRM.html"><a href="onewayRM.html#interpretation-8"><i class="fa fa-check"></i><b>28.3</b> Interpretation</a></li>
<li class="chapter" data-level="28.4" data-path="onewayRM.html"><a href="onewayRM.html#post-hoc-analysis"><i class="fa fa-check"></i><b>28.4</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="28.5" data-path="onewayRM.html"><a href="onewayRM.html#write-up-10"><i class="fa fa-check"></i><b>28.5</b> Write up</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="twowayCR.html"><a href="twowayCR.html"><i class="fa fa-check"></i><b>29</b> Two-way ANOVA Completely Randomized</a><ul>
<li class="chapter" data-level="29.1" data-path="twowayCR.html"><a href="twowayCR.html#effect-of-strain-and-diet-on-liver"><i class="fa fa-check"></i><b>29.1</b> Effect of Strain and Diet on Liver</a></li>
<li class="chapter" data-level="29.2" data-path="twowayCR.html"><a href="twowayCR.html#the-test"><i class="fa fa-check"></i><b>29.2</b> The test</a></li>
<li class="chapter" data-level="29.3" data-path="twowayCR.html"><a href="twowayCR.html#interpretation-of-2-way-cr-anova-output"><i class="fa fa-check"></i><b>29.3</b> Interpretation of 2 Way CR ANOVA Output</a><ul>
<li class="chapter" data-level="29.3.1" data-path="twowayCR.html"><a href="twowayCR.html#levenes"><i class="fa fa-check"></i><b>29.3.1</b> Levene’s</a></li>
<li class="chapter" data-level="29.3.2" data-path="twowayCR.html"><a href="twowayCR.html#anova-table"><i class="fa fa-check"></i><b>29.3.2</b> ANOVA Table</a></li>
</ul></li>
<li class="chapter" data-level="29.4" data-path="twowayCR.html"><a href="twowayCR.html#post-hoc-multiple-comparisons"><i class="fa fa-check"></i><b>29.4</b> Post Hoc Multiple Comparisons</a><ul>
<li class="chapter" data-level="29.4.1" data-path="twowayCR.html"><a href="twowayCR.html#write-up-11"><i class="fa fa-check"></i><b>29.4.1</b> Write Up</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="30" data-path="twowayRM.html"><a href="twowayRM.html"><i class="fa fa-check"></i><b>30</b> Two-way ANOVA Related Measures</a><ul>
<li class="chapter" data-level="30.1" data-path="twowayRM.html"><a href="twowayRM.html#cell-culture"><i class="fa fa-check"></i><b>30.1</b> Cell culture</a></li>
<li class="chapter" data-level="30.2" data-path="twowayRM.html"><a href="twowayRM.html#the-test-1"><i class="fa fa-check"></i><b>30.2</b> The test</a></li>
<li class="chapter" data-level="30.3" data-path="twowayRM.html"><a href="twowayRM.html#interpretation-of-the-output"><i class="fa fa-check"></i><b>30.3</b> Interpretation of the output</a><ul>
<li class="chapter" data-level="30.3.1" data-path="twowayRM.html"><a href="twowayRM.html#anova-table-1"><i class="fa fa-check"></i><b>30.3.1</b> ANOVA Table</a></li>
<li class="chapter" data-level="30.3.2" data-path="twowayRM.html"><a href="twowayRM.html#mauchlys-sphericity-test"><i class="fa fa-check"></i><b>30.3.2</b> Mauchly’s Sphericity Test</a></li>
</ul></li>
<li class="chapter" data-level="30.4" data-path="twowayRM.html"><a href="twowayRM.html#post-hoc-multiple-comparisons-1"><i class="fa fa-check"></i><b>30.4</b> Post Hoc multiple comparisons</a></li>
<li class="chapter" data-level="30.5" data-path="twowayRM.html"><a href="twowayRM.html#write-up-12"><i class="fa fa-check"></i><b>30.5</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="twowaymixed.html"><a href="twowaymixed.html"><i class="fa fa-check"></i><b>31</b> Two-way ANOVA RM/CR</a><ul>
<li class="chapter" data-level="31.1" data-path="twowaymixed.html"><a href="twowaymixed.html#chickweight-dataset"><i class="fa fa-check"></i><b>31.1</b> ChickWeight Dataset</a></li>
<li class="chapter" data-level="31.2" data-path="twowaymixed.html"><a href="twowaymixed.html#munge-chickweight-data"><i class="fa fa-check"></i><b>31.2</b> Munge ChickWeight data</a></li>
<li class="chapter" data-level="31.3" data-path="twowaymixed.html"><a href="twowaymixed.html#the-test-2"><i class="fa fa-check"></i><b>31.3</b> The test</a></li>
<li class="chapter" data-level="31.4" data-path="twowaymixed.html"><a href="twowaymixed.html#interpreting-the-anova-output"><i class="fa fa-check"></i><b>31.4</b> Interpreting the ANOVA output</a><ul>
<li class="chapter" data-level="31.4.1" data-path="twowaymixed.html"><a href="twowaymixed.html#anova-the-anova-table-1"><i class="fa fa-check"></i><b>31.4.1</b> $ANOVA: The ANOVA table</a></li>
<li class="chapter" data-level="31.4.2" data-path="twowaymixed.html"><a href="twowaymixed.html#mauchlys-test-and-corrections"><i class="fa fa-check"></i><b>31.4.2</b> Mauchly’s Test and Corrections</a></li>
</ul></li>
<li class="chapter" data-level="31.5" data-path="twowaymixed.html"><a href="twowaymixed.html#post-hoc-pairwise-tests"><i class="fa fa-check"></i><b>31.5</b> Post hoc pairwise tests</a><ul>
<li class="chapter" data-level="31.5.1" data-path="twowaymixed.html"><a href="twowaymixed.html#heres-whats-been-discovered"><i class="fa fa-check"></i><b>31.5.1</b> Here’s what’s been discovered</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="32" data-path="jaxwest2.html"><a href="jaxwest2.html"><i class="fa fa-check"></i><b>32</b> Reproducible Data Munging Mostly with Tidyverse</a><ul>
<li class="chapter" data-level="32.1" data-path="jaxwest2.html"><a href="jaxwest2.html#look-at-the-original-data-carefully"><i class="fa fa-check"></i><b>32.1</b> Look at the original data carefully</a></li>
<li class="chapter" data-level="32.2" data-path="jaxwest2.html"><a href="jaxwest2.html#our-goal"><i class="fa fa-check"></i><b>32.2</b> Our goal</a></li>
<li class="chapter" data-level="32.3" data-path="jaxwest2.html"><a href="jaxwest2.html#read-the-data-into-r"><i class="fa fa-check"></i><b>32.3</b> Read the data into R</a></li>
<li class="chapter" data-level="32.4" data-path="jaxwest2.html"><a href="jaxwest2.html#select-the-variables"><i class="fa fa-check"></i><b>32.4</b> Select the variables</a></li>
<li class="chapter" data-level="32.5" data-path="jaxwest2.html"><a href="jaxwest2.html#trim-the-cases"><i class="fa fa-check"></i><b>32.5</b> Trim the cases</a></li>
<li class="chapter" data-level="32.6" data-path="jaxwest2.html"><a href="jaxwest2.html#go-long"><i class="fa fa-check"></i><b>32.6</b> Go long</a></li>
<li class="chapter" data-level="32.7" data-path="jaxwest2.html"><a href="jaxwest2.html#pull-out-the-values-for-the-day-variable"><i class="fa fa-check"></i><b>32.7</b> Pull out the values for the day variable</a></li>
<li class="chapter" data-level="32.8" data-path="jaxwest2.html"><a href="jaxwest2.html#convert-day-to-numeric"><i class="fa fa-check"></i><b>32.8</b> Convert day to numeric</a></li>
<li class="chapter" data-level="32.9" data-path="jaxwest2.html"><a href="jaxwest2.html#convert-tumor_vol-to-numeric"><i class="fa fa-check"></i><b>32.9</b> Convert tumor_vol to numeric</a></li>
<li class="chapter" data-level="32.10" data-path="jaxwest2.html"><a href="jaxwest2.html#deal-with-that-na"><i class="fa fa-check"></i><b>32.10</b> Deal with that NA</a></li>
<li class="chapter" data-level="32.11" data-path="jaxwest2.html"><a href="jaxwest2.html#convert-variables-to-factor"><i class="fa fa-check"></i><b>32.11</b> Convert variables to factor</a></li>
<li class="chapter" data-level="32.12" data-path="jaxwest2.html"><a href="jaxwest2.html#plot-the-data"><i class="fa fa-check"></i><b>32.12</b> Plot the data</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="anovamc.html"><a href="anovamc.html"><i class="fa fa-check"></i><b>33</b> ANOVA power using Monte Carlo</a><ul>
<li class="chapter" data-level="33.1" data-path="anovamc.html"><a href="anovamc.html#alternatives-to-monte-carlo"><i class="fa fa-check"></i><b>33.1</b> Alternatives to Monte Carlo</a></li>
<li class="chapter" data-level="33.2" data-path="anovamc.html"><a href="anovamc.html#what-is-monte-carlo"><i class="fa fa-check"></i><b>33.2</b> What is Monte Carlo</a></li>
<li class="chapter" data-level="33.3" data-path="anovamc.html"><a href="anovamc.html#one-way-completely-randomized-anova-monte-carlo"><i class="fa fa-check"></i><b>33.3</b> One-way completely randomized ANOVA Monte Carlo</a><ul>
<li class="chapter" data-level="33.3.1" data-path="anovamc.html"><a href="anovamc.html#directions"><i class="fa fa-check"></i><b>33.3.1</b> Directions</a></li>
<li class="chapter" data-level="33.3.2" data-path="anovamc.html"><a href="anovamc.html#step-1-create-initial-values"><i class="fa fa-check"></i><b>33.3.2</b> Step 1: Create initial values</a></li>
<li class="chapter" data-level="33.3.3" data-path="anovamc.html"><a href="anovamc.html#step-2-visualize-one-random-sample"><i class="fa fa-check"></i><b>33.3.3</b> Step 2: Visualize one random sample</a></li>
<li class="chapter" data-level="33.3.4" data-path="anovamc.html"><a href="anovamc.html#step-3-run-the-power-simulator"><i class="fa fa-check"></i><b>33.3.4</b> Step 3: Run The Power Simulator</a></li>
<li class="chapter" data-level="33.3.5" data-path="anovamc.html"><a href="anovamc.html#step-4-optimize-for-suitable-power"><i class="fa fa-check"></i><b>33.3.5</b> Step 4: Optimize for suitable power</a></li>
<li class="chapter" data-level="33.3.6" data-path="anovamc.html"><a href="anovamc.html#notes-and-considerations"><i class="fa fa-check"></i><b>33.3.6</b> Notes And Considerations</a></li>
</ul></li>
<li class="chapter" data-level="33.4" data-path="anovamc.html"><a href="anovamc.html#one-way-related-measures-anova-monte-carlo"><i class="fa fa-check"></i><b>33.4</b> One-way related measures ANOVA Monte Carlo</a></li>
<li class="chapter" data-level="33.5" data-path="anovamc.html"><a href="anovamc.html#directions-1"><i class="fa fa-check"></i><b>33.5</b> Directions</a><ul>
<li class="chapter" data-level="33.5.1" data-path="anovamc.html"><a href="anovamc.html#step-1-initial-values"><i class="fa fa-check"></i><b>33.5.1</b> Step 1: Initial values</a></li>
<li class="chapter" data-level="33.5.2" data-path="anovamc.html"><a href="anovamc.html#step-2-visualize-one-sample"><i class="fa fa-check"></i><b>33.5.2</b> Step 2: Visualize one sample</a></li>
<li class="chapter" data-level="33.5.3" data-path="anovamc.html"><a href="anovamc.html#step-3-run-the-power-simulator-1"><i class="fa fa-check"></i><b>33.5.3</b> Step 3: Run the power simulator</a></li>
<li class="chapter" data-level="33.5.4" data-path="anovamc.html"><a href="anovamc.html#step-4-should-anything-be-changed"><i class="fa fa-check"></i><b>33.5.4</b> Step 4: Should anything be changed?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="34" data-path="correl.html"><a href="correl.html"><i class="fa fa-check"></i><b>34</b> Correlation</a><ul>
<li class="chapter" data-level="34.1" data-path="correl.html"><a href="correl.html#correlation-causation"><i class="fa fa-check"></i><b>34.1</b> Correlation != Causation</a></li>
<li class="chapter" data-level="34.2" data-path="correl.html"><a href="correl.html#correlation-in-multivariate-outcomes-and-paired-designs"><i class="fa fa-check"></i><b>34.2</b> Correlation in Multivariate Outcomes and Paired Designs</a></li>
<li class="chapter" data-level="34.3" data-path="correl.html"><a href="correl.html#correlation-coefficients"><i class="fa fa-check"></i><b>34.3</b> Correlation coefficients</a><ul>
<li class="chapter" data-level="34.3.1" data-path="correl.html"><a href="correl.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>34.3.1</b> Pearson’s correlation coefficient</a></li>
<li class="chapter" data-level="34.3.2" data-path="correl.html"><a href="correl.html#spearmans-rank-correlation"><i class="fa fa-check"></i><b>34.3.2</b> Spearman’s rank correlation</a></li>
<li class="chapter" data-level="34.3.3" data-path="correl.html"><a href="correl.html#kendalls-tau"><i class="fa fa-check"></i><b>34.3.3</b> Kendall’s tau</a></li>
<li class="chapter" data-level="34.3.4" data-path="correl.html"><a href="correl.html#which-correlation-method-to-use"><i class="fa fa-check"></i><b>34.3.4</b> Which correlation method to use?</a></li>
<li class="chapter" data-level="34.3.5" data-path="correl.html"><a href="correl.html#r-correlation-analysis-functions"><i class="fa fa-check"></i><b>34.3.5</b> R correlation analysis functions</a></li>
<li class="chapter" data-level="34.3.6" data-path="correl.html"><a href="correl.html#plot-the-correlations"><i class="fa fa-check"></i><b>34.3.6</b> Plot the correlations</a></li>
<li class="chapter" data-level="34.3.7" data-path="correl.html"><a href="correl.html#calculate-a-correlation-coefficient-and-posthoc-test"><i class="fa fa-check"></i><b>34.3.7</b> Calculate a correlation coefficient and posthoc test</a></li>
<li class="chapter" data-level="34.3.8" data-path="correl.html"><a href="correl.html#interpretation-of-correlation-output"><i class="fa fa-check"></i><b>34.3.8</b> Interpretation of correlation output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="35" data-path="regress.html"><a href="regress.html"><i class="fa fa-check"></i><b>35</b> Linear Regression</a><ul>
<li class="chapter" data-level="35.1" data-path="regress.html"><a href="regress.html#the-linear-regression-model"><i class="fa fa-check"></i><b>35.1</b> The linear regression model</a></li>
<li class="chapter" data-level="35.2" data-path="regress.html"><a href="regress.html#least-squares-fitting"><i class="fa fa-check"></i><b>35.2</b> Least squares fitting</a></li>
<li class="chapter" data-level="35.3" data-path="regress.html"><a href="regress.html#the-practical-importance-of-linear-model-parameters"><i class="fa fa-check"></i><b>35.3</b> The practical importance of linear model parameters</a></li>
<li class="chapter" data-level="35.4" data-path="regress.html"><a href="regress.html#linear-model-standard-errors"><i class="fa fa-check"></i><b>35.4</b> Linear model standard errors</a></li>
<li class="chapter" data-level="35.5" data-path="regress.html"><a href="regress.html#linear-regression-in-r"><i class="fa fa-check"></i><b>35.5</b> Linear regression in R</a></li>
<li class="chapter" data-level="35.6" data-path="regress.html"><a href="regress.html#intepretation-1"><i class="fa fa-check"></i><b>35.6</b> Intepretation</a><ul>
<li class="chapter" data-level="35.6.1" data-path="regress.html"><a href="regress.html#residuals"><i class="fa fa-check"></i><b>35.6.1</b> Residuals</a></li>
<li class="chapter" data-level="35.6.2" data-path="regress.html"><a href="regress.html#coefficients"><i class="fa fa-check"></i><b>35.6.2</b> Coefficients</a></li>
<li class="chapter" data-level="35.6.3" data-path="regress.html"><a href="regress.html#degrees-of-freedom-1"><i class="fa fa-check"></i><b>35.6.3</b> Degrees of freedom</a></li>
<li class="chapter" data-level="35.6.4" data-path="regress.html"><a href="regress.html#r-squared"><i class="fa fa-check"></i><b>35.6.4</b> R-squared</a></li>
<li class="chapter" data-level="35.6.5" data-path="regress.html"><a href="regress.html#f-statistic"><i class="fa fa-check"></i><b>35.6.5</b> F-statistic</a></li>
<li class="chapter" data-level="35.6.6" data-path="regress.html"><a href="regress.html#plotting-regression-results"><i class="fa fa-check"></i><b>35.6.6</b> Plotting regression results</a></li>
<li class="chapter" data-level="35.6.7" data-path="regress.html"><a href="regress.html#visualizing-residuals"><i class="fa fa-check"></i><b>35.6.7</b> Visualizing residuals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="36" data-path="nonlinearintro.html"><a href="nonlinearintro.html"><i class="fa fa-check"></i><b>36</b> Non-linear regression introduction</a><ul>
<li class="chapter" data-level="36.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#uses-for-nonlinear-regression"><i class="fa fa-check"></i><b>36.1</b> Uses for nonlinear regression</a></li>
<li class="chapter" data-level="36.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#nonlinear-models-and-parameters"><i class="fa fa-check"></i><b>36.2</b> Nonlinear models and parameters</a><ul>
<li class="chapter" data-level="36.2.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#hyperbolic-stimulus-response-functions"><i class="fa fa-check"></i><b>36.2.1</b> Hyperbolic stimulus response functions</a></li>
<li class="chapter" data-level="36.2.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#visualizing-nonlinear-data-and-log-scaling"><i class="fa fa-check"></i><b>36.2.2</b> Visualizing nonlinear data and log scaling</a></li>
</ul></li>
<li class="chapter" data-level="36.3" data-path="nonlinearintro.html"><a href="nonlinearintro.html#how-do-regression-fits-happen"><i class="fa fa-check"></i><b>36.3</b> How do regression fits happen?</a><ul>
<li class="chapter" data-level="36.3.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#selecting-the-right-model"><i class="fa fa-check"></i><b>36.3.1</b> Selecting the right model</a></li>
<li class="chapter" data-level="36.3.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#from-models-to-formulas"><i class="fa fa-check"></i><b>36.3.2</b> From models to formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="nestedregress.html"><a href="nestedregress.html"><i class="fa fa-check"></i><b>37</b> Nested-model nonlinear regression</a><ul>
<li class="chapter" data-level="37.1" data-path="nestedregress.html"><a href="nestedregress.html#read-and-plot-the-data"><i class="fa fa-check"></i><b>37.1</b> Read and plot the data</a></li>
<li class="chapter" data-level="37.2" data-path="nestedregress.html"><a href="nestedregress.html#perform-the-nonlinear-regression"><i class="fa fa-check"></i><b>37.2</b> Perform the nonlinear regression</a><ul>
<li class="chapter" data-level="37.2.1" data-path="nestedregress.html"><a href="nestedregress.html#troubleshooting-the-regression"><i class="fa fa-check"></i><b>37.2.1</b> Troubleshooting the regression</a></li>
<li class="chapter" data-level="37.2.2" data-path="nestedregress.html"><a href="nestedregress.html#interpreting-the-parameters"><i class="fa fa-check"></i><b>37.2.2</b> Interpreting the parameters</a></li>
<li class="chapter" data-level="37.2.3" data-path="nestedregress.html"><a href="nestedregress.html#residual-plots-to-compare-fits"><i class="fa fa-check"></i><b>37.2.3</b> Residual plots to compare fits</a></li>
<li class="chapter" data-level="37.2.4" data-path="nestedregress.html"><a href="nestedregress.html#compare-aic"><i class="fa fa-check"></i><b>37.2.4</b> Compare AIC</a></li>
<li class="chapter" data-level="37.2.5" data-path="nestedregress.html"><a href="nestedregress.html#other-ways-to-compare-models"><i class="fa fa-check"></i><b>37.2.5</b> Other ways to compare models</a></li>
<li class="chapter" data-level="37.2.6" data-path="nestedregress.html"><a href="nestedregress.html#interpretation-of-this-one-replicate"><i class="fa fa-check"></i><b>37.2.6</b> Interpretation of this one replicate</a></li>
<li class="chapter" data-level="37.2.7" data-path="nestedregress.html"><a href="nestedregress.html#alternate-analysis"><i class="fa fa-check"></i><b>37.2.7</b> Alternate analysis</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="nestedregress.html"><a href="nestedregress.html#summary-1"><i class="fa fa-check"></i><b>37.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="38" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html"><i class="fa fa-check"></i><b>38</b> Nonlinear regression of independent replicates</a><ul>
<li class="chapter" data-level="38.1" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#the-dataset"><i class="fa fa-check"></i><b>38.1</b> The dataset</a></li>
<li class="chapter" data-level="38.2" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#munging-for-regression-analysis"><i class="fa fa-check"></i><b>38.2</b> Munging for regression analysis</a><ul>
<li class="chapter" data-level="38.2.1" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#average-the-technical-replicates"><i class="fa fa-check"></i><b>38.2.1</b> Average the technical replicates</a></li>
<li class="chapter" data-level="38.2.2" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#create-one-table"><i class="fa fa-check"></i><b>38.2.2</b> Create one table</a></li>
<li class="chapter" data-level="38.2.3" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#plot-the-data-1"><i class="fa fa-check"></i><b>38.2.3</b> Plot the data</a></li>
<li class="chapter" data-level="38.2.4" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#clean-up-regression-results"><i class="fa fa-check"></i><b>38.2.4</b> Clean up regression results</a></li>
</ul></li>
<li class="chapter" data-level="38.3" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#t-test-on-half-lives"><i class="fa fa-check"></i><b>38.3</b> T-test on half-lives</a></li>
<li class="chapter" data-level="38.4" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#conclusion"><i class="fa fa-check"></i><b>38.4</b> Conclusion</a></li>
<li class="chapter" data-level="38.5" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#summary-figure"><i class="fa fa-check"></i><b>38.5</b> Summary figure</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="multregress.html"><a href="multregress.html"><i class="fa fa-check"></i><b>39</b> Multiple regression</a><ul>
<li class="chapter" data-level="39.1" data-path="multregress.html"><a href="multregress.html#the-linear-regression-model-1"><i class="fa fa-check"></i><b>39.1</b> The linear regression model</a></li>
<li class="chapter" data-level="39.2" data-path="multregress.html"><a href="multregress.html#multiple-regression-models"><i class="fa fa-check"></i><b>39.2</b> Multiple regression models</a></li>
<li class="chapter" data-level="39.3" data-path="multregress.html"><a href="multregress.html#experimental-multiple-regression"><i class="fa fa-check"></i><b>39.3</b> Experimental multiple regression</a><ul>
<li class="chapter" data-level="39.3.1" data-path="multregress.html"><a href="multregress.html#a-one-factor-experiment-with-3-groups"><i class="fa fa-check"></i><b>39.3.1</b> A one factor experiment with 3 groups</a></li>
<li class="chapter" data-level="39.3.2" data-path="multregress.html"><a href="multregress.html#a-two-factor-experiment-with-6-groups"><i class="fa fa-check"></i><b>39.3.2</b> A two factor experiment with 6 groups</a></li>
</ul></li>
<li class="chapter" data-level="39.4" data-path="multregress.html"><a href="multregress.html#multiple-linear-mixed-models"><i class="fa fa-check"></i><b>39.4</b> Multiple linear mixed models</a></li>
<li class="chapter" data-level="39.5" data-path="multregress.html"><a href="multregress.html#multiple-regression-of-observational-data"><i class="fa fa-check"></i><b>39.5</b> Multiple regression of observational data</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="logregress.html"><a href="logregress.html"><i class="fa fa-check"></i><b>40</b> Logistic regression</a><ul>
<li class="chapter" data-level="40.1" data-path="logregress.html"><a href="logregress.html#uses-of-logistic-regression"><i class="fa fa-check"></i><b>40.1</b> Uses of logistic regression</a><ul>
<li class="chapter" data-level="40.1.1" data-path="logregress.html"><a href="logregress.html#sidebar-doing-logistic-regression-is-machine-learning"><i class="fa fa-check"></i><b>40.1.1</b> Sidebar: Doing logistic regression is machine learning</a></li>
</ul></li>
<li class="chapter" data-level="40.2" data-path="logregress.html"><a href="logregress.html#derivation-of-the-logistic-regression-model"><i class="fa fa-check"></i><b>40.2</b> Derivation of the logistic regression model</a><ul>
<li class="chapter" data-level="40.2.1" data-path="logregress.html"><a href="logregress.html#relationship-of-logit-to-odds-to-the-model-coefficients-and-probability"><i class="fa fa-check"></i><b>40.2.1</b> Relationship of logit to odds to the model coefficients and probability</a></li>
<li class="chapter" data-level="40.2.2" data-path="logregress.html"><a href="logregress.html#additional-types-of-logistic-regression-models"><i class="fa fa-check"></i><b>40.2.2</b> Additional types of logistic regression models</a></li>
</ul></li>
<li class="chapter" data-level="40.3" data-path="logregress.html"><a href="logregress.html#stress-and-survival"><i class="fa fa-check"></i><b>40.3</b> Stress and survival</a><ul>
<li class="chapter" data-level="40.3.1" data-path="logregress.html"><a href="logregress.html#interpretation-of-output"><i class="fa fa-check"></i><b>40.3.1</b> Interpretation of output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="41" data-path="mixedlogistic.html"><a href="mixedlogistic.html"><i class="fa fa-check"></i><b>41</b> Mixed model logistic regression</a><ul>
<li class="chapter" data-level="41.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#mixed-models-fixed-and-random-effects"><i class="fa fa-check"></i><b>41.1</b> Mixed models, fixed and random effects</a><ul>
<li class="chapter" data-level="41.1.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#nfat-localization-within-smooth-muscle-cells"><i class="fa fa-check"></i><b>41.1.1</b> NFAT localization within smooth muscle cells</a></li>
</ul></li>
<li class="chapter" data-level="41.2" data-path="mixedlogistic.html"><a href="mixedlogistic.html#data-1"><i class="fa fa-check"></i><b>41.2</b> Data</a><ul>
<li class="chapter" data-level="41.2.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#inference-1"><i class="fa fa-check"></i><b>41.2.1</b> Inference</a></li>
</ul></li>
<li class="chapter" data-level="41.3" data-path="mixedlogistic.html"><a href="mixedlogistic.html#alternative-analysis"><i class="fa fa-check"></i><b>41.3</b> Alternative analysis</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">JABSTB: Statistical Design and Analysis of Experiments with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="onewayanova" class="section level1">
<h1><span class="header-section-number">Chapter 27</span> One-way ANOVA Completely Randomized</h1>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb506-1" title="1"><span class="kw">library</span>(magrittr)</a>
<a class="sourceLine" id="cb506-2" title="2"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb506-3" title="3"><span class="kw">library</span>(ggformula)</a>
<a class="sourceLine" id="cb506-4" title="4"><span class="kw">library</span>(DescTools)</a>
<a class="sourceLine" id="cb506-5" title="5"><span class="kw">library</span>(ez)</a>
<a class="sourceLine" id="cb506-6" title="6"><span class="kw">library</span>(lsr)</a></code></pre></div>
<p>If you haven’t yet read the ANOVA big picture, <a href="introanova.html#introanova">this is worth reading</a>)</p>
<div id="using-ezanova" class="section level2">
<h2><span class="header-section-number">27.1</span> Using <code>ezANOVA</code></h2>
<p>R has several functions to run ANOVA. In this course we’re going to use <code>ezANOVA</code> from the <code>ez</code> package because I feel the syntax for defining CR vs RM is a bit more straightforward.</p>
<p>In this chapter, we’ll run through an analysis of a one-way completely randomized ANOVA data set as ‘how to’ example.</p>
</div>
<div id="the-chickwt-data-set" class="section level2">
<h2><span class="header-section-number">27.2</span> The chickwt data set</h2>
<p>This data set in R’s base. It compares the influence of 6 different types of food sources on chick weight. There is one predictor variable, the factor ‘feed’, which is tested at 6 different levels (the various food sources).</p>
<p>There has one continuous outcome variable (weight). We can assume the chicks are outbred, and thus not intrinsically-related, and that they have been randomly assigned to a level of feed, and have been weighed after a period of time.</p>
<p>This is a classic one-way completely randomized ANOVA design. This chapter illustrates how to go through an analysis of the data.</p>
<div id="inspect-the-data" class="section level3">
<h3><span class="header-section-number">27.2.1</span> Inspect the data</h3>
<p>The next few scripts involve inspecting the data set, which should always be done prior to running any statistical tests.</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb507-1" title="1"><span class="kw">data</span>(chickwts)</a>
<a class="sourceLine" id="cb507-2" title="2"><span class="co">#take a look at the data structure, depending upon how you like to view data</span></a>
<a class="sourceLine" id="cb507-3" title="3"><span class="kw">str</span>(chickwts)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    71 obs. of  2 variables:
##  $ weight: num  179 160 136 227 217 168 108 124 143 140 ...
##  $ feed  : Factor w/ 6 levels &quot;casein&quot;,&quot;horsebean&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb509-1" title="1">chickwts</a></code></pre></div>
<pre><code>##    weight      feed
## 1     179 horsebean
## 2     160 horsebean
## 3     136 horsebean
## 4     227 horsebean
## 5     217 horsebean
## 6     168 horsebean
## 7     108 horsebean
## 8     124 horsebean
## 9     143 horsebean
## 10    140 horsebean
## 11    309   linseed
## 12    229   linseed
## 13    181   linseed
## 14    141   linseed
## 15    260   linseed
## 16    203   linseed
## 17    148   linseed
## 18    169   linseed
## 19    213   linseed
## 20    257   linseed
## 21    244   linseed
## 22    271   linseed
## 23    243   soybean
## 24    230   soybean
## 25    248   soybean
## 26    327   soybean
## 27    329   soybean
## 28    250   soybean
## 29    193   soybean
## 30    271   soybean
## 31    316   soybean
## 32    267   soybean
## 33    199   soybean
## 34    171   soybean
## 35    158   soybean
## 36    248   soybean
## 37    423 sunflower
## 38    340 sunflower
## 39    392 sunflower
## 40    339 sunflower
## 41    341 sunflower
## 42    226 sunflower
## 43    320 sunflower
## 44    295 sunflower
## 45    334 sunflower
## 46    322 sunflower
## 47    297 sunflower
## 48    318 sunflower
## 49    325  meatmeal
## 50    257  meatmeal
## 51    303  meatmeal
## 52    315  meatmeal
## 53    380  meatmeal
## 54    153  meatmeal
## 55    263  meatmeal
## 56    242  meatmeal
## 57    206  meatmeal
## 58    344  meatmeal
## 59    258  meatmeal
## 60    368    casein
## 61    390    casein
## 62    379    casein
## 63    260    casein
## 64    404    casein
## 65    318    casein
## 66    352    casein
## 67    359    casein
## 68    216    casein
## 69    222    casein
## 70    283    casein
## 71    332    casein</code></pre>
<p>It is also helpful to calculate some descriptive stats for inspection:</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb511-1" title="1">cw1 &lt;-<span class="st"> </span>chickwts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb511-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(feed) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb511-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb511-4" title="4">    <span class="dt">mean=</span> <span class="kw">mean</span>(weight),</a>
<a class="sourceLine" id="cb511-5" title="5">    <span class="dt">median=</span><span class="kw">median</span>(weight),</a>
<a class="sourceLine" id="cb511-6" title="6">    <span class="dt">sd=</span> <span class="kw">sd</span>(weight),</a>
<a class="sourceLine" id="cb511-7" title="7">    <span class="dt">n =</span> <span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb511-8" title="8">    <span class="dt">var=</span><span class="kw">var</span>(weight)</a>
<a class="sourceLine" id="cb511-9" title="9">    )</a>
<a class="sourceLine" id="cb511-10" title="10">cw1</a></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   feed       mean median    sd     n   var
##   &lt;fct&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
## 1 casein     324.   342   64.4    12 4152.
## 2 horsebean  160.   152.  38.6    10 1492.
## 3 linseed    219.   221   52.2    12 2729.
## 4 meatmeal   277.   263   64.9    11 4212.
## 5 soybean    246.   248   54.1    14 2930.
## 6 sunflower  329.   328   48.8    12 2385.</code></pre>
<p>The means and medians are about equal within each group. That’s a quick and dirty way to suggest no skew. Overall sample size is 71, distributed as 10-14 replicates per group, it’s a little unbalanced. But within acceptable limits. The variances are not equivalent, but are they unequal? Levene’s test in the ANOVA will provide that answer.</p>
<p>Plot the data for a look. Simply looking at the data graphically goes a long way to ensuring this is a one-way ANOVA design. Jitter plots are a great way to see group data like this. I like the <code>crossbar</code> geom to overlay some summary stats.</p>
<div class="sourceCode" id="cb513"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb513-1" title="1"><span class="kw">ggplot</span>(chickwts, <span class="kw">aes</span>(feed, weight))<span class="op">+</span></a>
<a class="sourceLine" id="cb513-2" title="2"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.2</span>, <span class="dt">size=</span><span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb513-3" title="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_sdl, </a>
<a class="sourceLine" id="cb513-4" title="4">               <span class="dt">fun.args =</span> <span class="kw">list</span>(<span class="dt">mult=</span><span class="dv">1</span>), </a>
<a class="sourceLine" id="cb513-5" title="5">               <span class="dt">geom=</span><span class="st">&quot;crossbar&quot;</span>, </a>
<a class="sourceLine" id="cb513-6" title="6">               <span class="dt">width=</span><span class="fl">0.2</span>, </a>
<a class="sourceLine" id="cb513-7" title="7">               <span class="dt">color=</span><span class="st">&quot;red&quot;</span></a>
<a class="sourceLine" id="cb513-8" title="8">               ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb513-9" title="9"><span class="st">  </span><span class="kw">theme_classic</span>()</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-270-1.png" width="672" /></p>
</div>
</div>
<div id="run-the-anova" class="section level2">
<h2><span class="header-section-number">27.3</span> Run the ANOVA</h2>
<p>We can imagine designing an experiment like this with either of 3 experimental objectives in mind.</p>
<ol style="list-style-type: decimal">
<li><p>Perhaps we’re interested mostly in whether any feeds are better than others for achieving weight gain? We could answer that by making all possible pairwise comparisons. Since there are 6 levels of the factor feed, that would involve <span class="math inline">\(C=\frac{6(6-1)}{2}=15\)</span> comparisons(!!)</p></li>
<li><p>Imagine casein is the standard feed, and we wish to know if any of the other feeds differ from this standard? We would compare casein to every feed. That would involve only 5 comparisons.</p></li>
<li><p>Perhaps we just want to know if any of the feeds differ in causing weight gain, but we aren’t interested in which specific feeds differ? We could answer that question using the F-test result, and not comparing any groups post hoc.</p></li>
</ol>
<p>Each of those objectives are scientifically-driven. They should be addressed <em>before</em> running an experiment so that an unbiased analysis is conducted <em>after</em> the data are in.</p>
<p>Other than, perhaps, how we order our data in the data set, which of these objectives is true doesn’t influence how we run the <code>ezANOVA</code> function per se. However, the objective will influence which post hoc analysis we conduct.</p>
<div id="run-the-chickwts-one-way-anova" class="section level3">
<h3><span class="header-section-number">27.3.1</span> Run the chickwts One Way ANOVA</h3>
<p>First, ezANOVA requires a ‘wid’, which is a unique ID variable for each independent replicate.</p>
<p>We need to add one to the chickwts data set. Since all the measures are independent, we’ll just do that by row number. At the same time we’ll convert the integer to a factor so ezANOVA won’t bark at us.</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb514-1" title="1">chickwts<span class="op">$</span>ID &lt;-<span class="st"> </span><span class="kw">as.factor</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(chickwts))</a></code></pre></div>
<p>You should look at R’s help for ezANOVA <code>?ezANOVA</code> to understand these test arguments. The help page is pretty clear for most of these.</p>
<p>Since we don’t use the term ‘dependent variable’ much in this course, to be clear, ‘dv’ is the outcome response variable. We have to specify it in the <code>ezANOVA</code> arguments.</p>
<p>If measurements for levels of the factor are not instrinsically-linked, if they are distributed to each replicate independently, the design is completely randomized. That factor should be listed in the function using a ‘between’ argument.</p>
<p>If measurements for levels of the factor are intrinsically-linked, it is arelated/repeated measures design. List it as a ‘within’ argument, rather than ‘between’.</p>
<p>Here, the <code>feed</code> factor is <code>between</code>. Every chick was randomly assigned a level of feed.</p>
<p>Notice that <code>ezANOVA</code> is a function. Use it to create a list object called <code>my.ezaov</code>, which has all of the output information. The object name could have been <code>foo</code>. We call specific elements from the <code>my.ezaov</code> object to see the results.</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb515-1" title="1">my.ezaov &lt;-<span class="st"> </span><span class="kw">ezANOVA</span>(</a>
<a class="sourceLine" id="cb515-2" title="2">            <span class="dt">data =</span> chickwts, </a>
<a class="sourceLine" id="cb515-3" title="3">            <span class="dt">wid =</span> ID, </a>
<a class="sourceLine" id="cb515-4" title="4">            <span class="dt">dv =</span> weight, </a>
<a class="sourceLine" id="cb515-5" title="5">            <span class="dt">between =</span> feed,</a>
<a class="sourceLine" id="cb515-6" title="6">            <span class="dt">type =</span> <span class="dv">2</span>, </a>
<a class="sourceLine" id="cb515-7" title="7">            <span class="dt">return_aov =</span> T, </a>
<a class="sourceLine" id="cb515-8" title="8">            <span class="dt">detailed =</span> T)</a></code></pre></div>
<pre><code>## Warning: Data is unbalanced (unequal N per group). Make sure you specified a
## well-considered value for the type argument to ezANOVA().</code></pre>
<pre><code>## Coefficient covariances computed by hccm()</code></pre>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb518-1" title="1">my.ezaov</a></code></pre></div>
<pre><code>## $ANOVA
##   Effect DFn DFd      SSn    SSd       F           p p&lt;.05       ges
## 1   feed   5  65 231129.2 195556 15.3648 5.93642e-10     * 0.5416855
## 
## $`Levene&#39;s Test for Homogeneity of Variance`
##   DFn DFd      SSn      SSd         F         p p&lt;.05
## 1   5  65 4389.241 76154.92 0.7492639 0.5896095      
## 
## $aov
## Call:
##    aov(formula = formula(aov_formula), data = data)
## 
## Terms:
##                     feed Residuals
## Sum of Squares  231129.2  195556.0
## Deg. of Freedom        5        65
## 
## Residual standard error: 54.85029
## Estimated effects may be unbalanced</code></pre>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb520-1" title="1"><span class="co"># my.ezaov$ANOVA</span></a>
<a class="sourceLine" id="cb520-2" title="2"><span class="co"># my.ezaov$Levene</span></a>
<a class="sourceLine" id="cb520-3" title="3"><span class="co"># my.ezaov$aov</span></a></code></pre></div>
</div>
<div id="interpreting-the-one-way-cr-anova-output" class="section level3">
<h3><span class="header-section-number">27.3.2</span> Interpreting the One-Way CR ANOVA Output</h3>
<p>The ezANOVA output prints 3 list objects by default:</p>
<ul>
<li>$ANOVA (which is the first data frame)</li>
<li>$<code>Levene's Test for Homogeneity of Variance</code> (which is the 2nd data frame)</li>
<li>$aov (which is the end of the console output)</li>
</ul>
<p>In fact, there is a great deal more computed that is not printed, which you can visualize in the console by typing <code>str(my.ezaov)</code>.</p>
<div id="anova-the-anova-table" class="section level4">
<h4><span class="header-section-number">27.3.2.1</span> $ANOVA: The ANOVA table</h4>
<p>For a CR one way ANOVA design, the SS are partitioned as follows, in general: <span class="math inline">\(SS_{total}=SS_{model}+SS_{residual}\)</span>.</p>
<p>In this example, <span class="math inline">\(SS_{model}= SS_{feed}\)</span>.</p>
<p>Thus, the ANOVA table summarizes the feed model.</p>
<p>The DFn = 5 corresponds to the 6 groups, less 1 degree of freedom (one is lost to calculate mean of groups (sort of)) for the model source of variance.</p>
<p>The DFn = 65 corresponds to the degrees of freedom for the residuals (one df is lost per group to calculate group means).</p>
<p>Therefore, this ANOVA tests a feed model against a null F distribution with 5 and 65 degrees of freedom.</p>
<p><span class="math inline">\(F=MS_{feed}/MS_{residual}=15.3648\)</span>, where <span class="math inline">\(MS = SS/df\)</span>. The SS can be found in the $aov output.</p>
<ul>
<li>ges = <a href="https://link.springer.com/article/10.3758/BF03192707">generalized eta-squared</a>.</li>
</ul>
<p><code>ges</code> is an effect size parameter for ANOVA. For this particular experimental design, <span class="math inline">\(ges=\frac{SS_n}{SS_n+SS_d}\)</span>. In other words, <code>ges</code> summarizes the variation associated with the model as a fraction of the total variation in the data.</p>
<p>Thus, 54.16% of the variation in weight is attributable to the different levels of feed in the experiment. In other words, the model explains 54.16% of the variation in the data.</p>
<p>Think of eta-squared, partial eta-squared, and generalized eta-squared as all related to the more commonly understood <span class="math inline">\(R^2\)</span> of regression. They are each calculated differently, but all related to <span class="math inline">\(R^2\)</span> in so far as they serve as estimates for how much of the variation is due to the model. <code>ges</code> takes on values from 0 to 1. Higher values indicate a greater degree of the overall variation is due to the factor tested in the experiment.</p>
<p>Having said that, it’s a bit of a Goldilock statistics. You only really begin to appreciate what it means after producing several of them.</p>
</div>
<div id="aov" class="section level4">
<h4><span class="header-section-number">27.3.2.2</span> $aov</h4>
<p>This table provides the accounting for the sum of squares and degrees of freedom, while calculating the residual standard error. It is somewhat redundant with the $ANOVA table, though the residual standard error can come in handy.</p>
<ul>
<li>DFn=degrees freedom for numerator. k-1, where k = levels of factor.</li>
<li>DFd=degrees freedom for denominator. n-k, where n = number of independent replicates.</li>
<li>SSn &amp; SSd = sum of squares for model and residual, respectively</li>
<li>Residual standard error is a parameter that estimates the precision by which the data fit the model, and is in units of the outcome variable, weight. <span class="math inline">\(SE\)</span> is the square root of the residual variance: <span class="math inline">\(S_{y.x}=\sqrt{\frac{SS_{residual}}{df_{residual}}}\)</span></li>
</ul>
<p>If <span class="math inline">\(S_{y.x}\)</span> were zero, there would be no residuals. The data points would all rest at the value of the group means. The data would fit perfectly to a model of 6 group means at their observed values. <span class="math inline">\(S_{y.x}\)</span> therefore is a descriptive statistic that declares how much error, or the degree by which the data is unexplained by the model. It has some utility for confidence intervals and power analysis.</p>
</div>
<div id="the-f-test-1" class="section level4">
<h4><span class="header-section-number">27.3.2.3</span> The F test</h4>
<p>The scientific prediction for this experiment is that chick weights will vary depending upon the type of feed they are grown on. The null is that their weights will be roughly the same, irrespective of food source.</p>
<p>ANOVA tests this hypothesis through the variance parameter. The question is whether the variance associated with the model, one of 6 different feed group means, is fractionally greater than the residual variance in the sample.</p>
<p>The null statistical hypothesis is that the variance associated with the different levels of feed is less than or equal to the residual variance. Therefore, the alternate hypothesis is the variance associated with feed is greater than residual variance.</p>
<p><span class="math inline">\(H_0: MS_{feed}\le MS_{residual}\)</span>, <span class="math inline">\(H_1: MS_{feed}&gt;MS_{residual}\)</span></p>
<p>Because of the relationship of group means to variance, it is just as valid to express the null hypothesis in terms of the group means, and that can be proven mathematically by a competent statistician:</p>
<p><span class="math inline">\(H_0: \mu_a=\mu_b=\mu_c=\mu_d=\mu_e=\mu_f\)</span> Though, strictly, rejecting the null doesn’t mean that all group means differ from each other, it just means that some of them differ. <span class="math inline">\(H_1: \mu_a\ne\mu_b\ne\mu_c\ne\mu_d\ne\mu_e\ne\mu_f\)</span></p>
<p>The F statistic of 15.3648 is extreme for a null F distribution of 5 and 65 degrees of freedom. The very low p-value illustrates this extremeness.</p>
<p>The probability of erroneously rejecting the null hypothesis is about 5e-10. We can reject the null and conclude that differences in effect on chick weights exist between this group of feeds.</p>
</div>
<div id="levenes-test-for-homogeneity-of-variance" class="section level4">
<h4><span class="header-section-number">27.3.2.4</span> Levene’s test for homogeneity of variance</h4>
<p>Levene’s test determines whether there is a substantial level of differences in variance <em>between</em> groups. Levene’s test is run as a check to determine if the groups variance is homogeneous, as homoskedasticity is one of the validity assumptions of ANOVA.</p>
<p>Levene’s test statistic is calculated as follows:</p>
<p><span class="math display">\[W=\frac{(n-k)}{(k-1)}\frac{\sum\limits_{i=1}^{k}n_i(\bar Z_i-\bar Z)^2}{\sum\limits_{i=1}^{k}\sum\limits_{j=1}^{n_i}(Z_{ij}-\bar Z_i)^2}\]</span></p>
<p>where <span class="math inline">\(Z_{ij}=|x_{ij}-\bar x_i|\)</span> and <span class="math inline">\(Z_i\)</span> are the group means and <span class="math inline">\(\bar Z\)</span> is the overall mean of <span class="math inline">\(Z_{ij}\)</span>.</p>
<p>The null hypothesis of the Levene test is rejected when <span class="math inline">\(W&gt;F_{(\alpha,\ k-1,\ n-k)}\)</span>, where the F is the critical value.</p>
<p>Levene’s test output is a 2nd ANOVA table, and can easily be confused with the ANOVA output. Levene’s test lacks a <span class="math inline">\(ges\)</span> parameter, nor does it have a column that lists the factor name.</p>
<p>If the Levene’s F value is low and the p-values is high, as is the case here, we can’t reject the null that the variances are the same. Thus, the variance homogeneity assumption is validated.</p>
<p>If this were not the case, you have two options.</p>
<p>Option 1: Simply ignore the result. The luck of the draw with small samples can explain group differences in variance, where none really exists. The impact on your inference will be very modest. What’s more important is that the population you are sampling is normally distributed. Do you have reason to think that is not the case?</p>
<p>Option 2: Transform the data to homogenize outliers and variance, or switch the analysis to a Kruskal-Wallis nonparametric test.</p>
</div>
</div>
</div>
<div id="posthoc" class="section level2">
<h2><span class="header-section-number">27.4</span> Post hoc pairwise comparisons</h2>
<p>If the ANOVA F test for the factor is extreme you may be interested in knowing which treatment groups differ. That’s achieved by conducting post hoc analysis, which typically involves multiple group comparisons.</p>
<p>In other words, post hoc involves testing several hypotheses simultaneously. Each test risks type1 error. Therefore, post hoc testing should be done in a way that keeps the cumulative, family-wise type1 error rate (FWER) below the type 1 error threshold that was set for the experiment; usually 5%.</p>
<div id="overview-of-options" class="section level3">
<h3><span class="header-section-number">27.4.1</span> Overview of options</h3>
<p>Sometimes we do these experiments without any clear plans of what groups we might want to compare. In those cases, we compare every group to all other groups. Doing so will involve <span class="math inline">\(\frac{k(k-1)}{k}\)</span> comparisons in an experiment with <span class="math inline">\(k\)</span> groups. That “burns” a lot of alpha, perhaps needlessly, but that’s the price paid for not planning. The tests for that include the Bonferroni (aka Dunn’s) and its cousins, Holm, Hommel, and Hochberg. They differ slightly, and will generate slightly different adjusted p-values given a common set of unadjusted p-values. Choose one.</p>
<p>Step-down tests operate a bit differently but do the same thing in terms of making all comparisons, these including the Tukey HSD and Newman-Keuls.</p>
<p>When we intend to compare all groups back to one level of the factor, thus making only a subset of all possible comparisons, we use Dunnett’s or the FisherLSD. But it’s just as valid to use any other of these methods.</p>
<div id="two-imperatives-in-pairwise-testing" class="section level4">
<h4><span class="header-section-number">27.4.1.1</span> Two imperatives in pairwise testing</h4>
<ol style="list-style-type: decimal">
<li><p>Since every p-value represents a hypothesis, when simultaneously testing many hypotheses always make adjustments to keep the FWER &lt; 0.05 (or whatever overall type1 error limit you preset for the experiment).</p></li>
<li><p>Let your scientific questions drive the comparisons you’ll make, and thus your choice of post hoc test.</p></li>
</ol>
<p>I suggest you worry less about the specific post hoc test, or about gamification of p-values, and think more about whether a comparison is scientifically important.</p>
<p>But there are a couple of provisos: 1) Bonferroni (or its cousins) works just fine if you don’t have too many means to compare, 2) Dunnett’s is for comparing two or more means back to a control mean but should not be used in related measures factors, 3) Fishers LSD will give you output to make those one or few key comparison you set out to make, even though you have many other groups in the experiment (ie, several of the other groups are internal controls and not particularly scientifically important).</p>
</div>
<div id="examples" class="section level4">
<h4><span class="header-section-number">27.4.1.2</span> Examples</h4>
<p><strong>No p-value adjustment</strong>: Sometimes it’s useful to generate p-values that are not corrected for multiple comparisons. For example, although you’ve done a simple ANOVA, the intention all along was to test only one hypothesis between two groups. The <code>pairwise.t.test</code> function produces a matrix of all comparisons, within which you can find the p-value for the comparison of interest.</p>
<p>The script below will generate a matrix of p-values for t tests of all possible comparisons, none of which are adjusted for multiple comparisons. When running the other scripts below, come back to this to see how adjusted p-value methods changes these results</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb521-1" title="1">allPairs &lt;-<span class="st"> </span><span class="kw">pairwise.t.test</span>(chickwts<span class="op">$</span>weight, chickwts<span class="op">$</span>feed, <span class="dt">p.adjust=</span> <span class="st">&quot;none&quot;</span>)</a>
<a class="sourceLine" id="cb521-2" title="2">allPairs</a></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  chickwts$weight and chickwts$feed 
## 
##           casein  horsebean linseed meatmeal soybean
## horsebean 2.1e-09 -         -       -        -      
## linseed   1.5e-05 0.01522   -       -        -      
## meatmeal  0.04557 7.5e-06   0.01348 -        -      
## soybean   0.00067 0.00032   0.20414 0.17255  -      
## sunflower 0.81249 8.2e-10   6.2e-06 0.02644  0.00030
## 
## P value adjustment method: none</code></pre>
<p>The unadjusted p-value output from the <code>pairwise.t.test</code> function is a matrix, which is important to know when the need arises to pull out specific elements of the analysis.</p>
<div class="sourceCode" id="cb523"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb523-1" title="1"><span class="kw">class</span>(allPairs<span class="op">$</span>p.value)</a></code></pre></div>
<pre><code>## [1] &quot;matrix&quot;</code></pre>
<div class="sourceCode" id="cb525"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb525-1" title="1">allPairs<span class="op">$</span>p.value</a></code></pre></div>
<pre><code>##                 casein    horsebean      linseed   meatmeal      soybean
## horsebean 2.067997e-09           NA           NA         NA           NA
## linseed   1.493344e-05 1.522197e-02           NA         NA           NA
## meatmeal  4.556672e-02 7.478012e-06 1.347894e-02         NA           NA
## soybean   6.654079e-04 3.246269e-04 2.041446e-01 0.17255391           NA
## sunflower 8.124949e-01 8.203777e-10 6.211836e-06 0.02643548 0.0002980438</code></pre>
<p>To quickly scan which comparisons are below the p &lt; 0.05 threshold we can apply this custom <code>extreme</code> function across the matrix:</p>
<div class="sourceCode" id="cb527"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb527-1" title="1">extreme &lt;-<span class="st"> </span><span class="cf">function</span>(x){</a>
<a class="sourceLine" id="cb527-2" title="2">  <span class="kw">ifelse</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb527-3" title="3">}</a>
<a class="sourceLine" id="cb527-4" title="4"></a>
<a class="sourceLine" id="cb527-5" title="5"><span class="kw">apply</span>(allPairs<span class="op">$</span>p.value, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), extreme)</a></code></pre></div>
<pre><code>##           casein horsebean linseed meatmeal soybean
## horsebean   TRUE        NA      NA       NA      NA
## linseed     TRUE      TRUE      NA       NA      NA
## meatmeal    TRUE      TRUE    TRUE       NA      NA
## soybean     TRUE      TRUE   FALSE    FALSE      NA
## sunflower  FALSE      TRUE    TRUE     TRUE    TRUE</code></pre>
<p><strong>All comparisons with Bonferroni adjustment</strong>: The Bonferroni correction is the easiest to understand, so I’ll use that to illustrate p-value adjusting. Let <span class="math inline">\(C\)</span> be the number of possible comparisons for a total of <span class="math inline">\(k\)</span> groups in the experiment. An adjusted type 1 error threshold for each comparison is:
<span class="math display">\[\alpha_k=\frac{\alpha}{C}\]</span></p>
<p>Thus, in an experiment with 15 possible comparisons, the adjusted type1 error threshold for each comparison would be <span class="math inline">\(\alpha_K\)</span> = 0.05/15 = 0.003333.</p>
<p>The adjusted p-value functions, however, makes the correction and then recalibrate the p-values back to the confidence level of choice. This can be a bit confusing for the first time. But you’ll note that the net effect is to increase each p-value. Some that were below the threshold unadjusted are greater than the threshold after the adjustment.</p>
<p>For example, you can see that the p-values adjusted using the Bonferroni correction below are all higher than they were above, when unadjusted.</p>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb529-1" title="1">bonf.adjustedAllpairs &lt;-<span class="st"> </span><span class="kw">pairwise.t.test</span>(chickwts<span class="op">$</span>weight, chickwts<span class="op">$</span>feed, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="dt">p.adjust =</span> <span class="st">&quot;bonferroni&quot;</span>)</a>
<a class="sourceLine" id="cb529-2" title="2">bonf.adjustedAllpairs</a></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  chickwts$weight and chickwts$feed 
## 
##           casein  horsebean linseed meatmeal soybean
## horsebean 3.1e-08 -         -       -        -      
## linseed   0.00022 0.22833   -       -        -      
## meatmeal  0.68350 0.00011   0.20218 -        -      
## soybean   0.00998 0.00487   1.00000 1.00000  -      
## sunflower 1.00000 1.2e-08   9.3e-05 0.39653  0.00447
## 
## P value adjustment method: bonferroni</code></pre>
<p>And here’s a quick scan for which of these are now below a FWER p &lt; 0.05. Note how a handful of comparisons that were scored extreme by this simple test above, without a p-value adjustment, are no longer extreme with the p-value adjustment.</p>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb531-1" title="1">extreme &lt;-<span class="st"> </span><span class="cf">function</span>(x){</a>
<a class="sourceLine" id="cb531-2" title="2">  <span class="kw">ifelse</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb531-3" title="3">  </a>
<a class="sourceLine" id="cb531-4" title="4">}</a>
<a class="sourceLine" id="cb531-5" title="5"><span class="kw">apply</span>(bonf.adjustedAllpairs<span class="op">$</span>p.value, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), extreme)</a></code></pre></div>
<pre><code>##           casein horsebean linseed meatmeal soybean
## horsebean   TRUE        NA      NA       NA      NA
## linseed     TRUE     FALSE      NA       NA      NA
## meatmeal   FALSE      TRUE   FALSE       NA      NA
## soybean     TRUE      TRUE   FALSE    FALSE      NA
## sunflower  FALSE      TRUE    TRUE    FALSE    TRUE</code></pre>
<p>Optional methods in these functions for the Bonferroni correction are “holm”, “hochberg” and “hommel”, each calculates p-value adjustments in slightly different ways. They are each considered slightly more liberal versions of the “bonferroni”.</p>
<p>Which is the best? For all practical purposes, none. Choose one early in your career and stick with it forever. What’s most important is to declare in the planning stages which will be used, and stick with it. That’s the best way to keeps it unbiased. You don’t want to ever find yourself interating through adjustment methods just to find the one that gives a borderline result an asterisk.</p>
<p><a href="http://www-stat.wharton.upenn.edu/~steele/Courses/956/Resource/MultipleComparision/Writght92.pdf">Read Wright for more information on the adjustment calculations and performance</a></p>
<p><strong>Adjusting p-values for subsets of comparisons</strong></p>
<p>Often, we don’t want to burn so much type1 error making scientifically uninteresting comparisons. In such cases, we instead want to compare subsets.</p>
<p>Here’s a three step procedure for doing just that.</p>
<p>Step1: First, run the <code>pairwise.t.test</code> function, setting the argument <code>p.adjust="none"</code>. The output includes a matrix of p-values we’ll name <code>allPairs</code>, providing all possible comparisons.</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb533-1" title="1"><span class="co">#just repeating from above</span></a>
<a class="sourceLine" id="cb533-2" title="2">allPairs &lt;-<span class="st"> </span><span class="kw">pairwise.t.test</span>(chickwts<span class="op">$</span>weight, chickwts<span class="op">$</span>feed, <span class="dt">p.adjust=</span> <span class="st">&quot;none&quot;</span>)</a></code></pre></div>
<p>Step2: Select from the <code>allPairs</code> matrix only the p-values that correspond to the comparisons you’d like to make. Name that vector of unadjusted p-values, <code>selectPairs</code>. This takes a bit of cleverness depending on what you want to grab from the matrix.</p>
<p>For example, we only want to compare all of the diets to casein. The comparisons we want are all in the first column. Use your matrix indexing skillz to grab only the unadjusted p-values from that first column:</p>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb534-1" title="1">selectPairs &lt;-<span class="st"> </span>allPairs<span class="op">$</span>p.value[, <span class="dv">1</span>]</a>
<a class="sourceLine" id="cb534-2" title="2">selectPairs</a></code></pre></div>
<pre><code>##    horsebean      linseed     meatmeal      soybean    sunflower 
## 2.067997e-09 1.493344e-05 4.556672e-02 6.654079e-04 8.124949e-01</code></pre>
<p>Step3: Pass unadjusted p-values in the <code>selectPairs</code> vector into the <code>p.adjust</code> function.</p>
<p>The output of this step is a vector of adjusted p-values for the selected group of comparisons.</p>
<div class="sourceCode" id="cb536"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb536-1" title="1">adjustedPvalues &lt;-<span class="st"> </span><span class="kw">p.adjust</span>(selectPairs, <span class="dt">method=</span><span class="st">&quot;bonferroni&quot;</span>)</a>
<a class="sourceLine" id="cb536-2" title="2">adjustedPvalues</a></code></pre></div>
<pre><code>##    horsebean      linseed     meatmeal      soybean    sunflower 
## 1.033998e-08 7.466720e-05 2.278336e-01 3.327039e-03 1.000000e+00</code></pre>
<p>Which of these are extreme? If it’s not clear by inspection (or too large), use a simple boolean:</p>
<div class="sourceCode" id="cb538"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb538-1" title="1">adjustedPvalues <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span></a></code></pre></div>
<pre><code>## horsebean   linseed  meatmeal   soybean sunflower 
##      TRUE      TRUE     FALSE      TRUE     FALSE</code></pre>
<p><strong>Fisher LSD</strong> This also doesn’t make adjustments for multiple comparisons. Notice how the p-values are no different than if using the <code>p.adjust="none"</code>. Fisher LSD is better than ‘none’ because it provides CI’s on the differences. Note: diff = difference between diet means.</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb540-1" title="1"><span class="co">#from the DescTools package</span></a>
<a class="sourceLine" id="cb540-2" title="2"><span class="kw">PostHocTest</span>(my.ezaov<span class="op">$</span>aov, <span class="dt">method =</span> <span class="st">&quot;lsd&quot;</span>)</a></code></pre></div>
<pre><code>## 
##   Posthoc multiple comparisons of means : Fisher LSD 
##     95% family-wise confidence level
## 
## $feed
##                            diff      lwr.ci       upr.ci    pval    
## horsebean-casein    -163.383333 -210.287097 -116.4795699 2.1e-09 ***
## linseed-casein      -104.833333 -149.554317  -60.1123496 1.5e-05 ***
## meatmeal-casein      -46.674242  -92.400318   -0.9481673 0.04557 *  
## soybean-casein       -77.154762 -120.248980  -34.0605437 0.00067 ***
## sunflower-casein       5.333333  -39.387650   50.0543170 0.81249    
## linseed-horsebean     58.550000   11.646237  105.4537634 0.01522 *  
## meatmeal-horsebean   116.709091   68.846051  164.5721307 7.5e-06 ***
## soybean-horsebean     86.228571   40.873216  131.5839270 0.00032 ***
## sunflower-horsebean  168.716667  121.812903  215.6204301 8.2e-10 ***
## meatmeal-linseed      58.159091   12.433016  103.8851660 0.01348 *  
## soybean-linseed       27.678571  -15.415647   70.7727896 0.20414    
## sunflower-linseed    110.166667   65.445683  154.8876504 6.2e-06 ***
## soybean-meatmeal     -30.480519  -74.616890   13.6558510 0.17255    
## sunflower-meatmeal    52.007576    6.281501   97.7336509 0.02644 *  
## sunflower-soybean     82.488095   39.393877  125.5823134 0.00030 ***
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>All of the following scripts do adjust p-values for multiple comparisons. Therefore, notice how they increase the p-values we see in the output above. Frequently, “significant” unadjusted p-values become “nonsignificant” after these adjustments.</p>
<div id="other-posthoc-tests" class="section level5">
<h5><span class="header-section-number">27.4.1.2.1</span> Other posthoc tests</h5>
<p><strong>Dunnett’s</strong>: This post hoc method differs from above because it only does dependent t tests, on a subset of the means. For example, use this when all group means are compared to the negative control mean.</p>
<p>The fewer comparisons don’t spread the allowed FWER as thin as the other options. The following script is configured to compare the means at each level of feed to that for the first listed feed.</p>
<p>Dunnett’s is nice because it gives you the effect size (diff) and the confidence interval limits for the difference, as well.</p>
<p>Note: diff = the difference between diet means for the compared groups.</p>
<p>Here’s an example comparing the weight effect of the various food sources back to casein. Adjusted for mulitple comparisons, horsebean, linseed and soybean each differ from casein.</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb542-1" title="1"><span class="kw">DunnettTest</span>(weight <span class="op">~</span><span class="st"> </span>feed, <span class="dt">data =</span> chickwts)</a></code></pre></div>
<pre><code>## 
##   Dunnett&#39;s test for comparing several treatments with a control :  
##     95% family-wise confidence level
## 
## $casein
##                         diff     lwr.ci     upr.ci    pval    
## horsebean-casein -163.383333 -223.95852 -102.80815 6.3e-09 ***
## linseed-casein   -104.833333 -162.58951  -47.07716 8.6e-05 ***
## meatmeal-casein   -46.674242 -105.72847   12.37999  0.1670    
## soybean-casein    -77.154762 -132.81000  -21.49952  0.0032 ** 
## sunflower-casein    5.333333  -52.42284   63.08951  0.9995    
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Tukey HSD</strong>: A method based upon the Studentized range, doing all comparisons, and providing adjusted p-values along with confidence intervals. Used when the question is, “Are there any group differences here at all?”</p>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb544-1" title="1"><span class="kw">TukeyHSD</span>(my.ezaov<span class="op">$</span>aov, <span class="st">&quot;feed&quot;</span>, <span class="dt">ordered =</span> T)</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
##     factor levels have been ordered
## 
## Fit: aov(formula = formula(aov_formula), data = data)
## 
## $feed
##                           diff        lwr       upr     p adj
## linseed-horsebean    58.550000 -10.413543 127.51354 0.1413329
## soybean-horsebean    86.228571  19.541684 152.91546 0.0042167
## meatmeal-horsebean  116.709091  46.335105 187.08308 0.0001062
## casein-horsebean    163.383333  94.419790 232.34688 0.0000000
## sunflower-horsebean 168.716667  99.753124 237.68021 0.0000000
## soybean-linseed      27.678571 -35.683721  91.04086 0.7932853
## meatmeal-linseed     58.159091  -9.072873 125.39106 0.1276965
## casein-linseed      104.833333  39.079175 170.58749 0.0002100
## sunflower-linseed   110.166667  44.412509 175.92082 0.0000884
## meatmeal-soybean     30.480519 -34.414070  95.37511 0.7391356
## casein-soybean       77.154762  13.792470 140.51705 0.0083653
## sunflower-soybean    82.488095  19.125803 145.85039 0.0038845
## casein-meatmeal      46.674242 -20.557722 113.90621 0.3324584
## sunflower-meatmeal   52.007576 -15.224388 119.23954 0.2206962
## sunflower-casein      5.333333 -60.420825  71.08749 0.9998902</code></pre>
<p><strong>Other</strong>: “BH” is Benjamini-Hochberg, an FDR-based tool that will gives you more positives at the risk of higher false positives. Use this when you have an excessive number of comparisons to make. For example, over-designed ANOVA, 3 way ANOVA, multivariate experiments. The BH procedure first ranks the differences between paired groups from largest to smallest, and then performs the tests, unadjusted, running down the list. It debits each p-value against a starting value of 0.05 (or whatever). Once that 0.05 is exhausted, it stops testing. In this way all of the type1 experimentwise error is spent on the biggest differences.</p>
</div>
</div>
</div>
</div>
<div id="reporting-the-result" class="section level2">
<h2><span class="header-section-number">27.5</span> Reporting the result</h2>
<p>Note how the R way is to subtract the 2nd group from the 1st. For this reason, the diff values are all negative, even though the feed sources caused higher growth than casein.</p>
<p><em>The effect of feed source accounted for 54% of the experiment’s observed variation in chick weights (one-way completely randomized ANOVA, type=2, F(5,65) = 15.365, p = 5.9e-10, ges=0.54. Pairwise group analysis using Dunnett’s test shows that horsebean (p=6.3e-9), linseed(p=8.6e-5) and soybean (p=0.0032) each differ from casein. (In methods: ANOVA analysis was performed using R v4.3, ez package).</em> (Note, it is better to put CI’s and p-values in a table)</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="fdistr.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="onewayRM.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["jabstb.pdf", "jabstb.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
