<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 22 The t-tests | JABSTB: Statistical Design and Analysis of Experiments with R</title>
  <meta name="description" content="Experimental biostatistics using R." />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 22 The t-tests | JABSTB: Statistical Design and Analysis of Experiments with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Experimental biostatistics using R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 22 The t-tests | JABSTB: Statistical Design and Analysis of Experiments with R" />
  
  <meta name="twitter:description" content="Experimental biostatistics using R." />
  

<meta name="author" content="TJ Murphy PhD, Department of Pharmacology and Chemical Biology, School of Medicine, Emory University, Atlanta, GA biostats538@gmail.com" />


<meta name="date" content="2020-02-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ranksum.html"/>
<link rel="next" href="ttestmc.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">JABSTB</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i><b>1</b> About the author and book</a></li>
<li class="chapter" data-level="2" data-path="history.html"><a href="history.html"><i class="fa fa-check"></i><b>2</b> A Brief History of Experimental Design</a></li>
<li class="chapter" data-level="3" data-path="software.html"><a href="software.html"><i class="fa fa-check"></i><b>3</b> Installing and Understanding the software</a><ul>
<li class="chapter" data-level="3.1" data-path="software.html"><a href="software.html#spring-2020-term-versions"><i class="fa fa-check"></i><b>3.1</b> Spring 2020 term versions</a><ul>
<li class="chapter" data-level="3.1.1" data-path="software.html"><a href="software.html#what-are-these"><i class="fa fa-check"></i><b>3.1.1</b> What are these?</a></li>
<li class="chapter" data-level="3.1.2" data-path="software.html"><a href="software.html#rule-1-install-r-first-install-rstudio-second"><i class="fa fa-check"></i><b>3.1.2</b> Rule 1: Install R first, install RStudio second</a></li>
<li class="chapter" data-level="3.1.3" data-path="software.html"><a href="software.html#rule-2-dont-pay"><i class="fa fa-check"></i><b>3.1.3</b> Rule 2: Don’t pay!</a></li>
<li class="chapter" data-level="3.1.4" data-path="software.html"><a href="software.html#rule-3-dont-compile"><i class="fa fa-check"></i><b>3.1.4</b> Rule 3: Don’t compile!</a></li>
<li class="chapter" data-level="3.1.5" data-path="software.html"><a href="software.html#rule-4-install-the-right-software-for-your-machine"><i class="fa fa-check"></i><b>3.1.5</b> Rule 4: Install the right software for your machine</a></li>
<li class="chapter" data-level="3.1.6" data-path="software.html"><a href="software.html#rule-5-use-this-installation-guide"><i class="fa fa-check"></i><b>3.1.6</b> Rule 5: Use this installation guide</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="software.html"><a href="software.html#after-installation"><i class="fa fa-check"></i><b>3.2</b> After installation</a><ul>
<li class="chapter" data-level="3.2.1" data-path="software.html"><a href="software.html#what-is-r"><i class="fa fa-check"></i><b>3.2.1</b> What is R?</a></li>
<li class="chapter" data-level="3.2.2" data-path="software.html"><a href="software.html#r-packages"><i class="fa fa-check"></i><b>3.2.2</b> R packages</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="software.html"><a href="software.html#important-avoid-compiling"><i class="fa fa-check"></i><b>3.3</b> Important: Avoid compiling</a><ul>
<li class="chapter" data-level="3.3.1" data-path="software.html"><a href="software.html#reasons-not-to-compile"><i class="fa fa-check"></i><b>3.3.1</b> Reasons not to compile</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>4</b> Start Learning R</a><ul>
<li class="chapter" data-level="4.1" data-path="getting-started.html"><a href="getting-started.html#digging-in-with-rrstudio"><i class="fa fa-check"></i><b>4.1</b> Digging in with R/RStudio</a></li>
<li class="chapter" data-level="4.2" data-path="getting-started.html"><a href="getting-started.html#the-tidyverse-package"><i class="fa fa-check"></i><b>4.2</b> The tidyverse package</a><ul>
<li class="chapter" data-level="4.2.1" data-path="getting-started.html"><a href="getting-started.html#do-swirlstats"><i class="fa fa-check"></i><b>4.2.1</b> Do swirlstats</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="getting-started.html"><a href="getting-started.html#other-resources"><i class="fa fa-check"></i><b>4.3</b> Other resources</a><ul>
<li class="chapter" data-level="4.3.1" data-path="getting-started.html"><a href="getting-started.html#internet-search"><i class="fa fa-check"></i><b>4.3.1</b> Internet search</a></li>
<li class="chapter" data-level="4.3.2" data-path="getting-started.html"><a href="getting-started.html#help-documents"><i class="fa fa-check"></i><b>4.3.2</b> Help Documents</a></li>
<li class="chapter" data-level="4.3.3" data-path="getting-started.html"><a href="getting-started.html#package-vignettes"><i class="fa fa-check"></i><b>4.3.3</b> Package Vignettes</a></li>
<li class="chapter" data-level="4.3.4" data-path="getting-started.html"><a href="getting-started.html#people"><i class="fa fa-check"></i><b>4.3.4</b> People</a></li>
<li class="chapter" data-level="4.3.5" data-path="getting-started.html"><a href="getting-started.html#typos"><i class="fa fa-check"></i><b>4.3.5</b> typos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="philos.html"><a href="philos.html"><i class="fa fa-check"></i><b>5</b> What is your philosophy?</a><ul>
<li class="chapter" data-level="5.1" data-path="philos.html"><a href="philos.html#exploration-and-uncertainty"><i class="fa fa-check"></i><b>5.1</b> Exploration and uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bigpic.html"><a href="bigpic.html"><i class="fa fa-check"></i><b>6</b> Stats: The Big Picture</a><ul>
<li class="chapter" data-level="6.1" data-path="bigpic.html"><a href="bigpic.html#what-are-experimental-statistics"><i class="fa fa-check"></i><b>6.1</b> What are experimental statistics?</a><ul>
<li class="chapter" data-level="6.1.1" data-path="bigpic.html"><a href="bigpic.html#descriptive-modeling"><i class="fa fa-check"></i><b>6.1.1</b> Descriptive modeling</a></li>
<li class="chapter" data-level="6.1.2" data-path="bigpic.html"><a href="bigpic.html#statistical-inference"><i class="fa fa-check"></i><b>6.1.2</b> Statistical inference</a></li>
<li class="chapter" data-level="6.1.3" data-path="bigpic.html"><a href="bigpic.html#experimental-design"><i class="fa fa-check"></i><b>6.1.3</b> Experimental design</a></li>
<li class="chapter" data-level="6.1.4" data-path="bigpic.html"><a href="bigpic.html#statistics-as-an-anti-bias-framework"><i class="fa fa-check"></i><b>6.1.4</b> Statistics as an anti-bias framework</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>7</b> Statistical Sampling</a><ul>
<li class="chapter" data-level="7.1" data-path="sampling.html"><a href="sampling.html#experimental-units"><i class="fa fa-check"></i><b>7.1</b> Experimental units</a><ul>
<li class="chapter" data-level="7.1.1" data-path="sampling.html"><a href="sampling.html#a-simple-test-to-define-the-experimental-unit"><i class="fa fa-check"></i><b>7.1.1</b> A simple test to define the experimental unit</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="sampling.html"><a href="sampling.html#independent-replicates"><i class="fa fa-check"></i><b>7.2</b> Independent Replicates</a><ul>
<li class="chapter" data-level="7.2.1" data-path="sampling.html"><a href="sampling.html#a-simple-test-for-independence"><i class="fa fa-check"></i><b>7.2.1</b> A simple test for independence</a></li>
<li class="chapter" data-level="7.2.2" data-path="sampling.html"><a href="sampling.html#some-replication-examples"><i class="fa fa-check"></i><b>7.2.2</b> Some replication examples</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sampling.html"><a href="sampling.html#random-process"><i class="fa fa-check"></i><b>7.3</b> Random process</a></li>
<li class="chapter" data-level="7.4" data-path="sampling.html"><a href="sampling.html#statistically-valid-samples"><i class="fa fa-check"></i><b>7.4</b> Statistically valid samples</a><ul>
<li class="chapter" data-level="7.4.1" data-path="sampling.html"><a href="sampling.html#select-random-subjects"><i class="fa fa-check"></i><b>7.4.1</b> Select random subjects</a></li>
<li class="chapter" data-level="7.4.2" data-path="sampling.html"><a href="sampling.html#randomize-to-sequence"><i class="fa fa-check"></i><b>7.4.2</b> Randomize to sequence</a></li>
<li class="chapter" data-level="7.4.3" data-path="sampling.html"><a href="sampling.html#randomize-to-location"><i class="fa fa-check"></i><b>7.4.3</b> Randomize to location</a></li>
<li class="chapter" data-level="7.4.4" data-path="sampling.html"><a href="sampling.html#randomize-to-block"><i class="fa fa-check"></i><b>7.4.4</b> Randomize to block</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sampling.html"><a href="sampling.html#independence-of-replicates"><i class="fa fa-check"></i><b>7.5</b> Independence of replicates</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>8</b> Data Classification</a><ul>
<li class="chapter" data-level="8.1" data-path="data.html"><a href="data.html#dependent-and-independent-variables"><i class="fa fa-check"></i><b>8.1</b> Dependent and independent variables</a><ul>
<li class="chapter" data-level="8.1.1" data-path="data.html"><a href="data.html#statistical-notation"><i class="fa fa-check"></i><b>8.1.1</b> Statistical notation</a></li>
<li class="chapter" data-level="8.1.2" data-path="data.html"><a href="data.html#when-there-is-no-independent-variable"><i class="fa fa-check"></i><b>8.1.2</b> When there is no independent variable</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="data.html"><a href="data.html#discrete-or-continuous-variables"><i class="fa fa-check"></i><b>8.2</b> Discrete or continuous variables</a><ul>
<li class="chapter" data-level="8.2.1" data-path="data.html"><a href="data.html#measured-variables"><i class="fa fa-check"></i><b>8.2.1</b> Measured variables</a></li>
<li class="chapter" data-level="8.2.2" data-path="data.html"><a href="data.html#discrete-categorical-and-ordinal-variables"><i class="fa fa-check"></i><b>8.2.2</b> Discrete categorical and ordinal variables</a></li>
<li class="chapter" data-level="8.2.3" data-path="data.html"><a href="data.html#rescaling-variables"><i class="fa fa-check"></i><b>8.2.3</b> Rescaling variables</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="data.html"><a href="data.html#working-with-data"><i class="fa fa-check"></i><b>8.3</b> Working with data</a><ul>
<li class="chapter" data-level="8.3.1" data-path="data.html"><a href="data.html#entering-data"><i class="fa fa-check"></i><b>8.3.1</b> Entering data</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="data.html"><a href="data.html#summary"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="dispersion.html"><a href="dispersion.html"><i class="fa fa-check"></i><b>9</b> Variability, Accuracy and Precision</a><ul>
<li class="chapter" data-level="9.0.1" data-path="dispersion.html"><a href="dispersion.html#data-are-messy"><i class="fa fa-check"></i><b>9.0.1</b> Data are messy</a></li>
<li class="chapter" data-level="9.1" data-path="dispersion.html"><a href="dispersion.html#illustration-of-a-model-with-error"><i class="fa fa-check"></i><b>9.1</b> Illustration of a model with error</a></li>
<li class="chapter" data-level="9.2" data-path="dispersion.html"><a href="dispersion.html#variance-quantifying-variation-by-least-squares"><i class="fa fa-check"></i><b>9.2</b> Variance: Quantifying variation by least squares</a><ul>
<li class="chapter" data-level="9.2.1" data-path="dispersion.html"><a href="dispersion.html#definition-of-variance"><i class="fa fa-check"></i><b>9.2.1</b> Definition of variance</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="dispersion.html"><a href="dispersion.html#standard-deviation"><i class="fa fa-check"></i><b>9.3</b> Standard deviation</a><ul>
<li class="chapter" data-level="9.3.1" data-path="dispersion.html"><a href="dispersion.html#what-does-the-standard-deviation-tell-us"><i class="fa fa-check"></i><b>9.3.1</b> What does the standard deviation tell us</a></li>
<li class="chapter" data-level="9.3.2" data-path="dispersion.html"><a href="dispersion.html#ways-of-describing-sample-variability"><i class="fa fa-check"></i><b>9.3.2</b> Ways of describing sample variability</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="dispersion.html"><a href="dispersion.html#precision-and-accuracy"><i class="fa fa-check"></i><b>9.4</b> Precision and Accuracy</a></li>
<li class="chapter" data-level="9.5" data-path="dispersion.html"><a href="dispersion.html#standard-error"><i class="fa fa-check"></i><b>9.5</b> Standard error</a><ul>
<li class="chapter" data-level="9.5.1" data-path="dispersion.html"><a href="dispersion.html#what-exactly-does-the-standard-error-represent"><i class="fa fa-check"></i><b>9.5.1</b> What exactly does the standard error represent?</a></li>
<li class="chapter" data-level="9.5.2" data-path="dispersion.html"><a href="dispersion.html#should-i-use-sd-or-sem"><i class="fa fa-check"></i><b>9.5.2</b> “Should I use SD or SEM?”</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="dispersion.html"><a href="dispersion.html#confidence-intervals"><i class="fa fa-check"></i><b>9.6</b> Confidence intervals</a><ul>
<li class="chapter" data-level="9.6.1" data-path="dispersion.html"><a href="dispersion.html#ci-definition"><i class="fa fa-check"></i><b>9.6.1</b> CI Definition</a></li>
<li class="chapter" data-level="9.6.2" data-path="dispersion.html"><a href="dispersion.html#evaluating-confidence-intervals"><i class="fa fa-check"></i><b>9.6.2</b> Evaluating confidence intervals</a></li>
<li class="chapter" data-level="9.6.3" data-path="dispersion.html"><a href="dispersion.html#ci-simulation-tools"><i class="fa fa-check"></i><b>9.6.3</b> CI Simulation tools</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="dispersion.html"><a href="dispersion.html#key-take-aways"><i class="fa fa-check"></i><b>9.7</b> Key take aways</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>10</b> Framing statistical hypotheses</a><ul>
<li class="chapter" data-level="10.1" data-path="hypotheses.html"><a href="hypotheses.html#the-decision-process"><i class="fa fa-check"></i><b>10.1</b> The decision process</a></li>
<li class="chapter" data-level="10.2" data-path="hypotheses.html"><a href="hypotheses.html#popper-and-falsification"><i class="fa fa-check"></i><b>10.2</b> Popper and falsification</a></li>
<li class="chapter" data-level="10.3" data-path="hypotheses.html"><a href="hypotheses.html#statistical-hypothesis-rubric"><i class="fa fa-check"></i><b>10.3</b> Statistical hypothesis rubric</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="error.html"><a href="error.html"><i class="fa fa-check"></i><b>11</b> Error</a><ul>
<li class="chapter" data-level="11.1" data-path="error.html"><a href="error.html#setting-type-1-and-type-2-error-thresholds"><i class="fa fa-check"></i><b>11.1</b> Setting type 1 and type 2 error thresholds</a><ul>
<li class="chapter" data-level="11.1.1" data-path="error.html"><a href="error.html#setting-alpha-the-type-1-error"><i class="fa fa-check"></i><b>11.1.1</b> Setting alpha-the type 1 error</a></li>
<li class="chapter" data-level="11.1.2" data-path="error.html"><a href="error.html#power-setting-beta-the-type-2-error"><i class="fa fa-check"></i><b>11.1.2</b> Power: Setting beta-the type 2 error</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="error.html"><a href="error.html#striking-the-right-balance"><i class="fa fa-check"></i><b>11.2</b> Striking the right balance</a></li>
<li class="chapter" data-level="11.3" data-path="error.html"><a href="error.html#false-discovery-rate"><i class="fa fa-check"></i><b>11.3</b> False discovery rate</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="pvalues.html"><a href="pvalues.html"><i class="fa fa-check"></i><b>12</b> P Values</a><ul>
<li class="chapter" data-level="12.1" data-path="pvalues.html"><a href="pvalues.html#definition"><i class="fa fa-check"></i><b>12.1</b> Definition</a></li>
<li class="chapter" data-level="12.2" data-path="pvalues.html"><a href="pvalues.html#test-statistics-come-from-null-distributions"><i class="fa fa-check"></i><b>12.2</b> Test statistics come from null distributions</a><ul>
<li class="chapter" data-level="12.2.1" data-path="pvalues.html"><a href="pvalues.html#p-value-behavior"><i class="fa fa-check"></i><b>12.2.1</b> P-value behavior</a></li>
<li class="chapter" data-level="12.2.2" data-path="pvalues.html"><a href="pvalues.html#p-values-and-the-decision-process"><i class="fa fa-check"></i><b>12.2.2</b> P-values and the decision process</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="pvalues.html"><a href="pvalues.html#a-blood-glucose-p-value"><i class="fa fa-check"></i><b>12.3</b> A blood glucose p-value</a></li>
<li class="chapter" data-level="12.4" data-path="pvalues.html"><a href="pvalues.html#how-p-values-should-be-interpreted"><i class="fa fa-check"></i><b>12.4</b> How p-values should be interpreted</a></li>
<li class="chapter" data-level="12.5" data-path="pvalues.html"><a href="pvalues.html#interpretation"><i class="fa fa-check"></i><b>12.5</b> Interpretation</a></li>
<li class="chapter" data-level="12.6" data-path="pvalues.html"><a href="pvalues.html#criticisms-of-p-values"><i class="fa fa-check"></i><b>12.6</b> Criticisms of p-values</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="jaxwest7.html"><a href="jaxwest7.html"><i class="fa fa-check"></i><b>13</b> Reproducible Data Munging in R</a><ul>
<li class="chapter" data-level="13.1" data-path="jaxwest7.html"><a href="jaxwest7.html#jaxwest7-glucose-data"><i class="fa fa-check"></i><b>13.1</b> Jaxwest7 glucose data</a><ul>
<li class="chapter" data-level="13.1.1" data-path="jaxwest7.html"><a href="jaxwest7.html#inspect-the-jaxwest7-data"><i class="fa fa-check"></i><b>13.1.1</b> Inspect the Jaxwest7 data</a></li>
<li class="chapter" data-level="13.1.2" data-path="jaxwest7.html"><a href="jaxwest7.html#munge-the-glucose-concentration-data-into-r"><i class="fa fa-check"></i><b>13.1.2</b> Munge the glucose concentration data into R</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="jaxwest7.html"><a href="jaxwest7.html#explore-the-jaxwest7-data"><i class="fa fa-check"></i><b>13.2</b> Explore the Jaxwest7 data</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="binomial.html"><a href="binomial.html"><i class="fa fa-check"></i><b>14</b> The Binomial Distribution</a><ul>
<li class="chapter" data-level="14.1" data-path="binomial.html"><a href="binomial.html#dbinom"><i class="fa fa-check"></i><b>14.1</b> dbinom</a></li>
<li class="chapter" data-level="14.2" data-path="binomial.html"><a href="binomial.html#pbinom"><i class="fa fa-check"></i><b>14.2</b> pbinom</a></li>
<li class="chapter" data-level="14.3" data-path="binomial.html"><a href="binomial.html#qbinom"><i class="fa fa-check"></i><b>14.3</b> qbinom</a></li>
<li class="chapter" data-level="14.4" data-path="binomial.html"><a href="binomial.html#rbinom"><i class="fa fa-check"></i><b>14.4</b> rbinom</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="poisson.html"><a href="poisson.html"><i class="fa fa-check"></i><b>15</b> The Poisson Distribution</a><ul>
<li class="chapter" data-level="15.1" data-path="poisson.html"><a href="poisson.html#poisson-events"><i class="fa fa-check"></i><b>15.1</b> Poisson Events</a></li>
<li class="chapter" data-level="15.2" data-path="poisson.html"><a href="poisson.html#dpois"><i class="fa fa-check"></i><b>15.2</b> dpois</a></li>
<li class="chapter" data-level="15.3" data-path="poisson.html"><a href="poisson.html#ppois"><i class="fa fa-check"></i><b>15.3</b> ppois</a></li>
<li class="chapter" data-level="15.4" data-path="poisson.html"><a href="poisson.html#qpois"><i class="fa fa-check"></i><b>15.4</b> qpois</a></li>
<li class="chapter" data-level="15.5" data-path="poisson.html"><a href="poisson.html#rpois"><i class="fa fa-check"></i><b>15.5</b> rpois</a></li>
<li class="chapter" data-level="15.6" data-path="poisson.html"><a href="poisson.html#overdispersion"><i class="fa fa-check"></i><b>15.6</b> Overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="normal.html"><a href="normal.html"><i class="fa fa-check"></i><b>16</b> The Normal Distribution</a><ul>
<li class="chapter" data-level="16.0.1" data-path="normal.html"><a href="normal.html#the-standard-normal"><i class="fa fa-check"></i><b>16.0.1</b> The Standard Normal</a></li>
<li class="chapter" data-level="16.1" data-path="normal.html"><a href="normal.html#dnorm"><i class="fa fa-check"></i><b>16.1</b> dnorm</a></li>
<li class="chapter" data-level="16.2" data-path="normal.html"><a href="normal.html#pnorm"><i class="fa fa-check"></i><b>16.2</b> pnorm</a><ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#calculating-p-values-using-pnorm"><i class="fa fa-check"></i>Calculating “p-values”" using pnorm</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#calculating-percentiles-using-pnorm"><i class="fa fa-check"></i>Calculating percentiles using pnorm</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="normal.html"><a href="normal.html#qnorm"><i class="fa fa-check"></i><b>16.3</b> qnorm</a></li>
<li class="chapter" data-level="16.4" data-path="normal.html"><a href="normal.html#rnorm"><i class="fa fa-check"></i><b>16.4</b> rnorm</a><ul>
<li class="chapter" data-level="16.4.1" data-path="normal.html"><a href="normal.html#plotting-histograms-of-some-rnorm-samples"><i class="fa fa-check"></i><b>16.4.1</b> Plotting histograms of some rnorm samples</a></li>
<li class="chapter" data-level="16.4.2" data-path="normal.html"><a href="normal.html#bins-and-binwidth"><i class="fa fa-check"></i><b>16.4.2</b> Bins and Binwidth</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="categorical.html"><a href="categorical.html"><i class="fa fa-check"></i><b>17</b> Statistics for Categorical Data</a><ul>
<li class="chapter" data-level="17.1" data-path="categorical.html"><a href="categorical.html#types-of-categorical-data"><i class="fa fa-check"></i><b>17.1</b> Types of categorical data</a><ul>
<li class="chapter" data-level="17.1.1" data-path="categorical.html"><a href="categorical.html#proportions"><i class="fa fa-check"></i><b>17.1.1</b> Proportions</a></li>
<li class="chapter" data-level="17.1.2" data-path="categorical.html"><a href="categorical.html#frequencies"><i class="fa fa-check"></i><b>17.1.2</b> Frequencies</a></li>
<li class="chapter" data-level="17.1.3" data-path="categorical.html"><a href="categorical.html#associations"><i class="fa fa-check"></i><b>17.1.3</b> Associations</a></li>
<li class="chapter" data-level="17.1.4" data-path="categorical.html"><a href="categorical.html#statistics-covered-here"><i class="fa fa-check"></i><b>17.1.4</b> Statistics Covered Here</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="categorical.html"><a href="categorical.html#exact-v-asymptotic-calculations-of-p-values"><i class="fa fa-check"></i><b>17.2</b> Exact v Asymptotic Calculations of p-values</a><ul>
<li class="chapter" data-level="17.2.1" data-path="categorical.html"><a href="categorical.html#choosing-exact-or-asymptotic"><i class="fa fa-check"></i><b>17.2.1</b> Choosing exact or asymptotic</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="categorical.html"><a href="categorical.html#overview-of-the-types-of-hypothesis-testing"><i class="fa fa-check"></i><b>17.3</b> Overview of the types of hypothesis testing</a><ul>
<li class="chapter" data-level="17.3.1" data-path="categorical.html"><a href="categorical.html#proportion-analysis"><i class="fa fa-check"></i><b>17.3.1</b> Proportion analysis</a></li>
<li class="chapter" data-level="17.3.2" data-path="categorical.html"><a href="categorical.html#goodness-of-fit-testing"><i class="fa fa-check"></i><b>17.3.2</b> Goodness of fit testing</a></li>
<li class="chapter" data-level="17.3.3" data-path="categorical.html"><a href="categorical.html#contingency-analysis"><i class="fa fa-check"></i><b>17.3.3</b> Contingency Analysis</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="categorical.html"><a href="categorical.html#comparing-proportions"><i class="fa fa-check"></i><b>17.4</b> Comparing proportions</a><ul>
<li class="chapter" data-level="17.4.1" data-path="categorical.html"><a href="categorical.html#a-mouse-t-cell-pilot-experiment-the-cytokine-inducible-antigen-gradstudin"><i class="fa fa-check"></i><b>17.4.1</b> A Mouse T Cell Pilot Experiment: The Cytokine-inducible antigen gradstudin</a></li>
<li class="chapter" data-level="17.4.2" data-path="categorical.html"><a href="categorical.html#calculating-proportions"><i class="fa fa-check"></i><b>17.4.2</b> Calculating Proportions</a></li>
<li class="chapter" data-level="17.4.3" data-path="categorical.html"><a href="categorical.html#what-a-proportion-estimates"><i class="fa fa-check"></i><b>17.4.3</b> What A Proportion Estimates</a></li>
<li class="chapter" data-level="17.4.4" data-path="categorical.html"><a href="categorical.html#confidence-intervals-of-proportions"><i class="fa fa-check"></i><b>17.4.4</b> Confidence Intervals of Proportions</a></li>
<li class="chapter" data-level="17.4.5" data-path="categorical.html"><a href="categorical.html#a-one-sample-proportion-test"><i class="fa fa-check"></i><b>17.4.5</b> A One-Sample Proportion Test</a></li>
<li class="chapter" data-level="17.4.6" data-path="categorical.html"><a href="categorical.html#an-exact-test-for-one-proportion"><i class="fa fa-check"></i><b>17.4.6</b> An exact test for one proportion</a></li>
<li class="chapter" data-level="17.4.7" data-path="categorical.html"><a href="categorical.html#comparing-two-proportions"><i class="fa fa-check"></i><b>17.4.7</b> Comparing Two Proportions</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="categorical.html"><a href="categorical.html#exact-tests-for-two-proportions"><i class="fa fa-check"></i><b>17.5</b> Exact tests for two proportions</a></li>
<li class="chapter" data-level="17.6" data-path="categorical.html"><a href="categorical.html#goodness-of-fit-tests"><i class="fa fa-check"></i><b>17.6</b> Goodness of fit Tests</a><ul>
<li class="chapter" data-level="17.6.1" data-path="categorical.html"><a href="categorical.html#an-exact-goodness-of-fit-test"><i class="fa fa-check"></i><b>17.6.1</b> An Exact Goodness of Fit test</a></li>
<li class="chapter" data-level="17.6.2" data-path="categorical.html"><a href="categorical.html#an-approximate-goodness-of-fit-test"><i class="fa fa-check"></i><b>17.6.2</b> An Approximate Goodness of Fit test</a></li>
</ul></li>
<li class="chapter" data-level="17.7" data-path="categorical.html"><a href="categorical.html#contingency-testing"><i class="fa fa-check"></i><b>17.7</b> Contingency Testing</a><ul>
<li class="chapter" data-level="17.7.1" data-path="categorical.html"><a href="categorical.html#interpretation-of-contingency-results"><i class="fa fa-check"></i><b>17.7.1</b> Interpretation of Contingency Results</a></li>
<li class="chapter" data-level="17.7.2" data-path="categorical.html"><a href="categorical.html#write-up-4"><i class="fa fa-check"></i><b>17.7.2</b> Write Up</a></li>
<li class="chapter" data-level="17.7.3" data-path="categorical.html"><a href="categorical.html#interpretation-of-chi-square-output"><i class="fa fa-check"></i><b>17.7.3</b> Interpretation of chi-square output</a></li>
<li class="chapter" data-level="17.7.4" data-path="categorical.html"><a href="categorical.html#write-up-5"><i class="fa fa-check"></i><b>17.7.4</b> Write Up</a></li>
<li class="chapter" data-level="17.7.5" data-path="categorical.html"><a href="categorical.html#which-contingency-test-is-best"><i class="fa fa-check"></i><b>17.7.5</b> Which contingency test is best?</a></li>
<li class="chapter" data-level="17.7.6" data-path="categorical.html"><a href="categorical.html#higher-dimension-contingency-analysis"><i class="fa fa-check"></i><b>17.7.6</b> Higher dimension contingency analysis</a></li>
<li class="chapter" data-level="17.7.7" data-path="categorical.html"><a href="categorical.html#other-experimental-designs-involving-categorical-data"><i class="fa fa-check"></i><b>17.7.7</b> Other experimental designs involving categorical data</a></li>
</ul></li>
<li class="chapter" data-level="17.8" data-path="categorical.html"><a href="categorical.html#power-analysis-for-proportion-tests"><i class="fa fa-check"></i><b>17.8</b> Power analysis for proportion tests</a></li>
<li class="chapter" data-level="17.9" data-path="categorical.html"><a href="categorical.html#power-analysis-functions-for-proportion-tests"><i class="fa fa-check"></i><b>17.9</b> Power analysis functions for proportion tests</a></li>
<li class="chapter" data-level="17.10" data-path="categorical.html"><a href="categorical.html#graphing-proportions"><i class="fa fa-check"></i><b>17.10</b> Graphing Proportions</a></li>
<li class="chapter" data-level="17.11" data-path="categorical.html"><a href="categorical.html#key-takeaways"><i class="fa fa-check"></i><b>17.11</b> Key Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chisquare.html"><a href="chisquare.html"><i class="fa fa-check"></i><b>18</b> The Chi-square Distribution</a><ul>
<li class="chapter" data-level="18.1" data-path="chisquare.html"><a href="chisquare.html#background"><i class="fa fa-check"></i><b>18.1</b> Background</a></li>
<li class="chapter" data-level="18.2" data-path="chisquare.html"><a href="chisquare.html#dchisq"><i class="fa fa-check"></i><b>18.2</b> dchisq</a></li>
<li class="chapter" data-level="18.3" data-path="chisquare.html"><a href="chisquare.html#pchisq"><i class="fa fa-check"></i><b>18.3</b> pchisq</a><ul>
<li class="chapter" data-level="18.3.1" data-path="chisquare.html"><a href="chisquare.html#calculating-p-values-from-pchisq"><i class="fa fa-check"></i><b>18.3.1</b> Calculating p-values from pchisq</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="chisquare.html"><a href="chisquare.html#qchisq"><i class="fa fa-check"></i><b>18.4</b> qchisq</a></li>
<li class="chapter" data-level="18.5" data-path="chisquare.html"><a href="chisquare.html#rchisq"><i class="fa fa-check"></i><b>18.5</b> rchisq</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="nonparametrics.html"><a href="nonparametrics.html"><i class="fa fa-check"></i><b>19</b> Nonparametric Statistical Tests</a><ul>
<li class="chapter" data-level="19.1" data-path="nonparametrics.html"><a href="nonparametrics.html#nonparametric-sampling-distributions"><i class="fa fa-check"></i><b>19.1</b> Nonparametric sampling distributions</a></li>
<li class="chapter" data-level="19.2" data-path="nonparametrics.html"><a href="nonparametrics.html#experiments-involving-discrete-data"><i class="fa fa-check"></i><b>19.2</b> Experiments involving discrete data</a><ul>
<li class="chapter" data-level="19.2.1" data-path="nonparametrics.html"><a href="nonparametrics.html#ordered-data-1"><i class="fa fa-check"></i><b>19.2.1</b> Ordered data</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="nonparametrics.html"><a href="nonparametrics.html#experiments-involving-deviant-data"><i class="fa fa-check"></i><b>19.3</b> Experiments involving deviant Data</a></li>
<li class="chapter" data-level="19.4" data-path="nonparametrics.html"><a href="nonparametrics.html#sign-test"><i class="fa fa-check"></i><b>19.4</b> Sign Test</a><ul>
<li class="chapter" data-level="19.4.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-1"><i class="fa fa-check"></i><b>19.4.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.4.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-6"><i class="fa fa-check"></i><b>19.4.2</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-test-for-one-group"><i class="fa fa-check"></i><b>19.5</b> Wilcoxon Sign Rank Test for One Group</a><ul>
<li class="chapter" data-level="19.5.1" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-experimental-designs"><i class="fa fa-check"></i><b>19.5.1</b> Wilcoxon Sign Rank Experimental Designs</a></li>
<li class="chapter" data-level="19.5.2" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-2"><i class="fa fa-check"></i><b>19.5.2</b> Interpretation</a></li>
<li class="chapter" data-level="19.5.3" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-7"><i class="fa fa-check"></i><b>19.5.3</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-mann-whitney-rank-sum-test-for-2-independent-groups"><i class="fa fa-check"></i><b>19.6</b> Wilcoxon Mann Whitney Rank Sum Test for 2 independent groups</a><ul>
<li class="chapter" data-level="19.6.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-3"><i class="fa fa-check"></i><b>19.6.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.6.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-8"><i class="fa fa-check"></i><b>19.6.2</b> Write Up</a></li>
<li class="chapter" data-level="19.6.3" data-path="nonparametrics.html"><a href="nonparametrics.html#plot"><i class="fa fa-check"></i><b>19.6.3</b> Plot</a></li>
</ul></li>
<li class="chapter" data-level="19.7" data-path="nonparametrics.html"><a href="nonparametrics.html#wilcoxon-sign-rank-test-for-paired-groups"><i class="fa fa-check"></i><b>19.7</b> Wilcoxon Sign Rank Test for paired groups</a><ul>
<li class="chapter" data-level="19.7.1" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-4"><i class="fa fa-check"></i><b>19.7.1</b> Interpretation</a></li>
<li class="chapter" data-level="19.7.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-9"><i class="fa fa-check"></i><b>19.7.2</b> Write up</a></li>
<li class="chapter" data-level="19.7.3" data-path="nonparametrics.html"><a href="nonparametrics.html#plot-1"><i class="fa fa-check"></i><b>19.7.3</b> Plot</a></li>
</ul></li>
<li class="chapter" data-level="19.8" data-path="nonparametrics.html"><a href="nonparametrics.html#kruskal-wallis"><i class="fa fa-check"></i><b>19.8</b> Kruskal-Wallis</a><ul>
<li class="chapter" data-level="19.8.1" data-path="nonparametrics.html"><a href="nonparametrics.html#the-experimental-design"><i class="fa fa-check"></i><b>19.8.1</b> The experimental design</a></li>
<li class="chapter" data-level="19.8.2" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-10"><i class="fa fa-check"></i><b>19.8.2</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="19.9" data-path="nonparametrics.html"><a href="nonparametrics.html#friedman-test"><i class="fa fa-check"></i><b>19.9</b> Friedman test</a><ul>
<li class="chapter" data-level="19.9.1" data-path="nonparametrics.html"><a href="nonparametrics.html#blocked-experimental-design"><i class="fa fa-check"></i><b>19.9.1</b> Blocked experimental design</a></li>
<li class="chapter" data-level="19.9.2" data-path="nonparametrics.html"><a href="nonparametrics.html#interpretation-5"><i class="fa fa-check"></i><b>19.9.2</b> Interpretation</a></li>
<li class="chapter" data-level="19.9.3" data-path="nonparametrics.html"><a href="nonparametrics.html#write-up-11"><i class="fa fa-check"></i><b>19.9.3</b> Write up</a></li>
</ul></li>
<li class="chapter" data-level="19.10" data-path="nonparametrics.html"><a href="nonparametrics.html#nonparametric-power-calculations"><i class="fa fa-check"></i><b>19.10</b> Nonparametric power calculations</a><ul>
<li class="chapter" data-level="19.10.1" data-path="nonparametrics.html"><a href="nonparametrics.html#how-it-works"><i class="fa fa-check"></i><b>19.10.1</b> How it works</a></li>
<li class="chapter" data-level="19.10.2" data-path="nonparametrics.html"><a href="nonparametrics.html#simulating-response-data"><i class="fa fa-check"></i><b>19.10.2</b> Simulating response data</a></li>
<li class="chapter" data-level="19.10.3" data-path="nonparametrics.html"><a href="nonparametrics.html#an-example"><i class="fa fa-check"></i><b>19.10.3</b> An example</a></li>
<li class="chapter" data-level="19.10.4" data-path="nonparametrics.html"><a href="nonparametrics.html#nonpara.pwr"><i class="fa fa-check"></i><b>19.10.4</b> nonpara.pwr</a></li>
</ul></li>
<li class="chapter" data-level="19.11" data-path="nonparametrics.html"><a href="nonparametrics.html#summary-1"><i class="fa fa-check"></i><b>19.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="signrank.html"><a href="signrank.html"><i class="fa fa-check"></i><b>20</b> Signed Rank Distribution</a><ul>
<li class="chapter" data-level="20.1" data-path="signrank.html"><a href="signrank.html#transformation-of-data-into-sign-ranks"><i class="fa fa-check"></i><b>20.1</b> Transformation of data into sign ranks</a><ul>
<li class="chapter" data-level="20.1.1" data-path="signrank.html"><a href="signrank.html#for-a-one-group-sample"><i class="fa fa-check"></i><b>20.1.1</b> For a one group sample</a></li>
<li class="chapter" data-level="20.1.2" data-path="signrank.html"><a href="signrank.html#for-a-paired-sample"><i class="fa fa-check"></i><b>20.1.2</b> For a paired sample</a></li>
<li class="chapter" data-level="20.1.3" data-path="signrank.html"><a href="signrank.html#the-sign-rank-test-statistic-in-r"><i class="fa fa-check"></i><b>20.1.3</b> The sign rank test statistic in R</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="signrank.html"><a href="signrank.html#rs-four-sign-rank-distribution-functions"><i class="fa fa-check"></i><b>20.2</b> R’s Four Sign Rank Distribution Functions</a><ul>
<li class="chapter" data-level="20.2.1" data-path="signrank.html"><a href="signrank.html#dsignrank"><i class="fa fa-check"></i><b>20.2.1</b> dsignrank</a></li>
<li class="chapter" data-level="20.2.2" data-path="signrank.html"><a href="signrank.html#psignrank"><i class="fa fa-check"></i><b>20.2.2</b> psignrank</a></li>
<li class="chapter" data-level="20.2.3" data-path="signrank.html"><a href="signrank.html#qsignrank"><i class="fa fa-check"></i><b>20.2.3</b> qsignrank</a></li>
<li class="chapter" data-level="20.2.4" data-path="signrank.html"><a href="signrank.html#rsignrank"><i class="fa fa-check"></i><b>20.2.4</b> rsignrank</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="ranksum.html"><a href="ranksum.html"><i class="fa fa-check"></i><b>21</b> Rank Sum Distribution</a><ul>
<li class="chapter" data-level="21.0.1" data-path="ranksum.html"><a href="ranksum.html#transformation-of-data-into-rank-summs"><i class="fa fa-check"></i><b>21.0.1</b> Transformation of data into rank summs</a></li>
<li class="chapter" data-level="21.0.2" data-path="ranksum.html"><a href="ranksum.html#the-sign-rank-test-statistic-in-r-1"><i class="fa fa-check"></i><b>21.0.2</b> The sign rank test statistic in R</a></li>
<li class="chapter" data-level="21.1" data-path="ranksum.html"><a href="ranksum.html#rs-four-sign-rank-distribution-functions-1"><i class="fa fa-check"></i><b>21.1</b> R’s Four Sign Rank Distribution Functions</a><ul>
<li class="chapter" data-level="21.1.1" data-path="ranksum.html"><a href="ranksum.html#dwilcox"><i class="fa fa-check"></i><b>21.1.1</b> dwilcox</a></li>
<li class="chapter" data-level="21.1.2" data-path="ranksum.html"><a href="ranksum.html#pwilcox"><i class="fa fa-check"></i><b>21.1.2</b> pwilcox</a></li>
<li class="chapter" data-level="21.1.3" data-path="ranksum.html"><a href="ranksum.html#qwilcox"><i class="fa fa-check"></i><b>21.1.3</b> qwilcox</a></li>
<li class="chapter" data-level="21.1.4" data-path="ranksum.html"><a href="ranksum.html#rwilcox"><i class="fa fa-check"></i><b>21.1.4</b> rwilcox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="ttests.html"><a href="ttests.html"><i class="fa fa-check"></i><b>22</b> The t-tests</a><ul>
<li class="chapter" data-level="22.1" data-path="ttests.html"><a href="ttests.html#data-assumptions-for-t-tests"><i class="fa fa-check"></i><b>22.1</b> Data assumptions for t-tests</a></li>
<li class="chapter" data-level="22.2" data-path="ttests.html"><a href="ttests.html#the-t-statistic"><i class="fa fa-check"></i><b>22.2</b> The t Statistic</a><ul>
<li class="chapter" data-level="22.2.1" data-path="ttests.html"><a href="ttests.html#one-sample-t-tests"><i class="fa fa-check"></i><b>22.2.1</b> One sample t tests</a></li>
<li class="chapter" data-level="22.2.2" data-path="ttests.html"><a href="ttests.html#unpaired-t-tests"><i class="fa fa-check"></i><b>22.2.2</b> Unpaired t tests</a></li>
<li class="chapter" data-level="22.2.3" data-path="ttests.html"><a href="ttests.html#paired-t-tests"><i class="fa fa-check"></i><b>22.2.3</b> Paired t tests</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="ttests.html"><a href="ttests.html#t-test-hypotheses"><i class="fa fa-check"></i><b>22.3</b> t Test Hypotheses</a><ul>
<li class="chapter" data-level="22.3.1" data-path="ttests.html"><a href="ttests.html#one-sample-hypotheses"><i class="fa fa-check"></i><b>22.3.1</b> One sample hypotheses</a></li>
<li class="chapter" data-level="22.3.2" data-path="ttests.html"><a href="ttests.html#unpaired-hypotheses"><i class="fa fa-check"></i><b>22.3.2</b> Unpaired hypotheses</a></li>
<li class="chapter" data-level="22.3.3" data-path="ttests.html"><a href="ttests.html#paired-hypotheses"><i class="fa fa-check"></i><b>22.3.3</b> Paired hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="ttests.html"><a href="ttests.html#confidence-intervals-of-means"><i class="fa fa-check"></i><b>22.4</b> Confidence Intervals of Means</a></li>
<li class="chapter" data-level="22.5" data-path="ttests.html"><a href="ttests.html#parameters-small-samples-and-reliability"><i class="fa fa-check"></i><b>22.5</b> Parameters, small samples, and reliability</a><ul>
<li class="chapter" data-level="22.5.1" data-path="ttests.html"><a href="ttests.html#reporting-sd-or-sem"><i class="fa fa-check"></i><b>22.5.1</b> Reporting SD or SEM?</a></li>
</ul></li>
<li class="chapter" data-level="22.6" data-path="ttests.html"><a href="ttests.html#t-tests-running-the-analysis"><i class="fa fa-check"></i><b>22.6</b> t Tests: Running the analysis</a><ul>
<li class="chapter" data-level="22.6.1" data-path="ttests.html"><a href="ttests.html#one-sample-t-test"><i class="fa fa-check"></i><b>22.6.1</b> One sample t test</a></li>
<li class="chapter" data-level="22.6.2" data-path="ttests.html"><a href="ttests.html#unpaired-t-test"><i class="fa fa-check"></i><b>22.6.2</b> Unpaired t test</a></li>
<li class="chapter" data-level="22.6.3" data-path="ttests.html"><a href="ttests.html#paired-t-test"><i class="fa fa-check"></i><b>22.6.3</b> Paired t Test</a></li>
</ul></li>
<li class="chapter" data-level="22.7" data-path="ttests.html"><a href="ttests.html#plotting-t-tests"><i class="fa fa-check"></i><b>22.7</b> Plotting t Tests</a><ul>
<li class="chapter" data-level="22.7.1" data-path="ttests.html"><a href="ttests.html#unpaired"><i class="fa fa-check"></i><b>22.7.1</b> Unpaired</a></li>
<li class="chapter" data-level="22.7.2" data-path="ttests.html"><a href="ttests.html#paired"><i class="fa fa-check"></i><b>22.7.2</b> Paired</a></li>
</ul></li>
<li class="chapter" data-level="22.8" data-path="ttests.html"><a href="ttests.html#t-test-power"><i class="fa fa-check"></i><b>22.8</b> t Test Power</a><ul>
<li class="chapter" data-level="22.8.1" data-path="ttests.html"><a href="ttests.html#interpretation-9"><i class="fa fa-check"></i><b>22.8.1</b> Interpretation</a></li>
</ul></li>
<li class="chapter" data-level="22.9" data-path="ttests.html"><a href="ttests.html#summary-2"><i class="fa fa-check"></i><b>22.9</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="ttestmc.html"><a href="ttestmc.html"><i class="fa fa-check"></i><b>23</b> Statistical design of t-tests</a><ul>
<li class="chapter" data-level="23.1" data-path="ttestmc.html"><a href="ttestmc.html#about-this-chapter"><i class="fa fa-check"></i><b>23.1</b> About this chapter</a><ul>
<li class="chapter" data-level="23.1.1" data-path="ttestmc.html"><a href="ttestmc.html#overview"><i class="fa fa-check"></i><b>23.1.1</b> Overview</a></li>
<li class="chapter" data-level="23.1.2" data-path="ttestmc.html"><a href="ttestmc.html#simulating-data"><i class="fa fa-check"></i><b>23.1.2</b> Simulating data</a></li>
<li class="chapter" data-level="23.1.3" data-path="ttestmc.html"><a href="ttestmc.html#change-n-to-zero-in-on-the-power-you-want"><i class="fa fa-check"></i><b>23.1.3</b> Change n to zero in on the power you want</a></li>
<li class="chapter" data-level="23.1.4" data-path="ttestmc.html"><a href="ttestmc.html#scenario"><i class="fa fa-check"></i><b>23.1.4</b> Scenario</a></li>
<li class="chapter" data-level="23.1.5" data-path="ttestmc.html"><a href="ttestmc.html#what-would-be-a-scientifically-meaningful-response"><i class="fa fa-check"></i><b>23.1.5</b> What would be a scientifically meaningful response?</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="ttestmc.html"><a href="ttestmc.html#one-sample-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.2</b> One sample t-test Monte Carlo</a></li>
<li class="chapter" data-level="23.3" data-path="ttestmc.html"><a href="ttestmc.html#unpaired-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.3</b> Unpaired t-test Monte Carlo</a></li>
<li class="chapter" data-level="23.4" data-path="ttestmc.html"><a href="ttestmc.html#paired-t-test-monte-carlo"><i class="fa fa-check"></i><b>23.4</b> Paired t-test Monte Carlo</a></li>
<li class="chapter" data-level="23.5" data-path="ttestmc.html"><a href="ttestmc.html#dt"><i class="fa fa-check"></i><b>23.5</b> dt</a></li>
<li class="chapter" data-level="23.6" data-path="ttestmc.html"><a href="ttestmc.html#pt"><i class="fa fa-check"></i><b>23.6</b> pt</a></li>
<li class="chapter" data-level="23.7" data-path="ttestmc.html"><a href="ttestmc.html#qt"><i class="fa fa-check"></i><b>23.7</b> qt</a></li>
<li class="chapter" data-level="23.8" data-path="ttestmc.html"><a href="ttestmc.html#rt"><i class="fa fa-check"></i><b>23.8</b> rt</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="simcorrelation.html"><a href="simcorrelation.html"><i class="fa fa-check"></i><b>24</b> Simulating correlated variables</a><ul>
<li class="chapter" data-level="24.1" data-path="simcorrelation.html"><a href="simcorrelation.html#estimating-correlation-between-two-variables"><i class="fa fa-check"></i><b>24.1</b> Estimating correlation between two variables</a></li>
<li class="chapter" data-level="24.2" data-path="simcorrelation.html"><a href="simcorrelation.html#simulating-correlated-variables"><i class="fa fa-check"></i><b>24.2</b> Simulating correlated variables</a></li>
<li class="chapter" data-level="24.3" data-path="simcorrelation.html"><a href="simcorrelation.html#monte-carlo-simulation"><i class="fa fa-check"></i><b>24.3</b> Monte Carlo simulation</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="introanova.html"><a href="introanova.html"><i class="fa fa-check"></i><b>25</b> Introduction to ANOVA</a><ul>
<li class="chapter" data-level="25.1" data-path="introanova.html"><a href="introanova.html#factors-and-levels"><i class="fa fa-check"></i><b>25.1</b> Factors and levels</a></li>
<li class="chapter" data-level="25.2" data-path="introanova.html"><a href="introanova.html#anova-models-one--two--and-three-way"><i class="fa fa-check"></i><b>25.2</b> ANOVA models: One-, Two-, and Three-way</a></li>
<li class="chapter" data-level="25.3" data-path="introanova.html"><a href="introanova.html#anova-inference-protocol"><i class="fa fa-check"></i><b>25.3</b> ANOVA inference protocol</a></li>
<li class="chapter" data-level="25.4" data-path="introanova.html"><a href="introanova.html#anova-calculations"><i class="fa fa-check"></i><b>25.4</b> ANOVA calculations</a><ul>
<li class="chapter" data-level="25.4.1" data-path="introanova.html"><a href="introanova.html#sums-of-squares-partitioning"><i class="fa fa-check"></i><b>25.4.1</b> Sums of Squares partitioning</a></li>
<li class="chapter" data-level="25.4.2" data-path="introanova.html"><a href="introanova.html#degrees-of-freedom"><i class="fa fa-check"></i><b>25.4.2</b> Degrees of freedom</a></li>
<li class="chapter" data-level="25.4.3" data-path="introanova.html"><a href="introanova.html#the-mean-squares"><i class="fa fa-check"></i><b>25.4.3</b> The mean squares</a></li>
<li class="chapter" data-level="25.4.4" data-path="introanova.html"><a href="introanova.html#the-anova-table"><i class="fa fa-check"></i><b>25.4.4</b> The ANOVA table</a></li>
<li class="chapter" data-level="25.4.5" data-path="introanova.html"><a href="introanova.html#the-f-test"><i class="fa fa-check"></i><b>25.4.5</b> The F-test</a></li>
<li class="chapter" data-level="25.4.6" data-path="introanova.html"><a href="introanova.html#post-hoc-group-comparisons"><i class="fa fa-check"></i><b>25.4.6</b> Post-hoc group comparisons</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="introanova.html"><a href="introanova.html#completely-randomized-or-related-measures"><i class="fa fa-check"></i><b>25.5</b> Completely randomized or related measures</a><ul>
<li class="chapter" data-level="25.5.1" data-path="introanova.html"><a href="introanova.html#the-problem-of-lost-data-in-related-measures-designs"><i class="fa fa-check"></i><b>25.5.1</b> The problem of lost data in related measures designs</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="introanova.html"><a href="introanova.html#two-way-anova"><i class="fa fa-check"></i><b>25.6</b> Two-way ANOVA</a></li>
<li class="chapter" data-level="25.7" data-path="introanova.html"><a href="introanova.html#other-anova-models"><i class="fa fa-check"></i><b>25.7</b> Other ANOVA models</a><ul>
<li class="chapter" data-level="25.7.1" data-path="introanova.html"><a href="introanova.html#r-and-anova"><i class="fa fa-check"></i><b>25.7.1</b> R and ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="25.8" data-path="introanova.html"><a href="introanova.html#alternatives-to-anova"><i class="fa fa-check"></i><b>25.8</b> Alternatives to ANOVA</a><ul>
<li class="chapter" data-level="25.8.1" data-path="introanova.html"><a href="introanova.html#screw-anova-just-tell-me-how-to-t-test-everything"><i class="fa fa-check"></i><b>25.8.1</b> Screw ANOVA, Just Tell Me How to t-Test Everything</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="fdistr.html"><a href="fdistr.html"><i class="fa fa-check"></i><b>26</b> The F distribution</a><ul>
<li class="chapter" data-level="26.1" data-path="fdistr.html"><a href="fdistr.html#background-1"><i class="fa fa-check"></i><b>26.1</b> Background</a><ul>
<li class="chapter" data-level="26.1.1" data-path="fdistr.html"><a href="fdistr.html#sample-variance-and-fs-pdf"><i class="fa fa-check"></i><b>26.1.1</b> Sample Variance and F’s PDF</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="fdistr.html"><a href="fdistr.html#df"><i class="fa fa-check"></i><b>26.2</b> df</a></li>
<li class="chapter" data-level="26.3" data-path="fdistr.html"><a href="fdistr.html#pf"><i class="fa fa-check"></i><b>26.3</b> pf</a></li>
<li class="chapter" data-level="26.4" data-path="fdistr.html"><a href="fdistr.html#qf"><i class="fa fa-check"></i><b>26.4</b> qf</a></li>
<li class="chapter" data-level="26.5" data-path="fdistr.html"><a href="fdistr.html#rf"><i class="fa fa-check"></i><b>26.5</b> rf</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="onewayanova.html"><a href="onewayanova.html"><i class="fa fa-check"></i><b>27</b> One-way ANOVA Completely Randomized</a><ul>
<li class="chapter" data-level="27.1" data-path="onewayanova.html"><a href="onewayanova.html#using-ezanova"><i class="fa fa-check"></i><b>27.1</b> Using <code>ezANOVA</code></a></li>
<li class="chapter" data-level="27.2" data-path="onewayanova.html"><a href="onewayanova.html#the-chickwt-data-set"><i class="fa fa-check"></i><b>27.2</b> The chickwt data set</a><ul>
<li class="chapter" data-level="27.2.1" data-path="onewayanova.html"><a href="onewayanova.html#inspect-the-data"><i class="fa fa-check"></i><b>27.2.1</b> Inspect the data</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="onewayanova.html"><a href="onewayanova.html#run-the-anova"><i class="fa fa-check"></i><b>27.3</b> Run the ANOVA</a><ul>
<li class="chapter" data-level="27.3.1" data-path="onewayanova.html"><a href="onewayanova.html#run-the-chickwts-one-way-anova"><i class="fa fa-check"></i><b>27.3.1</b> Run the chickwts One Way ANOVA</a></li>
<li class="chapter" data-level="27.3.2" data-path="onewayanova.html"><a href="onewayanova.html#interpreting-the-one-way-cr-anova-output"><i class="fa fa-check"></i><b>27.3.2</b> Interpreting the One-Way CR ANOVA Output</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="onewayanova.html"><a href="onewayanova.html#posthoc"><i class="fa fa-check"></i><b>27.4</b> Post hoc pairwise comparisons</a><ul>
<li class="chapter" data-level="27.4.1" data-path="onewayanova.html"><a href="onewayanova.html#overview-of-options"><i class="fa fa-check"></i><b>27.4.1</b> Overview of options</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="onewayanova.html"><a href="onewayanova.html#reporting-the-result"><i class="fa fa-check"></i><b>27.5</b> Reporting the result</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="onewayRM.html"><a href="onewayRM.html"><i class="fa fa-check"></i><b>28</b> One-way ANOVA Related Measures</a><ul>
<li class="chapter" data-level="28.1" data-path="onewayRM.html"><a href="onewayRM.html#data-prep"><i class="fa fa-check"></i><b>28.1</b> Data prep</a></li>
<li class="chapter" data-level="28.2" data-path="onewayRM.html"><a href="onewayRM.html#run-the-anova-1"><i class="fa fa-check"></i><b>28.2</b> Run the ANOVA</a></li>
<li class="chapter" data-level="28.3" data-path="onewayRM.html"><a href="onewayRM.html#interpretation-10"><i class="fa fa-check"></i><b>28.3</b> Interpretation</a></li>
<li class="chapter" data-level="28.4" data-path="onewayRM.html"><a href="onewayRM.html#post-hoc-analysis"><i class="fa fa-check"></i><b>28.4</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="28.5" data-path="onewayRM.html"><a href="onewayRM.html#write-up-12"><i class="fa fa-check"></i><b>28.5</b> Write up</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="twowayCR.html"><a href="twowayCR.html"><i class="fa fa-check"></i><b>29</b> Two-way ANOVA Completely Randomized</a><ul>
<li class="chapter" data-level="29.1" data-path="twowayCR.html"><a href="twowayCR.html#effect-of-strain-and-diet-on-liver"><i class="fa fa-check"></i><b>29.1</b> Effect of Strain and Diet on Liver</a></li>
<li class="chapter" data-level="29.2" data-path="twowayCR.html"><a href="twowayCR.html#the-test"><i class="fa fa-check"></i><b>29.2</b> The test</a></li>
<li class="chapter" data-level="29.3" data-path="twowayCR.html"><a href="twowayCR.html#interpretation-of-2-way-cr-anova-output"><i class="fa fa-check"></i><b>29.3</b> Interpretation of 2 Way CR ANOVA Output</a><ul>
<li class="chapter" data-level="29.3.1" data-path="twowayCR.html"><a href="twowayCR.html#levenes"><i class="fa fa-check"></i><b>29.3.1</b> Levene’s</a></li>
<li class="chapter" data-level="29.3.2" data-path="twowayCR.html"><a href="twowayCR.html#anova-table"><i class="fa fa-check"></i><b>29.3.2</b> ANOVA Table</a></li>
</ul></li>
<li class="chapter" data-level="29.4" data-path="twowayCR.html"><a href="twowayCR.html#post-hoc-multiple-comparisons"><i class="fa fa-check"></i><b>29.4</b> Post Hoc Multiple Comparisons</a><ul>
<li class="chapter" data-level="29.4.1" data-path="twowayCR.html"><a href="twowayCR.html#write-up-13"><i class="fa fa-check"></i><b>29.4.1</b> Write Up</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="30" data-path="twowayRM.html"><a href="twowayRM.html"><i class="fa fa-check"></i><b>30</b> Two-way ANOVA Related Measures</a><ul>
<li class="chapter" data-level="30.1" data-path="twowayRM.html"><a href="twowayRM.html#cell-culture"><i class="fa fa-check"></i><b>30.1</b> Cell culture</a></li>
<li class="chapter" data-level="30.2" data-path="twowayRM.html"><a href="twowayRM.html#the-test-1"><i class="fa fa-check"></i><b>30.2</b> The test</a></li>
<li class="chapter" data-level="30.3" data-path="twowayRM.html"><a href="twowayRM.html#interpretation-of-the-output"><i class="fa fa-check"></i><b>30.3</b> Interpretation of the output</a><ul>
<li class="chapter" data-level="30.3.1" data-path="twowayRM.html"><a href="twowayRM.html#anova-table-1"><i class="fa fa-check"></i><b>30.3.1</b> ANOVA Table</a></li>
<li class="chapter" data-level="30.3.2" data-path="twowayRM.html"><a href="twowayRM.html#mauchlys-sphericity-test"><i class="fa fa-check"></i><b>30.3.2</b> Mauchly’s Sphericity Test</a></li>
</ul></li>
<li class="chapter" data-level="30.4" data-path="twowayRM.html"><a href="twowayRM.html#post-hoc-multiple-comparisons-1"><i class="fa fa-check"></i><b>30.4</b> Post Hoc multiple comparisons</a></li>
<li class="chapter" data-level="30.5" data-path="twowayRM.html"><a href="twowayRM.html#write-up-14"><i class="fa fa-check"></i><b>30.5</b> Write Up</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="twowaymixed.html"><a href="twowaymixed.html"><i class="fa fa-check"></i><b>31</b> Two-way ANOVA RM/CR</a><ul>
<li class="chapter" data-level="31.1" data-path="twowaymixed.html"><a href="twowaymixed.html#chickweight-dataset"><i class="fa fa-check"></i><b>31.1</b> ChickWeight Dataset</a></li>
<li class="chapter" data-level="31.2" data-path="twowaymixed.html"><a href="twowaymixed.html#munge-chickweight-data"><i class="fa fa-check"></i><b>31.2</b> Munge ChickWeight data</a></li>
<li class="chapter" data-level="31.3" data-path="twowaymixed.html"><a href="twowaymixed.html#the-test-2"><i class="fa fa-check"></i><b>31.3</b> The test</a></li>
<li class="chapter" data-level="31.4" data-path="twowaymixed.html"><a href="twowaymixed.html#interpreting-the-anova-output"><i class="fa fa-check"></i><b>31.4</b> Interpreting the ANOVA output</a><ul>
<li class="chapter" data-level="31.4.1" data-path="twowaymixed.html"><a href="twowaymixed.html#anova-the-anova-table-1"><i class="fa fa-check"></i><b>31.4.1</b> $ANOVA: The ANOVA table</a></li>
<li class="chapter" data-level="31.4.2" data-path="twowaymixed.html"><a href="twowaymixed.html#mauchlys-test-and-corrections"><i class="fa fa-check"></i><b>31.4.2</b> Mauchly’s Test and Corrections</a></li>
</ul></li>
<li class="chapter" data-level="31.5" data-path="twowaymixed.html"><a href="twowaymixed.html#post-hoc-pairwise-tests"><i class="fa fa-check"></i><b>31.5</b> Post hoc pairwise tests</a><ul>
<li class="chapter" data-level="31.5.1" data-path="twowaymixed.html"><a href="twowaymixed.html#heres-whats-been-discovered"><i class="fa fa-check"></i><b>31.5.1</b> Here’s what’s been discovered</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="32" data-path="jaxwest2.html"><a href="jaxwest2.html"><i class="fa fa-check"></i><b>32</b> Reproducible Data Munging Mostly with Tidyverse</a><ul>
<li class="chapter" data-level="32.1" data-path="jaxwest2.html"><a href="jaxwest2.html#look-at-the-original-data-carefully"><i class="fa fa-check"></i><b>32.1</b> Look at the original data carefully</a></li>
<li class="chapter" data-level="32.2" data-path="jaxwest2.html"><a href="jaxwest2.html#our-goal"><i class="fa fa-check"></i><b>32.2</b> Our goal</a></li>
<li class="chapter" data-level="32.3" data-path="jaxwest2.html"><a href="jaxwest2.html#read-the-data-into-r"><i class="fa fa-check"></i><b>32.3</b> Read the data into R</a></li>
<li class="chapter" data-level="32.4" data-path="jaxwest2.html"><a href="jaxwest2.html#select-the-variables"><i class="fa fa-check"></i><b>32.4</b> Select the variables</a></li>
<li class="chapter" data-level="32.5" data-path="jaxwest2.html"><a href="jaxwest2.html#trim-the-cases"><i class="fa fa-check"></i><b>32.5</b> Trim the cases</a></li>
<li class="chapter" data-level="32.6" data-path="jaxwest2.html"><a href="jaxwest2.html#go-long"><i class="fa fa-check"></i><b>32.6</b> Go long</a></li>
<li class="chapter" data-level="32.7" data-path="jaxwest2.html"><a href="jaxwest2.html#pull-out-the-values-for-the-day-variable"><i class="fa fa-check"></i><b>32.7</b> Pull out the values for the day variable</a></li>
<li class="chapter" data-level="32.8" data-path="jaxwest2.html"><a href="jaxwest2.html#convert-day-to-numeric"><i class="fa fa-check"></i><b>32.8</b> Convert day to numeric</a></li>
<li class="chapter" data-level="32.9" data-path="jaxwest2.html"><a href="jaxwest2.html#convert-tumor_vol-to-numeric"><i class="fa fa-check"></i><b>32.9</b> Convert tumor_vol to numeric</a></li>
<li class="chapter" data-level="32.10" data-path="jaxwest2.html"><a href="jaxwest2.html#deal-with-that-na"><i class="fa fa-check"></i><b>32.10</b> Deal with that NA</a></li>
<li class="chapter" data-level="32.11" data-path="jaxwest2.html"><a href="jaxwest2.html#convert-variables-to-factor"><i class="fa fa-check"></i><b>32.11</b> Convert variables to factor</a></li>
<li class="chapter" data-level="32.12" data-path="jaxwest2.html"><a href="jaxwest2.html#plot-the-data"><i class="fa fa-check"></i><b>32.12</b> Plot the data</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="anovamc.html"><a href="anovamc.html"><i class="fa fa-check"></i><b>33</b> ANOVA power using Monte Carlo</a><ul>
<li class="chapter" data-level="33.1" data-path="anovamc.html"><a href="anovamc.html#alternatives-to-monte-carlo"><i class="fa fa-check"></i><b>33.1</b> Alternatives to Monte Carlo</a></li>
<li class="chapter" data-level="33.2" data-path="anovamc.html"><a href="anovamc.html#what-is-monte-carlo"><i class="fa fa-check"></i><b>33.2</b> What is Monte Carlo</a></li>
<li class="chapter" data-level="33.3" data-path="anovamc.html"><a href="anovamc.html#one-way-completely-randomized-anova-monte-carlo"><i class="fa fa-check"></i><b>33.3</b> One-way completely randomized ANOVA Monte Carlo</a><ul>
<li class="chapter" data-level="33.3.1" data-path="anovamc.html"><a href="anovamc.html#directions"><i class="fa fa-check"></i><b>33.3.1</b> Directions</a></li>
<li class="chapter" data-level="33.3.2" data-path="anovamc.html"><a href="anovamc.html#step-1-create-initial-values"><i class="fa fa-check"></i><b>33.3.2</b> Step 1: Create initial values</a></li>
<li class="chapter" data-level="33.3.3" data-path="anovamc.html"><a href="anovamc.html#step-2-visualize-one-random-sample"><i class="fa fa-check"></i><b>33.3.3</b> Step 2: Visualize one random sample</a></li>
<li class="chapter" data-level="33.3.4" data-path="anovamc.html"><a href="anovamc.html#step-3-run-the-power-simulator"><i class="fa fa-check"></i><b>33.3.4</b> Step 3: Run The Power Simulator</a></li>
<li class="chapter" data-level="33.3.5" data-path="anovamc.html"><a href="anovamc.html#step-4-optimize-for-suitable-power"><i class="fa fa-check"></i><b>33.3.5</b> Step 4: Optimize for suitable power</a></li>
<li class="chapter" data-level="33.3.6" data-path="anovamc.html"><a href="anovamc.html#notes-and-considerations"><i class="fa fa-check"></i><b>33.3.6</b> Notes And Considerations</a></li>
</ul></li>
<li class="chapter" data-level="33.4" data-path="anovamc.html"><a href="anovamc.html#one-way-related-measures-anova-monte-carlo"><i class="fa fa-check"></i><b>33.4</b> One-way related measures ANOVA Monte Carlo</a></li>
<li class="chapter" data-level="33.5" data-path="anovamc.html"><a href="anovamc.html#directions-1"><i class="fa fa-check"></i><b>33.5</b> Directions</a><ul>
<li class="chapter" data-level="33.5.1" data-path="anovamc.html"><a href="anovamc.html#step-1-initial-values"><i class="fa fa-check"></i><b>33.5.1</b> Step 1: Initial values</a></li>
<li class="chapter" data-level="33.5.2" data-path="anovamc.html"><a href="anovamc.html#step-2-visualize-one-sample"><i class="fa fa-check"></i><b>33.5.2</b> Step 2: Visualize one sample</a></li>
<li class="chapter" data-level="33.5.3" data-path="anovamc.html"><a href="anovamc.html#step-3-run-the-power-simulator-1"><i class="fa fa-check"></i><b>33.5.3</b> Step 3: Run the power simulator</a></li>
<li class="chapter" data-level="33.5.4" data-path="anovamc.html"><a href="anovamc.html#step-4-should-anything-be-changed"><i class="fa fa-check"></i><b>33.5.4</b> Step 4: Should anything be changed?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="34" data-path="correl.html"><a href="correl.html"><i class="fa fa-check"></i><b>34</b> Correlation</a><ul>
<li class="chapter" data-level="34.1" data-path="correl.html"><a href="correl.html#correlation-causation"><i class="fa fa-check"></i><b>34.1</b> Correlation != Causation</a></li>
<li class="chapter" data-level="34.2" data-path="correl.html"><a href="correl.html#correlation-in-multivariate-outcomes-and-paired-designs"><i class="fa fa-check"></i><b>34.2</b> Correlation in Multivariate Outcomes and Paired Designs</a></li>
<li class="chapter" data-level="34.3" data-path="correl.html"><a href="correl.html#correlation-coefficients"><i class="fa fa-check"></i><b>34.3</b> Correlation coefficients</a><ul>
<li class="chapter" data-level="34.3.1" data-path="correl.html"><a href="correl.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>34.3.1</b> Pearson’s correlation coefficient</a></li>
<li class="chapter" data-level="34.3.2" data-path="correl.html"><a href="correl.html#spearmans-rank-correlation"><i class="fa fa-check"></i><b>34.3.2</b> Spearman’s rank correlation</a></li>
<li class="chapter" data-level="34.3.3" data-path="correl.html"><a href="correl.html#kendalls-tau"><i class="fa fa-check"></i><b>34.3.3</b> Kendall’s tau</a></li>
<li class="chapter" data-level="34.3.4" data-path="correl.html"><a href="correl.html#which-correlation-method-to-use"><i class="fa fa-check"></i><b>34.3.4</b> Which correlation method to use?</a></li>
<li class="chapter" data-level="34.3.5" data-path="correl.html"><a href="correl.html#r-correlation-analysis-functions"><i class="fa fa-check"></i><b>34.3.5</b> R correlation analysis functions</a></li>
<li class="chapter" data-level="34.3.6" data-path="correl.html"><a href="correl.html#plot-the-correlations"><i class="fa fa-check"></i><b>34.3.6</b> Plot the correlations</a></li>
<li class="chapter" data-level="34.3.7" data-path="correl.html"><a href="correl.html#calculate-a-correlation-coefficient-and-posthoc-test"><i class="fa fa-check"></i><b>34.3.7</b> Calculate a correlation coefficient and posthoc test</a></li>
<li class="chapter" data-level="34.3.8" data-path="correl.html"><a href="correl.html#interpretation-of-correlation-output"><i class="fa fa-check"></i><b>34.3.8</b> Interpretation of correlation output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="35" data-path="regress.html"><a href="regress.html"><i class="fa fa-check"></i><b>35</b> Linear Regression</a><ul>
<li class="chapter" data-level="35.1" data-path="regress.html"><a href="regress.html#the-linear-regression-model"><i class="fa fa-check"></i><b>35.1</b> The linear regression model</a></li>
<li class="chapter" data-level="35.2" data-path="regress.html"><a href="regress.html#least-squares-fitting"><i class="fa fa-check"></i><b>35.2</b> Least squares fitting</a></li>
<li class="chapter" data-level="35.3" data-path="regress.html"><a href="regress.html#the-practical-importance-of-linear-model-parameters"><i class="fa fa-check"></i><b>35.3</b> The practical importance of linear model parameters</a></li>
<li class="chapter" data-level="35.4" data-path="regress.html"><a href="regress.html#linear-model-standard-errors"><i class="fa fa-check"></i><b>35.4</b> Linear model standard errors</a></li>
<li class="chapter" data-level="35.5" data-path="regress.html"><a href="regress.html#linear-regression-in-r"><i class="fa fa-check"></i><b>35.5</b> Linear regression in R</a></li>
<li class="chapter" data-level="35.6" data-path="regress.html"><a href="regress.html#intepretation"><i class="fa fa-check"></i><b>35.6</b> Intepretation</a><ul>
<li class="chapter" data-level="35.6.1" data-path="regress.html"><a href="regress.html#residuals"><i class="fa fa-check"></i><b>35.6.1</b> Residuals</a></li>
<li class="chapter" data-level="35.6.2" data-path="regress.html"><a href="regress.html#coefficients"><i class="fa fa-check"></i><b>35.6.2</b> Coefficients</a></li>
<li class="chapter" data-level="35.6.3" data-path="regress.html"><a href="regress.html#degrees-of-freedom-1"><i class="fa fa-check"></i><b>35.6.3</b> Degrees of freedom</a></li>
<li class="chapter" data-level="35.6.4" data-path="regress.html"><a href="regress.html#r-squared"><i class="fa fa-check"></i><b>35.6.4</b> R-squared</a></li>
<li class="chapter" data-level="35.6.5" data-path="regress.html"><a href="regress.html#f-statistic"><i class="fa fa-check"></i><b>35.6.5</b> F-statistic</a></li>
<li class="chapter" data-level="35.6.6" data-path="regress.html"><a href="regress.html#plotting-regression-results"><i class="fa fa-check"></i><b>35.6.6</b> Plotting regression results</a></li>
<li class="chapter" data-level="35.6.7" data-path="regress.html"><a href="regress.html#visualizing-residuals"><i class="fa fa-check"></i><b>35.6.7</b> Visualizing residuals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="36" data-path="nonlinearintro.html"><a href="nonlinearintro.html"><i class="fa fa-check"></i><b>36</b> Non-linear regression introduction</a><ul>
<li class="chapter" data-level="36.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#uses-for-nonlinear-regression"><i class="fa fa-check"></i><b>36.1</b> Uses for nonlinear regression</a></li>
<li class="chapter" data-level="36.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#nonlinear-models-and-parameters"><i class="fa fa-check"></i><b>36.2</b> Nonlinear models and parameters</a><ul>
<li class="chapter" data-level="36.2.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#hyperbolic-stimulus-response-functions"><i class="fa fa-check"></i><b>36.2.1</b> Hyperbolic stimulus response functions</a></li>
<li class="chapter" data-level="36.2.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#visualizing-nonlinear-data-and-log-scaling"><i class="fa fa-check"></i><b>36.2.2</b> Visualizing nonlinear data and log scaling</a></li>
</ul></li>
<li class="chapter" data-level="36.3" data-path="nonlinearintro.html"><a href="nonlinearintro.html#how-do-regression-fits-happen"><i class="fa fa-check"></i><b>36.3</b> How do regression fits happen?</a><ul>
<li class="chapter" data-level="36.3.1" data-path="nonlinearintro.html"><a href="nonlinearintro.html#selecting-the-right-model"><i class="fa fa-check"></i><b>36.3.1</b> Selecting the right model</a></li>
<li class="chapter" data-level="36.3.2" data-path="nonlinearintro.html"><a href="nonlinearintro.html#from-models-to-formulas"><i class="fa fa-check"></i><b>36.3.2</b> From models to formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="nestedregress.html"><a href="nestedregress.html"><i class="fa fa-check"></i><b>37</b> Nested-model nonlinear regression</a><ul>
<li class="chapter" data-level="37.1" data-path="nestedregress.html"><a href="nestedregress.html#read-and-plot-the-data"><i class="fa fa-check"></i><b>37.1</b> Read and plot the data</a></li>
<li class="chapter" data-level="37.2" data-path="nestedregress.html"><a href="nestedregress.html#perform-the-nonlinear-regression"><i class="fa fa-check"></i><b>37.2</b> Perform the nonlinear regression</a><ul>
<li class="chapter" data-level="37.2.1" data-path="nestedregress.html"><a href="nestedregress.html#troubleshooting-the-regression"><i class="fa fa-check"></i><b>37.2.1</b> Troubleshooting the regression</a></li>
<li class="chapter" data-level="37.2.2" data-path="nestedregress.html"><a href="nestedregress.html#interpreting-the-parameters"><i class="fa fa-check"></i><b>37.2.2</b> Interpreting the parameters</a></li>
<li class="chapter" data-level="37.2.3" data-path="nestedregress.html"><a href="nestedregress.html#residual-plots-to-compare-fits"><i class="fa fa-check"></i><b>37.2.3</b> Residual plots to compare fits</a></li>
<li class="chapter" data-level="37.2.4" data-path="nestedregress.html"><a href="nestedregress.html#f-test-for-model-comparison"><i class="fa fa-check"></i><b>37.2.4</b> F test for model comparison</a></li>
<li class="chapter" data-level="37.2.5" data-path="nestedregress.html"><a href="nestedregress.html#compare-aic"><i class="fa fa-check"></i><b>37.2.5</b> Compare AIC</a></li>
<li class="chapter" data-level="37.2.6" data-path="nestedregress.html"><a href="nestedregress.html#other-ways-to-compare-models"><i class="fa fa-check"></i><b>37.2.6</b> Other ways to compare models</a></li>
<li class="chapter" data-level="37.2.7" data-path="nestedregress.html"><a href="nestedregress.html#interpretation-of-this-one-replicate"><i class="fa fa-check"></i><b>37.2.7</b> Interpretation of this one replicate</a></li>
<li class="chapter" data-level="37.2.8" data-path="nestedregress.html"><a href="nestedregress.html#alternate-analysis"><i class="fa fa-check"></i><b>37.2.8</b> Alternate analysis</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="nestedregress.html"><a href="nestedregress.html#summary-3"><i class="fa fa-check"></i><b>37.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="38" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html"><i class="fa fa-check"></i><b>38</b> Nonlinear regression of independent replicates</a><ul>
<li class="chapter" data-level="38.1" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#the-dataset"><i class="fa fa-check"></i><b>38.1</b> The dataset</a></li>
<li class="chapter" data-level="38.2" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#munging-for-regression-analysis"><i class="fa fa-check"></i><b>38.2</b> Munging for regression analysis</a><ul>
<li class="chapter" data-level="38.2.1" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#average-the-technical-replicates"><i class="fa fa-check"></i><b>38.2.1</b> Average the technical replicates</a></li>
<li class="chapter" data-level="38.2.2" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#create-one-table"><i class="fa fa-check"></i><b>38.2.2</b> Create one table</a></li>
<li class="chapter" data-level="38.2.3" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#plot-the-data-1"><i class="fa fa-check"></i><b>38.2.3</b> Plot the data</a></li>
<li class="chapter" data-level="38.2.4" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#run-the-regressions"><i class="fa fa-check"></i><b>38.2.4</b> Run the regressions</a></li>
<li class="chapter" data-level="38.2.5" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#clean-up-regression-results"><i class="fa fa-check"></i><b>38.2.5</b> Clean up regression results</a></li>
</ul></li>
<li class="chapter" data-level="38.3" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#t-test-on-half-lives"><i class="fa fa-check"></i><b>38.3</b> T-test on half-lives</a></li>
<li class="chapter" data-level="38.4" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#conclusion"><i class="fa fa-check"></i><b>38.4</b> Conclusion</a></li>
<li class="chapter" data-level="38.5" data-path="nonlinearreplicates.html"><a href="nonlinearreplicates.html#summary-figure"><i class="fa fa-check"></i><b>38.5</b> Summary figure</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="multregress.html"><a href="multregress.html"><i class="fa fa-check"></i><b>39</b> Multiple regression</a><ul>
<li class="chapter" data-level="39.1" data-path="multregress.html"><a href="multregress.html#the-linear-regression-model-1"><i class="fa fa-check"></i><b>39.1</b> The linear regression model</a></li>
<li class="chapter" data-level="39.2" data-path="multregress.html"><a href="multregress.html#multiple-regression-models"><i class="fa fa-check"></i><b>39.2</b> Multiple regression models</a></li>
<li class="chapter" data-level="39.3" data-path="multregress.html"><a href="multregress.html#experimental-multiple-regression"><i class="fa fa-check"></i><b>39.3</b> Experimental multiple regression</a><ul>
<li class="chapter" data-level="39.3.1" data-path="multregress.html"><a href="multregress.html#a-one-factor-experiment-with-3-groups"><i class="fa fa-check"></i><b>39.3.1</b> A one factor experiment with 3 groups</a></li>
<li class="chapter" data-level="39.3.2" data-path="multregress.html"><a href="multregress.html#a-two-factor-experiment-with-6-groups"><i class="fa fa-check"></i><b>39.3.2</b> A two factor experiment with 6 groups</a></li>
</ul></li>
<li class="chapter" data-level="39.4" data-path="multregress.html"><a href="multregress.html#multiple-linear-mixed-models"><i class="fa fa-check"></i><b>39.4</b> Multiple linear mixed models</a></li>
<li class="chapter" data-level="39.5" data-path="multregress.html"><a href="multregress.html#multiple-regression-of-observational-data"><i class="fa fa-check"></i><b>39.5</b> Multiple regression of observational data</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="logregress.html"><a href="logregress.html"><i class="fa fa-check"></i><b>40</b> Logistic regression</a><ul>
<li class="chapter" data-level="40.1" data-path="logregress.html"><a href="logregress.html#uses-of-logistic-regression"><i class="fa fa-check"></i><b>40.1</b> Uses of logistic regression</a><ul>
<li class="chapter" data-level="40.1.1" data-path="logregress.html"><a href="logregress.html#sidebar-doing-logistic-regression-is-machine-learning"><i class="fa fa-check"></i><b>40.1.1</b> Sidebar: Doing logistic regression is machine learning</a></li>
</ul></li>
<li class="chapter" data-level="40.2" data-path="logregress.html"><a href="logregress.html#derivation-of-the-logistic-regression-model"><i class="fa fa-check"></i><b>40.2</b> Derivation of the logistic regression model</a><ul>
<li class="chapter" data-level="40.2.1" data-path="logregress.html"><a href="logregress.html#relationship-of-logit-to-odds-to-the-model-coefficients-and-probability"><i class="fa fa-check"></i><b>40.2.1</b> Relationship of logit to odds to the model coefficients and probability</a></li>
<li class="chapter" data-level="40.2.2" data-path="logregress.html"><a href="logregress.html#additional-types-of-logistic-regression-models"><i class="fa fa-check"></i><b>40.2.2</b> Additional types of logistic regression models</a></li>
</ul></li>
<li class="chapter" data-level="40.3" data-path="logregress.html"><a href="logregress.html#stress-and-survival"><i class="fa fa-check"></i><b>40.3</b> Stress and survival</a><ul>
<li class="chapter" data-level="40.3.1" data-path="logregress.html"><a href="logregress.html#interpretation-of-output"><i class="fa fa-check"></i><b>40.3.1</b> Interpretation of output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="41" data-path="mixedlogistic.html"><a href="mixedlogistic.html"><i class="fa fa-check"></i><b>41</b> Mixed model logistic regression</a><ul>
<li class="chapter" data-level="41.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#mixed-models-fixed-and-random-effects"><i class="fa fa-check"></i><b>41.1</b> Mixed models, fixed and random effects</a><ul>
<li class="chapter" data-level="41.1.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#nfat-localization-within-smooth-muscle-cells"><i class="fa fa-check"></i><b>41.1.1</b> NFAT localization within smooth muscle cells</a></li>
</ul></li>
<li class="chapter" data-level="41.2" data-path="mixedlogistic.html"><a href="mixedlogistic.html#data-1"><i class="fa fa-check"></i><b>41.2</b> Data</a></li>
<li class="chapter" data-level="41.3" data-path="mixedlogistic.html"><a href="mixedlogistic.html#linear-model"><i class="fa fa-check"></i><b>41.3</b> Linear model</a><ul>
<li class="chapter" data-level="41.3.1" data-path="mixedlogistic.html"><a href="mixedlogistic.html#inference-1"><i class="fa fa-check"></i><b>41.3.1</b> Inference</a></li>
</ul></li>
<li class="chapter" data-level="41.4" data-path="mixedlogistic.html"><a href="mixedlogistic.html#alternative-analysis"><i class="fa fa-check"></i><b>41.4</b> Alternative analysis</a></li>
</ul></li>
<li class="chapter" data-level="42" data-path="lognormal.html"><a href="lognormal.html"><i class="fa fa-check"></i><b>42</b> The lognormal distribution</a><ul>
<li class="chapter" data-level="42.1" data-path="lognormal.html"><a href="lognormal.html#dlnorm"><i class="fa fa-check"></i><b>42.1</b> dlnorm</a></li>
<li class="chapter" data-level="42.2" data-path="lognormal.html"><a href="lognormal.html#plnorm"><i class="fa fa-check"></i><b>42.2</b> plnorm</a></li>
<li class="chapter" data-level="42.3" data-path="lognormal.html"><a href="lognormal.html#qlnorm"><i class="fa fa-check"></i><b>42.3</b> qlnorm</a></li>
<li class="chapter" data-level="42.4" data-path="lognormal.html"><a href="lognormal.html#rlnorm"><i class="fa fa-check"></i><b>42.4</b> rlnorm</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">JABSTB: Statistical Design and Analysis of Experiments with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ttests" class="section level1">
<h1><span class="header-section-number">Chapter 22</span> The t-tests</h1>
<p>The t-tests, otherwise known as “Student’s t tests”, are for experimental designs that test hypotheses comparing one group to a standard or two groups two each other, or paired measures within replicates <strong>and</strong> where the outcome variable is continuous and on an equal interval scale.</p>
<p>In other words, t-tests are for dependent variables involving measured data and when two or fewer levels of an independent variable are tested.</p>
<p>To recall, continuous data are on scales that have values between their intervals. For example, we might use a mass balance to measure the mass of individual mice, and then record how their weight change in response to some factor at two different levels. Here, mass would be an equal interval measurement. Mass is continuous, in so far as a theoretically infinite number of values can exist between two units on the scale, depending upon the sensitivity of the measurements.</p>
<p>Derivative continuous variables are common in t-testing. For example, growth rate, in grams/week, is a derivative of the mass and time measurement scales. Like mass and time, growth rate is also continuous.</p>
<p>Just as importantly, the statistics derived from continuous, equal interval data also have the properties of continuous, equal interval data. For example, the means and standard deviations, the standard errors of the mean, and the t-test statistic itself are also scaled continuous.</p>
<div id="data-assumptions-for-t-tests" class="section level2">
<h2><span class="header-section-number">22.1</span> Data assumptions for t-tests</h2>
<p>The following assumptions should be checked to use t-tests properly.</p>
<div id="strong-assumptions-t-tests-are-invalid-if-these-not-met" class="section level4">
<h4><span class="header-section-number">22.1.0.1</span> Strong assumptions, t tests are invalid if these not met:</h4>
<ol style="list-style-type: decimal">
<li><p>The replicate data arise from a randomized process.</p></li>
<li><p>Each sample replicate is independent of every other sample replicate.</p></li>
</ol>
<p><em>Don’t confuse a measurement with a replicate. Paired designs have two measurements from one replicate. For example, a measurement after placebo and then a second measurement after drug.</em></p>
</div>
<div id="weak-assumptions-t-tests-are-less-robust-when-these-are-not-met" class="section level4">
<h4><span class="header-section-number">22.1.0.2</span> Weak assumptions: t-tests are less robust when these are not met:</h4>
<ol start="3" style="list-style-type: decimal">
<li><p>The sampled population for each group is normally distributed.</p></li>
<li><p>The variances of the compared groups are equivalent.</p></li>
</ol>
<p>We are now at the simplest application of the linear model. Wherein one <span class="math inline">\(x_1\)</span>, or more commonly two <span class="math inline">\(x_1,x_2\)</span> levels of the independent variable <span class="math inline">\(X\)</span> predicts the response of the dependent variable <span class="math inline">\(Y\)</span> as <span class="math display">\[E(Y) = \beta_0 +\beta_1X+e\]</span></p>
<p>The focus of t-testing is to estimate for the value of <span class="math inline">\(\beta_1\)</span> and ask whether it differs statistically from zero. When <span class="math inline">\(\beta_1=0\)</span>, a line drawn between the pair of points <span class="math inline">\(x_1,y_1\)</span> and <span class="math inline">\(x_2, y_2\)</span> has a slope of zero. <span class="math inline">\(X\)</span> has no effect on <span class="math inline">\(Y\)</span> and thus <span class="math inline">\(E(Y)\)</span> equals the value of the intercept, <span class="math inline">\(Y = \beta_0\)</span>. Think of the intercept as the background or basal level the dependent variable.</p>
<p>Gauss discovered that a property of continuous data when measurements are taken from the linear range on its scale is that residual error <span class="math inline">\(e\)</span> <a href="https://www.maa.org/sites/default/files/pdf/upload_library/22/Allendoerfer/stahl96.pdf">is normally distributed.</a></p>
<p>The smaller the sample size, the more difficult it is to assess the distribution of <span class="math inline">\(e\)</span>. Thus, it is hard to validate the latter two assumptions above.</p>
<p>There are two equally valid ways to approach this.</p>
<p>Normality tests such as the Shapiro-Wilk (<code>shapiro.test</code>), tests the null hypothesis that the values of a random variable are normally-distributed. Levene’s test <code>library(car), leveneTest</code> is useful to test the homogeneity of variance assumption. The use of these tests should be declared in advance in the design phase. Unless you’re dealing with sample sizes of ~30 or greater, it is probably futile to try to make these assessments.</p>
<p>If their nulls are rejected, the data can be normalized through log or reciprocal transformation. The t-tests are then performed on these transformed values. Alternately, nonparametric analysis with the Wilcoxon tests can be used instead.@(nonparametrics) Again, these decisions should be declared in advance.</p>
<p>The performance of t-tests and their nonparametric counterparts are virtually identical when the normality and homoscedasticity assumptions are met. Whereas nonparametrics statistics can be more powerful when these assumptions are unmet.</p>
<div class="figure"><span id="fig:unnamed-chunk-2"></span>
<img src="images/pwr_tvw_tests.jpeg" alt="Comparison of Wilcoxon test power to t-tests when sampling from skewed (lognormal) and normal distributions." width="441" />
<p class="caption">
Figure 22.1: Comparison of Wilcoxon test power to t-tests when sampling from skewed (lognormal) and normal distributions.
</p>
</div>
</div>
</div>
<div id="the-t-statistic" class="section level2">
<h2><span class="header-section-number">22.2</span> The t Statistic</h2>
<p>The <span class="math inline">\(t\)</span> statistic is a ratio signifying the signal to noise ratio in a sample.</p>
<p>The numerator would be a measure for the magnitude of the average effect, whereas the denominator would represent the precision by which those mean differences are determined. There are 3 different ways to calculate the numerators and denominators of <span class="math inline">\(t\)</span>, which correspond to three very different experimental designs.</p>
<p>The decision to use one or the other t-test is entirely scientific and based upon how the experiment is conducted. If you understand your experimental design, you’ll know which t test is applicable.</p>
<p><em>One sample tests inspect the difference between a sample mean and a hypothetical mean.
</em>Unpaired tests inspect the difference between the means of two groups.
*The paired t test inspects the mean of the differences between paired observations.</p>
<p><em>The most common mistake made by statistically naive researchers is running unpaired t-tests on experiments that have a paired design.</em></p>
<div id="one-sample-t-tests" class="section level3">
<h3><span class="header-section-number">22.2.1</span> One sample t tests</h3>
<p>For comparing the mean response <span class="math inline">\(\bar y\)</span> to a single level of a predictor variable against a hypothetical population mean, <span class="math inline">\(\mu\)</span>. A group comprised of <span class="math inline">\(n\)</span> independent observations, whose <span class="math inline">\(\bar y\)</span> The one sample t test has <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
<p><span class="math display">\[t=\frac{\bar y-\mu}{\frac{sd}{\sqrt n}}\]</span></p>
<div id="example" class="section level4">
<h4><span class="header-section-number">22.2.1.1</span> Example</h4>
<p>For example, normal blood glucose in mice is 100 mg/dl. Blood glucose is measured in a random sample of mice with a disrupted insulin receptor gene. A one-sample t-test compares their measured glucose values to the <span class="math inline">\(\mu\)</span>=100 mg/dl.</p>
</div>
</div>
<div id="unpaired-t-tests" class="section level3">
<h3><span class="header-section-number">22.2.2</span> Unpaired t tests</h3>
<p>This test is used for experiments in which the measurements are all independent from each other.</p>
<div id="students-t-test" class="section level4">
<h4><span class="header-section-number">22.2.2.1</span> Student’s t-test</h4>
<p>The unpaired Student’s t-test compares the difference between the mean responses to each of two levels, A and B, of a predictor variable. The design is comprised of a total of <span class="math inline">\(n_A + n_B\)</span> observations. A degree of freedom is lost for each of the two calculated group means. <span class="math inline">\(s_p\)</span> would be the pooled standard deviation of the sample. <span class="math inline">\(s^2_p\)</span> is the pooled variance of the sample.</p>
<p><span class="math display">\[t=\frac{\bar y_A-\bar y_B}{\sqrt{\frac{s^2_p}{n_A}+\frac{s^2_p}{n_B}}}\]</span></p>
<p>The pooled variance is calculated using the sum of the squared deviates <span class="math inline">\(SS_A\ and\ SS_B\)</span> from each group as follows: <span class="math display">\[s^2_p=\frac{SS_A+SS_B}{df_A+df_B}\]</span>, where <span class="math inline">\(df_A=n_A-1\)</span> and <span class="math inline">\(df_B=n_B-1\)</span>.</p>
<p>The null sampling distribution for <span class="math inline">\(t\)</span> has <span class="math inline">\((n_A + n_B)-2\)</span> degrees of freedom.</p>
<p>The denominator of the <span class="math inline">\(t\)</span> ratio is the standard error of the test. The standard error represents the test’s precision but note how it represents the standard error of two means.</p>
<p>Inspection of the pooled variance equation and how it factors into the calculation of the test statistic should give you some indication for how unequal sample sizes or variance between groups can be problematic. When unbalanced the calculation can be biased to one of the groups.</p>
</div>
<div id="welchs-t-test" class="section level4">
<h4><span class="header-section-number">22.2.2.2</span> Welch’s t-test</h4>
<p>Welch’s t-test, which is the default in R for comparing group means, differs from Student’s t-test. First, Welch does not use a pooled variance term.</p>
<p><span class="math display">\[t=\frac{\bar y_A-\bar y_B}{\sqrt{\frac{s^2_A}{n_A}+\frac{s^2_B}{n_B}}}\]</span></p>
<p>Second, the degrees of freedom <span class="math inline">\(\nu\)</span> for the null <span class="math inline">\(t\)</span> distribution of the test is calculated differently: <span class="math display">\[\nu=\frac{(\frac{s^2_A}{n_A}+\frac{s^2_B}{n_B})^2}{\frac{s^4_A}{n^2_A\nu_A}+\frac{s^4_B}{n^2_b\nu_B}}\]</span></p>
<p>It is important to note that in R’s <code>t.test</code> function the default option <code>var.equal=F</code> calls for Welch’s test. When set to <code>TRUE</code>, it runs the Two Sample t-test.</p>
<p>Under some conditions, the two tests can yield quite different values for <span class="math inline">\(t\)</span> and <span class="math inline">\(p-values\)</span> when fed the same data. The Welch t-test is held to perform better under a variety of sampling conditions, but such generalities are about as useful as reading these words costs you. YMMV.</p>
<p>When conducting power analysis during the experimental design phase, particularly when planning unequal sample sizes or for unequal variances, it is useful to compare how the two tests perform given your expected experiment. It is important to know how these tests perform when evaluating your own variables. And it is easy enough to run the simulation.</p>
</div>
<div id="example-1" class="section level4">
<h4><span class="header-section-number">22.2.2.3</span> Example</h4>
<p>A mouse model of diabetes has been established. It is used to test whether novel blood glucose lowering drugs work. A sample of mice are randomly assigned to treatment with either a placebo or with a drug. Blood glucose measurements are taken from all mice, and the two groups are compared. Every measurement stands as an independent replicate.</p>
</div>
</div>
<div id="paired-t-tests" class="section level3">
<h3><span class="header-section-number">22.2.3</span> Paired t tests</h3>
<p>This test is used when measurements are intrinsically-linked. Each of <span class="math inline">\(n\)</span> replicates is exposed to both levels, A and B, of a predictor variable. There are <span class="math inline">\(n\)</span> pairs of measurements in the design. The mean difference <span class="math inline">\(\bar d\)</span> of the paired responses is compared to the value of zero. <span class="math inline">\(sd_d\)</span> is the standard deviation of the <span class="math inline">\(n\)</span> differences. The experiment has <span class="math inline">\(n-1\)</span> degrees of freedom, because only the mean of the differences is taken.</p>
<p><span class="math display">\[t=\frac{\bar d}{\frac{sd_d}{\sqrt n}}\]</span></p>
<div id="example-2" class="section level4">
<h4><span class="header-section-number">22.2.3.1</span> Example</h4>
<p>A random sample of a group of diabetic mice is selected from a colony. For each mouse a blood sample is drawn after administration of a placebo in which glucose is measured. Each mouse is next administered a drug. Within hours, a second blood sample is drawn, in which glucose is measured again. The drug effect is calculated as the difference between the glucose measurements after placebo and drug. Each pair of measurements stands as an independent replicate.</p>
</div>
</div>
</div>
<div id="t-test-hypotheses" class="section level2">
<h2><span class="header-section-number">22.3</span> t Test Hypotheses</h2>
<p>As for whether to choose a paired or unpaired analysis, the choice of t-test hypotheses depends upon the experimental design and the scientific question at hand. In R, the hypothesis via options in the <code>alternative</code> argument of the <code>t.test</code> function.</p>
<p>Since t-tests are parametric, hypotheses are stated on the basis of the statistical parameters of the sampled population. In this case, the means of the samples are meant to infer the sampled population, so we revert to Greek notation.</p>
<p>To put this another way, that the sample shows a difference is a mathematical fact. We don’t need a statistical test to tell us that. The test helps us infer whether the populations that were sampled differ.</p>
<p>One-sided hypotheses predict the direction of an effect. For example, “the response to treatment will be greater than control.” Or, “the response to treatment will be less than control.”</p>
<p>Two-sided hypothesis do not predict the direction of an effect: “The response to treatment will differ from control, either higher or lower.” Therefore, use a one-sided hypothesis if you think your treatment will go in a specific direction. Choose a two-sided test when you’re not willing to bet on an effect’s direction.</p>
<p>This matters because at the 95% confidence level the threshold value of the t statistic will be lower for a one-sided test ( eg,<code>qt(0.05, 2</code>) than for a two-sided test (<code>qt(0.025, 2)</code>) given the same data. Put another way, the “significance” threshold will always be a higher bar to cross for a two-sided hypothesis. For a one-sided test, all of the 5% cumulative probability is on one side of the distribution. For a two-sided test, that 5% is evenly split to both sides.</p>
<p>Therefore, two-sided tests are slightly more stringent. There is a school of thought that all testing should be two-sided. One reason for this is the enhanced stringency. Another is that 95% confidence intervals of the estimate are more readily interpretable as they have both upper and lower bounds. A third reason is that if testing one-sided and the effect goes extreme but in the direction opposite of predicted, the null cannot be rejected formally. The experiment will need to be repeated.</p>
<div id="one-sample-hypotheses" class="section level3">
<h3><span class="header-section-number">22.3.1</span> One sample hypotheses</h3>
<p>Two sided: Use when, going into an experiment, you are not sure which direction the predictor variable will change the outcome variable relative to the population mean.</p>
<p>H_0: <span class="math inline">\(\bar x = \mu\)</span>
H_1: <span class="math inline">\(\bar \ne \mu\)</span></p>
<p>One sided: Use when, going into an experiment, you are confident the predictor variable will cause the outcome response to be higher than the population mean.</p>
<p>H_0: <span class="math inline">\(\bar x \le \mu\)</span>
H_1: <span class="math inline">\(\bar x&gt;\mu\)</span></p>
<p>Or you are confident the predictor variable will cause the outcome response to be lower than the population mean.</p>
<p>H_0: <span class="math inline">\(\bar x \ge \mu\)</span>
H_1: <span class="math inline">\(\bar x&lt;\mu\)</span></p>
</div>
<div id="unpaired-hypotheses" class="section level3">
<h3><span class="header-section-number">22.3.2</span> Unpaired hypotheses</h3>
<p>Two sided: Use when, going into an experiment, you are not sure whether level A or B of the predictor will cause a higher outcome response.</p>
<p>H_0: <span class="math inline">\(\bar x_A = \bar x_B\)</span>
H_1: <span class="math inline">\(\bar x_A \ne \bar x_B\)</span></p>
<p>One sided: Use when, going into an experiment, you are confident level A of the predictor variable will cause the outcome response to be higher than that for level B.</p>
<p>H_0: <span class="math inline">\(\bar x_A \le \bar x_B\)</span>
H_1: <span class="math inline">\(\bar x_A &gt; \bar x_B\)</span></p>
<p>Or when you are confident the level A of the predictor variable will cause the outcome response to be lower than that for level B.</p>
<p>H_0: <span class="math inline">\(\bar x_A \ge \bar x_B\)</span>
H_1: <span class="math inline">\(\bar x_A &lt; \bar x_B\)</span></p>
</div>
<div id="paired-hypotheses" class="section level3">
<h3><span class="header-section-number">22.3.3</span> Paired hypotheses</h3>
<p>Two sided: Use when, going into an experiment, you are not sure whether the mean difference between levels of the predictor variable will be less than or greater than zero.</p>
<p>H_0: <span class="math inline">\(\bar x = 0\)</span>
H_1: <span class="math inline">\(\bar x \ne 0\)</span></p>
<p>One sided: Use when, going into an experiment, you are confident the mean difference between levels of the predictor will be greater than zero.</p>
<p>H_0: <span class="math inline">\(\bar x \le 0\)</span>
H_1: <span class="math inline">\(\bar x&gt;0\)</span></p>
<p>Or when, going into an experiment, you are confident the mean difference between levels of the predictor will be less than zero.</p>
<p>H_0: <span class="math inline">\(\bar x \ge 0\)</span>
H_1: <span class="math inline">\(\bar x&lt;0\)</span></p>
</div>
</div>
<div id="confidence-intervals-of-means" class="section level2">
<h2><span class="header-section-number">22.4</span> Confidence Intervals of Means</h2>
<p>A 95% confidence interval is an inferential statistic that allows for estimating the accuracy of a sample. The 95% CI is the range of values within which there is 95% confidence the true mean rests.</p>
<p>A two-sided 95% CI can be calculated as follows: <span class="math display">\[mean\pm qt(0.975, df)*\frac{sd}{\sqrt n}\]</span></p>
<p>For example, given a sample size of n=3, that has a mean of 100. and a standard deviation of 25</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1">upper.limit &lt;-<span class="st"> </span><span class="dv">100</span><span class="op">+</span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dv">2</span>)<span class="op">*</span>(<span class="dv">25</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">3</span>))</a>
<a class="sourceLine" id="cb1-2" title="2">lower.limit &lt;-<span class="st"> </span><span class="dv">100</span><span class="op">-</span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dv">2</span>)<span class="op">*</span>(<span class="dv">25</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">3</span>))</a>
<a class="sourceLine" id="cb1-3" title="3">upper.limit</a></code></pre></div>
<pre><code>## [1] 162.1034</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">lower.limit</a></code></pre></div>
<pre><code>## [1] 37.89656</code></pre>
<p>Thus, the point estimate for the mean is 100 and, <em>on the basis of this single sample</em>, we can assert 95% confidence the true population mean is somewhere between 37.89 and 162.10.</p>
<p>Another way to think about this is in frequentist terms. If we sampled 100 times, where each sample has n independent replicates, 95% of the resulting confidence intervals would include our point estimate of 100.</p>
<p>I like to think that the standard error of the mean, <span class="math inline">\(SEM\)</span>, or <span class="math inline">\(\frac{sd}{\sqrt n}\)</span>, provides information about the precision of the mean estimate. As the sample size increases <span class="math inline">\(SEM\)</span> lowers.</p>
<p>I like to think about the 95% confidence interval as providing information about the accuracy of the mean; the range of values the true mean <em>might</em> be based upon this one sample. Of course, when sampling from unknown hypothetical populations it’s never possible to know if something is accurate with perfect certainty. However, it is useful from time to time assert how confident we are in an estimate in terms of the values it might otherwise taken on.</p>
<p>As we muddle our way through the so-called replication crisis there is growing recognition that data summaries should focus more on confidence intervals and less on point estimates.</p>
<p>For example, one can readily imagine scenarios where the point estimate for a dependent variable of 100 is scientifically meaningful, but a point estimate of 37 is note. When the confidence interval includes values that are not scientifically impressive, the point estimate of 100 requires greater skepticism. The sample could very well be a high outlier.</p>
</div>
<div id="parameters-small-samples-and-reliability" class="section level2">
<h2><span class="header-section-number">22.5</span> Parameters, small samples, and reliability</h2>
<p>A great deal of biomedical research revolves around experiments based upon small samples. A lot of this boils down to assessing the effects of independent variables by comparing two groups. The t-tests are easily the most frequently used test in biostatistics, whether used appropriately on measured variables, or inappropriately on sorted or ordered variables.</p>
<p>The t-tests are based upon the sample parameters <span class="math inline">\(\bar y, n, sd, \&amp; sem=\frac{sd}{\sqrt n}\)</span> that are worth understanding intuitively.</p>
<p>The figure below illustrates the outcome of repeatedly sampling the <strong>known</strong> population <span class="math inline">\(N(\mu=100, \sigma=25)\)</span>. The coefficient of variation for this simulation is <span class="math inline">\(cv=\frac{\sigma}{\mu}=0.25\)</span>, which my sense says is pretty typical for bio-variable with a well behaved signal to noise ratio. But YMMV.</p>
<p>At first, this script samples at size <span class="math inline">\(n=2\)</span>, repeating the sampling many times. Each time it calculates the sample <span class="math inline">\(\bar y\)</span>, <span class="math inline">\(sd\)</span>, and <span class="math inline">\(SEM\)</span>. Then it moves up to a sample size of <span class="math inline">\(n=3\)</span>, collecting these parameter values from each sample. And so on and so on up to a sample size of <span class="math inline">\(n=100\)</span></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="co"># a function to calculate parameter values for each sample drawn.</span></a>
<a class="sourceLine" id="cb5-2" title="2">sampler &lt;-<span class="st"> </span><span class="cf">function</span>(n) {</a>
<a class="sourceLine" id="cb5-3" title="3">  samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n, <span class="dv">100</span>, <span class="dv">25</span>)</a>
<a class="sourceLine" id="cb5-4" title="4">  msamp &lt;-<span class="st"> </span><span class="kw">mean</span>(samp)</a>
<a class="sourceLine" id="cb5-5" title="5">  sdsamp &lt;-<span class="st"> </span><span class="kw">sd</span>(samp)</a>
<a class="sourceLine" id="cb5-6" title="6">  sesamp &lt;-<span class="st"> </span>sdsamp<span class="op">/</span><span class="kw">sqrt</span>(n)</a>
<a class="sourceLine" id="cb5-7" title="7"></a>
<a class="sourceLine" id="cb5-8" title="8">  <span class="kw">tibble</span>(n, msamp, sdsamp, sesamp)</a>
<a class="sourceLine" id="cb5-9" title="9">}</a>
<a class="sourceLine" id="cb5-10" title="10"></a>
<a class="sourceLine" id="cb5-11" title="11"><span class="co"># apply sampler to a column of n&#39;s, by row</span></a>
<a class="sourceLine" id="cb5-12" title="12">sampsize &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">n=</span><span class="dv">2</span><span class="op">:</span><span class="dv">100</span>)</a>
<a class="sourceLine" id="cb5-13" title="13">test &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(<span class="kw">apply</span>(sampsize, <span class="dv">1</span>, sampler))</a>
<a class="sourceLine" id="cb5-14" title="14"></a>
<a class="sourceLine" id="cb5-15" title="15"><span class="co"># repeat 50X per n, the parameters in a list of lists</span></a>
<a class="sourceLine" id="cb5-16" title="16">outputs &lt;-<span class="st"> </span><span class="kw">list</span>()</a>
<a class="sourceLine" id="cb5-17" title="17"></a>
<a class="sourceLine" id="cb5-18" title="18"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">50</span>) {</a>
<a class="sourceLine" id="cb5-19" title="19">  output &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(<span class="kw">apply</span>(sampsize, <span class="dv">1</span>, sampler))</a>
<a class="sourceLine" id="cb5-20" title="20"></a>
<a class="sourceLine" id="cb5-21" title="21">  outputs[[i]] &lt;-<span class="st"> </span>output</a>
<a class="sourceLine" id="cb5-22" title="22">}</a>
<a class="sourceLine" id="cb5-23" title="23"></a>
<a class="sourceLine" id="cb5-24" title="24"><span class="co"># tidyverse magic, converts list of lists to data frame</span></a>
<a class="sourceLine" id="cb5-25" title="25">outputs &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(outputs)</a>
<a class="sourceLine" id="cb5-26" title="26"></a>
<a class="sourceLine" id="cb5-27" title="27"><span class="co"># plot it!</span></a>
<a class="sourceLine" id="cb5-28" title="28"><span class="kw">ggplot</span>(outputs)<span class="op">+</span></a>
<a class="sourceLine" id="cb5-29" title="29"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(n, msamp), <span class="dt">color=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb5-30" title="30"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(n, sdsamp), <span class="dt">color =</span><span class="st">&quot;red&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb5-31" title="31"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(n, sesamp), <span class="dt">color=</span><span class="st">&quot;black&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb5-32" title="32"><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;parameter value&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb5-33" title="33"><span class="st">  </span><span class="kw">annotate</span>(<span class="dt">geom=</span><span class="st">&quot;text&quot;</span>, </a>
<a class="sourceLine" id="cb5-34" title="34">           <span class="dt">x=</span><span class="kw">c</span>(<span class="dv">75</span>,<span class="dv">75</span>, <span class="dv">75</span>), </a>
<a class="sourceLine" id="cb5-35" title="35">           <span class="dt">y=</span><span class="kw">c</span>(<span class="dv">125</span>,<span class="dv">40</span>, <span class="dv">12</span>), </a>
<a class="sourceLine" id="cb5-36" title="36">           <span class="dt">label=</span><span class="kw">c</span>(<span class="st">&quot;mean&quot;</span>,<span class="st">&quot;sd&quot;</span>, <span class="st">&quot;sem&quot;</span>),</a>
<a class="sourceLine" id="cb5-37" title="37">           <span class="dt">color=</span><span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;black&quot;</span>),</a>
<a class="sourceLine" id="cb5-38" title="38">           <span class="dt">size=</span><span class="dv">8</span></a>
<a class="sourceLine" id="cb5-39" title="39">           )<span class="op">+</span></a>
<a class="sourceLine" id="cb5-40" title="40"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-4"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-4-1.png" alt="Simulation of the relationships between the sample parameters used in t-tests. These can represent either group parameters or the parameters for the difference between groups. " width="672" />
<p class="caption">
Figure 22.2: Simulation of the relationships between the sample parameters used in t-tests. These can represent either group parameters or the parameters for the difference between groups.
</p>
</div>
<p>What strikes you about this result?</p>
<p>The biggest thing it tells me is that small samples are crappy.</p>
<p>We <strong>know</strong> the mean and standard deviation are 100 and 25, respectively. We coded them to be exactly that. Yet, at low sample sizes, <span class="math inline">\(n\)</span>, their estimates from the samples can be pretty far off. And these vary quite a lot, too. By random chance, a sample mean and standard deviation can range anywhere from perfect to awful crappy estimates of the population values. And we’d never know which one we got.</p>
<p>The researcher is not at fault for this. This crappiness is inherent to the sampled population. This happens even with exquisite technique and perfectly calibrated pipettes and other instrumentation. Biological systems have variance. And when we do an experimental something to those systems we tend to provoke even more variance.</p>
<p>When do small samples get less crappy? In some respects that is in the eye of the beholder. To my eye, for this case <span class="math inline">\(n &gt;30\)</span> seems less crappy than under 30.</p>
<p>Importantly, the coefficient of variation will have a big role in this. Small samples of variables with low <span class="math inline">\(cv\)</span> will be less crappy, relatively speaking. And the larger the effect size the greater latitude we have in tolerating crappy small samples, irrespective of their <span class="math inline">\(cv\)</span>.</p>
<p>This is where power calculations come in very handy. They are designed to tell us how low our sample size can be before we become victims of the crap.</p>
<p>The second thing this illustrator tells me is that <span class="math inline">\(sd\)</span> and <span class="math inline">\(sem\)</span> are not telling me the same thing. The sample <span class="math inline">\(sd\)</span> reports dispersion in the sample, but that is also an estimate of <span class="math inline">\(\sigma\)</span>, the dispersion in the population.</p>
<p>Whereas the <span class="math inline">\(sem\)</span> gets lower and lower as sample size increases, because <span class="math inline">\(sem=\frac{sd}{\sqrt n}\)</span>. Theoretically, <span class="math inline">\(sem\)</span> approaches zero.</p>
<p>The <span class="math inline">\(sem\)</span> is actually the standard deviation of the theoretical population of sample means, a concept which is derived from the central limit theorem. As a result, we infer from the <span class="math inline">\(sem\)</span> of a single sample how precisely that sample estimates of population mean. As you can see from this illustrator, the precision by which a mean is estimated improves as sample size increases. Whereas <span class="math inline">\(sd\)</span> oscillates with each sample around a fixed value, reflective of the dispersion of values in the population, <span class="math inline">\(sem\)</span> gets better and better (when one assumes low is better).</p>
<div id="reporting-sd-or-sem" class="section level3">
<h3><span class="header-section-number">22.5.1</span> Reporting SD or SEM?</h3>
<p>Are you estimating the value of a physical constant, such as the mass of a boson, the <span class="math inline">\(K_D\)</span> of a drug receptor interaction, the <span class="math inline">\(K_M\)</span> of an enzyme? Something that should have the same value no matter where in the universe it is estimated? Researchers who are in the business of estimating those values with high precision, such as when those values are under dispute, cannot be faulted for reporting the <span class="math inline">\(sem\)</span>. Particularly when the goal of the experiment was to get a better estimate of the physical constant or how a variable changes it.</p>
<p>For everything else just report the SD.</p>
<p>Another consequence of the so-called replication crisis is that journals are requiring authors to show all their data more openly. Use scatter plots to show all data points rather than bar graphs with error bars. With respect to the latter, most people who are honest about why they use SEM error in bar graphs will admit because it makes the data look better. Since the motivation is basically deception, that is not a good reason to use SEM.</p>
<p>If you do use SEM in bar graphs, then you must report the exact value of <span class="math inline">\(n\)</span> for each group so a reader can back calculate out the SD. Which gets messy in both figure legends and in graphs.</p>
<p>So just report the SD.</p>
</div>
</div>
<div id="t-tests-running-the-analysis" class="section level2">
<h2><span class="header-section-number">22.6</span> t Tests: Running the analysis</h2>
<p>In R <code>t.test</code> represents a single function by which each of the three t test experimental designs can be analyzed.</p>
<div id="one-sample-t-test" class="section level3">
<h3><span class="header-section-number">22.6.1</span> One sample t test</h3>
<p>Let’s say a standard to measure against is the value of 100. We can ask if a random sample that is 2-fold greater is different than 100, less than 100, or greater than 100:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="co"># this makes the sample reproducible</span></a>
<a class="sourceLine" id="cb6-2" title="2"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb6-3" title="3"><span class="co"># here&#39;s a random sample</span></a>
<a class="sourceLine" id="cb6-4" title="4">a &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">3</span>, <span class="dt">mean=</span><span class="dv">200</span>, <span class="dt">sd=</span><span class="dv">25</span>)</a>
<a class="sourceLine" id="cb6-5" title="5"></a>
<a class="sourceLine" id="cb6-6" title="6"><span class="co"># you can run t.test without naming it as an object</span></a>
<a class="sourceLine" id="cb6-7" title="7">one2 &lt;-<span class="st"> </span><span class="kw">t.test</span>(a, <span class="dt">mu=</span><span class="dv">100</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="dt">conf.level=</span><span class="fl">0.95</span> )</a>
<a class="sourceLine" id="cb6-8" title="8">oneL &lt;-<span class="kw">t.test</span>(a, <span class="dt">mu=</span><span class="dv">100</span>, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">conf.level=</span><span class="fl">0.95</span>)</a>
<a class="sourceLine" id="cb6-9" title="9">oneG &lt;-<span class="st"> </span><span class="kw">t.test</span>(a, <span class="dt">mu=</span><span class="dv">100</span>, <span class="dt">alternative =</span><span class="st">&quot;greater&quot;</span>, <span class="dt">conf.level=</span><span class="fl">0.95</span>)</a>
<a class="sourceLine" id="cb6-10" title="10"></a>
<a class="sourceLine" id="cb6-11" title="11"><span class="co"># the following line makes jabstb more readable</span></a>
<a class="sourceLine" id="cb6-12" title="12"><span class="co"># broom::tidy is a function to clean up R test output</span></a>
<a class="sourceLine" id="cb6-13" title="13"><span class="co"># not a bad trick to have for functions or writing clean reports </span></a>
<a class="sourceLine" id="cb6-14" title="14">knitr<span class="op">::</span><span class="kw">kable</span>(<span class="kw">bind_rows</span>(<span class="kw">tidy</span>(one2), <span class="kw">tidy</span>(oneL), <span class="kw">tidy</span>(oneG)), <span class="dt">caption=</span><span class="st">&quot;One-sample t-test output. Read text for interpretation.&quot;</span>)         </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-5">Table 22.1: </span>One-sample t-test output. Read text for interpretation.</caption>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">201.29</td>
<td align="right">6.037536</td>
<td align="right">0.0263538</td>
<td align="right">2</td>
<td align="right">129.1056</td>
<td align="right">273.4744</td>
<td align="left">One Sample t-test</td>
<td align="left">two.sided</td>
</tr>
<tr class="even">
<td align="right">201.29</td>
<td align="right">6.037536</td>
<td align="right">0.9868231</td>
<td align="right">2</td>
<td align="right">-Inf</td>
<td align="right">250.2778</td>
<td align="left">One Sample t-test</td>
<td align="left">less</td>
</tr>
<tr class="odd">
<td align="right">201.29</td>
<td align="right">6.037536</td>
<td align="right">0.0131769</td>
<td align="right">2</td>
<td align="right">152.3023</td>
<td align="right">Inf</td>
<td align="left">One Sample t-test</td>
<td align="left">greater</td>
</tr>
</tbody>
</table>
<div id="interpretation-6" class="section level4">
<h4><span class="header-section-number">22.6.1.1</span> Interpretation</h4>
<ul>
<li><p><span class="math inline">\(t\)</span> is a descriptive statistic, calculated from the sample values <a href="###%20One%20sample%20t%20tests">as described above</a>. The test uses ordinary least squares. See <a href="dispersion.html#dispersion">the chapter on dispersion</a>.</p></li>
<li><p>Notice how the t-value is the same for all 3 tests. The same sample will give the same signal to noise ratio, irrespective of the hypothesis tested.</p></li>
<li><p>You may be disappointed by no output for the <span class="math inline">\(sd\)</span> or <span class="math inline">\(sem\)</span> of the sample. But these are easy enough to calculate. From the equation <a href="###%20One%20sample%20t%20tests">as described above</a>: <span class="math inline">\(sem=\frac{\bar y}{t}\)</span>, and <span class="math inline">\(sd=sem \times \sqrt n\)</span></p></li>
<li><p>Parameter is value for the degrees of freedom. This sample with <span class="math inline">\(n=3\)</span> has <span class="math inline">\(df=2\)</span>. A degree of freedom was lost in calculating <span class="math inline">\(\bar y\)</span></p></li>
<li><p>The p-value is a cumulative probability from a null <span class="math inline">\(t_{df=2}\)</span> distribution. It is the probability of the observed value for <span class="math inline">\(t\)</span> or a value more extreme, if the null hypothesis is true.</p></li>
<li><p>The p-values do differ between the 3 tests because the hypotheses differ, and these hypotheses affect the calculation of <span class="math inline">\(p\)</span> even though <span class="math inline">\(t\)</span> is the same for each test.</p></li>
<li><p>The one-sided <code>less</code> hypothesis argument predicts the sample mean will be less than <span class="math inline">\(\mu\)</span>. Its p-value calculation is <code>pt(q=6.037536, df=2, lower.tail=T)</code>. It is large because it is the wrong hypothesis for these data. If the sign of the <span class="math inline">\(t\)</span> were negative, this would be the correct hypothesis.</p></li>
</ul>
<p>The one-sided <code>greater</code> hypothesis greater predicts the sample mean will be greater than <span class="math inline">\(\mu\)</span>. Its p-value calculation is <code>pt(q=6.037536, df=2, lower.tail=F)</code>.</p>
<ul>
<li><p>The <code>two.sided</code> hypothesis is the sample mean does not equal <span class="math inline">\(\mu\)</span>. Its p-value is <code>pt(t=6.037536, df=2, lower.tail=T)/2</code></p></li>
<li><p>The 95% confidence level is the default. If you want a different confidence level, for example, an 86.75309% CI, simply enter an argument for it.</p></li>
<li><p>The upper and lower confidence limits differ between the 3 tests. The one-sided tests give you an infinite limit on one side. These are hard to interpret and not particularly useful. If you are tempted to to combine the upper of less with the lower of greater, you’ve created a 90% confidence interval, so don’t.</p></li>
<li><p>The simplest way to get a “typical” 95% CI in R that has both upper and lower limits is to run a two.sided t.test and pull it out of that.</p></li>
<li><p>There is no Welch’s test for one-sample measurements.</p></li>
</ul>
</div>
</div>
<div id="unpaired-t-test" class="section level3">
<h3><span class="header-section-number">22.6.2</span> Unpaired t test</h3>
<p>Now we will pull two random samples: one from a normal distribution that has a mean of 200, and the second from a distribution that has a mean of 100. Both have standard deviations of 25. We have the option to run three different hypotheses.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb7-2" title="2">a &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">3</span>, <span class="dt">mean=</span><span class="dv">200</span>, <span class="dt">sd=</span><span class="dv">25</span>)</a>
<a class="sourceLine" id="cb7-3" title="3">b &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">3</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">25</span>)</a>
<a class="sourceLine" id="cb7-4" title="4">up2 &lt;-<span class="st"> </span><span class="kw">t.test</span>(a, b, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="dt">var.equal =</span> F )</a>
<a class="sourceLine" id="cb7-5" title="5">upL &lt;-<span class="st"> </span><span class="kw">t.test</span>(a, b, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">var.equal =</span> F)</a>
<a class="sourceLine" id="cb7-6" title="6">upG &lt;-<span class="st"> </span><span class="kw">t.test</span>(a,b, <span class="dt">alternative =</span><span class="st">&quot;greater&quot;</span>, <span class="dt">var.equal =</span> F)</a>
<a class="sourceLine" id="cb7-7" title="7"></a>
<a class="sourceLine" id="cb7-8" title="8">knitr<span class="op">::</span><span class="kw">kable</span>(<span class="kw">bind_rows</span>(<span class="kw">tidy</span>(up2), <span class="kw">tidy</span>(upL), <span class="kw">tidy</span>(upG)), <span class="dt">caption=</span><span class="st">&quot;Unpaired t-test output. See text for interpretation. See interpretation of one-sample tests for details omitted here common to all tests.&quot;</span>)   </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-6">Table 22.2: </span>Unpaired t-test output. See text for interpretation. See interpretation of one-sample tests for details omitted here common to all tests.</caption>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">estimate1</th>
<th align="right">estimate2</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">113.0443</td>
<td align="right">201.29</td>
<td align="right">88.24569</td>
<td align="right">3.920543</td>
<td align="right">0.0208179</td>
<td align="right">3.622275</td>
<td align="right">29.58648</td>
<td align="right">196.5022</td>
<td align="left">Welch Two Sample t-test</td>
<td align="left">two.sided</td>
</tr>
<tr class="even">
<td align="right">113.0443</td>
<td align="right">201.29</td>
<td align="right">88.24569</td>
<td align="right">3.920543</td>
<td align="right">0.9895910</td>
<td align="right">3.622275</td>
<td align="right">-Inf</td>
<td align="right">176.4025</td>
<td align="left">Welch Two Sample t-test</td>
<td align="left">less</td>
</tr>
<tr class="odd">
<td align="right">113.0443</td>
<td align="right">201.29</td>
<td align="right">88.24569</td>
<td align="right">3.920543</td>
<td align="right">0.0104090</td>
<td align="right">3.622275</td>
<td align="right">49.68623</td>
<td align="right">Inf</td>
<td align="left">Welch Two Sample t-test</td>
<td align="left">greater</td>
</tr>
</tbody>
</table>
<div id="interpretation-7" class="section level4">
<h4><span class="header-section-number">22.6.2.1</span> Interpretation</h4>
<ul>
<li><p>The interpretation is is similar to the one sample case but there are some evident differences.</p></li>
<li><p>The estimate is the difference between the means of each group.</p></li>
<li><p>Estimate1 and estimate2 are the means of each group.</p></li>
<li><p>Statistic is the value of <span class="math inline">\(t\)</span>, in this example calculated by the <a href="####%20Welch&#39;s%20t-test">Welch method</a></p></li>
<li><p>Parameter is the value for <span class="math inline">\(df\)</span>,in this example also calculated by the <a href="####%20Welch&#39;s%20t-test">Welch method</a>. These are almost always fractional, whereas degrees of freedom for the Student’s t-test is always an integer value.</p></li>
<li><p>Although you can calculate the standard error for the test, <span class="math inline">\(se = \frac{estimate}{statistic}\)</span>, because there are two means, note how this value is not a standard error of the mean. In fact, each group will have different <span class="math inline">\(sem\)</span> values. Best use R to calculate: <code>sem &lt;- sd(a)/sqrt(length(a))</code></p></li>
<li><p>The “mean of x” corresponds to the <code>a</code> sample, or the first group in the argument. In the unpaired t test, good practice is to put the ‘treatment’ as the first data argument, and the ‘control’ as the second argument.</p></li>
<li><p>That will make interpretation of one-sided test output a LOT easier.</p></li>
<li><p>Welch’s test is only for unpaired tests, because it serves as an adjustment for when the sample sizes and variances of the two groups differ. The one-sample doesn’t have two groups, whereas the group variances are irrelevant in the paired t-tests.</p></li>
</ul>
</div>
</div>
<div id="paired-t-test" class="section level3">
<h3><span class="header-section-number">22.6.3</span> Paired t Test</h3>
<p>The paired test calculates the differences between paired measurements. Then it asks how the mean of these differences differs from zero.</p>
<p>In fact, although two groups are involved, the test calculates the mean its standard error of a third group: the values for the differences. Thus it is much more like the one-sample t-test than it is like the unpaired t-test.</p>
<p>The structure of the data input matters. If entered as two vectors (like below), the first value of the first vector will be paired with the first value of the second vector, and so on. Alternately, like all t-tests, you can run it using the formula method.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb8-2" title="2"></a>
<a class="sourceLine" id="cb8-3" title="3">a &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">3</span>, <span class="dt">mean=</span><span class="dv">200</span>, <span class="dt">sd=</span><span class="dv">25</span>)</a>
<a class="sourceLine" id="cb8-4" title="4">b &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">3</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">25</span>)</a>
<a class="sourceLine" id="cb8-5" title="5"></a>
<a class="sourceLine" id="cb8-6" title="6">p2 &lt;-<span class="st"> </span><span class="kw">t.test</span>(a, b, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="dt">paired=</span>T)</a>
<a class="sourceLine" id="cb8-7" title="7">pL &lt;-<span class="st"> </span><span class="kw">t.test</span>(a, b, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">paired=</span>T)</a>
<a class="sourceLine" id="cb8-8" title="8">pG &lt;-<span class="st"> </span><span class="kw">t.test</span>(a, b, <span class="dt">alternative =</span><span class="st">&quot;greater&quot;</span>, <span class="dt">paired=</span>T)</a>
<a class="sourceLine" id="cb8-9" title="9"></a>
<a class="sourceLine" id="cb8-10" title="10"><span class="co">#make a data frame suitable for the formula argument</span></a>
<a class="sourceLine" id="cb8-11" title="11">long &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">replicate=</span><span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, a, b) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb8-12" title="12"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>replicate, </a>
<a class="sourceLine" id="cb8-13" title="13">               <span class="dt">names_to=</span><span class="st">&quot;group&quot;</span>, </a>
<a class="sourceLine" id="cb8-14" title="14">               <span class="dt">values_to=</span><span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb8-15" title="15"></a>
<a class="sourceLine" id="cb8-16" title="16"><span class="co">#running the formula argument</span></a>
<a class="sourceLine" id="cb8-17" title="17">l2 &lt;-<span class="st"> </span><span class="kw">t.test</span>(response <span class="op">~</span><span class="st"> </span>group, <span class="dt">data=</span>long, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="dt">paired=</span>T)</a>
<a class="sourceLine" id="cb8-18" title="18"></a>
<a class="sourceLine" id="cb8-19" title="19">knitr<span class="op">::</span><span class="kw">kable</span>(<span class="kw">bind_rows</span>(<span class="kw">tidy</span>(l2), <span class="kw">tidy</span>(p2), <span class="kw">tidy</span>(pL), <span class="kw">tidy</span>(pG)), <span class="dt">caption=</span><span class="st">&quot;Paired t-test output. See text for interpretation. See interpretation of one-sample tests for details omitted here common in all tests.&quot;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-7">Table 22.3: </span>Paired t-test output. See text for interpretation. See interpretation of one-sample tests for details omitted here common in all tests.</caption>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">113.0443</td>
<td align="right">12.10457</td>
<td align="right">0.0067559</td>
<td align="right">2</td>
<td align="right">72.86194</td>
<td align="right">153.2268</td>
<td align="left">Paired t-test</td>
<td align="left">two.sided</td>
</tr>
<tr class="even">
<td align="right">113.0443</td>
<td align="right">12.10457</td>
<td align="right">0.0067559</td>
<td align="right">2</td>
<td align="right">72.86194</td>
<td align="right">153.2268</td>
<td align="left">Paired t-test</td>
<td align="left">two.sided</td>
</tr>
<tr class="odd">
<td align="right">113.0443</td>
<td align="right">12.10457</td>
<td align="right">0.9966221</td>
<td align="right">2</td>
<td align="right">-Inf</td>
<td align="right">140.3140</td>
<td align="left">Paired t-test</td>
<td align="left">less</td>
</tr>
<tr class="even">
<td align="right">113.0443</td>
<td align="right">12.10457</td>
<td align="right">0.0033779</td>
<td align="right">2</td>
<td align="right">85.77465</td>
<td align="right">Inf</td>
<td align="left">Paired t-test</td>
<td align="left">greater</td>
</tr>
</tbody>
</table>
<div id="interpretation-8" class="section level4">
<h4><span class="header-section-number">22.6.3.1</span> Interpretation</h4>
<ul>
<li><p>The first row of the output is from the formula test. It should have the same everything as the second row.</p></li>
<li><p>The estimate is the mean of the differences between pairs. Group means are irrelevant. What matters in a paired t-test is whether the differences are reliably different from zero.</p></li>
<li><p>Notice how, given the same data, the paired computes a higher value for <span class="math inline">\(t\)</span> compared to the unpaired.</p></li>
<li><p><span class="math inline">\(t\)</span> is the ratio of the mean of the differences divided by the standard error of the mean of the differences.</p></li>
<li><p>Notice how, given the same data, the paired test computes a lower p-value compared to the unpaired.</p></li>
<li><p>The 95% CI is for the mean of the differences. There is 95% confidence the true mean of the differences in the population sampled is included within the range bounded by conf.low and conf.high.</p></li>
<li><p>The parameter is the degrees of freedom. In this sample <span class="math inline">\(df=2\)</span> because there are 3 pairs. A degree of freedom was lost by calculating the mean of the differences.</p></li>
<li><p>The paired test has the same number of measurements as the unpaired test, but fewer independent replicates. This is due to the experimental design, which called for paired measurements from each replicate. Which is based entirely upon scientific judgment.</p></li>
<li><p>There is no Welch’s test for paired measurements.</p></li>
<li><p>Good statistical judgment is not conflating the paired and unpaired tests, or assuming they differ trivially. They differ dramatically.</p></li>
</ul>
</div>
</div>
</div>
<div id="plotting-t-tests" class="section level2">
<h2><span class="header-section-number">22.7</span> Plotting t Tests</h2>
<p>Plot t-tests in a way that illustrates the experimental design.</p>
<div id="unpaired" class="section level3">
<h3><span class="header-section-number">22.7.1</span> Unpaired</h3>
<p>An unpaired t-test compares two means. So the plot should show two means, and perhaps some summary statistics along with it.</p>
<p>Tidy the data, which makes it simple to create a descriptive statistics summary table:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="co">#data munge</span></a>
<a class="sourceLine" id="cb9-2" title="2">data.u &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">replicate=</span><span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">control=</span>b, <span class="dt">treatment=</span>a) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb9-3" title="3"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols=</span><span class="kw">c</span>(control, treatment),</a>
<a class="sourceLine" id="cb9-4" title="4">               <span class="dt">names_to=</span><span class="st">&quot;Predictor&quot;</span>,</a>
<a class="sourceLine" id="cb9-5" title="5">               <span class="dt">values_to=</span><span class="st">&quot;Response&quot;</span>)</a>
<a class="sourceLine" id="cb9-6" title="6"></a>
<a class="sourceLine" id="cb9-7" title="7"><span class="co">#summary statistics table to have</span></a>
<a class="sourceLine" id="cb9-8" title="8">data.y &lt;-<span class="st"> </span>data.u<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb9-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(Predictor) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb9-10" title="10"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb9-11" title="11">     <span class="dt">mean=</span><span class="kw">mean</span>(Response),</a>
<a class="sourceLine" id="cb9-12" title="12">     <span class="dt">sd=</span><span class="kw">sd</span>(Response),</a>
<a class="sourceLine" id="cb9-13" title="13">     <span class="dt">n=</span><span class="kw">length</span>(Response),</a>
<a class="sourceLine" id="cb9-14" title="14">     <span class="dt">sem=</span><span class="kw">mean</span>(Response)<span class="op">/</span><span class="kw">sqrt</span>(n)</a>
<a class="sourceLine" id="cb9-15" title="15">           )</a>
<a class="sourceLine" id="cb9-16" title="16"></a>
<a class="sourceLine" id="cb9-17" title="17">knitr<span class="op">::</span><span class="kw">kable</span>(data.y, <span class="dt">caption=</span><span class="st">&quot;Summary statistics for a two group sample.&quot;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-8">Table 22.4: </span>Summary statistics for a two group sample.</caption>
<thead>
<tr class="header">
<th align="left">Predictor</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">n</th>
<th align="right">sem</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">control</td>
<td align="right">88.24569</td>
<td align="right">36.32957</td>
<td align="right">6</td>
<td align="right">36.02615</td>
</tr>
<tr class="even">
<td align="left">treatment</td>
<td align="right">201.29004</td>
<td align="right">25.99038</td>
<td align="right">6</td>
<td align="right">82.17631</td>
</tr>
</tbody>
</table>
<p>Unless there is a scientific reason to report precision (and there rarely is a good one) plot the data points with mean +/- standard deviation.</p>
<p>A straight forward ways to add error bars is by use of the <code>stat_summary</code> function:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="kw">ggplot</span>(data.u, <span class="kw">aes</span>(Predictor, Response)) <span class="op">+</span></a>
<a class="sourceLine" id="cb10-2" title="2"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width=</span><span class="fl">0.15</span>, <span class="dt">size=</span><span class="dv">4</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb10-3" title="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_sdl, </a>
<a class="sourceLine" id="cb10-4" title="4">               <span class="dt">fun.args =</span> <span class="kw">list</span>(<span class="dt">mult=</span><span class="dv">1</span>), </a>
<a class="sourceLine" id="cb10-5" title="5">               <span class="dt">geom=</span><span class="st">&quot;crossbar&quot;</span>, </a>
<a class="sourceLine" id="cb10-6" title="6">               <span class="dt">width=</span><span class="fl">0.2</span>, </a>
<a class="sourceLine" id="cb10-7" title="7">               <span class="dt">color=</span><span class="st">&quot;red&quot;</span></a>
<a class="sourceLine" id="cb10-8" title="8">               )</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-9"></span>
<img src="jabstb_files/figure-html/unnamed-chunk-9-1.png" alt="More journals want small sample t-test data as scatter plots. Use stat_summary geoms to add error bars and use SD not SEM. The argument mult=1 coupled with mean_sdl draws +/- 1 SD" width="672" />
<p class="caption">
Figure 22.3: More journals want small sample t-test data as scatter plots. Use stat_summary geoms to add error bars and use SD not SEM. The argument mult=1 coupled with mean_sdl draws +/- 1 SD
</p>
</div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">  <span class="co"># or if you prefer</span></a>
<a class="sourceLine" id="cb11-2" title="2">  <span class="co"># stat_summary(fun.data=&quot;mean_sdl&quot;, fun.args=list(mult=1), </span></a>
<a class="sourceLine" id="cb11-3" title="3">  <span class="co">#              geom=&quot;errorbar&quot;, color=&quot;red&quot;, width=0.2) +</span></a>
<a class="sourceLine" id="cb11-4" title="4">  <span class="co"># stat_summary(fun.y=mean, geom=&quot;point&quot;, color=&quot;red&quot;, shape=&quot;plus&quot;, size=5)</span></a></code></pre></div>
</div>
<div id="paired" class="section level3">
<h3><span class="header-section-number">22.7.2</span> Paired</h3>
<p>Paired t test data should always be plotted with point-to-point lines to illustrate the paired relationship of the measurements. In the paired design, each replicate is a pair of observations. The means of the two groups of observations are irrelevant.</p>
<p>The design tests for the <em>difference</em> the treatment causes within each pair, which the slope of the line illustrates. For example, a horizontal line connects a replicate would indicate no effect of the predictor variable!</p>
<p>Munge the data into a long data frame format. Adding an ID for each replicate is necessary for a grouping variable for the plot aesthetics.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1">data.w &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">control=</span>b, <span class="dt">treatment=</span>a, <span class="dt">id=</span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb12-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols=</span><span class="kw">c</span>(control, treatment),</a>
<a class="sourceLine" id="cb12-3" title="3">               <span class="dt">names_to=</span><span class="st">&quot;Predictor&quot;</span>,</a>
<a class="sourceLine" id="cb12-4" title="4">               <span class="dt">values_to=</span><span class="st">&quot;Response&quot;</span>)</a></code></pre></div>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="kw">ggplot</span>(data.w, <span class="kw">aes</span>(Predictor, Response, <span class="dt">group=</span>id)) <span class="op">+</span></a>
<a class="sourceLine" id="cb13-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size=</span><span class="dv">4</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb13-3" title="3"><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">color=</span><span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="jabstb_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
</div>
<div id="t-test-power" class="section level2">
<h2><span class="header-section-number">22.8</span> t Test Power</h2>
<p>See Chapter <a href="ttestmc.html#ttestmc">23</a> for Monte Carlo-based power calculations. You should find that a properly executed Monte Carlo will give you the same result as a t-test power function.</p>
<p>A power analysis should precede every planned experiment to decide upon an optimal sample size for a severe test of an hypothesis. The principle output of any power function is the sample size that would be necessary to conduct a well-powered experiment.</p>
<p>The <code>pwr</code> package in R has the <code>pwr.t.test</code> function. It is very simple to execute. This function requires that several decisions be made in advance.</p>
<p>First, it takes arguments for acceptable type1 error and for intended power. The standard for these in basic biomedical research is 5% and 80%, respectively, but you can use any level you deem appropriate. If you want to run at 86.75309% power, go for it.</p>
<p>Two other arguments are <code>type</code>, which is the experimental design, and <code>alternative</code>, which is the hypothesis.</p>
<p>Finally, there is the <code>d</code> argument, which is Cohen’s <span class="math inline">\(\delta\)</span>. This is less obvious, but very important and simple to understand. Cohen’s <span class="math inline">\(\delta\)</span> is the signal to noise for the effect size you anticipate.</p>
<p><strong>I strongly recommend against defaulting Cohen’s values for “large”, “medium” and “small” effects, which apply to common standards in psychological research. They are much too ambiguous to be useful.</strong></p>
<p>Imagine you anticipate measurements that will have a standard deviation of 25 units. You know this because of familiarity with the assay. You estimate this value on the basis of your own preliminary data or on published information. It takes scientific judgment to settle on that value.</p>
<p>You also believe the average response to a negative control or basal level of the predictor variable will be around 50 units. In your mind, a minimally scientifically valid treatment effect will have a 100 unit response, or 2-fold above the negative control.</p>
<p>The signal will be 100-50=50, and the noise will be 25. Cohen’s <span class="math inline">\(\delta\)</span> will therefore be 50/25=2.</p>
<p>A power calculation for a one-sided hypothesis is illustrated for a unpaired design:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">d=</span><span class="dv">2</span>, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">power=</span><span class="fl">0.8</span>, <span class="dt">type=</span><span class="st">&quot;two.sample&quot;</span>, <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 3.986998
##               d = 2
##       sig.level = 0.05
##           power = 0.8
##     alternative = greater
## 
## NOTE: n is number in *each* group</code></pre>
<div id="interpretation-9" class="section level3">
<h3><span class="header-section-number">22.8.1</span> Interpretation</h3>
<p>The experiment should have a total sample size total of at least 8, 4 in each of two groups.</p>
<p>Randomly allocate each of two levels of the predictor variable to 4 replicates each. Notice how this function produces a bizarre, fractional sample size. Obviously, there is no such critter as a partial replicate. So always round up.</p>
<p>People seem to have difficulty with Cohen’s delta. It’s nothing more complicated than a simple signal-to-noise estimate, just like is the t-statistic. You need some idea about what value to expect for a mean (whether its difference between means or mean of the differences). You need some idea of the standard deviation.</p>
<p>Don’t make the mistake of putting too fine of a point on Cohen’s delta. Scientific judgement is required to calculate the values to use to calculate Cohen’s delta. Use your best scientific guess for standard deviation and the response magnitude, and err on the conservative side.</p>
<p>When designing an experiment temper your hoped for effect size with a sense of what you consider to be a minimally scientifically relevant effect size. In some systems, 2-fold is huge, whereas in other systems (with a lot of variation) a 2-fold response is deemed insignificant.</p>
<p>I strongly caution against using Cohen’s delta values recommended for “small”, “medium”, and “large” effects. There’s a good chance his idea of large effects is a lot smaller probably closer to your idea of small effects.</p>
</div>
</div>
<div id="summary-2" class="section level2">
<h2><span class="header-section-number">22.9</span> Summary</h2>
<ul>
<li>Use t-tests for factorial experiments involving measured dependent variables.</li>
<li>Assumptions about normality and homoscedacticity are difficult to validate with small samples.</li>
<li>Although people commonly use t-tests on data transformed from proportions to percents, or on ordered data, proportion and nonparametric tests can be better options.</li>
<li>The t-test is actually 3 different types of t-tests, only one of which compares the means of two groups.</li>
<li>Which t-test to use depends entirely on the experimental design and requires matching scientific judgment with statistical judgment.</li>
<li>Plot your data based on the experimental design.</li>
<li>Configuration of the test depends upon the statistical hypothesis.</li>
<li>The t-test permeates statistical analyis of biomedical experiments, from simple stand alone experiments to posthoc testing testing of ANOVA and regression coefficients. For this reason, you are advised to embrace a spiritual relationship with the t-test.</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ranksum.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ttestmc.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["jabstb.pdf", "jabstb.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
